apache/openwhisk

.travis.yml, tools/build/scanCode.sh
This demonstrates the use of Travis-CI to run tests.
=> Use Travis-CI to test for code conventions

README.md, tools/vagrant/Vagrantfile
Updated vagrant instructions for shared mode so that reload and provision all used shared mode.
=> Updated installation instructions

core/controller/src/whisk/core/entitlement/Collection.scala, core/controller/src/whisk/core/entitlement/Entitlement.scala, core/controller/src/whisk/core/entitlement/RateThrottler.scala, tests/src/common/WskCli.java
Limit rate at which triggers are accepted by the controller on a per subject basis.  Build #25.
=> Trigger Throttle

core/controller/src/whisk/core/entitlement/Entitlement.scala, core/controller/src/whisk/core/entitlement/RateThrottler.scala
Refactor overload checks to allow for overrides.
=> Refactor overload and throttle checks to allow for overrides.

catalog/installCatalog.sh, catalog/util.sh, tests/src/system/basic/WskBasicTests.scala, tools/cloudant/loadTransientDBViews.sh, tools/cloudant/wipeTransientDBs.sh
Removes datastore credentials from stdout, and removes echo of wsk system keys to stdout.
Also in this commit: added a test to list assets in default namespace regardless of test overrides in basic CLI tests.
=> Fixes issue #36

common/scala/src/whisk/common/ConsulKV.scala, core/dispatcher/src/whisk/core/invoker/Invoker.scala, core/loadBalancer/src/whisk/core/loadBalancer/ActivationThrottle.scala, core/loadBalancer/src/whisk/core/loadBalancer/InvokerHealth.scala, core/loadBalancer/src/whisk/core/loadBalancer/LoadBalancer.scala, core/loadBalancer/src/whisk/core/loadBalancer/LoadBalancerToKafka.scala
This change will explode userActivationCount in Consul to use a directory structure.
=> Replay UserActivationCount work

common/scala/src/whisk/common/SimpleExec.scala, core/dispatcher/src/whisk/core/container/ContainerUtils.scala, core/dispatcher/src/whisk/core/container/WhiskContainer.scala, core/dispatcher/src/whisk/core/invoker/Invoker.scala
Build 47.  Clean up logging in the invoker and fix the isBlackbox predicate.
=> Fix blackbox predicate; logging cleanup

core/dispatcher/src/whisk/core/invoker/Invoker.scala
Return the container to the pool is performed after write activation record.  This removes the delay induced by "docker pause" and speeds up the activation completing.  Build 51.
=> Defer docker pause operation until after activation log

README.md
(And shame ourselves into fixing it when it doesn't.)
=> Proudly tell the world when the build passes.

core/dispatcher/src/whisk/core/container/ContainerPool.scala, core/dispatcher/src/whisk/core/container/WhiskContainer.scala, core/dispatcher/src/whisk/core/invoker/Invoker.scala, core/nodejsAction/app.js, core/nodejsAction/runner.js, core/nodejsAction/src/service.js, core/nodejsAction/src/whisk.js
Refactoring to move in the direction of 2-phase container initialization in support of warm containers.  Also authkey no longer propagated via docker environment variables but through run API.
Verifying build from a few days ago.  Waiting for system to clear up to get a new build.
=> Prealloc container

CLA-CORPORATE.md, CLA-INDIVIDUAL.md, CONTRIBUTING.md
A few sentences were lost in translation. Corrected IBM name. Some minor tweaks to format.
=> Correct a few errors lost in translation. Small tweaks to formatting.

tests/build.xml
Uses the `testsfailonfailure` property to control testexecution.
=> Restoring testfailure behaviour

.travis.yml, tools/travis/setup.sh, tools/ubuntu-setup/all.sh, tools/ubuntu-setup/ansible.sh, tools/ubuntu-setup/pip.sh
Updating ubuntu-setup and travis.yml with ansible
=> Install prereqs for ansible migration

services/consul/deploy.yml
Signed-off-by: Hoang Anh Le <hoang@de.ibm.com>
issue #102 start registrators with consul
=> issue #102 initial playbook for consul

core/controller/deploy.yml, core/loadBalancer/deploy.yml, services/consul/deploy.yml
=> issue #123 add wait_for and pull command for controller, consul and loadbalancer

core/dispatcher/src/whisk/core/invoker/Invoker.scala
Change error message of malformed json to a WARNing if it's not a managed container.  Otherwise, change error message to be something more diagnosable.
IPG 176
=> Improve error messages for malformed json; use WARN if user container

core/dispatcher/src/whisk/core/container/ContainerUtils.scala, core/nodejsAction/runner.js
Lift require so file handle use done early.
Move a file close from a catch to a finally.
PG 186 passed
=> Fix 2 file handle related issues

catalog/installSystem.sh, catalog/installWatson.sh
also remove payload from sampleOutput of cat
=> fix two invalid json issues in installWatson.sh and installSystem.sh

environments/local/group_vars/all, services/kafka/deploy.yml
=> issue #101: init playbook for kafka (incl. zookeeper)

catalog/installWeather.sh, catalog/weather/pollen.js
Part of moving the pollen demo to start using weather app.
=> adding weather pollen action

ansible/roles/activator/tasks/main.yml, ansible/whisk.yml
activator deployable via playbook.
=> issue #159 provide initial playbook for activator

build.xml, tools/db/wipeTransientDBs.sh
=> issue #177: remove redundant DB_PREFIX env var from build.xml

tools/ubuntu-setup/docker.sh
second part of pinning docker version. fixes dev envs additionally to travis.yml.
=> pinning docker to 1.10.3 on ubuntu-setup also.

common/scala/src/whisk/core/WhiskConfig.scala
Signed-off-by: Fatih Ulusoy <ulusoy@de.ibm.com>
=> Variables (which exist already in whisk.properties) are added to WhikConfig

catalog/samples/countdown.js
Signed-off-by: Christian Bickel <cbickel@de.ibm.com>
=> Issue #1673. Fixing countdown action.

common/scala/src/whisk/common/HttpUtils.scala
=> Add httpClient.close

core/swift3Action/Dockerfile, core/swift3Action/proxy.py, core/swiftAction/Dockerfile, core/swiftAction/proxy.py, tests/src/actionContainers/ActionContainer.scala, tests/src/actionContainers/Swift3ActionContainerTests.scala, tests/src/actionContainers/SwiftActionContainerTests.scala
Superseeds #355 and fixes/checks that Swift actions can print to stdout.
=> Action containers tweaks

catalog/watson/languageId.js
=> Update languageId.js to fix typo in comments

common/scala/src/whisk/common/Logging.scala, common/scala/src/whisk/core/database/CouchDbRestStore.scala, common/scala/src/whisk/core/database/InMemoryCache.scala, core/dispatcher/src/whisk/core/container/ContainerUtils.scala, core/dispatcher/src/whisk/core/invoker/Invoker.scala
This PR includes the instrumentation of the Database-calls.
=> Add markers to instrument Database-library

docs/catalog.md
=> Update docs for alarm

core/dispatcher/src/whisk/core/container/ContainerPool.scala
=> Skip pause/unpause of pre-warmed containers

core/dispatcher/src/whisk/core/container/ContainerPool.scala
=> Fix flag scope error from teardown PR change

tools/ubuntu-setup/ansible.sh
Rebase change in #531 to quickly resolve conflict.
=> Relax the version for ansible to 2.* Fixes #530

ansible/roles/controller/tasks/deploy.yml
=> add whisk_version_buildno by deploying controller

docs/actions.md
Close issue #375 
Add the detail guidances for Java Actions in docs/actions.md.
=> Add user documentation for Java Actions

docs/actions.md
=> Add the explanation on how to add a Python action

tools/db/wipeTransientDBs.sh
=> Allows wipe db script to run from anywhere.

ansible/README.md, ansible/roles/cloudant/tasks/initdb.yml
=> disable auto-prompt mode for cloudant. also update README.md file

ansible/roles/invoker/tasks/deploy.yml
=> fix missing images to pull on invoker role.

tests/src/whisk/core/entity/test/ConformanceTests.scala
=> Ignore a conformance test until chunking resolved

common/scala/src/whisk/connector/kafka/KafkaConsumerConnector.scala, tests/src/services/KafkaConnectorTests.scala
Change kafka test to do 5 iterations since first one it topic creation.
PPG 587 passed
=> Fix Kakfa consumer property and flag.  

tools/build/README.md
Ported relevant information from commit message.
=> README.md for tools/build/

settings.gradle, tools/go-cli/build.gradle
=> Add Go CLI to OpenWhisk - Gradle

ansible/edge.yml, ansible/environments/local/group_vars/all, ansible/environments/mac/group_vars/all, ansible/environments/travis/group_vars/all, ansible/roles/go-cli/tasks/clean.yml, ansible/roles/go-cli/tasks/deploy.yml, ansible/roles/go-cli/tasks/main.yml
- Setup Ansible so that Go CLI can be published with nginx (not included)
=> Add Go CLI to OpenWhisk - Ansible

ansible/setup.yml
fixes issue https://github.com/openwhisk/openwhisk/issues/745
FYI: @sjfink
=> [review] issue #745: fix setup.yml for killing the db_local.ini

common/scala/src/main/scala/whisk/utils/ExecutionContextFactory.scala, tests/src/whisk/core/admin/WskAdminTests.scala, tests/src/whisk/core/entity/test/ConformanceTests.scala, tools/cli/wsk, tools/cli/wskutil.py
adds -i to match go CLI (allow insecure SSL); added also -s to enforce trusted SSL.
two other unrelated changes - @psuter squash before merging.
=> [Ready] implement -i for python CLI

ansible/roles/kafka/tasks/deploy.yml
=> improve isAlive method for zookeeper, kafka

catalog/samples/helloPromises.js, core/nodejsActionBase/runner.js, tests/src/actionContainers/NodeJsActionContainerTests.scala, tests/src/packages/UtilsTests.scala
Add support for promises.
JSHint cleanup as well.
=> Support promises for Node.js

common/scala/build.gradle, core/controller/build.gradle, core/dispatcher/build.gradle, tests/build.gradle
Also gets rid of warnings in latest eclipse scala versions.
=> Bumping scala version to 2.11.8

mobile/iOS/starterapp/Cartfile
Change git repo location to correct project
=> Issue #875 fix repo location in Cartfile

mobile/iOS/starterapp/OpenWhiskStarterApp/ViewController.swift, tests/src/whisk/core/dispatcher/test/DispatcherTests.scala
@paulcastro if you build the framework with the latest Swift SDK, the starter app won't build since there was a recent changed in the SDK. Can you review and check why the iOS jenkins build didn't catch this?
=> Fix IOS SDK and a timing bug in DispatcherTest

tests/src/system/basic/WskBasicTests.scala, tests/src/system/basic/WskSdkTests.scala, tools/go-cli/go-whisk-cli/commands/sdk.go, tools/go-cli/go-whisk-cli/commands/wsk.go
Add command to generate bash auto-completion script
Fixes #802
=> [WIP] Add `wsk sdk install bashauto` command to generate CLI auto completion bash script

tests/src/system/basic/WskSdkTests.scala
Update test case to place bash auto complete script in temp dir
Related to PR #923
=> [WIP] Update test case to place bash auto complete script in temp dir

tests/src/system/basic/WskBasicTests.scala
- Disable test that is using the property file to set the auth key
=> Disable Trigger Test that uses Prop file

tests/src/system/basic/WskBasicTests.scala
"show api build using http apihost" test in WskBasicTests is failing.
=> The test should be moved into another package

catalog/installWatson.sh
Fix for some annotation errors found when using the Watson actions from the UI
=> Watson annotation updates

tools/go-cli/build.gradle
Fixes #1002 problem with using softlinks in vagrant using windows host
=> use copytask for go-cli copy Fixes #1002

tools/go-cli/go-whisk-cli/commands/action.go, tools/go-cli/go-whisk-cli/commands/activation.go, tools/go-cli/go-whisk-cli/commands/flags.go, tools/go-cli/go-whisk-cli/commands/namespace.go, tools/go-cli/go-whisk-cli/commands/package.go, tools/go-cli/go-whisk-cli/commands/property.go, tools/go-cli/go-whisk-cli/commands/rule.go, tools/go-cli/go-whisk-cli/commands/sdk.go, tools/go-cli/go-whisk-cli/commands/trigger.go, tools/go-cli/go-whisk-cli/commands/wsk.go
Update Go CLI usage syntax
- Follow Bluemix bx CLI usage conventions as much as possible
- Fix incorrect syntax
- Fixes #934
=> Update Go CLI usage syntax

tests/src/system/basic/CLIPythonTests.scala
- Relax python action environment test (edge host value from action included ip/port)
- Fixes #2393
=> Relax python action environment test

tools/go-cli/Dockerfile, tools/go-cli/go-whisk-cli/Godeps/Godeps.json, tools/go-cli/go-whisk-cli/commands/action.go, tools/go-cli/go-whisk-cli/commands/activation.go, tools/go-cli/go-whisk-cli/commands/commands.go, tools/go-cli/go-whisk-cli/commands/namespace.go, tools/go-cli/go-whisk-cli/commands/package.go, tools/go-cli/go-whisk-cli/commands/property.go, tools/go-cli/go-whisk-cli/commands/rule.go, tools/go-cli/go-whisk-cli/commands/sdk.go, tools/go-cli/go-whisk-cli/commands/trigger.go, tools/go-cli/go-whisk-cli/commands/util.go, tools/go-cli/go-whisk-cli/commands/wsk.go, tools/go-cli/go-whisk-cli/main.go, tools/go-cli/go-whisk-cli/wski18n/detection.go, tools/go-cli/go-whisk-cli/wski18n/i18n.go, tools/go-cli/go-whisk-cli/wski18n/resources/en_US.all.json, tools/go-cli/go-whisk-cli/wski18n/resources/fr_FR.all.json
- Externalize go-whisk-cli\ UI strings
- See #1118
=> Externalize Go CLI UI strings

tools/go-cli/go-whisk-cli/commands/util.go
Remove use of go-prettyjson package due to package issue.
Fixes #1142
=> Remove use of go-prettyjson package

gradle/docker.gradle
check docker version before tagging
=> check docker version before tagging

docs/about.md, docs/actions.md, docs/catalog.md
and other minor formatting changes to sync with blue
=> update slack token refence in docs

README.md, tools/db/README.md, tools/macos/README.md, tools/vagrant/README.md, tools/vagrant/Vagrantfile
update main readme
minor fix for macos readme
Fixes #1215 
Fixes #1214
=> switch to use go cli for vagrant

gradle/docker.gradle
- Add build timing to be able to see what slows the build down
- Refactored docker.gradle
=> Add timing information to build to be able to diagnose travis buildtimes

tests/src/whisk/core/cli/test/WskBasicUsageTests.scala, tools/go-cli/go-whisk-cli/commands/commands.go, tools/go-cli/go-whisk-cli/commands/property.go, tools/go-cli/go-whisk-cli/commands/util.go
- Allow different protocols to be used with the API hosts
=> Allow Protocol to be Set for API Hosts

common/scala/src/main/scala/whisk/http/ErrorResponse.scala, tests/src/limits/ThrottleTests.scala
=> Change missleading error messages of throttling

ansible/environments/mac/group_vars/all, tests/src/limits/ThrottleTests.scala
@perryibm I think we need these additional fixes to the test.
pg1/514 approved.
=> Adjust throttle tests to settle correctly should test fail.

core/nodejsActionBase/app.js, tests/src/actionContainers/NodeJsActionContainerTests.scala
Added a test that ensures "large" source files can be processed as actions.
=> Raised payload size limit in nodejsaction proxy

core/swift3Action/Dockerfile, core/swift3Action/epilogue.swift, core/swift3Action/spm-build/Package.swift, core/swift3Action/spm-build/Whisk.swift, core/swift3Action/swift3runner.py, tests/src/actionContainers/Swift3ActionContainerTests.scala, tests/src/actionContainers/SwiftActionContainerTests.scala
This updates the Swift 3 runtime and associated tests.  It does not update the default Swift container to be Swift 3.
=> Issue 1133, update Swift 3 container and tests

common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala, tests/src/services/KafkaConnectorTests.scala
=> Prevent KafkaConsumerConnector from Commit-Exceptions #1043

core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala
=> Introduce bounded slack between container removal and creation.

ansible/templates/whisk.properties.j2
the flags were not forwarded to consul yet.
=> fix missing invoker parallel docker operations flag.

core/nodejsActionBase/app.js, core/nodejsActionBase/runner.js, core/nodejsActionBase/src/service.js, tests/src/actionContainers/NodeJsActionContainerTests.scala
Trying to dial down the callback hell in the proxy code.
The underlying reason is that with attachments, `doInit()` is becoming asynchronous.
FYI @rabbah
=> Use Promises within nodeJsAction proxy code

ansible/README.md, ansible/roles/invoker/tasks/deploy.yml, ansible/roles/prereq/tasks/deploy.yml, tools/macos/README.md, tools/macos/tweak-dockermachine.sh, tools/travis/setup.sh, tools/ubuntu-setup/ansible.sh
* Bump ansible version to 2.1.2.0 and docker-py to 1.9
* Use docker_container instead of docker (deprecated)
=> Bump ansible

tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
- Display 256 as default memory limit
- Display 10 as default log limit
- Display 60000 as default timeout limit
- Fixes https://github.com/openwhisk/openwhisk/issues/1172
=> Update Default Values for Limits

core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala
rework comments from PR https://github.com/openwhisk/openwhisk/pull/1404
=> set the transactionId of the container explicitly to sid for teardown

docs/actions.md
@rabbah please review
- minor formatting items
- update to docker action update section by @krook to he submitted to bluemix docs
=> update docs, minor format and docker update

tests/src/common/Wsk.scala
Improve extract activation id to work for 'wsk activation get' run result
=> Improve test helpers

ansible/roles/consul/tasks/deploy.yml, ansible/roles/controller/tasks/deploy.yml, ansible/roles/docker/templates/docker.j2, ansible/roles/invoker/tasks/deploy.yml, ansible/roles/kafka/tasks/deploy.yml, ansible/roles/nginx/tasks/deploy.yml, tools/travis/setup.sh
docker user namespaces issue 898
=> User namespaces issue 898

tests/src/whisk/core/database/test/ExtendedCouchDbRestClient.scala
=> Add option to include Docs in ExtendedCouchClient

tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/commands/activation.go, tools/cli/go-whisk-cli/commands/namespace.go, tools/cli/go-whisk-cli/commands/package.go, tools/cli/go-whisk-cli/commands/rule.go, tools/cli/go-whisk-cli/commands/trigger.go, tools/cli/go-whisk-cli/commands/util.go, tools/cli/go-whisk/whisk/wskerror.go
- Raise an error when entity name is missing
- Error when too many "/" are provided
- Prevent entity name that is a "."
Closes https://github.com/openwhisk/openwhisk/issues/1420
=> Enhance Qualified Name Parsing

tests/src/system/basic/WskBasicTests.scala
- Update action field filter test to expect an exec key
=> Fix Failing Property Filter Test

common/scala/src/main/scala/whisk/http/ErrorResponse.scala, core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala, core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala, core/controller/src/main/scala/whisk/core/controller/Packages.scala, core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala, core/controller/src/main/scala/whisk/core/entitlement/PackageCollection.scala, tests/src/whisk/core/cli/test/WskEntitlementTests.scala, tests/src/whisk/core/controller/test/AuthorizeTests.scala, tests/src/whisk/core/controller/test/PackagesApiTests.scala
Add tests for binding a private package or trying to get properties of private packages.
=> Fix gaps in package entitlement.

ansible/apigateway.yml, ansible/roles/apigateway/tasks/clean.yml, ansible/roles/apigateway/tasks/deploy.yml, ansible/roles/apigateway/tasks/main.yml, ansible/roles/redis/tasks/clean.yml, ansible/roles/redis/tasks/deploy.yml, ansible/roles/redis/tasks/main.yml
- scope it for now to apigateway host
- created redis role and add check
=> update apigateway ansible deploy

tests/dat/actions/emptyJSONResult.js, tests/src/system/basic/WskBasicTests.scala, tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk/whisk/activation.go
- Do not display the result field from an activation record if it empty
Closes https://github.com/openwhisk/openwhisk/issues/1467
=> Omit Result from Activation if Empty

ansible/roles/apigateway/tasks/deploy.yml, ansible/roles/consul/tasks/deploy.yml, ansible/roles/couchdb/tasks/deploy.yml, ansible/roles/kafka/tasks/deploy.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/prereq/tasks/clean.yml, ansible/roles/prereq/tasks/deploy.yml, ansible/roles/redis/tasks/deploy.yml
running an experiment for Travis build
=> Fix Travis build by explicit docker pull and pinning requests to 2.10.0

ansible/group_vars/all, ansible/roles/consul/tasks/deploy.yml, ansible/roles/couchdb/tasks/deploy.yml, ansible/roles/kafka/tasks/deploy.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/redis/tasks/deploy.yml
=> Pin image versions and move them to ansible config

tests/src/whisk/core/cli/test/WskBasicUsageTests.scala, tools/cli/go-whisk-cli/commands/api.go, tools/cli/go-whisk-cli/commands/commands.go, tools/cli/go-whisk-cli/commands/flags.go, tools/cli/go-whisk-cli/commands/util.go, tools/cli/go-whisk-cli/commands/wsk.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json, tools/cli/go-whisk/whisk/api.go, tools/cli/go-whisk/whisk/client.go
- Initial CLI changes to support API GW
- Negative usage tests for now (positive tests awaiting local API GW - coming soon)
=> API GW CLI Updates

ansible/roles/consul/tasks/deploy.yml, ansible/roles/consul/templates/config.json.j2
=> start consul as server to fix restartability

tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/commands/package.go, tools/cli/go-whisk-cli/commands/rule.go, tools/cli/go-whisk-cli/commands/trigger.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
- Inform users that an entity will be created if it does not exist when an update command is executed
Closes https://github.com/openwhisk/openwhisk/issues/1151
=> Display Proper Message for Update Command Usage

ansible/roles/routemgmt/files/installRouteMgmt.sh, core/routemgmt/activateApi.js, core/routemgmt/createApi.js, core/routemgmt/createRoute.js, core/routemgmt/deactivateApi.js, core/routemgmt/deleteApi.js, core/routemgmt/getApi.js, core/routemgmt/syncApi.js, tests/build.gradle, tests/src/common/Wsk.scala, tests/src/whisk/core/apigw/actions/test/ApiGwRoutemgmtActionTests.scala, tests/src/whisk/core/cli/test/ApiGwTests.scala, tools/cli/go-whisk-cli/commands/api.go, tools/cli/go-whisk/whisk/action.go, tools/cli/go-whisk/whisk/activation.go, tools/cli/go-whisk/whisk/api.go, tools/cli/go-whisk/whisk/client.go, tools/cli/go-whisk/whisk/namespace.go, tools/cli/go-whisk/whisk/package.go, tools/cli/go-whisk/whisk/rule.go, tools/cli/go-whisk/whisk/trigger.go
PR on behave of @mdeuser for APIGW enablement of tests
=> Enable API GW routemgmt action tests

tests/src/whisk/core/controller/test/MetaApiTests.scala
=> Remove duplicate test case

common/scala/src/main/scala/whisk/core/connector/Message.scala, common/scala/src/main/scala/whisk/core/entitlement/Privilege.scala, common/scala/src/main/scala/whisk/core/entity/Identity.scala, core/controller/src/main/scala/whisk/core/controller/Authenticate.scala, core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala, core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala, core/invoker/src/main/scala/whisk/core/container/WhiskContainer.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, tests/src/system/basic/WskSequenceTests.scala, tests/src/whisk/core/cli/test/WskEntitlementTests.scala, tests/src/whisk/core/dispatcher/test/DispatcherTests.scala, tests/src/whisk/core/entity/test/SchemaTests.scala
=> Fix namespace passed to action to be subject namespace not action namespace.

common/scala/src/main/scala/whisk/common/TransactionId.scala, common/scala/src/main/scala/whisk/core/entity/ActivationId.scala, common/scala/src/main/scala/whisk/core/entity/AuthKey.scala, common/scala/src/main/scala/whisk/core/entity/LogLimit.scala, common/scala/src/main/scala/whisk/core/entity/MemoryLimit.scala, common/scala/src/main/scala/whisk/core/entity/Secret.scala, common/scala/src/main/scala/whisk/core/entity/TimeLimit.scala, common/scala/src/main/scala/whisk/core/entity/UUID.scala, common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala, core/actionProxy/invoke.py, core/controller/src/main/scala/whisk/core/controller/Meta.scala, core/controller/src/main/scala/whisk/core/controller/actions/PostActionActivation.scala, core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala, core/invoker/src/main/scala/whisk/core/container/ContainerUtils.scala, core/invoker/src/main/scala/whisk/core/container/WhiskContainer.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, core/nodejsActionBase/runner.js, tests/src/whisk/core/controller/test/ActivationsApiTests.scala, tests/src/whisk/core/controller/test/AuthenticateTests.scala, tests/src/whisk/core/controller/test/AuthenticateV2Tests.scala, tests/src/whisk/core/controller/test/ControllerTestCommon.scala, tests/src/whisk/core/controller/test/PackagesApiTests.scala, tests/src/whisk/core/controller/test/RulesApiTests.scala, tests/src/whisk/core/limits/ActionLimitsTests.scala
Also fix couple of defects with container test script and allow for main to be specified.
pg2/829 approved.
=> Remove remaining apply() to String.

ansible/README.md, tools/db/README.md
=> Fix broken link.

docs/apigateway.md, docs/catalog.md, docs/mobile_sdk.md, docs/reference.md, docs/triggers_rules.md
- additions for apigateway for swagger file configuration
- additions to let the user know to use openwhisk npm package
- Other changes for formatting and typos.
=> update docs for apigateway and other minor changes

common/scala/src/main/scala/whisk/core/database/ArtifactStoreExceptions.scala, common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala, common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala, core/controller/src/main/scala/whisk/core/controller/Actions.scala, core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala, core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala, core/controller/src/main/scala/whisk/core/controller/Entities.scala, core/controller/src/main/scala/whisk/core/controller/Namespaces.scala, core/controller/src/main/scala/whisk/core/controller/Packages.scala, core/controller/src/main/scala/whisk/core/controller/Rules.scala, core/controller/src/main/scala/whisk/core/controller/Triggers.scala, tests/src/whisk/core/controller/test/ActivationsApiTests.scala
=> Remove throwable's message from HTTP response on 500 codes.

docs/apigateway.md, docs/reference.md
- update `wsk api` with `wsk api-experimental`
- remove redundant digit, since already stating alphanumeric
=> various minor updates for docs

ansible/group_vars/all
=> Do not retrieve new git revisions by default for openwhisk-catalog

common/scala/build.gradle
Getting the latest bugfixes is goodness 👍
=> Bump akka and spray dependencies

ansible/files/auth_index.json, ansible/logs.yml, ansible/tasks/initdb.yml, tests/src/whisk/core/admin/WskAdminTests.scala, tools/admin/wskadmin, tools/vagrant/README.md
Fixes #1132.
Fixes #1748.
PG1/1084, PG2/913, PG3/185 all approved.
PG1/1085, PG2/915, PG3/186 re-approved.
=> Add namespace CRUD operations for wskadmin.

core/swift3Action/spm-build/Whisk.swift
This fixes Issues #1777, #1752. 
- add url encoding to the uri path of the Whisk object's REST calls to avoid issues
- remove errant log statement in Whisk object that printed out communication details
=> Add url encoding to Whisk Object in Swift 3 container

ansible/group_vars/all
per @rabbah 's request, increase the max allowed for sequences to 50.
=> Bump sequence max length to 50

tests/src/common/Wsk.scala, tests/src/whisk/core/cli/test/ApiGwTests.scala, tools/cli/go-whisk-cli/commands/api.go, tools/cli/go-whisk-cli/commands/util.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json, tools/cli/go-whisk/whisk/util.go
=> Fix CLI `api-experimental list` column alignment

core/controller/src/main/scala/whisk/core/controller/Entities.scala, core/controller/src/main/scala/whisk/core/controller/Meta.scala, tests/src/whisk/core/controller/test/MetaApiTests.scala
Limits formdata and post body earlier rather than later. I missed this earlier it should've been part of this commit https://github.com/openwhisk/openwhisk/commit/a81de9af10fba35c55598a2d52b7feada2d13727. It might be helpful to look at the changes ignoring white space: https://github.com/openwhisk/openwhisk/pull/1798/files?w=1.
PG2/1003.
=> Add entity limit test for meta route.

README.md
=> Update Readme to point to new Slack

ansible/roles/nginx/templates/nginx.conf.j2, core/controller/src/main/resources/application.conf, core/invoker/src/main/resources/application.conf, tests/src/whisk/core/cli/test/WskWebActionsTests.scala
Enable auto-timeouts. Remove unnecessary server configuration in invoker.
=> Tweak server configurations.

docs/apigateway.md
Just a tiny fix for CLI configuration broken link
=> Fix broken link

tests/src/common/WskTestHelpers.scala, tests/src/system/basic/WskActionTests.scala, tools/cli/go-whisk-cli/commands/action.go
- When copying an action ensure that parameters and annotations are also copied
Closes https://github.com/openwhisk/openwhisk/issues/418
=> Include Parameters and Annotations when Copying an Action

common/scala/src/main/scala/whisk/core/database/CloudantRestClient.scala, common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala, tests/src/whisk/core/database/test/ExtendedCouchDbRestClient.scala, tests/src/whisk/core/database/test/ReplicatorTests.scala
=> Harden replication test

docs/feeds.md
first pull request -  just to get my feet wet
=> Minor corrections for spaces and new lines in the feeds.md doc

ansible/group_vars/all, ansible/templates/whisk.properties.j2, common/scala/src/main/scala/whisk/core/WhiskConfig.scala, core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala, core/invoker/src/main/scala/whisk/core/container/RuncUtils.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
This causes the invoker to perform a dynamic runc flag guarded by a useRunc configuration deployment flag. PG2-1041
=> Add runc flag

core/invoker/src/main/scala/whisk/core/container/ContainerUtils.scala, tests/dat/actions/openFiles.js, tests/src/whisk/core/limits/ActionLimitsTests.scala
Tightened tests.
Replaces #1716 which seems to be stagnating.
PG1/1156.
=> Tweak tests in pr#1716, set fileHandleLimit to 1024

docs/README.md
=> README.md updates

tools/build/scanCode.py
Complete spell check ran against source file, fixed all typos and corrected alignment (leading spacing) of license header in comment block.
=> Update scanCode.py - fix typos/spacing identified in previous PR

ansible/roles/invoker/tasks/deploy.yml, core/invoker/Dockerfile
=> Issue 1879 invoker socket

docs/actions.md
* Add links to the other sections at the bottom of the actions document so that they can be found
* Add a section about listing actions using the cli tool
=> Action document improvements

tests/src/whisk/core/limits/MaxActionDurationTests.scala
Do we really need this test?
If yes, what about paralleling it?
=> Reduce time to execute tests by 10 minutes

common/scala/src/main/scala/whisk/core/entity/Exec.scala, common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala, core/actionProxy/actionproxy.py, core/actionProxy/invoke.py, core/javaAction/proxy/src/main/java/openwhisk/java/action/Proxy.java, tests/src/actionContainers/ActionContainer.scala, tests/src/actionContainers/ActionProxyContainerTests.scala, tests/src/actionContainers/JavaActionContainerTests.scala, tests/src/whisk/core/entity/test/SchemaTests.scala
Further normalization of the `Exec` types.
=> Normalize initializer for all execs.

core/nodejs6Action/Dockerfile, docs/reference.md
updating only nodejs6 npm openwhisk library
=> updating openwhisk npm package

core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, tests/src/test/scala/whisk/core/container/test/ContainerPoolTests.scala
=> Remove unused verosity variables

tests/src/test/scala/actionContainers/PythonActionContainerTests.scala
A more surgical approach than https://github.com/openwhisk/openwhisk/pull/1975
=> testEcho() now works with Python 2 and Python 3

tools/vagrant/README.md
Fix up a couple of points @csantanapr raised in #1989.
=> Tidy up Vagrant docs about insecure use of wsk

ansible/environments/local/group_vars/all, ansible/environments/mac/group_vars/all, ansible/roles/invoker/tasks/deploy.yml, ansible/templates/whisk.properties.j2, core/invoker/Dockerfile, core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala
=> use runc to unpause if needed

tools/admin/wskadmin
finding myself having to do get tid twice, once for controller, once for invoker: this makes those default, hence can grab tid logs from both at once.
=> Add controller and invoker0 as default components for syslog get

core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala, tests/src/test/scala/system/basic/WskSequenceTests.scala
Update test accordingly.
This is a fix for #1822 
Note that I left the scanLeft unchanged. I'd rather do the "optimization" refactoring in a different pass since it's  a lot more involved than current change. I'm guessing we'd like to promote this change soonish.
=> Treat error field differently if present in the initial payload to a sequence

ansible/files/filter_design_document.json, ansible/tasks/db/actionsDbViews.yml, ansible/tasks/db/filterViews.yml, ansible/tasks/initdb.yml, tests/src/test/scala/whisk/core/database/test/ExtendedCouchDbRestClient.scala, tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala, tools/db/replicateDbs.py
Use filter to avoid design-documents and deleted documents in snapshots.
=> Replicate db

core/actionProxy/actionproxy.py, core/swift3Action/Dockerfile, core/swift3Action/swift3runner.py, tests/dat/actions/unicode2.py, tests/dat/actions/unicode3.py, tests/src/test/scala/actionContainers/ActionProxyContainerTests.scala, tests/src/test/scala/actionContainers/NodeJsActionContainerTests.scala, tests/src/test/scala/actionContainers/PythonActionContainerTests.scala, tests/src/test/scala/actionContainers/SwiftActionContainerTests.scala, tests/src/test/scala/system/basic/WskUnicodeTests.scala, tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk/whisk/action.go, tools/travis/build.sh
This replaces #2069 (was rebased on  pr #1903).
Fixes #362.
PG2/1327 🔵
=> fix unicode handling for swift and python 2 actions

tools/jenkins/apache/dockerhub.groovy
=> add jenkinsfile to push images to dockerhub from apache jenkins server

tools/jenkins/apache/dockerhub.groovy
fix the push for couchdb-snapshot
=> push couchdb-snapshot docker image from jenkins

ansible/environments/distributed/group_vars/all, ansible/environments/local/group_vars/all, ansible/environments/mac/group_vars/all, ansible/roles/routemgmt/files/installRouteMgmt.sh, ansible/roles/routemgmt/files/uninstallRouteMgmt.sh, ansible/templates/whisk.properties.j2, core/routemgmt/common/apigw-utils.js, core/routemgmt/createApi/createApi.js, core/routemgmt/deleteApi/deleteApi.js, core/routemgmt/getApi/getApi.js, tests/src/test/scala/whisk/core/apigw/actions/test/ApiGwRoutemgmtActionTests.scala
Update backend actions to add support for the "V2" API GW interface
- New package for actions configured without whisk authentication annotation
- Updated action tests
- Ansible updates to add a new V2 API GW host property
Partial replacement for PR #2031.  A separate PR for only CLI changes will complete the replacement.
=> API GW V2 - Update backend actions

core/swift3Action/spm-build/WhiskJsonUtils.swift
Fixes issue #2144 -- update code to use JSONSerialization to create strings to improve performance.
=> Use JSONSerialization to create json strings in swift3Action

tests/src/test/scala/common/Wsk.scala, tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/system/basic/WskRuleTests.scala, tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/commands/activation.go, tools/cli/go-whisk-cli/commands/package.go, tools/cli/go-whisk-cli/commands/rule.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
- Display entity names for actions and packages when deleting
- Add tests to ensure proper failure when deleting entities that do not exist
Closes: https://github.com/openwhisk/openwhisk/issues/2019
=> Make Error Messages Consistent in CLI

core/controller/src/main/scala/whisk/core/controller/WebActions.scala, docs/actions.md, docs/webactions.md, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
=> Remove 'OK' from HTTP response when no 'body' is present.

tests/src/test/scala/system/basic/WskBasicTests.scala, tools/cli/go-whisk-cli/commands/trigger.go
- Dissociate a feed from a trigger before a trigger is deleted
=> Delete Trigger Feed Before Trigger

tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala, tools/db/replicateDbs.py
This PR adds the ability to exclude some databases from the backup with the exclude parameter.
In addition it improves deletion of old replication design documents.
=> Add exclude parameter to replication script

tests/src/test/scala/whisk/consul/ConsulClientTests.scala
=> Replace sleep with retry in Consul test

ansible/roles/couchdb/tasks/deploy.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/tasks/db/recreateDb.yml, ansible/tasks/db/recreateDoc.yml
=> Remove ansible templating warnings

docs/reference.md, docs/rest_api.md
=> Rest api docs chapter content

tools/cli/go-whisk-cli/commands/api.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json, tools/cli/go-whisk/whisk/client.go
Base CLI http changes to allow for custom error response body parsing
=> API GW CLI SSO support

tests/src/test/scala/system/basic/WskBasicPythonTests.scala
Bump activation polling total timeout to accommodate occasional database delays
Fixes #2224
=> Bump "Python virtualenv" test timeout

.github/ISSUE_TEMPLATE.md, README.md, ansible/README.md, core/controller/src/main/scala/whisk/core/controller/Controller.scala, docs/about.md, docs/catalog.md, tools/jenkins/apache/dockerhub.groovy, tools/ubuntu-setup/README.md, tools/vagrant/README.md
=> replace github refs openwhisk to apache

tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
`DockerContainerTests` were the only of the new suites still partly using `ScalaFutures`. This aligns everything (the tests have failed with a timeout on a weak machine).
=> Align future timeouts in DockerContainer tests

tools/db/cleanUpActivations.py, tools/travis/flake8.sh
* https://docs.python.org/3.3/whatsnew/3.0.html#integers
* https://www.python.org/dev/peps/pep-0237
=> Define `long` integer for Python 3

common/scala/Dockerfile, core/javaAction/Dockerfile
FYI @sven-lange-last 
FYI @bjustin-ibm
=> Update JDK version to 8.131.11

ansible/roles/kafka/tasks/clean.yml
remove kafka volume when clean up
=> remove kafka volume when clean up

README.md
=> update travis badge to point to apache

core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala, core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
Use `scheduleOnce` in combination with a `WeakReference` to avoid timeout handlers holding on to ActivationRecords long after the activations have successfully completed
Fixes #2292 
Fixes #2293 
PG2 1604 🔵 
PG4 289 🔵
=> Fix memory drag in LoadBalancer and PrimitiveActions

ansible/environments/distributed/group_vars/all, ansible/environments/local/group_vars/all, ansible/environments/mac/group_vars/all, ansible/group_vars/all, ansible/roles/cli/tasks/clean.yml, ansible/roles/cli/tasks/deploy.yml, ansible/roles/cli/tasks/main.yml, ansible/roles/consul/tasks/clean.yml, ansible/roles/consul/tasks/deploy.yml, ansible/roles/consul/tasks/main.yml, ansible/roles/nginx/tasks/clean.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/nginx/tasks/main.yml, ansible/roles/registry/tasks/deploy.yml, ansible/roles/registry/templates/recycle-registry.py.j2, ansible/roles/routemgmt/tasks/clean.yml, ansible/roles/routemgmt/tasks/deploy.yml, ansible/roles/sdk/tasks/clean.yml, ansible/roles/sdk/tasks/deploy.yml, ansible/tasks/installOpenwhiskCatalog.yml, ansible/templates/whisk.properties.j2
Rework dir-variables in ansible to avoid duplication in every environment.
=> Rework config-dir variables

tests/src/test/scala/common/TestUtils.java, tests/src/test/scala/common/Wsk.scala
Update test framework to allow stdin input from a file
=> Support interactive cli testing via input file

tools/vagrant/README.md
Fix a small error in vagrant document.
=> Fix a small error in /tools/vagrant/README.md

tools/build/ASFLicenseHeader.txt, tools/build/ApacheIBMLicenseHeader.txt, tools/build/README.md, tools/build/scanCode.cfg, tools/build/scanCode.py, tools/travis/build.sh
Reverts apache/incubator-openwhisk#2325
using the Github button 🤣
=> Revert "Run scancode utility from the utility repo/project"

ansible/README_DISTRIBUTED.md, ansible/environments/distributed/files/openstack/README_OS.md, ansible/environments/distributed/files/openstack/openstack.env
Making a few changes to the Readme to make the scripts more IaaS generic. Also moved Openstack specific references/dependencies to a separate document
=> Updating readme for distributed deployment

tools/ubuntu-setup/all.sh, tools/ubuntu-setup/ansible.sh, tools/ubuntu-setup/docker.sh, tools/ubuntu-setup/java8.sh, tools/ubuntu-setup/misc.sh, tools/ubuntu-setup/pip.sh, tools/ubuntu-setup/scala.sh
running the scripts sequentially didn't add more than a minute
it will make vagrant fail on first error
printing commands when executing helps for debugging
adding the installation of libssl-dev to fix problem installing python-dev
=> have ubuntu setup scripts error on first error

tools/ubuntu-setup/all.sh
=> add back SCRIPTDIR to ubuntu all.sh

tests/src/test/scala/whisk/core/cli/test/SwiftTests.scala
...until the failure root cause is identified and fixed
/cc @paulcastro
=> Ignore broken swift3 sdk tests

tests/src/test/scala/whisk/core/cli/test/SwiftTests.scala
This reverts commit bdc40d81ff7b84bd614f804c216a3ad256709b27.
=> Put back swift tests

docs/actions.md, tests/src/test/scala/common/Wsk.scala, tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala, tools/cli/Dockerfile, tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/commands/flags.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
Add native action for binary injection.
Proposed fix for #2011.
=> Allow docker actions with zip files. 

ansible/roles/apigateway/tasks/deploy.yml, ansible/roles/cli/tasks/deploy.yml, ansible/roles/consul/tasks/deploy.yml, ansible/roles/controller/tasks/deploy.yml, ansible/roles/couchdb/tasks/deploy.yml, ansible/roles/invoker/tasks/deploy.yml, ansible/roles/kafka/tasks/deploy.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/redis/tasks/deploy.yml, ansible/roles/registry/tasks/deploy.yml
=> Add retries to all docker pull commands in ansible

common/scala/src/main/scala/whisk/core/entity/InstanceId.scala, tests/dat/actions/TimedOut.java, tests/dat/actions/unicode/src/main/java/Unicode.java, tests/src/test/scala/whisk/core/controller/actions/test/SequenceAccountingTests.scala, tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerServiceObjectTests.scala, tests/src/test/scala/whisk/utils/test/ExecutionContextFactoryTests.scala
Some new scala files were added with the old license.
=> Fix licenses on scala and java files.

tools/build/README.md, tools/travis/build.sh
Phase 1: Reference Travis to new home of scancode, but preserve one here until confirmed.
=> Reference scancode from utils repo. but preserve local copy (phase 1)

ansible/group_vars/all, ansible/roles/invoker/tasks/deploy.yml, tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
=> docker pull invoker images runtimes from manifest

.gitignore
=> ignore *.class with .gitignore

core/controller/src/main/scala/whisk/core/controller/WebActions.scala, tests/dat/actions/corsHeaderMod.js, tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Fixes: https://github.com/apache/incubator-openwhisk/issues/2443
=> Display CORS Headers for Non-Options Requests (Review)

common/scala/src/main/scala/whisk/core/entity/Identity.scala, core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala, core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala, core/controller/src/main/scala/whisk/core/entitlement/RateThrottler.scala, core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala, docs/reference.md, tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala, tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala, tests/src/test/scala/whisk/core/controller/test/RateThrottleTests.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Fixes https://github.com/apache/incubator-openwhisk/issues/2266.
=> Normalize rate checks to the identity namespace (uuid).

common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
Searching for Kafka
https://github.com/apache/incubator-openwhisk/search?utf8=%E2%9C%93&q=KafkaConnectorTest&type=
no results
https://github.com/apache/incubator-openwhisk/search?utf8=%E2%9C%93&q=KafkaConnectorTests&type=
finds the class.
=> Fix reference to a class in inline comment

core/routemgmt/common/apigw-utils.js, core/routemgmt/common/utils.js, core/routemgmt/createApi/createApi.js, core/routemgmt/deleteApi/deleteApi.js, core/routemgmt/getApi/getApi.js, tests/src/test/scala/whisk/core/apigw/actions/test/ApiGwRoutemgmtActionTests.scala, tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala, tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
- Do not enforce need for gwUrl parameter in api gw actions
- Enable http redirect forwarding
Fixes #2318
=> API GW V2 updates

docs/actions.md, tests/src/test/scala/common/Wsk.scala, tests/src/test/scala/common/WskTestHelpers.scala, tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/system/basic/WskSequenceTests.scala, tools/cli/build.gradle, tools/cli/go-whisk-cli/commands/activation.go, tools/cli/go-whisk-cli/commands/flags.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json, tools/cli/go-whisk/whisk/activation.go
Added flag  "--last" or "-l" in the CLI that gets the most recent activation id for activation's get, logs and result. Closes https://github.com/apache/incubator-openwhisk/issues/1498
=> (Review) Added --last Activation Flag 

docs/actions.md, docs/webactions.md
Document how to get an action and web action URL.
=> Doc Action URL CLI Flag

core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
The closure doesn't keep a reference to the entire result anymore and is decoupled by the timeout handler through the underlying state-map. The WeakReference is not needed anymore and can actually cause failures if a garbage collection happens in between creating and getting the reference in this case.
=> Remove unneeded WeakReference.

core/controller/src/main/scala/whisk/core/controller/Actions.scala
Checking proper package access rights is done on a deeper level. Disambiguating here is redundant.
=> Remove redundancy in entitlement checks.

tools/macos/README.md, tools/macos/docker-machine/README.md, tools/ubuntu-setup/README.md
Just fix broken links for setting up cli.
=> Fix broken link for setting up the openwhisk cli

tests/src/test/scala/apigw/healthtests/ApiGwEndToEndTests.scala
- Also improve logging for troubleshooting
=> Add increased timout to api gw end-to-end test

tests/src/test/scala/system/basic/WskRuleTests.scala, tools/cli/go-whisk-cli/commands/rule.go, tools/cli/go-whisk-cli/commands/util.go
The output looks like this now
```
rules
/guest/rule-hello2                                                     private              active
/guest/rule-hello                                                       private              inactive
```
Fixes #312
Still working on test cases for this, just creating the pull request for feedback
=> Adding status of rule to output. 

tools/jenkins/apache/dockerhub.groovy
=> exclude H22 problematic node in apache jenkins

README.md, tools/vagrant/README.md
Updated the main README file to reflect the need for an ssh client to be installed on Windows machines.
=> Readme update

ansible/registry.yml, ansible/roles/cli/tasks/clean.yml, ansible/roles/controller/tasks/clean.yml, ansible/roles/controller/tasks/deploy.yml, ansible/roles/docker/tasks/clean.yml, ansible/roles/docker/tasks/deploy.yml, ansible/roles/invoker/tasks/clean.yml, ansible/roles/invoker/tasks/deploy.yml, ansible/roles/nginx/tasks/clean.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/prereq/tasks/clean.yml, ansible/roles/prereq/tasks/deploy.yml, ansible/roles/registry/tasks/clean.yml, ansible/roles/registry/tasks/deploy.yml, ansible/roles/sdk/tasks/clean.yml, tools/travis/build.sh
I'm not sure why the privilege escalation is needed - suggesting we remove them.
PG2/1868 🔵 
@jeremiaswerner @markusthoemmes @csantanapr could you sanity check please.
=> Remove privilege escalation.

ansible/registry.yml, ansible/roles/cli/tasks/clean.yml, ansible/roles/controller/tasks/clean.yml, ansible/roles/controller/tasks/deploy.yml, ansible/roles/docker/tasks/clean.yml, ansible/roles/docker/tasks/deploy.yml, ansible/roles/invoker/tasks/clean.yml, ansible/roles/invoker/tasks/deploy.yml, ansible/roles/nginx/tasks/clean.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/prereq/tasks/clean.yml, ansible/roles/prereq/tasks/deploy.yml, ansible/roles/registry/tasks/clean.yml, ansible/roles/registry/tasks/deploy.yml, ansible/roles/sdk/tasks/clean.yml, tools/travis/build.sh
This reverts commit 97aba7136fa81c3d5accbbb1a32a3a83304af1b3.
=> Revert "Remove privilege escalation. (#2536)"

core/routemgmt/common/apigw-utils.js, core/routemgmt/createApi/createApi.js, core/routemgmt/deleteApi/deleteApi.js, core/routemgmt/getApi/getApi.js
- Set the User-Agent header to "OpenWhisk CLI" to better indicate the client context to the API GW
- jshint fixes
=> Set user agent header in API GW requests

ansible/environments/docker-machine/group_vars/all
Apparently got lost while adding Docker for Mac.
=> Add JMX arguments to docker-machine again.

.gitignore, common/scala/build.gradle
This PR updates the zookeeper library.
In addition, it updates the .gitignore to add own environments without poluting local git.
=> Update dependencies and gitignore

tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala, tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/commands/activation.go, tools/cli/go-whisk-cli/commands/api.go, tools/cli/go-whisk-cli/commands/commands.go, tools/cli/go-whisk-cli/commands/namespace.go, tools/cli/go-whisk-cli/commands/package.go, tools/cli/go-whisk-cli/commands/property.go, tools/cli/go-whisk-cli/commands/rule.go, tools/cli/go-whisk-cli/commands/sdk.go, tools/cli/go-whisk-cli/commands/shared.go, tools/cli/go-whisk-cli/commands/trigger.go, tools/cli/go-whisk-cli/commands/util.go, tools/cli/go-whisk/whisk/action.go, tools/cli/go-whisk/whisk/activation.go, tools/cli/go-whisk/whisk/api.go, tools/cli/go-whisk/whisk/client.go, tools/cli/go-whisk/whisk/info.go, tools/cli/go-whisk/whisk/namespace.go, tools/cli/go-whisk/whisk/package.go, tools/cli/go-whisk/whisk/rule.go, tools/cli/go-whisk/whisk/sdk.go, tools/cli/go-whisk/whisk/shared.go, tools/cli/go-whisk/whisk/trigger.go, tools/cli/go-whisk/whisk/util.go, tools/cli/go-whisk/whisk/wskerror.go
Closes https://github.com/apache/incubator-openwhisk/issues/2428
=> Ensure Action Update Creates a Web Action (Review)

ansible/environments/distributed/group_vars/all, ansible/environments/distributed/hosts, ansible/roles/cli/tasks/copy_local_openwhisk_cli.yml, ansible/roles/cli/tasks/deploy.yml
Here's some minor changes for deploying ow in distributed environment.
Without these changes, you may fail in deploying with 'environment/distributed' in latest version.
=> Fix ansible script for distributed environment

common/scala/src/main/scala/whisk/http/BasicHttpService.scala, core/controller/src/main/scala/whisk/core/controller/Controller.scala, core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, core/invoker/src/main/scala/whisk/core/invoker/InvokerServer.scala
@dubeejw I think this works and avoid the actor conflation in the http service.
=> Remove unnecessary Actor conflation and simplify BasicHTTPService

tools/cli/README.md
Add information on how to build the CLI binaries for the other platforms.
=> Update CLI readme with cross platform information

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
Multiple concurrent calls of `docker pull` to the same image create unnecessary network traffic. Instead, all of those calls are collapsed into the first calls. After that call finished, a subsequent pull will result in a `docker pull` again to enable updates to the same image, without having to work with tags for convenience.
=> Collapse multiple concurrent pulls of the same image.

core/controller/src/main/scala/whisk/core/controller/WebActions.scala, tests/dat/actions/base64Web.js, tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Closes https://github.com/apache/incubator-openwhisk/issues/2612
=> Fix Illegal Header Warnings

tests/src/test/scala/common/Wsk.scala
This a small code improvement PR
* Add try/catch to prevent possible resource leak
* Removed unnecessary braces for string interpolation
=> Small Wsk.scala test improvement

core/controller/src/main/scala/whisk/core/controller/Triggers.scala
=> Patch posting of trigger activation.

core/controller/src/main/scala/whisk/core/controller/WebActions.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
=> Loosen formdata check.

tools/jenkins/apache/dockerhub.groovy
=> remove nodes and clean ansible/couchdb

common/scala/src/main/scala/whisk/http/BasicHttpService.scala
The way those directives worked changed a bit. Unfortunately they were poorly typed so that didn't get caught.
Reordering the directives causes only `Complete` requests should reach the DebuggingDirectives.
@dubeejw would you please review?
=> Readd BasicHttpService log line

common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala, common/scala/src/main/scala/whisk/http/ErrorResponse.scala, core/controller/src/main/scala/whisk/core/controller/Actions.scala, core/controller/src/main/scala/whisk/core/controller/Activations.scala, core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala, core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala, core/controller/src/main/scala/whisk/core/controller/Entities.scala, core/controller/src/main/scala/whisk/core/controller/Namespaces.scala, core/controller/src/main/scala/whisk/core/controller/Packages.scala, core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala, core/controller/src/main/scala/whisk/core/controller/Rules.scala, core/controller/src/main/scala/whisk/core/controller/Triggers.scala, core/controller/src/main/scala/whisk/core/controller/WebActions.scala, core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
=> Pretty print webaction JSON response.

common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala
We trusted git because there where no conflicts. Meh.
=> Fix compile error because of subsequent merges.

core/controller/src/main/scala/whisk/core/controller/WebActions.scala, tests/dat/actions/pngWeb.js, tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Closes https://github.com/apache/incubator-openwhisk/issues/2682
=> Fix Binary Content-Type Responses for Web Actions

common/scala/src/main/scala/whisk/core/connector/Message.scala, common/scala/src/main/scala/whisk/core/entity/ActivationResult.scala, common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala, core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala, core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala, core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala, core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala, core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala, core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala, core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala, tests/src/test/scala/common/LoggedFunction.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala, tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
This allows non blocking requests to drop their results from the activeack response.
=> Add blocking indicator for activation request.

tests/src/test/scala/apigw/healthtests/ApiGwEndToEndTests.scala, tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
@mdeuser @dubeejw @bpoole16 FYI
=> API gw test cleanup

tests/src/test/scala/ha/CacheInvalidationTests.scala
If we need to retry the condition, `deleteAction` will always fail because the if it succeeded once it will never return `200` again.
=> Fix false assertion, refactor CacheInvalidationTests

ansible/group_vars/all, ansible/roles/cli/tasks/clean.yml, ansible/roles/cli/tasks/deploy.yml, ansible/roles/controller/tasks/clean.yml, ansible/roles/controller/tasks/deploy.yml, ansible/roles/invoker/tasks/clean.yml, ansible/roles/invoker/tasks/deploy.yml, ansible/roles/nginx/tasks/clean.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/sdk/tasks/clean.yml, ansible/roles/sdk/tasks/deploy.yml
This allows to deploy with no sudo/root access.
=> initial work on no root ansible

ansible/roles/whiskhost/tasks/patchKernel.yml
=> fix syntax error in patchKernel.yml

.travis.yml
=> Fix Travis jobs with group: deprecated-2017Q3

docs/rest_api.md, tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala, tools/cli/go-whisk-cli/commands/commands.go, tools/cli/go-whisk/whisk/api.go, tools/cli/go-whisk/whisk/client.go
=> User-Agent CLI/version header

tests/src/test/scala/ha/ShootComponentsTests.scala
Add a test, that checks, that the hot standby controller is used as expected.
PG3#1031 started
=> Add tests to check ha of controller

common/scala/src/main/scala/whisk/core/entity/ActivationResult.scala, core/invoker/src/main/scala/whisk/core/containerpool/docker/HttpUtils.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/ContainerConnectionTests.scala, tests/src/test/scala/whisk/core/entity/test/ActivationResponseTests.scala
=> Disable explicit retry on container http connection.

ansible/roles/couchdb/tasks/deploy.yml
=> Ping couchdb ready by using utils

core/swift3Action/spm-build/_Whisk.swift, tests/dat/actions/createRule.swift, tests/dat/actions/createTrigger.swift, tests/src/test/scala/whisk/core/cli/test/Swift3Tests.scala
Updated name of method for sending Whisk API request.
Cleaned up the parameter naming a little for consistency.
Changed to using guard to check for the trigger name argument
Added additional assertion that the rule created did actually get fired and run ok
Added tests for creating a trigger and a rule
Documentation
Supersedes #2171.
Closes #2156.
PG3/1089 🏃
=> Added functions to create a trigger and create a rule.

core/controller/src/main/scala/whisk/core/controller/WebActions.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Fix the following issues with JSON content types in web actions:
1. base64 encoded bodies with a content-type of `application/patch-json+json` should work.
1. JSON dictionary bodies with a content-type of `application/patch-json+json` should work.
1. base64 encoded bodies with a content-type of `application/hal+json` should work.
1. JSON dictionary bodies with a content-type of `application/hal+json` should work.
I chose these two media types as one is "known" by Akka and one is "unknown" as the behaviour is currently different for each one. 
In practice, all media types that are of the correct format should be acceptable, so this PR fixes that which means that technically, we don't need both sets of unit tests. However, I used both sets to prove that the fix worked when developing it. …
=> Content type header improvements

ansible/group_vars/all
=> allow to override runtimesManifest

core/swift3Action/spm-build/_Whisk.swift, tests/dat/actions/createRule.swift, tests/dat/actions/createTrigger.swift, tests/src/test/scala/whisk/core/cli/test/Swift3Tests.scala
Closes #2156.
PR to add the following to the swift runtime:
- create a trigger
- create a rule
=> Extend Swift SDK with trigger create and rule create

.gitignore
=> update .gitignore out/ for intellij

tools/vagrant/Vagrantfile
=> fix wsk autocomplete for Vagrant

tests/src/test/scala/apigw/healthtests/ApiGwEndToEndTests.scala
=> update apigw end-to-end to be more resilient

tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Adds a unit test that ensures JSON strings, booleans, numbers, and arrays are acceptable body arguments with a `application/json` content type.
=> Test JSON values as web action body arguments

tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/commands/activation.go, tools/cli/go-whisk-cli/commands/api.go, tools/cli/go-whisk-cli/commands/commands.go, tools/cli/go-whisk-cli/commands/namespace.go, tools/cli/go-whisk-cli/commands/package.go, tools/cli/go-whisk-cli/commands/property.go, tools/cli/go-whisk-cli/commands/qualified_name.go, tools/cli/go-whisk-cli/commands/rule.go, tools/cli/go-whisk-cli/commands/sdk.go, tools/cli/go-whisk-cli/commands/trigger.go, tools/cli/go-whisk-cli/commands/util.go, tools/cli/go-whisk-cli/commands/wsk.go, tools/cli/go-whisk/whisk/client.go
@mdeuser These should be the final changes required for this repo to work.
Contains several changes in casing (name -> Name) of names of functions and variables so that they get exported and can be used in other places.
=> Added changes for classes and variables casing to be get exported and can be used in other places

common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala
Currently, each time we try to get a value out of our cache `putIfAbsent` is called, which causes thread-contention. Instead, this uses `computeIfAbsent` which does a `get` first and thus is non-blocking for getting cached values under load.
```scala
object Test {
import scala.concurrent.ExecutionContext.Implicits.global
implicit val as = ActorSystem()
def main(args: Array[String]): Unit = {
val cache: ConcurrentMapBackedCache[String] = new ConcurrentMapBackedCache(
Caffeine
.newBuilder()
.asInstanceOf[Caffeine[Any, Future[String]]]
.expireAfterWrite(5, TimeUnit.MINUTES)
.softValues()
.build()
.asMap())
(1 to 100000000).par.foreach { _ =>
cache.apply("testKey", () => akka.pattern.after(3.seconds, as.scheduler)(Future.successful("test2")))
}
as.terminate()
}
}
```
=> Use non-blocking computation of cache values.

tools/db/README.md
Fixed links for couchdb and cloudant
=> Fix links for couchdb and cloudant

docs/cli.md
=> add workaround for inserting space on autocomplete on Mac

tests/src/test/scala/ha/CacheInvalidationTests.scala, tests/src/test/scala/whisk/core/cli/test/WskEntitlementTests.scala, tests/src/test/scala/whisk/core/controller/test/PackageActionsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/SequenceApiTests.scala, tests/src/test/scala/whisk/core/controller/test/migration/SequenceActionApiMigrationTests.scala, tests/src/test/scala/whisk/core/database/test/DbUtils.scala
=> delete test assets

tools/jenkins/apache/dockerhub.groovy
=> only build invoker and controller

tests/src/test/scala/common/BaseWsk.scala, tests/src/test/scala/common/WhiskProperties.java, tests/src/test/scala/common/Wsk.scala, tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala, tools/cli/go-whisk-cli/commands/action.go, tools/cli/go-whisk-cli/commands/flags.go, tools/cli/go-whisk-cli/commands/util.go, tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json, tools/cli/go-whisk/whisk/action.go
- Prototype that allows the CLI to extract the code from an action and save that code on the local system
Usage:
`wsk action get ACTION_NAME --save`
`wsk action get ACTION_NAME --save-as FILE_NAME`
=> Allow CLI to Save Code from Action

tests/src/test/scala/whisk/core/database/test/BatcherTests.scala
In an environment with no parallelism some assertion do not hold water which makes this test non-deterministic. Adding a bit of a delay between batching calls allows the batch to build up.
Nice datapoint: I ran the old version of this test locally 30.000 times (thirty-thousand!). Not. A. Single. Failure.
We might want to have one Travis build which runs the test a thousand times, just to be sure.
=> Add batching time to BatcherTests.

tests/src/test/scala/whisk/core/cli/test/WskConfigTests.scala, tools/cli/go-whisk-cli/commands/util.go
=> Fix issue with trailing spaces and handle comments in the property file.

core/nodejs6Action/Dockerfile, docs/reference.md
=> Update nodejs to 6.11.4

core/javaAction/Dockerfile, docs/actions.md
Doc change for https://github.com/apache/incubator-openwhisk-runtime-java/pull/2
=> Added support for configurable java action method name.

tests/build.gradle, tests/src/test/scala/common/WskTestHelpers.scala, tests/src/test/scala/system/basic/WskActionTests.scala, tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/system/basic/WskCliActionTests.scala, tests/src/test/scala/system/basic/WskCliPackageTests.scala, tests/src/test/scala/system/basic/WskPackageTests.scala, tests/src/test/scala/system/basic/WskRestActionTests.scala, tests/src/test/scala/system/basic/WskRestPackageTests.scala
=> Replace the test cases of action and package with REST implementation

tools/cli/build.gradle
@bpoole16 is experiencing CLI build issues. Attempting to resolve those issues.
=> Ensure Proper Order of CLI Build Tasks

tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala, tools/db/replicateDbs.py
With our current replication skript, we are only able to exclude databases by its name, but not by its base-name. This means, that if a database has a suffix, it has to be excluded explicitly. 
With this PR, these databases can be excluded by their base name.
=> Be able to exclude databases by basename in replication

common/scala/build.gradle, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
Add optional command line argument for invoker name
and invoker proposed id to support Mesos deployment
(see issue https://github.com/apache/incubator-openwhisk/issues/2872).
=> invoker cmd line support for dyanamicId assignment

tests/src/test/scala/system/basic/WskSdkTests.scala, tests/src/test/scala/whisk/core/cli/test/WskConfigTests.scala, tools/cli/go-whisk/whisk/client.go, tools/cli/go-whisk/whisk/info.go, tools/cli/go-whisk/whisk/sdk.go, tools/cli/go-whisk/wski18n/resources/en_US.all.json
=> Add the support of certificate checking for secure mode

common/scala/src/main/scala/whisk/http/BasicHttpService.scala
One line that should have gone to this PR https://github.com/apache/incubator-openwhisk/pull/2930/
=> Emit an additional counter metric for http service

common/scala/src/main/scala/whisk/http/ErrorResponse.scala, core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala, core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala, tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/whisk/core/controller/test/EntitlementProviderTests.scala, tests/src/test/scala/whisk/core/controller/test/PackageActionsApiTests.scala
=> Better error controller message for authorization failure

ansible/roles/controller/tasks/deploy.yml
Creates a heap dump in the /logs directory when an out of memory exception occurs.
=> Create heap dump when OOM exceptions occur in the controller

actionRuntimes/nodejs6Action/Dockerfile, docs/reference.md
- node 6.11.4 -> 6.12
- openwhisk 3.9 -> 3.10
- doc updates
🔵 PG3 1349
=> update to nodejs 6.12

ansible/group_vars/all, ansible/logs.yml, common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala, common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala, core/controller/src/main/scala/whisk/core/controller/Activations.scala, tests/src/test/scala/common/rest/WskRest.scala, tests/src/test/scala/system/basic/WskConsoleTests.scala, tests/src/test/scala/system/basic/WskRuleTests.scala, tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
=> Enable v2 views

ansible/environments/distributed/group_vars/all, ansible/environments/docker-machine/group_vars/all, ansible/environments/local/group_vars/all, ansible/roles/nginx/tasks/clean.yml
This makes it much easier to delete all configuration with only one command.
=> Change the confdir for the default environments.

tests/src/test/scala/whisk/core/admin/WskAdminTests.scala, tools/admin/README.md, tools/admin/wskadmin, tools/vagrant/README.md
Added README describing `wskadmin` and examples how to use it.
Also added utility for listing all namespaces for a subject.
Fixes #2889.
=> Enhance wskadmin to list all spaces for a subject and add README

ansible/environments/local/hosts
this will help get Travis back green, while we look into fixing #3026 and #3016 which will require to have session stickiness in controllers.
=> use 1 controller in travis/local env

actionRuntimes/actionProxy/invoke.py, docs/reference.md
Also update docs for max result size.
Closes #1832.
=> Update invoke.py to reflect changes in repository

ansible/README.md
I wrote down current limitation on CouchDB clustering.
This is to inform those who may face similar issue to this : https://github.com/apache/incubator-openwhisk/issues/3029
=> Add guide about limitation on couchdb clustering

ansible/roles/nginx/templates/nginx.conf.j2
Some minor changes in nginx. Further changes to improve performance will follow.
=> Minor nginx changes

core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
Using mutable datastructures, especially closing over them in Futures, is dangerous and non-deterministic. This aims to further terse down the logic used as well.
=> Refactored EntitlementProvider to not contain mutability.

actionRuntimes/actionProxy/invoke.py
The arg parsing preserves existing behavior of init and run.
```bash
usage: invoke.py [-h] [-v] [--host HOST] [-p PORT] {init,run} ...
initialize and run an OpenWhisk action container
optional arguments:
-h, --help            show this help message and exit
-v, --verbose         verbose output
--host HOST           action container host
-p PORT, --port PORT  action container port number
available commands:
{init,run}
init                initialize container with src or zip/tgz file
run                 send arguments to container to run action
```
=> Give helper script proper command line parsing.

core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerData.scala, core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala, tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala
=> make sure to cancel the timeout handler, in LoadBalancerService

common/scala/src/main/scala/whisk/core/connector/Message.scala, common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala, tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
=> Enforce WhiskAction equality mod DocRevision.

common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala, common/scala/src/main/scala/whisk/core/WhiskConfig.scala, common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala, common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala, core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala, core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala, core/invoker/src/main/scala/whisk/core/containerpool/docker/RuncClient.scala
As suggested by @markusthoemmes in comment for #3156
=> PureConfigKeys => ConfigKeys; shorten field names

common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala, tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala, tests/src/test/scala/whisk/core/database/test/DbUtils.scala
Fixes https://github.com/apache/incubator-openwhisk/issues/3027.
=> Fix heisenbug by using the correct view.

common/scala/src/main/scala/whisk/http/ErrorResponse.scala, core/controller/src/main/scala/whisk/core/controller/Actions.scala, core/controller/src/main/scala/whisk/core/controller/Activations.scala, core/controller/src/main/scala/whisk/core/controller/Packages.scala, core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala, core/controller/src/main/scala/whisk/core/controller/Rules.scala, core/controller/src/main/scala/whisk/core/controller/Triggers.scala, core/controller/src/main/scala/whisk/core/entitlement/Collection.scala, tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala, tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala, tests/src/test/scala/whisk/core/controller/test/RulesApiTests.scala, tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
Allow asset listing in namespace to skip and limit.
=> Impose list limit on all entity types.

tests/src/test/scala/common/rest/WskRest.scala, tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
This PR removes the CLI specific test cases in WskBasicUsageTests and
rewrites the other test cases with REST interface.
=> Rewrite WskBasicUsageTests

ansible/group_vars/all, ansible/roles/controller/tasks/deploy.yml, ansible/templates/whisk.properties.j2, common/scala/src/main/resources/application.conf, common/scala/src/main/scala/whisk/common/TransactionId.scala, common/scala/src/main/scala/whisk/core/WhiskConfig.scala, core/controller/src/main/scala/whisk/core/controller/Controller.scala, core/invoker/src/main/scala/whisk/core/invoker/InvokerServer.scala, tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala, tests/src/test/scala/whisk/core/database/test/DbUtils.scala
Allows the number of TIDs to be skipped in a controller to be configured.
=> Add TID stride configuration

tools/vagrant/Vagrantfile
remove hardcoded slashes
Closes https://github.com/apache/incubator-openwhisk/issues/3183
=> Fix vagrant on Windows

docs/actions.md
Documents that you can run Go actions in OpenWhisk - which has been true for a while but not formally listed in our docs. This follows the support in place for executing any binary compatible executable.
=> Document Go actions.

common/scala/build.gradle, tests/src/test/scala/common/rest/WskRest.scala
update to latest commons-io version
=> update commons-io to latest (2.6)

core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
Due to duplicate names of variables, the loadbalancer thought, that the home invoker of an action has still some free slots. But the controller asked for the wrong invoker, so the invoker was totally overloaded.
=> Fix overload of invoker.

tools/vagrant/Vagrantfile
=> print url for swagger UI on Vagrant deploy

common/scala/src/main/scala/whisk/core/entity/DocInfo.scala, common/scala/src/main/scala/whisk/core/entity/FullyQualifiedEntityName.scala, core/controller/src/main/scala/whisk/core/controller/Triggers.scala, core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala, tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/system/basic/WskRuleTests.scala, tests/src/test/scala/whisk/core/cli/test/Swift311Tests.scala, tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
- no longer create/persist a rule activation record when trigger fires
- include the async action invocation response info in the trigger activation log
- adjust rule tests
=> reduce rule activation records

common/scala/src/main/scala/whisk/http/ErrorResponse.scala, core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala, tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala, tests/src/test/scala/whisk/core/controller/test/RulesApiTests.scala, tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
The current error message does not make since if the limit provided is less than zero.
=> Refactor List Limit Error Message

common/scala/src/main/scala/whisk/core/WhiskConfig.scala
Close the source instance with try-finally usage
=> Fixes #3212 - WhiskConfig should close the property file source

common/scala/src/main/scala/whisk/common/Logging.scala, common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala, core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
This PR ads two additional metrics:
- loadbalancer_activations_<namespaceId>_count : counter for activation starts in load balancer
- invoker_container_start_<containerState>_<namespace>_<action>_ count
I also adds another info level log statement with container start information
=> add additional metrics and logs

core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
The newly added logline had no benefits but to generate a new metric. This is done explicitly through the MetricEmitter now and the old logline (including the invoker it scheduled to) is revived.
=> Remove unneeded logline and revive old marker.

core/controller/src/main/scala/whisk/core/controller/Triggers.scala
Some bits of the triggers API did include duplicated code.  Didn't get around to post comments to the specific PRs so here are my proposed fixes.
@mdeuser would you have a look please?
=> Refactor some bits of the triggers API.

tests/src/test/scala/common/rest/WskRest.scala
The API host was hardcoded to `WhiskProperties.getApiHost` which is not correct for all tests. It should use the one defined in `WskProps`.
It's unnecessary to open a connection-pool per request. A single request should be sufficient.
Co-authored-by: cbickel <github@cbickel.de>
Co-authored-by: jeremiaswerner <jeremias.werner@gmail.com>
=> Use proper API host and reduce logging noise.

tools/admin/wskutil.py
Allows wskadmin to gracefully fail if there is a connection timeout.
=> Add HTTP request timeout.

tests/src/test/scala/common/WskTestHelpers.scala
The AssetHelper is supposed to retry a package deletion if it returns a conflic. This can happen, if the package contained other entities (like an action), which got deleted first but the package's view does not yet reflect that deletion. The DELETE call will then complain about "entities still in package". A retry resolves that issue.
- Some cleanup of the helpers file.
- Refactoring of the annotations helper.
=> Actually retry package remove on conflict.

ansible/roles/couchdb/tasks/clean.yml
This is a follow-up patch to the below:
- Add couchdb clustering. (#2810)
commit e587bf8ec632320614f14114c4e85e67f39c06c2
Please review it,
Thanks.
=> Updated couchdb docker image name to apache/couchdb

common/scala/src/main/scala/whisk/utils/Retry.scala
The default retry timeout is fairly low today (1 millisecond). Rather than adjusting each value locally, we should use a more decent value to start with globally.
=> Bump default retry timeout to 50 milliseconds.

docs/webactions.md
We didn't have the docs for working with raw http actions for PHP, so I added them.
=> Add base64 example for PHP

common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/LogDriverLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/LogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/SplunkLogStore.scala, core/controller/src/main/scala/whisk/core/controller/Activations.scala, tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
Pass HTTP request and user `Identity` to log store's `fetchLogs()`
=> Update Log Store Fetch

tests/src/test/scala/common/WhiskProperties.java
=> Remove dead field.

common/scala/src/main/resources/application.conf, common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala, common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala, common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala, common/scala/src/main/scala/whisk/core/connector/MessageConsumer.scala, common/scala/src/main/scala/whisk/core/connector/MessagingProvider.scala, common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, tests/src/test/scala/ha/ShootComponentsTests.scala, tests/src/test/scala/services/KafkaConnectorTests.scala, tests/src/test/scala/whisk/core/connector/test/MessageFeedTests.scala, tests/src/test/scala/whisk/core/connector/test/TestConnector.scala
- Make sessionTimeout configurable
- Handle exception from Kafka broker down
- Reuse docker command functions
Resolve #3022
=> Enhance kafka message provider

tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
Timeouts of 1 second are a bit narrow and that narrowness is not necessary here. Bumped to 10 seconds.
Also refactored some bit for a more density.
=> Make SplunkLogStore tests more resilient.

tests/src/test/scala/system/basic/WskBasicTests.scala
Fix for the following kind of automated test failure recently observed
```
system.basic.WskBasicTests > Wsk Package REST should create, update, get and list a package FAILED
org.scalatest.exceptions.TestFailedException: "0.0.[1]" was not equal to "0.0.[2]"
```
Add some retries to allow for entity update to settle
=> Add retries to some entity "update" tests

ansible/roles/cli/tasks/deploy.yml
Update cli role .yml
Local testing via vagrant VM
Travis testing
=> WIP: CLI deployment failure due to permissions

common/scala/src/main/scala/whisk/core/database/ArtifactStore.scala, common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala, common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala, common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala, tests/build.gradle, tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala
PR which implements the proposal at #3356
=> Adds method deleteAttachments to ArtifactStore

tests/src/test/scala/actionContainers/ActionContainer.scala
The change I made in #3335 perhaps not surprisingly has been observed to fail a few times with Connection Reset errors. This change partially reverts the commit, restricting the use of port mapping only when running tests on MacOSX.
I restored the previous behavior for now of using docker inspect, except when running on MacOSX. Actual changes https://github.com/apache/incubator-openwhisk/pull/3397/files?w=1.
- ~[ ] I added tests to cover my changes.~
- ~[ ] My changes require further changes to the documentation.~
- ~[ ] I updated the documentation where necessary.~
=> Partially revert change to route all action proxy tests through port mapping

docs/apigateway.md
=> Fix typos in api gw doc

common/scala/src/main/resources/reference.conf
As proposed on the dev-list, this switches the default loadbalancer to be the sharding implementation.
- ~~[ ] I opened an issue to propose and discuss this change (#????)~~
- ~~[ ] I added tests to cover my changes.~~
- ~~[ ] My changes require further changes to the documentation.~~
- ~~[ ] I updated the documentation where necessary.~~
=> Use ShardingContainerPoolBalancer as the default.

tools/build/scanCode.cfg
Right now scanCode.cfg contains following line
*.go=has_block_license, no_tabs, no_trailing_spaces, eol_at_eof
which causes any go code which contains tabs to be rejected in builds. Actually it's standard in go to use tabs and gofmt - the standard formatting tool in go - reformats all go code to use tabs for indentation.
In order to get go code be accepted according go coding standards
*.go=has_block_license, no_tabs, no_trailing_spaces, eol_at_eof
has to be changed to
*.go=has_block_license, no_trailing_spaces, eol_at_eof
This PR adresses https://github.com/apache/incubator-openwhisk/issues/3403
Build and tests were executed in PG1#2698.  One test `whisk.core.admin.WskAdminTests.Wsk Admin CLI should block and unblock a user respectively` failed but is not related to the cfg change.
The …
=> Allow tabs for indentation in go code

common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
1. `endOffsets` might be eventually consistent to the locally stored offset value. Negative values need to be normalized to 0.
2. `endOffsets` can "block indefinitly" per documentation, so we need to make sure to protect the execution context against thread starvation.
~~- [ ] I opened an issue to propose and discuss this change (#????)~~
~~- [ ] I added tests to cover my changes.~~
~~- [ ] My changes require further changes to the documentation.~~
~~- [ ] I updated the documentation where necessary.~~
=> Fix negative values and blocking usage in Kafka lag monitoring.

settings.gradle, tests/src/test/scala/system/basic/WskBasicSwift3Tests.scala, tests/src/test/scala/system/basic/WskRestBasicSwift311Tests.scala, tests/src/test/scala/whisk/core/cli/test/Swift311Tests.scala
include swift41 project in settings so it's picked up by distDocker
=> Add swift41 settings gradle

ansible/roles/controller/tasks/deploy.yml, tests/src/test/scala/common/Pair.java, tests/src/test/scala/common/rest/WskRest.scala, tests/src/test/scala/system/basic/WskRuleTests.scala, tests/src/test/scala/whisk/core/connector/test/MessageFeedTests.scala, tests/src/test/scala/whisk/core/controller/test/ControllerApiTests.scala, tests/src/test/scala/whisk/core/controller/test/WhiskAuthHelpers.scala
Some code clean up here:
- Refactor controller deploy.yml to use pre-defined variables
- Update license headers
- WskRest was using a content-type that does not support an empty string
- Check rule status when going from active to inactive  when updating a rule to use a different trigger
- Remove code comment
=> Code clean up

core/controller/src/main/resources/apiv1swagger.json
=> Update API v1 swagger "limit" parameter description

tools/macos/README.md
Currently, java8 is no longer the default `current` version in brew cask.
Use `alternative` version for java8 now.
=> Ensure java8 is installed instead of 9

common/scala/build.gradle, common/scala/src/main/resources/application.conf, common/scala/src/main/resources/reference.conf, common/scala/src/main/scala/whisk/core/WhiskConfig.scala, common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala, common/scala/src/main/scala/whisk/core/mesos/MesosTask.scala, docs/mesos.md, tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
Enables use of a Mesos cluster for creating action containers
Some details in docs/mesos.md
Enable it via:
```
INVOKER_OPTS="-Dwhisk.spi.ContainerFactoryProvider=whisk.core.mesos.MesosContainerFactoryProvider -Dwhisk.mesos.master-url=http://192.168.99.100:5050 -Dwhisk.mesos.master-url-public=http://192.168.99.100:5050"
```
=> MesosContainerFactory

.gitignore
The addition of SSL certificates for controller can leave a ‘*.csr’ file in ansible/roles/controller/files during build.  This file could inadvertently be added to Git if it is not ignored.  This PR adds `ansible/roles/controller/files/*.csr` to the .gitignore.  (Note:  Perhaps we need a unified approach to certificate management across the cluster — we seem to be making lots of them.)
=> Ignore controller Certificate Signing Requests in git

tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
Removes an email address from API GW tests.
=> Remove email address

ansible/README.md
Update CLI documentation per #3426 to acurately reflect the process for local CLI build.
Update to `ansible/README.md` to reflect changes in the CLI build process and to clarify the need
to run `mode=clean` as part of attempting an in-place install.  This change alone does not close #3426 as there are still changes needed to the `incubator-openwhisk-cli` documentation.
For @dubeejw @lornajane
=> CLI docs update and markdown linting.

tests/src/test/scala/common/rest/WskRest.scala
Removing what appears to be unnecessary/dead code.
Also removed some code duplication around resolving fully qualified names.
=> Remove deadcode and clone/own.

tools/admin/wskadmin, tools/admin/wskutil.py
Updates wskadmin to be python3 compatible. No semantic changes intended.
=> Makes wskadmin python2 and python3 compatible

ansible/roles/cli/tasks/deploy.yml, ansible/roles/kafka/tasks/deploy.yml
If target directory already has unzip files, the unzip command will
give tip:[y]es, [n]o, [A]ll, [N]one, [r]ename, so it is better to
use the -o option to overwrite files.
~~- [ ] I opened an issue to propose and discuss this change (#????)~~
~~- [ ] I added tests to cover my changes.~~
~~- [ ] My changes require further changes to the documentation.~~
~~- [ ] I updated the documentation where necessary.~~
=> Add -o option to overwrite target files

actionRuntimes/swift4.1Action/Dockerfile, docs/actions.md, tools/build/compile_swift.sh, tools/travis/build.sh
Bump swift 4.1 to latest release
Update default swift 4.1 runtime
Closes #3444 
Closes #3508
=> Bump swift 4.1 to latest release

actionRuntimes/nodejs6Action/Dockerfile, actionRuntimes/nodejs8Action/Dockerfile, docs/reference.md
update nodejs 6.14.0. 8.11.0 npm openwhisk 3.14
Closes #3508
=> update nodejs 6.14.0. 8.11.0 npm openwhisk 3.14

common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
Wrap producer.send with Future to make it asynchronous
=> Wrap producer.send with Future

common/scala/src/main/scala/whisk/core/WhiskConfig.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala, common/scala/src/main/scala/whisk/http/PoolingRestClient.scala, core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala, tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchLogStoreTests.scala, tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
Provides a log store that allows logs to be fetched from ElasticSearch.
=> Add ElasticSearch Log Store

tools/macos/docker-machine/README.md
Incorrect version is stated in the docker-machine setup document.
=> Fix wrong Ansible version for docker-machine setup

performance/.travis.yml, performance/README.md, performance/preparation/create.sh, performance/preparation/deploy.sh, performance/wrk_tests/latency.sh, performance/wrk_tests/post.lua, performance/wrk_tests/throughput.sh
As discussed on the Apache Mailing list, this PR moves the content of the performance repository to the core repository, as performance is one of the key aspects of OpenWhisk.
Moving the content here has been discussed on the mailing list.
=> Move performance repository to core repository.

docs/webactions.md
Updating CLI documentation to include an example using the new `--web-secure` flag.
https://github.com/apache/incubator-openwhisk-cli/pull/244
=> --web-secure option doc update

tests/src/test/scala/system/basic/WskBasicTests.scala, tests/src/test/scala/whisk/core/cli/test/ApiGwRestTests.scala, tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala, tests/src/test/scala/whisk/core/cli/test/WskEntitlementTests.scala, tests/src/test/scala/whisk/core/cli/test/WskRestEntitlementTests.scala
Removes improper usage of `regex` and `"""`.
=> Code clean up in test suites

tests/build.gradle, tests/src/test/scala/common/Wsk.scala, tests/src/test/scala/common/WskTestHelpers.scala, tests/src/test/scala/system/basic/WskConsoleTests.scala, tests/src/test/scala/system/basic/WskRestBasicTests.scala, tests/src/test/scala/system/basic/WskRuleTests.scala, tests/src/test/scala/whisk/core/cli/test/ApiGwRestBasicTests.scala, tests/src/test/scala/whisk/core/cli/test/ApiGwRestTests.scala, tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala, tests/src/test/scala/whisk/core/cli/test/WskRestBasicUsageTests.scala
My attempt to finish up the final 3 files in https://github.com/apache/incubator-openwhisk-cli/issues/259
along with some other test clean up
CLI companion https://github.com/apache/incubator-openwhisk-cli/pull/270
renaming Basic and ApiGW tests to reflect what is being tested (wsk REST) in order to avoid duplicate naming issues with the cli
https://github.com/apache/incubator-openwhisk-cli/issues/259
=> More test clean up

ansible/roles/invoker/tasks/deploy.yml, common/scala/src/main/scala/whisk/core/WhiskConfig.scala, common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala, common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala, core/invoker/src/main/resources/application.conf, core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala, core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala, core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala, core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala, tests/src/test/scala/common/LoggedFunction.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala, tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerArgsConfigTest.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
added test for DockerContainerFactory to verify proper args in docker run
fixes #3110
=> implement ContainerFactory.cpuShare to fix #3110

ansible/roles/controller/tasks/deploy.yml, common/scala/src/main/scala/whisk/core/WhiskConfig.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, docs/deploy.md
This is essentially a leftover of the removal of the old loadbalancer.
=> Remove bookkeeping setting which is no longer applicable.

common/scala/build.gradle, common/scala/src/main/scala/whisk/core/entity/ArgNormalizer.scala, core/controller/build.gradle, tests/build.gradle, tests/src/test/scala/common/BaseWsk.scala, tests/src/test/scala/common/rest/WskRest.scala, tests/src/test/scala/system/basic/WskActionTests.scala, tests/src/test/scala/system/basic/WskBasicSwift3Tests.scala, tests/src/test/scala/system/basic/WskConductorTests.scala, tests/src/test/scala/system/basic/WskConsoleTests.scala, tests/src/test/scala/system/rest/ActionSchemaTests.scala, tests/src/test/scala/system/rest/RestUtil.scala, tests/src/test/scala/whisk/core/cli/test/Swift311Tests.scala, tests/src/test/scala/whisk/core/connector/test/MessageFeedTests.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala, tests/src/test/scala/whisk/core/database/test/CleanUpActivationsTest.scala, tests/src/test/scala/whisk/core/entity/test/ActivationResponseTests.scala
The newest akka-http contains a new connection-pool implementation which we can make use of to stabilize our akka-http based clients (most notably couchdb).
~~- [ ] I added tests to cover my changes.~~
~~- [ ] My changes require further changes to the documentation.~~
~~- [ ] I updated the documentation where necessary.~~
=> Update akka to 2.5.12 and akka-http to 10.1.1.

common/scala/build.gradle, common/scala/src/main/resources/application.conf, common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala, common/scala/src/main/scala/whisk/core/mesos/MesosTask.scala, docs/mesos.md, tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
For use when launching container using MesosContainerFactory
added config properties to MesosConfig:
```
whisk.mesos{
constraints = [] //placement constraint strings to use for managed containers e.g. ["att1 LIKE v1", "att2 UNLIKE v2"]
blackbox-constraints = [] //placement constraints to use for blackbox containers
constraint-delimiter = " "//used to parse constraint strings
teardown-on-exit = true //set to true to disable the mesos framework on system exit; set for false for HA deployments
}
```
=> add support for mesos attribute constraints 

ansible/README.md
=> Fix command to build CLI in ansible guide, fixes #3575

ansible/group_vars/all, ansible/roles/nginx/templates/nginx.conf.j2
It's good practice in general to not report version numbers in http responses. This disables that as well as bumping the nginx version to 1.13.
=> Bump nginx version to latest and disable server-side information.

tests/src/test/scala/whisk/core/containerpool/docker/test/RuncClientTests.scala
Switch to using ScalaFutures with IntegrationPatience (default timeout of 15 sec) for this test
Fixes #3583
=> Increase RuncClientTests timeout

README.md
Adds the codecov coverage badge to readme
=> Add codecov coverage badge

common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala, tests/src/test/scala/common/WskTestHelpers.scala
Fixes typo in `WhiskActivation` JSON serdes reader.
=> Fix error message type

LICENSE.txt
Partially-closes: apache/incubator-openwhisk-release#109
Change the LICENSE file into the correct format defined in openwhisk release.
- [x ] Documentation
- [ x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
=> Change the LICENSE file into the correct format defined in openwhisk release

core/controller/src/main/scala/whisk/core/controller/Actions.scala, core/controller/src/main/scala/whisk/core/controller/Activations.scala, core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala, core/controller/src/main/scala/whisk/core/controller/Packages.scala, core/controller/src/main/scala/whisk/core/controller/Rules.scala, core/controller/src/main/scala/whisk/core/controller/Triggers.scala
Removes unneeded parameters from `getEntity()` and `getEntityAndProject()` methods in `ApiUtils` making those methods easier to interface with.
=> Shorten parameters for entity fetching utils

common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala, common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala, tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreQueryBehaviors.scala
=> Make count with skip to work with CouchDB

.gitignore, ansible/controller.yml, ansible/roles/controller/tasks/clean.yml, ansible/roles/controller/tasks/deploy.yml, ansible/roles/controller/tasks/join_akka_cluster.yml, ansible/yamllint.yml
Add a level of abstraction the controller role in ansible.  It will now accept a set of parameters to configure:
1.  `host_group` - the group from the hosts file used to determine indexing during deployment
2.  `name_prefix` - the prefix (i.e. 'controller', 'crudController') used to name docker instances
3.  `controller_index_base` - the base starting point for indexing in the total controller arrays
4.  `join_akka_cluster` - (book) true=join the cluster; false=keep akka local
While working on #3412, it was uncovered that some (or at least one major) implementers of OpenWhisk segregate their controllers and use a copy of the rolefile to deploy it.  That creates maintenance overhead and deployment complexity in keeping ansible playbooks in sync.  This change abstracts the necessary …
=> Add abstraction to controller role in ansible

tools/ubuntu-setup/README.md, tools/ubuntu-setup/ansible.sh, tools/ubuntu-setup/java8.sh
Closes #3605 
There are some problems installing some pip packages in ubuntu14.
=> Fix ubuntu14 setup for pip packages 

.scalafmt.conf, common/scala/src/main/resources/application.conf, common/scala/src/main/resources/logging.conf, common/scala/src/main/resources/reference.conf, core/controller/src/main/resources/application.conf, core/controller/src/main/resources/reference.conf, core/invoker/src/main/resources/application.conf
Scala .conf files contain IP and are non-trivial; therefore, we should add ASF headers to these files as per release policy.
=> Add ASF license headers to all Scala .conf files.

docs/dev/troubleshooting/build-failures.md
Creates a troubleshooting guide for the OpenWhisk build process.
=> Create troubleshooting guide for dependency download failures

docs/dev/troubleshooting/build-failures.md
scanCode fails due to missing license header in build-failures.md.
=> Add license header to build-failures.md

ansible/roles/nginx/templates/nginx.conf.j2, docs/mobile_sdk.md
Closes #3630 
bump new version of ios staterapp in nginx
=> bump new version of ios staterapp

ansible/README.md, tools/macos/README.md, tools/macos/docker-machine/README.md, tools/travis/setup.sh, tools/ubuntu-setup/ansible.sh
Kube has problems with Ansible 2.5.0 which are resolved in 2.5.2.
=> Bump Ansible to 2.5.2

actionRuntimes/actionProxy/Dockerfile
Bump dockerskeleton default image
diff https://github.com/apache/incubator-openwhisk-runtime-docker/compare/dockerskeleton@1.2.0...dockerskeleton@1.3.0
=> update docker runtime from 1.2.0 to 1.3.0

actionRuntimes/actionProxy/Dockerfile, actionRuntimes/javaAction/Dockerfile, actionRuntimes/nodejs6Action/Dockerfile, actionRuntimes/nodejs8Action/Dockerfile, actionRuntimes/php7.1Action/Dockerfile, actionRuntimes/python2Action/Dockerfile, actionRuntimes/pythonAction/Dockerfile, actionRuntimes/swift3.1.1Action/Dockerfile, actionRuntimes/swift4.1Action/Dockerfile, common/scala/Dockerfile, core/controller/Dockerfile, core/invoker/Dockerfile, sdk/docker/Dockerfile
All Dockerfiles must have an ASF approved license header
=> Assure all Dockerfiles have ASF header.

ansible/roles/nginx/templates/nginx.conf.j2
Verify upstream ssl certs. This prevents from a potential MITM attack in case the path between edge and controller is compromised.
=> Assure nginx verifies upstream ssl certs

tools/dev/src/main/groovy/couchdbViews.groovy, tools/jenkins/apache/dockerhub.groovy
=> Add ASF Headers to .groovy source files.

ansible/group_vars/all
See screenshot - not sure where this snuck in.
=> Remove non-ascii character.

actionRuntimes/actionProxy/build.gradle, actionRuntimes/javaAction/build.gradle, actionRuntimes/nodejs6Action/build.gradle, actionRuntimes/nodejs8Action/build.gradle, actionRuntimes/php7.1Action/build.gradle, actionRuntimes/python2Action/build.gradle, actionRuntimes/pythonAction/build.gradle, actionRuntimes/swift3.1.1Action/build.gradle, actionRuntimes/swift4.1Action/build.gradle, ansible/environments/distributed/group_vars/all, ansible/environments/docker-machine/group_vars/all, ansible/environments/local/group_vars/all, ansible/environments/vagrant/group_vars/all, ansible/group_vars/all, build.gradle, common/scala/build.gradle, common/scala/src/main/resources/logback.xml, core/controller/build.gradle, core/invoker/build.gradle, gradle/docker.gradle, gradle/wrapper/gradle-wrapper.properties, performance/gatling_tests/build.gradle, sdk/docker/build.gradle, settings.gradle, tests/build.gradle, tests/dat/blackbox/badaction/build.gradle, tests/dat/blackbox/badproxy/build.gradle, tools/dev/build.gradle, tools/eclipse/scala.properties, tools/vagrant/Vagrantfile
Adhere to project Apache 2 license header policy.
=> Update last, edge-case files without ASF headers.

core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Fix method name in scaladoc and replace with method links.
=> Use method links and correct method name.

CONTRIBUTING.md
=> Slightly expand description of ICLA process.

common/scala/src/main/resources/logback.xml, tests/dat/actions/unicode/build.gradle, tests/performance/gatling_tests/src/gatling/resources/conf/logback.xml, tests/src/test/resources/logback-test.xml
=> Add ASF license to optional XML files and last gradle file.

tests/dat/actions/unicode/build.gradle
=> Single build.gradle file missing ASF license header

.travis.yml, tests/performance/README.md, tests/performance/gatling_tests/src/gatling/resources/data/users.csv, tests/performance/gatling_tests/src/gatling/scala/ColdBlockingInvokeSimulation.scala
Add another gatling load test. It executes as much cold invocations as possible.
=> Add gatling-throughput test for cold invocations.

ansible/group_vars/all, core/controller/src/main/resources/application.conf
Read the details in the recent similar PR dedicated for Kafka SSL https://github.com/apache/incubator-openwhisk/pull/3604
=> Limit cipher suites used for controller https

common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala, common/scala/src/main/scala/whisk/core/entity/ActivationResult.scala, tests/src/test/scala/actionContainers/ActionContainer.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/ContainerConnectionTests.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala, tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala, tests/src/test/scala/whisk/core/entity/test/ActivationResponseTests.scala
On systems with high load, POSTing the action container `/init` endpoint occasionally fails with `NoRouteToHostException`. Retry if this exception occurs.
* So far, the HTTP client retried when the connection to an action container failed with `HttpHostConnectException`. This is safe because no data has been transmitted yet when this exception occurs. Usually, this exception will occur if the action container startup is slow such that the target socket is not listening yet.
* This change adds `NoRouteToHostException` as retryable exception. Root cause for this exception is high system load. It is safe to retry after this exception occurred because it implies that no data has been transmitted yet.
* Needed to restructure the code to add the second retryable exception.
* Lowered the time …
=> Make REST communication with action containers more robust

README.md
Updating avaiable to available.
=> README: Available typo

tools/travis/scan.sh
=> Update Travis to use ASF-Release.cfg.

tests/src/test/scala/system/basic/WskBasicSwift3Tests.scala, tests/src/test/scala/system/basic/WskUnicodeTests.scala
swift tests sometimes take longer to invoke, due to compile step or docker pull the large image
this adds a bit of time to tests to run and to get activation result
=> give more time to swift tests to run

common/scala/src/main/resources/application.conf
Increases the `max-open-requests` akka-http configuration value so that triggers invocations will not be as  likely to encounter a `akka.stream.BufferOverflowException`. This is a temporary patch until a proper fix is implemented. 
Error example:
```
[TriggersApi] trigger-fired action 'someTrigger' failed to invoke with akka.stream.BufferOverflowException: Exceeded configured max-open-requests value of [512]. This means that the request queue of this pool (HostConnectionPoolSetup(localhost,8080,ConnectionPoolSetup(ConnectionPoolSettings(128,0,5,512,1,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.1.1),10 seconds,1 minute,512,None,WebSocketSettings(<function0>,ping,Duration.Inf,<function0>),List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,52428800,Strict,RFC6265,fa …
```
=> Bump max open requests configuration value

common/scala/src/main/scala/whisk/core/entity/Size.scala, tests/src/test/scala/whisk/core/entity/test/SizeTests.scala
The ByteSize method did not satisfy this requirement for Comparables:
```
* <p>It is strongly recommended, but <i>not</i> strictly required that
* <tt>(x.compareTo(y)==0) == (x.equals(y))</tt>.  Generally speaking, any
* class that implements the <tt>Comparable</tt> interface and violates
* this condition should clearly indicate this fact.  The recommended
* language is "Note: this class has a natural ordering that is
* inconsistent with equals."
```
This wasn't caught by the tests because they weren't actually asserting the invariants - `equals` vs `should be` or some equivalent variant. Adjusted tests and added equals method.
=> Add equals method to ensure that ByteSize instances satisfy Comparable contract

common/scala/Dockerfile
use a prebuilt alpine+oracle java image
As briefly discussed in https://github.com/apache/incubator-openwhisk/pull/3063#pullrequestreview-90904845, why not use a pre-baked image with the oracle java bits already setup, since the Dockerfile is somewhat complicated for alpine + oracle java.
I currently chose the 8u162b12_server-jre variant, and not the 8u162b12_jdk variant - from what I've read most jdk runtime tools are there, but I don't have an exhaustive list of differences. Open to change to jdk if needed, but if not, would rather avoid the extra space and use the smallest possible base image.
sed + curl are installed, since they are required for init scripts in use already. curl is used by alpine-java, but removed after use; sed is available without update, but not compatible with our …
=> use alpine-java base image (alpine 3.7 + oracle 8u162b12_server-jre)

core/controller/src/main/scala/whisk/core/controller/Rules.scala
Working with rules only requires to make sure certain actions exist. We only need their metadata, not the full blown action including its code.
=> Only get action metadata when working with rules.

docs/actions.md
Add documentation on using [Composer](https://getcomposer.org] with the PHP runtime.
=> Add information on using Composer with the PHP runtime

docs/webactions.md
Mainly remove the redundant `A`.
=> Correct text in webaction doc.

tests/src/test/scala/common/WhiskProperties.java
By default, the path of python2.7 is located at `/usr/bin/`
instead of `/usr/local/bin/`. Since folks may desire to use homebrew
installation and the path _might_ be relocated at `/usr/local/bin/`. Support path
from `/usr/bin` both is better to avoid python3 override the default
`python` without any penalty.
Not sure the small change is needed to open an additional issue? Didn't find similar issue, though.
=> Support alternative path for python in whiskprops

build.gradle
Excludes logback-test.xml from being packaged in test sources jar
Fixes #3739 by avoiding `logback-test.xml` from being packaged in test sources jar. This would ensure that there is only one logback-test.xml in classpath which would prevent Logback from complaining and logging below warning
```
17:08:57,257 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs multiple times on the classpath.
17:08:57,257 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [jar:file:/home/travis/.m2/repository/org/apache/openwhisk/openwhisk-tests/1.0.0-SNAPSHOT/openwhisk-tests-1.0.0-SNAPSHOT-tests.jar!/logback-test.xml]
17:08:57,257 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs …
```
=> Exclude logback-test.xml from test sources jar

.github/ISSUE_TEMPLATE.md
Often issues are being created for setup issue which are better addressed by connecting on Slack or Mailing list. This. PR updates the issue template with links to Slack and mailing list details.
=> Mention Slack and mailing list links in issue template

tests/src/test/scala/system/basic/WskActivationTests.scala
Provides an integration test for the activation result API.
=> Add activation result integration test

core/invoker/Dockerfile
This reverts commit 008996d099a730a2179ead97504ab631d30f1a80.
=> Revert "Mitigate missing docker 1.12 binary download. (#3758)" as the cli is downloadbale again.

common/scala/src/main/resources/application.conf, common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala, tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/whisk/core/database/test/DbUtils.scala, tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
Fixes #3769. See #3770 for details
=> Disable inlining logic if maxInlineSize is zero

common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala, common/scala/src/main/scala/whisk/core/database/CloudantRestClient.scala, common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala, common/scala/src/main/scala/whisk/http/PoolingRestClient.scala, tests/src/test/scala/whisk/core/database/test/ExtendedCouchDbRestClient.scala, tests/src/test/scala/whisk/http/PoolingRestClientTests.scala
Make it possible to unit test the PoolingRestClient, and adds some unit tests.
=> Refactor and unit test PoolingRestClient

docs/actions.md
=> Fix typos in actions doc

common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
The internal `offset` held by the KafkaConsumerConnector starts at 0 but is only meaningful after the first message has been read from Kafka. In case of an Invoker restart for example, the reported offset difference might be absurdly high, because the offset in Zookeeper is high, while the internal offset is still 0.
=> Only send kafka offset metrics, if offsets are meaningful.

core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
Fixes EntitlementProvider to use SpiLoader for MessagingProvider 
Currently EntitlementProvider  uses hardcoded KafkaMessagingProvider. This PR fixes it.
- [x ] Controller
- [ x] Bug fix (generally a non-breaking change which closes an issue).
- [ x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
=> Fixes EntitlementProvider to use SpiLoader

common/scala/src/main/scala/whisk/core/WhiskConfig.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchLogStore.scala
Renames configuration name for `elasticSearch` to `logStoreElasticSearch` to prevent name clashes when future Elasticsearch configurations are provided for other components.
=> Refactor Elasticsearch log store config name

docs/actions.md, docs/security.md
Updates to actions doc to remove redundant list of action runtimes. Add link to securing actions.
=> add a doc for securing actions 

tools/admin/build.gradle
This is a quick fix for the test compilation failure that the cli is experiencing due to https://github.com/apache/incubator-openwhisk/commit/daa14c6cd515fd20482951218c292474738cc0ed .
Adds the maven plugin to admin `build.gradle` so that the project structure is picked up in maven `.jar` archive step.
CLI tests depend on maven `.jar`s. Any additions to the gradle project structure needs to take into account that the CLI relies solely on the maven image and will not compile without these class paths included in the `.jar`
=> allow CLI to compile open maven jar

tests/build.gradle
Temporary workaround for #3823
This change installs the admin module jars to local maven repo upon test module install. This would fix the issue being seen in builds of other repos as seen in #3823. 
How to confirm
First delete local modules
```
$ cd ~/.m2/repository/org/apache/openwhisk
$ rm -rf *
```
Now build java runtime
```
$./gradlew :tests:compileTestScala
```
Now in OpenWhisk home build
```
$./gradlew \
:common:scala:install \
:core:controller:install \
:core:invoker:install \
:tests:install
```
Now you should see `openwhisk-admin-tools` in _~/.m2/repository/org/apache/openwhisk_ and also java runtime build would also pass
=> Install admin module upon test module install

LICENSE.txt, common/scala/src/main/scala/whisk/core/database/ConcurrentMapBackedCache.scala
=> Remove the copyright of Lightbend

ansible/tasks/writeWhiskProperties.yml
Since the initial openwhisk release does not package the folder tests, we
need to make sure application.conf.j2 exists in order to copy to the remote
server.
=> Check the file existence of application.conf.j2

common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
When not specifying any ConnectionManager for the HttpClient used by HttpUtils, it defaults to an arbitrary PoolingManager with 5 connections. This can hide subtle bugs in connection management, since we expect it to only have one connection to the specific container, we'll default to the BasicConnectionManager.
Furthermore, there are subtle issues when an entity returned by a HttpRequest is not consumed fully (which could happen if it gets truncated or content-length is not returned correctly). That can cause the ConnectionPool (which shouldn't be there in the first place) to go stale.
We also never closed the entity's stream.
=> Make HttpUtils actually use only one connection and harden connection release.

core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
This was a long due writeup on my side. Feedback very welcome, let's make this as understandable as possible!
=> Add documentation to the loadbalancer.

common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
For debugging purposes, write the rotating log filename `DockerToActivationFileLogStore` uses to system logs.
=> Include rotating user log filename in system logs

common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
The PoolingConnectionManager checks connections for their staleness, which is important because we're pausing/resuming containers all the time. Connections can go stale in this process.
=> Use a PoolingConnectionManager even for single connection use-cases.

common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
The changes introduced here are subject so latency and stability problems in larger environments. Especially the impact of consuming the whole entity needs to be carefully asserted and verified before getting it back in.
=> Revert hardening of HttpUtils.

docs/metrics.md
Just some clean up of metrics.md.
=> Fix typos in metrics doc

common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala, tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
Elasticsearch 'must' query will now accept an array of 'ranges'.
=> Allow Elasticsearch 'must' query to take an array of 'ranges'

ansible/invoker.yml, ansible/roles/invoker/tasks/clean.yml, ansible/roles/invoker/tasks/deploy.yml
Refactors the invoker Ansible roles to make the invoker have plugable tasks, and simplifies invoker name and index retrieval within Ansible scripts.
=> Refactor invoker roles

common/scala/src/main/scala/whisk/core/connector/Message.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala, common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala, common/scala/src/main/scala/whisk/core/entity/Exec.scala, common/scala/src/main/scala/whisk/core/entity/Parameter.scala, common/scala/src/main/scala/whisk/core/entity/WhiskPackage.scala, core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala, core/controller/src/main/scala/whisk/core/controller/Triggers.scala, core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala, core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala, tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala, tests/src/test/scala/common/rest/WskRestOperations.scala, tests/src/test/scala/system/basic/WskRestBasicTests.scala, tests/src/test/scala/system/rest/RestUtil.scala, tests/src/test/scala/whisk/core/cli/test/WskRestBasicUsageTests.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/ContainerConnectionTests.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala, tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala, tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala, tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala, tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala, tests/src/test/scala/whisk/core/database/test/DocumentHandlerTests.scala, tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala, tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala, tests/src/test/scala/whisk/http/PoolingRestClientTests.scala
Use `JsObject.empty`, which is a persistent singleton object, instead of creating new case classes by using `JsObject()`.
=> Replace occurrences of JsObject() with JsObject.empty

common/scala/src/main/scala/whisk/core/entity/LogLimit.scala, common/scala/src/main/scala/whisk/core/entity/MemoryLimit.scala, common/scala/src/main/scala/whisk/core/entity/TimeLimit.scala, core/controller/src/main/scala/whisk/core/controller/Controller.scala, tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala, tests/src/test/scala/system/basic/WskActionTests.scala, tests/src/test/scala/system/basic/WskSequenceTests.scala, tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/whisk/core/controller/test/ControllerApiTests.scala
Adds the following `min_action*` and `sequence_length` to the `limits` property accessible from the API host:
```json
"limits": {
"min_action_logs": 0,
"max_action_memory": 536870912,
"actions_per_minute": 60,
"min_action_memory": 134217728,
"concurrent_actions": 30,
"triggers_per_minute": 60,
"sequence_length": 50,
"max_action_logs": 10485760,
"min_action_duration": 100,
"max_action_duration": 300000
}
```
Adjusts a test which needs the sequence limit to use this information.
Closes https://github.com/apache/incubator-openwhisk/issues/335.
=> Add action limits to API host standard response

tests/src/test/scala/actionContainers/ActionContainer.scala, tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala, tests/src/test/scala/common/WhiskProperties.java
I'm cleaning up the Travis builds for the runtime repos which are unnecessarily pulling images and building parts of openwhisk for no reason. Here's an example post cleanup: https://github.com/apache/incubator-openwhisk-runtime-docker/pull/53 which cuts Travis time between 5 and 10 minutes see for example:
https://travis-ci.org/apache/incubator-openwhisk-runtime-python/pull_requests
https://travis-ci.org/apache/incubator-openwhisk-runtime-docker/pull_requests
https://travis-ci.org/apache/incubator-openwhisk-runtime-java/pull_requests
=> Add bypass for test (failing in Swift, PHP). Fix NPEs.

tools/build/README.md, tools/build/citool
The introduction of a Travis build matrix requires some changes to the `citool` to pull the right logs. This patch will allow for the build matrix index to be appended to the Travis job id to pull logs for a specific subjob.
```
> citool monitor 400722572.1
whisk.core.cli.test.WskRestEntitlementTests > Wsk Package Entitlement should not allow unauthorized subject to operate on private action FAILED
whisk.core.cli.test.WskRestEntitlementTests > Wsk Package Entitlement should reject update action in shared package not owned by authkey FAILED
whisk.core.cli.test.WskRestEntitlementTests > Wsk Package Action should invoke an action sequence from package FAILED
whisk.core.cli.test.WskRestEntitlementTests > Wsk Package Action should not allow invoke an action sequence with more than one …
```
=> Adjust citool to work with Travis build matrix.

ansible/group_vars/all, ansible/roles/controller/tasks/deploy.yml, common/scala/src/main/resources/reference.conf, core/controller/src/main/scala/whisk/core/controller/Controller.scala, core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala, core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
SPI introduced for entitlement providers
This PR introduces an SPI to swap and exchange entitlements providers,
enabling the integration of external policy systems. 
I explained the background of these changes on the mailing list
[Extending Authentication and Entitlement - Heads up](https://lists.apache.org/thread.html/891855d699710ba53e89a12c817c6e7d2560023c588f6f5a3bd74ca6@%3Cdev.openwhisk.apache.org%3E)
[PG 3:2510 passed]
=> Introduce entitlement spi

common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala, common/scala/src/main/scala/whisk/core/entity/InstanceId.scala, core/controller/src/main/scala/whisk/core/controller/Controller.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
This PR aims to add invoker container name into the health protocol for the case when the name differs from the Kafka topic name.
Previous response from the invokers endpoint:
```
curl https://localhost:8080/invokers -k
{"invoker0":"up"}
```
New response if invoker container name differs from the kafka topic name:
```
curl https://localhost:8080/invokers -k
{"invoker0/invoker-j8ptk":"up"}
```
=> Add invoker container name to health protocol

core/invoker/build.gradle, core/invoker/src/main/scala/whisk/core/invoker/InstanceIdAssigner.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, settings.gradle, tests/build.gradle, tests/src/test/scala/whisk/core/invoker/test/InstanceIdAssignerTests.scala
Fixes #3856 
This PR fixes the id assignment path and also add some tests based on [Curator Test Support](https://curator.apache.org/curator-test/). To enable test some refactoring was done to extract the existing id assignment logic to a new class `InstanceIdAssigner`. 
Going forward this would also simplify work for #3858
=> Fix invokerId assignment path in zookeeper

ansible/group_vars/all, ansible/roles/kafka/tasks/deploy.yml, core/controller/src/main/resources/application.conf
This PR limits tls protocols to be used while talking via SSL with Controller and Kafka.
From now on TLS 1.2 will be the only allowed protocol mainly because of the weak cipher suites used in the previous version, e.g. MD5.
=> Limit TLS protocols used for kafka and controller

ansible/group_vars/all
=> Fix typo dp_port in ansible/group_vars/all

common/scala/src/main/resources/reference.conf, common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/LogDriverLogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/LogStore.scala, common/scala/src/main/scala/whisk/core/containerpool/logging/SplunkLogStore.scala, common/scala/src/main/scala/whisk/core/database/ActivationStore.scala, common/scala/src/main/scala/whisk/core/database/ArtifactActivationStore.scala, common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala, core/controller/src/main/scala/whisk/core/controller/Actions.scala, core/controller/src/main/scala/whisk/core/controller/Activations.scala, core/controller/src/main/scala/whisk/core/controller/Controller.scala, core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala, core/controller/src/main/scala/whisk/core/controller/Triggers.scala, core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala, core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala, core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancer.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala, core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala, core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesInvokerAgentLogStore.scala, core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala, tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala, tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
- Cleaned up some edges around SPIs, made their factory method "instance" where applicable.
- Moved the ActivationStore to "whisk.core.database".
=> Cleanup SPIs, move ActivationStore to whisk.core.database.

docs/actions.md
=> Fix links in actions.md

.travis.yml, tests/performance/README.md, tests/performance/gatling_tests/src/gatling/scala/LatencySimulation.scala
This change might need to increase the thresholds of the latency test, because the containers will be paused and unpaused now, because the duration between the requests is higher than the pause-grace.
=> Add pause in latency test to handle asynchrounous log collecting.

ansible/README.md, tools/macos/README.md
Documents how to prevent configuration errors that occur in the Docker for Mac environment after rebooting the host machine.
=> Document OPENWHISK_TMP_DIR usage

tests/src/test/scala/whisk/core/cli/test/ApiGwRestBasicTests.scala
It looks like all of the tests in ```ApiGwTests.scala``` that involve creating actions create actions in the default package. This PR adds a test that creates an api for an action in a custom package.
=> Add api gateway test that uses custom package for action

docs/dev/modules.md
Update to include links to new Ballerina and Ruby runtimes
=> Update runtime repo listing

common/scala/src/main/scala/whisk/common/ForcibleSemaphore.scala, core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, tests/src/test/scala/whisk/common/ForcibleSemaphoreTests.scala, tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala, tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
@rabbah made me aware that it's "Forcible" instead of "Forcable".
"Unresponsible" was just... yeah 😁
=> Fix misspelled or wrongly named types.

core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala, tests/src/test/scala/system/basic/WskSequenceTests.scala, tests/src/test/scala/whisk/core/controller/test/SequenceApiTests.scala
When invoking a sequence that has a missing component an error is generated in the controller logs and the sequence activation is never stored.
Steps to reproduce:
```
$ wsk action create comp ~/actions/logs.js
$ wsk action create seq --sequence comp
$ wsk action delete comp
$ wsk action invoke seq
ok: invoked /_/seq with id 2373488081eb4ed3b3488081ebbed31e
$ wsk activation get 2373488081eb4ed3b3488081ebbed31e
error: Unable to get activation '2373488081eb4ed3b3488081ebbed31e': The requested resource does not exist. (code fb60fd27845202c2af0e97b4157b8bd5)
```
Log error:
```
[ActionsApi] sequence activation failed: not found on 'get'
```
=> Display proper error when sequence invocation fails due to missing component

ansible/roles/invoker/tasks/deploy.yml, common/scala/src/main/scala/whisk/core/WhiskConfig.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
Command line parsing and deciding which case to go to was a bit confusing, so I refactored it and took duplicate bits out.
=> Refactor invoker command line parsing.

common/scala/src/main/resources/logback.xml, tests/src/test/resources/logback-test.xml
As per title, like all the other libraries we depend on, ERROR logging should be sufficient.
=> Tune down excessive Zookeeper logging in core components and tests.

tests/build.gradle
These tests were never run. It should though!
=> Run 'limits' tests in travis.

core/controller/src/main/resources/apiv1swagger.json, tests/build.gradle, tests/src/test/resources/swagger-config.json, tests/src/test/scala/common/rest/SwaggerValidator.scala, tests/src/test/scala/common/rest/WskRestOperations.scala, tools/travis/runTests.sh
This change wires up all existing API tests that use WskRestOperations to validate the HTTP requests and responses against the Controller API's Swagger spec.
It also adds a new Gradle task - :tests:testSwaggerCodegen - that does a basic validation of the Swagger spec and generates a basic Java client from that spec and verifies that the client compiles. CI is wired up to run this new test task.
The result of both of the above are a number of changes to the Swagger spec, also included here. This brings our Swagger spec much closer to matching the reality of the Controller API, and any additional coverage in the API test suite will further increase coverage of the Swagger spec.
There are some existing tests that purposely test API responses when passed invalid data, so the new …
=> Validate the Controller Swagger spec matches the impl

common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
Expand log file write access to other groups.
=> Adjust write user log file write access

common/scala/src/main/scala/whisk/core/containerpool/AkkaContainerClient.scala, common/scala/src/main/scala/whisk/http/PoolingRestClient.scala
Some intermittent build failures in various runtimes that use `ActionContainer` for tests (which uses the akka http client as of recently) shows some errors where connections are prematurely terminated. 
In separate testing, I think this is related to use of `Connection: close` request header, to dissuade connection reuse.
This change:
* removes `Connection:close` header
* uses instead the `SO.KeepAlive(false)` (SocketOption); similar to the apache client setting to disable connection reuse
Since Akka client is not enabled by default in existing code except the `ActionContainer` test base class, this change and its affects are not obvious, until runtimes using this test class are running on this change. Locally testing, I was able to intermittently reproduce problems with the previous …
=> use KeepAlive(false) (SocketOption) instead of Connection:close (HTTP header)

core/controller/src/main/scala/whisk/core/controller/WebActions.scala, tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Reverts removal of base64 for json responses from PR #3939
recent PR #3919 added the ability for web actions to specify a `string` type in the `body` of the response and removed the support for the legacy requirement of handing base64.
We got feedback from users that they have webactions with this old behavior in place and their actions were not working as expected.
```javascript
function main(params){
return {
headers: { 'Content-Type': 'application/json' },
body: new Buffer(JSON.stringify(params)).toString('base64')
}
}
```
This requirement was removed a year ago from code also documentation.
The proposal is to restore the base64, and announce of the braking change to user to give a period for them to update their webactions and remove this extra step of doing base64 for JSON not need …
=> restore base64 json responses for webactions

ansible/tasks/db/createUsers.yml, ansible/tasks/db/grantPermissions.yml
=> Make ansible script to grant permissions more general.

tools/jenkins/apache/dockerhub.groovy
=> Publish tools/scriptRunner and tools/ansibleRunner to Dockerhub

common/scala/build.gradle
Prefer offers with least cpus
The earlier implementation was picking up the first available offer that satisfies the requirements/constraints. Now the offers with least cpus are preferred so that scale downs can happen easily.
=> Upgrading mesos-actor

tests/src/test/scala/common/WhiskProperties.java
Closes https://github.com/apache/incubator-openwhisk/issues/3862
=> remove stale JUnit test concurrency flag

core/controller/src/main/resources/reference.conf
=> Correct default-value for user-memory in Loadbalancer.

common/scala/build.gradle, common/scala/src/main/scala/whisk/core/database/cosmosdb/CosmosDBUtil.scala
Updates CosmosDB SDK to [v2.1.0](https://github.com/Azure/azure-cosmosdb-java/releases/tag/v2.1.0) which includes an important fix for Azure/azure-cosmosdb-java#63
All CosmosDB related tests passed on CI from my fork branch.
=> Update CosmosDB SDK to v2.1.0

.travis.yml, tests/README.md, tests/build.gradle, tests/src/test/scala/common/WhiskProperties.java, tests/src/test/scala/common/WskOperations.scala, tests/src/test/scala/system/basic/WskConductorTests.scala, tests/src/test/scala/system/rest/RestUtil.scala
Enables running the basic system test without requiring a `whisk.properties` file to be present. This would be useful to run test against a remote setup which is not configured via local ansible playbooks
See updated readme for details. In brief for a local default setup basic system test can be run just via
```
$ ./gradlew :tests:testSystemBasic -Dwhisk.auth="23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP" -Dwhisk.server=https://localhost -Dwhisk.ssl.relax=true
```
The test do require knowing about OpenWhisk home directory (current repo base) via env `OPNEHWISK_HOME` or system property `openwhisk.home`
=> Enable running basic system tests without requiring whisk.properties

tools/admin/README-NEXT.md
Fix the example command given for setting limits. The namespace should come in the end
=> Fix limits command docs

core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
Don't use "nodejs:6" for health action, rather "nodejs:default".
For cases in the future (or now) when nodejs:6 is not in the runtimes manifest.
=> use "nodejs:default" for health action (instead of "nodejs:6")

ansible/roles/controller/tasks/deploy.yml, ansible/roles/invoker/tasks/deploy.yml, common/scala/src/main/scala/whisk/core/entity/InstanceId.scala, common/scala/src/main/scala/whisk/core/entity/Size.scala, core/controller/src/main/resources/reference.conf, core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala, core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala, tests/src/test/scala/whisk/core/connector/tests/CompletionMessageTests.scala, tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala, tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala, tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala, tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Currently, all invokers share the same value from invoker.use-memory,
but in some cases, some invoker machines have big memory, some invoker
machines may have low memory, so it is necessary to customize invoker
use memory
for example, in `environments/local/hosts`
```
[invokers]
invoker0            ansible_host=172.17.0.1 ansible_connection=local
invoker1            ansible_host=172.17.0.1 ansible_connection=local user_memory='512 m'
invoker2            ansible_host=172.17.0.1 ansible_connection=local user_memory='2048 m'
```
=> Customize invoker use memory for memory based loadbalancing

core/controller/Dockerfile, core/invoker/Dockerfile
Add checksum verification in invoker and controller DockerFiles.
Small PR to ensure integrity of downloaded software.
=> Verify checksums of downloaded software in Dockerfiles

ansible/tasks/initdb.yml
This change is useful if some additional namespaces belonging to a subject must be initialised when couchdb is deployed.
=> Allow additional namespaces for subjects created in initdb.yml

ansible/roles/couchdb/tasks/deploy.yml
=> Fixes deprecation warning in couch playbook

common/scala/Dockerfile
Updates the base image tag from `jdk8u172-b11-alpine` to `x86_64-alpine-jdk8u172-b11` which is based on alpine:3.8
Recently there was a new release of [alpine:3.8.1][3] was done which included fix of [RCE Vulnerability][2] (see [3.8.1][3] release announcement)
> It contains an important security update for apk-tools which fixes a potential remote execution. A CVE is pending.
Current build are based on `alpine:3.7`. With AdoptOpenJDK/openjdk-docker#59 an updated build was pushed against tag `x86_64-alpine-jdk8u172-b11` which updates the base alpine version from 3.7.0 to 3.8.
Further it seems that tag naming is changed as per [latest tags at dockerhub][4].
So key points
* Base alpine updated from 3.7 -> 3.8
* Tag name changed per new convention to `x86_64-alpine-jdk8u172-b11`
[1]: …
=> Update base jdk image tag to pickup alpine:3.8

tools/travis/flake8.sh
The newest flake8 version (3.6.x) introduced new warnings - [W503, W504] ([a bug opened yesterday](https://gitlab.com/pycqa/flake8/issues/463)) and W604 which break our travis build.  
Ignoring the warnings should be ok.
The failures we observed:
```
Flake8: second round to find any other stylistic issues...
./ansible/callbacks/logformatter.py:75:12: W504 line break after binary operator
./tools/db/replicateDbs.py:85:18: W605 invalid escape sequence '\d'
./tools/actionProxy/invoke.py:60:26: W605 invalid escape sequence '\d'
./tools/admin/wskprop.py:37:16: W504 line break after binary operator
2     W504 line break after binary operator
2     W605 invalid escape sequence '\d'
./tools/admin/wskadmin:661:20: W605 invalid escape sequence '\['
./tools/admin/wskadmin:661:29: W605 invalid escape …
```
=> Fix travis failures due to flake8 update

common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
When the execute _send()_ on the Kafka producer from the underlying java library fails, there is bunch of Kafka exceptions we do not catch. In some cases the Callback is not executed as a result of the call and it could be the reason of the consumer hangup https://github.com/apache/incubator-openwhisk/issues/4076. Since we still do not fully understand the nature of the failures, the main aim of this PR is to expose the exceptions that happen in the producer.
=> Catch kafka producer exceptions and recreate the producer

ansible/roles/controller/tasks/join_akka_cluster.yml
fixes #3640 by usage of `loop_control` and `loop_var` to fix warning
#3640
=> Variable warning in controller playbook

common/scala/build.gradle, common/scala/src/main/resources/application.conf, common/scala/src/main/scala/whisk/common/Logging.scala, common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala, common/scala/src/main/scala/whisk/core/mesos/MesosTask.scala, tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
Emit metrics for mesos task launch/delete timing
Make all mesos timeouts configurable
Update mesos actor (supplants #4086)
=> Mesos metrics

core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
When a trigger is invoked, an activation object is created even if active rules are not associated with the trigger. This activation entity is not used at all when active rules are not associated with the trigger though. These changes create the activation object only when active rules are present.
=> Create trigger activation only when active rule(s) are present

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
It looks like a code comment that accidentally entered. so I erased it and put up pr.
=> Delete unnecessary code comments

common/scala/build.gradle
This sdk update addresses an issue reported against cosmosdb sdk https://github.com/Azure/azure-cosmosdb-java/issues/73
Under certain loads (ordered queries) with certain data characteristics (multiple/many partitions in data), we experienced netty `LEAK` errors and `OutOfDirectMemory` exceptions, ultimately leading to failing OW controllers. 
We (primarily @chetanmeh ) isolated the issue to the cosmosdb sdk, and provided the issue to Microsoft. Microsoft developed a fix and provided an updated SDK that we have tested with good success.
=> update to cosmosdb sdk 2.3.0

tests/src/test/scala/common/RunCliCmd.scala
Existing CLI test cases implicitly target the namespace via the `--auth` flag.  In some test scenarios, it's desirable to run the tests using the configured namespace without having the `--auth` override.  This change enables the existing CLI test cases to be run against the configured namespace.  The existing tests are left as-is.  To take advantage of this feature
- create a wrapper trait ("NewRunCliCmd") that extends an existing `RunCliCmd` trait.  Inside this new trait, override the `prohibitAuthOverride` property value with a value of `true`
- create a wrapper wsk cli class ("NewWsk") that extends the `Wsk` class.  This new class will also extend your "NewRunCliCmd" class
- create a wrapper test class that extends an existing test class.  Inside this new class, override the `wsk` …
=> optionally prohibit test cases using --auth to override the namespace target

ansible/README.md, ansible/controller-lean.yml, ansible/openwhisk-lean.yml, ansible/roles/controller/tasks/deploy.yml, ansible/roles/controller/tasks/lean.yml, ansible/roles/invoker/tasks/deploy.yml, ansible/setup.yml, common/scala/src/main/scala/org/apache/openwhisk/connector/lean/LeanConsumer.scala, common/scala/src/main/scala/org/apache/openwhisk/connector/lean/LeanMessagingProvider.scala, common/scala/src/main/scala/org/apache/openwhisk/connector/lean/LeanProducer.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala, core/lean/Dockerfile, core/lean/Dockerfile.cov, core/lean/build.gradle, core/lean/init.sh, settings.gradle, tests/build.gradle, tests/performance/preparation/deploy-lean.sh, tests/src/test/scala/org/apache/openwhisk/core/cli/test/BaseApiGwTests.scala, tools/travis/distDocker-lean.sh, tools/travis/setupLeanSystem.sh, tools/vagrant/README.md, tools/vagrant/Vagrantfile
The proposition is to get rid of Kafka, have controller and invoker compiled together into a "lean" controller-invoker (have a Gradle project for that) with controller calling the invoker's method directly via an in-memory object (a queue, which is also loaded via SPI) via a new pluggable load balancer that is selected via SPI using configuration file property setting. For more information here is a [blog](https://medium.com/@davidbr_9022/lean-openwhisk-open-source-faas-for-edge-computing-fb823c6bbb9b)
As well, briefly discussed it in this [thread](https://lists.apache.org/thread.html/516efc0ed9afb09fe52e30d10eb9fe5091af91df53a46c07e1701122@%3Cdev.openwhisk.apache.org%3E)
The goal is to avoid changes in the core components as much as possible. Rather this PR adds a few components. The …
=> Proposing Lean OpenWhisk

docs/actions-new.md
As we look to better fill out and reference the project documentation from our project web page, we found this page that was not referenced and appeared to need some organization and cleanup.
=> Cleanup/organize instructions for adding a new Action Runtime

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
This PR will add additional information into the loadbalancer which enhances debugging. With these information it will be much easier to debug, which user and which action consumed how much memory.
=> Add additional debug information to Loadbalancer.

docs/actions-new.md, docs/concurrency.md, docs/mesos.md, docs/spi.md
As the package name changes from `whisk` to `org.apache.openwhisk`, I updated the package name in documents.
=> Update the package name and path in documents

tests/src/test/scala/common/rest/WskRestOperations.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestEntitlementTests.scala, tests/src/test/scala/system/basic/WskRestBasicTests.scala, tests/src/test/scala/system/basic/WskRestRuleTests.scala
This PR adds the tid from the tid-header to the rest result. This will enhance debugging failed test cases.
In addition this PR cleans up the Warnings in `WskRestOperations`.
=> Add tid from header to RestResult in tests.

tests/performance/README.md
#4188
- [ x] I opened an issue to propose and discuss this change (#4188 )
- [ x] Tests
- [ x] Bug fix (generally a non-breaking change which closes an issue).
- [ x] I updated the documentation where necessary.
=> Fix class path in the gatling test instructions

tests/src/test/resources/application.conf.j2
Disables system exit by akka for test runs
At times I am seeing travis build failure with error message by Gradle like 
```
--
 
Execution failed for task ':tests:testCoverageLean'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 137
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the user guide at https://docs.gradle.org/4.10.2/userguide/java_plugin.html#sec:test_execution
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
See https://scans.gradle.com/s/gpsagdjubkvmc/console-log for one such case
I suspect this may be due Akka …
=> Disable system exit by akka for test runs

ansible/logs.yml, tools/travis/box-upload.py, tools/travis/setup.sh
The existing proxy for uploads of logs to Box has become unstable and is not accessible for maintenance.  I have deployed a new Proxy in BlueMix and these changes are intended to upload via that proxy.  This is likely a temporary solution while we discuss better options on the dev mailing list.
=> Switch to new Box Upload proxy

ansible/group_vars/all, ansible/roles/controller/tasks/deploy.yml, core/controller/src/main/resources/reference.conf, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
This PR makes the fraction of the pool of managed invokers configurable. This also allows to have an overlap between the pool of blackbox invokers and the pool of managed invokers.
The topic has been discussed here: https://lists.apache.org/thread.html/508e10ec9e800bb239363861385818c95d90ad1aa7df64f3b8904580@%3Cdev.openwhisk.apache.org%3E
=> Make fraction of managed invokers configurable.

tools/admin/Dockerfile, tools/admin/build.gradle, tools/ow-utils/Dockerfile, tools/ow-utils/README.md, tools/ow-utils/build.gradle
Adds a docker image containing wskadmin  to be used in kubernetes deployment for administration.
=> add wskadmin to ow-utils docker image

docs/about.md
The supported languages info in the system overview page (docs/about.md) was slightly outdated.
=> Update supported languages in documentation

ansible/group_vars/all, ansible/roles/cli-install/tasks/deploy.yml, ansible/roles/nginx/tasks/deploy.yml, ansible/roles/nginx/templates/nginx.conf.j2, tests/src/test/scala/system/rest/GoCLINginxTests.scala
Allows a host path to be served from nginx as static content as discussed on Zoom community call.
=> Mount an optional html directory for serving static content.

docs/rest_api.md
This is a doc update to remove references to openwhisk.ng.bluemix.net from the docs.
=> Update docs to remove bluemix refs.

ansible/roles/nginx/templates/nginx.conf.j2, docs/cli.md
This replays #4252 without the ansible change that proved problematic in dependent projects.
Also not removing the longer path because it is referenced in numerous places: https://github.com/search?q=%22%2Fcli%2Fgo%2Fdownload%22&type=Code
=> Allow CLI download form /cli in addition to the longer /cli/go/download

CODE_OF_CONDUCT.md
Add a COC with pointer to the Apache COC.
=> Add code of conduct pointer.

tools/travis/runTests.sh
=> Re-enable Swagger tests.

ansible/files/runtimes.json, tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
See https://github.com/apache/incubator-openwhisk-catalog/issues/294 for details.
=> Restore nodejs:6 as default. 

ansible/roles/couchdb/tasks/deploy.yml
=> Create _users database only if it does not already exist.

tools/admin/wskadmin
A small enhancement to wskadmin to revoke a key. This already exists in wskadmin-next (#4005) but recently has an experience where running the new tool was too slow and took several seconds (it was not a very powerful CPU) and running the python version was faster. I could add a test for this reusing what's there for wskadmin-next.
@chetanmeh thoughts?
(I also added a "generate only" feature to get a new uuid:key without actually storing them, was handy for testing without affecting the database. I can add this to -next.)
=> Add revoke key feature to wskadmin

ansible/roles/nginx/templates/nginx.conf.j2, common/scala/build.gradle, common/scala/src/main/resources/application.conf, common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala, common/scala/src/main/scala/org/apache/openwhisk/common/Prometheus.scala, common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala, common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala, common/scala/src/main/scala/org/apache/openwhisk/http/BasicHttpService.scala, common/scala/src/main/scala/org/apache/openwhisk/http/BasicRasService.scala, tests/src/test/scala/org/apache/openwhisk/common/PrometheusTests.scala
Enables support for exporting the metrics to [Prometheus][1] via [Kamon Prometheus][2] exporter.
This PR enables support for exposing the metrics via `/metrics` web endpoint. By default the metrics are not exposed. It can be enabled via following config 
```
whisk {
metrics {
prometheus-enabled = false
}
}
```
Sample output of `/metrics` endpoint
```
counter_loadbalancer_invokerState_unhealthy_count_total 0.0
counter_controller_startup0_count_total 0.0
counter_database_getDocument_start_total 0.0
counter_loadbalancer_activations_count_total 0.0
counter_database_saveDocument_start_total 0.0
counter_controller_kafka_start_total 0.0
counter_http_get_200_count_total 1.0
counter_database_cacheMiss_count_total 0.0
```
It needs the Kamon integration to be enabled. This PR also moves some of the …
=> Enable publishing metrics to Prometheus

common/scala/build.gradle
Update CosmosDB SDK v to 2.40 from 2.3.0 (see [changelog][1])
Major version change
- Netty from 4.1.22 to 4.1.32
- Guava - 20.0 -> 27.0.1
- Jackson - 2.9.7 -> 2.9.8
Below is the diff of jars packaged in controller.tar with new sdk version.
```diff
26a27
> animal-sniffer-annotations-1.17.jar
35,38c36,39
< azure-cosmosdb-2.3.0.jar
< azure-cosmosdb-commons-2.3.0.jar
< azure-cosmosdb-direct-2.3.0.jar
< azure-cosmosdb-gateway-2.3.0.jar
---
> azure-cosmosdb-2.4.0.jar
> azure-cosmosdb-commons-2.4.0.jar
> azure-cosmosdb-direct-2.4.0.jar
> azure-cosmosdb-gateway-2.4.0.jar
41a43,44
> checker-qual-2.5.2.jar
> commons-beanutils-1.9.2.jar
44a48
> commons-digester-1.8.1.jar
46c50,52
< commons-lang3-3.5.jar
---
> commons-lang3-3.8.1.jar
> commons-text-1.6.jar
> commons-validator-1.6.jar
52a59,60
> …
```
=> Update CosmosDB SDK to v2.4.0

ansible/templates/whisk.properties.j2, tests/src/test/scala/common/WhiskProperties.java, tests/src/test/scala/common/WskCliOperations.scala
Closes https://github.com/apache/incubator-openwhisk/issues/3861.
=> Remove deadcode.

test.txt, tests/build.gradle
updated ScalaTest to v 3.0.5 from v 3.0.1 [changelog](http://www.scalatest.org/release_notes/3.0.5)
updated ScalaMock to v 3.6.0 from v 3.4.2 [changelog](https://github.com/paulbutcher/ScalaMock/releases/tag/v3.6.0)
- [ x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
=> Scalatest version update

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala, docs/metrics.md
Increasing intial delay to 10sec for `schedule` to ensure ShardingContainerPoolBalancer is initialized before being used.
=> Bug fix 4285

ansible/roles/cli/tasks/deploy.yml, tools/macos/README.md, tools/macos/docker-machine/README.md
After this change https://github.com/apache/incubator-openwhisk/commit/1e8f07032cdcda6324fdddf1790bc6ada73f498d, we started seeing errors in our local development environments on MacOS. Installing `gnu-tar` fixed the errors.
Error:
```
TASK [cli : Expand the archive into the build directory] *************************************************************************************************************************************************************************************
Wednesday 13 February 2019  14:25:41 -0500 (0:00:00.068)       0:06:05.071 **** 
fatal: [172.17.0.1]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/Users/Shared/wskconf/nginx/cli_temp/openwhisk_cli.tgz\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" …
```
=> Comment on CLI unarchive failure

NOTICE.txt
=> update second year in copyright notice

ansible/tasks/installOpenwhiskCatalog.yml
Changing the way OpenWhisk Catalog is being deployed. Instead of using shell scripts for each package, moving towards catalog deployment with whisk deploy manifests.
Here is the PR from catalog repo: https://github.com/apache/incubator-openwhisk-catalog/pull/268
=> Changing Catalog installation to use whisk deploy

core/controller/src/main/resources/apiv1swagger.json
This PR fixes the following issues with the Swagger specification:
1. Fixed 2 typos that refer to non-existing response 'TooManyRequsts'
2. Updated description of PUT method for rule
3. Updated description of PUT method for trigger
4. Created new definition ActivationBrief
5. Changed response type for GET activations to refer to ActivationBrief instead of EntityBrief, which didn't match the actual response
6. Added attribute statusCode to definition ActivationBrief and Activation
7. Modified description of GET activations (#2271)
8. Added operationId to GET activation logs and result (#318)
9. Removed the init attribute from the ActionExec definition (#4201)
10. Use of 2 spaces for indentation, which is the default when working with the Swagger editor, instead of the four spaces …
=> Multiple fixes to apiv1swagger.json

docs/actions.md
Adds information about statusCode field in activation records.
=> Add information about statusCode field in activation records to docs/actions.md

common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
Explicitly list some of the expectations and requirements an actual container factory / container implementation needs to satisfy. Addresses #4002.
=> Improve container factory documentation

docs/metrics.md
Add documentation to support addition of new metrics.
=> Add description for new metrics added

tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
Restores `ExecMainfest`'s runtimes after YARN tests complete. Since `ExecMainfest` is a global object, modifications to its runtimes may result in unexpected behavior in other tests utilizing the object.
=> Restore default runtimes after YARN tests finish

docs/actions.md, docs/metrics.md
Cleaning up a couple typos in `actions.md` and `metrics.md`. Typos detected using https://github.com/client9/misspell.
=> Fix typos in docs

common/scala/build.gradle
Adds [Kamon Datadog](https://github.com/kamon-io/kamon-datadog) dependencies to common so that Kamon Datadog reporter can be configured for setups using Datadog
So far we only include Kamon Statsd reporter. This PR also adds the Kamon Datadog reporter such that it can be configured (if required) on setups which use Datadog for monitoring
It pulls in 1 more jars
```
|    +--- io.kamon:kamon-datadog_2.12:1.0.0
|    |    +--- org.scala-lang:scala-library:2.12.1 -> 2.12.7
|    |    +--- io.kamon:kamon-core_2.12:1.1.2 -> 1.1.3 (*)
|    |    +--- com.squareup.okhttp3:okhttp:3.10.0 (*)
|    |    \--- org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 (*)
```
So far we were maintaining separate repos internally which extend the docker images to include the datadog dependencies. Now with support …
=> Include Kamon Datadog dependencies

tests/src/test/scala/common/WskCliOperations.scala
This fixes a regression described here https://github.com/apache/incubator-openwhisk-client-go/issues/118.
=> Adapts test harness to parses activation ids from wsk activation list with new format.

ansible/environments/jenkins/ansible_jenkins.cfg, ansible/environments/jenkins/group_vars/all, ansible/environments/jenkins/hosts.j2.ini, ansible/setup.yml, tools/jenkins/Jenkinsfile
This PR is just the commit to add the Jenkins build file into the repository. It adds the features to run checkout, build, deploy, and test in Jenkins pipeline. The optimization will be done to the script in future.
Closes-Bug: #4335
=> Initial commit to add the deployment configuration for Jenkins

docs/actions-nodejs.md, docs/actions.md, docs/conductors.md, docs/triggers_rules.md
Updating documentation to reflect the new format of the output from `wsk activation list`.
=> Updated documentation to reflect the new output from wsk activation list

Jenkinsfile
I have created a pipeline in Apache Jenkins build. What we need to change in this repo is to put the file Jenkinsfile under the root directory.
=> Add the file Jenkinsfile into the root directory of OpenWhisk

common/scala/src/main/resources/application.conf, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBUtil.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala, tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSoftDeleteTests.scala, tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBStoreBehaviorBase.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreCRUDBehaviors.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreQueryBehaviors.scala
This PR enables soft delete of documents in CosmosDB. This is required for #4277
By default the documents in CosmosDB are deleted directly. This PR exposes a config option `soft-delete-ttl` which once enabled for a collection would enable the soft delete mode. In this mode instead of actually deleting the document `CosmosDBArtifactStore` would 
1. Set a `_deleted` property to `true`
2. Configure a TTL with value as specified in `soft-delete-ttl`
This ensures that document gets deleted at some later time. This would allow a service like cache invalidator to  pickup up deleted document in change feed.
The implementation of this feature needs to ensure following invariants
1. A soft deleted document cannot be read again using `get` call
2. A `put` for soft deleted document should work …
=> Enable soft delete mode for documents in CosmosDB

ansible/roles/nginx/templates/nginx.conf.j2
Fix for https://github.com/apache/incubator-openwhisk/issues/4359. 301 redirect in nginx is causing request method degradation for non-GET methods, making nginx use "308 redirect" for controller to have request method intact.
=> Request method downgraded with 301 redirect in nginx, use 308 redirect instead.

docs/metrics.md
Since we have introduced `gauge` in Openwhisk, addition to the documentation for the metrics is done here.
=> Add gauge metrics to docs

Jenkinsfile, ansible/environments/jenkins/group_vars/openwhisk-vm1-he-de, ansible/environments/jenkins/group_vars/openwhisk-vm2-he-de, ansible/environments/jenkins/group_vars/openwhisk-vm3-he-de
=> Add the test to verify the scenario when one invoker is stopped

common/scala/Dockerfile
Switches to ssl endpoint for alpine package downloads
Alpine use http endpoint (http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz) for downloading the index files. 
Per [discussion at gliderlabs/docker-alpine#184](https://github.com/gliderlabs/docker-alpine/issues/184#issuecomment-250831640) there is a suggestion to use https://alpine.global.ssl.fastly.net/alpine/
Per comment on [alpine forum](https://bugs.alpinelinux.org/issues/8087#note-3) use of http seems to be safe
> apk checks downloaded packages using repository public keys, so it shouldn't really matter much. If you insist on using HTTPS, you could use a mirror supporting it directly, without using the Fastly CDN. All this considered, using HTTP for this will have no impact on security. It will only avoid the …
=> Use https endpoint for alpine packages

tests/build.gradle, tests/dat/actions/memoryWithGC.js, tools/ow-utils/build.gradle
Trivial changes to conform to tighter scancode (I will be opening PR against utilities repo for scancode tweaks).
=> Conform to scancode.

common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala, common/scala/src/main/scala/org/apache/openwhisk/http/BasicHttpService.scala, docs/metrics.md
Replace the `count` suffix for metrics by `counter`.
Suffix `count` has been used in OpenWhisk code for recording metrics - gauges and histogram which as per definition of graphite data source corresponds to the max value by aggregation. This has been reporting incorrect information. The recommendation is to use any other suffix other than `count`, `max` and `min`, if actual count at given time is the expected output hence changing it in logging logic to `counter`.
- The data being represented for eg in - Grafana would be reported correctly. Today, due to the use of `count`, the value is aggregated by `max`.
- The graphical representation of the `count` metrics would need adaption.
=> Replace count suffix with counter

Jenkinsfile, tests/build.gradle, tests/src/test/scala/invokerShoot/ShootInvokerTests.scala
=> Fix the test report issue, so all the test result is posted

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
=> Turn method 'remove' into tail recursive

common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskPackage.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala, tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/TestJsonArgs.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala, tests/src/test/scala/system/basic/WskRestBasicTests.scala
Resolve issue https://github.com/apache/incubator-openwhisk/issues/4419, replace `JsBoolean(false)` and `JsBoolean(true)` with `JsFalse` and `JsTrue` respectively.
=> Replace JsBoolean(true | false) with JsTrue and JsFalse

common/scala/src/main/scala/org/apache/openwhisk/http/PoolingRestClient.scala, tests/src/test/scala/org/apache/openwhisk/http/PoolingRestClientTests.scala
Co-authored-by: Sugandha Agrawal <sugandha.agrawal18@gmail.com>
This PR is related to https://github.com/apache/incubator-openwhisk/pull/4388. Seeing only a http response 400 Bad Request isn't enough to understand the root cause, but the detailed error and reason information which may exist in the error response will do.
This code change adds the error and reason info of the error response to the the HTTP status code.
=> Add detailed error and reason information to status code

common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
As discussed in #3917 in some of the cases we generate dynamic metric names where the possible values are not bounded. For such cases it would be better to capture such dynamic part as tags such that metric system which does not support regex over metric names can work on tags
Fixes #3917
=> Use static metric names when tag support is enabled

common/scala/Dockerfile
Add apk update and upgrade to the common/scala/Dockerfile to deal with vulnerabilities
=> Add apk update and upgrade to deal with vulnerabilities

common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/s3/S3AttachmentStore.scala, tests/src/test/scala/org/apache/openwhisk/core/database/test/AttachmentStoreBehaviors.scala
In S3AttachmentStore, deleting attachments for entity documents is performed by:
* listing bucket keys that match the document name as prefix
* deleting each matching key
The current matching logic for listing bucket keys specific to a document matches attachment keys for other documents in some cases, where the document name prefix is the same as the to-be-deleted document.
Considering these 2 actions:
* <package1>/<action1>
* <package1>/<action1>foo
deleting <package1>/<action1> will cause deletion of bucket keys:
* <package1>/<action1>/attach1
* <package1>/<action1>/attach2
* <package1>/<action1>foo/attach3
* <package1>/<action1>foo/attach3
To repair this, I updated the matching to include a trailing slash, and updated the attachment delete test to verify this.
=> S3AttachmentStore: prevent deletion of other s3 bucket keys on doc delete

docs/metrics.md
=> repair metric name suffix 'count' to 'counter'

tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/ElasticSearchLogStoreTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/ElasticSearchRestClientTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/LogDriverLogStoreTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/SplunkLogStoreTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala, tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala, tests/src/test/scala/org/apache/openwhisk/http/PoolingRestClientTests.scala
Shutdown actorSystem for tests which is inherited from TestKit to avoid memory leak
=> Shutdown actorSystem when tests are finished

docs/actions-docker.md, docs/actions-nodejs.md
Adding common use-case instructions based on community feedback. 
Re-wrote Node.js and Docer action documentation to incorporate common issues users having been running into based on my interactions in the external community. 
This includes...
- Bundling external modules with native deps in Node.js
- Using module bundlers to build single source file
- Extending custom runtimes with Docker support
- Better examples for `--native` flag.
=> Updating Node.js and Docker docs.

docs/actions-nodejs.md
Great job on the updated docs but I think we should remove the `ibmcloud` part from the commands as we should remain vendor agnostic.
=> Remove ibmcloud specific command

tools/admin/wskadmin
The returns of zip and  popen in python2 and python3 are not compatible.
Therefore,  this caused a typeerror in python3.
=> make wskadmin python2 and python3 compatible

README.md, docs/actions-actionloop.md, docs/actions.md
Documentation to implement an actionloop based runtime
Added documents
How to create an actionloop runtime
=> Actionloop docs

tests/dat/actions/openFiles.js, tests/src/test/scala/invokerShoot/ShootInvokerTests.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala, tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala, tests/src/test/scala/system/basic/WskActionTests.scala, tests/src/test/scala/system/basic/WskRestBasicTests.scala
Fix the automated test cases to also work with nodejs:10 as default nodejs runtime.
These changes are to prepare for the upcoming nodejs:6 deprecation.
When switching to nodejs:10 as the default nodejs runtime, several testcases fail. Reason for this is, that the test cases assume/expect, nodejs:6 is used to execute the actions. With the deprecation of nodejs:6 it will be necessary that the tests will work with a newer nodejs version.
The testcases have now been modified to work with nodejs:6 and with nodejs:10 as the default runtime. Nodejs:8 may also work, but has not been tested.
This PR does not change the default nodejs runtime. It is just to prepare for switching to nodejs:10 as the default runtime.
In most cases the test now explicitly execute on nodejs:10 and also check, that they …
=> Fix test cases to also work with nodejs:10 as default nodejs runtime.

docs/actions-actionloop.md
=> Touch-up Action loop markdown adjusting grammar/flow

tools/ubuntu-setup/README.md
Java runtime errors occur consistently on ubuntu 14 -- fix proposed.
=> ubuntu installation guide change

common/scala/build.gradle, common/scala/src/main/resources/application.conf, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala, common/scala/src/main/scala/org/apache/openwhisk/http/PoolingRestClient.scala, settings.gradle, tests/build.gradle, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala, tools/build/README.md
Updates the following dependencies
* Akka modules - 2.5.12 -> 2.5.22
* Akka HTTP - 10.1.1 -> 10.1.8
* Scala - 2.12.7 - 2.12.8
Required for #4315 and #4217
=> Update version for Akka dependencies and Scala

docs/actions-actionloop.md
=> Additional cleanup and simplifications for the ActionLoop docs

core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
Recent merge of the https://github.com/apache/incubator-openwhisk/commit/6982f460c293214928f4b62b2572d6bd83d61a4e introduced a bug in LeanBalancer. This PR comes to resolve it by instantiating Invoker via SPI
=> Resolves broken LeanBalancer

Jenkinsfile
Adds a test to Jenkins to test Lean Openwhisk setup by running WskRestBasicTests on Lean setup
=> Adding Lean Openwhisk test to Jenkins

Jenkinsfile
=> Fixing Jenkins Lean Openwhisk test

tools/ow-utils/Dockerfile
For more information please check https://github.com/apache/incubator-openwhisk-deploy-kube/issues/467
=> Invoker agent failed to pull docker images if using private docker registry.

common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala, tests/src/test/scala/common/WhiskProperties.java, tests/src/test/scala/common/rest/WskRestOperations.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
=> Remove default port on api host.

common/scala/src/main/scala/org/apache/openwhisk/core/entity/Annotations.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala, core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala, tests/src/test/scala/invokerShoot/ShootInvokerTests.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala, tests/src/test/scala/system/basic/WskActionTests.scala, tests/src/test/scala/system/basic/WskConsoleTests.scala, tests/src/test/scala/system/basic/WskRestBasicTests.scala
Consolidated and moved all the annotations into a single location as described in the issue (#3401) and replaced all occurences.
https://github.com/apache/incubator-openwhisk/issues/3401
=> #3401: Moved local variables to Constants and renamed all occurences

core/standalone/build.gradle
Currently the `./gradlew install` is failing. This PR fixes that
Currently the `./gradlew install` results in following error message
```
> Task :core:standalone:install FAILED
Execution failed for task ':core:standalone:install'.
> Could not publish configuration 'archives'
> Cannot publish artifact 'openwhisk-standalone.jar' (/path/to/openwhisk/core/standalone/build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar) as it does not exist.
```
It looks like Gradle Boot Plugin disables the jar task and hence `install` task does not finds the jar to install. Based on workaround suggested in spring-projects/spring-boot#13187 now we add dependency on `bootJar` for `install` task
=> Fix the install task for standalone module

common/scala/src/main/scala/org/apache/openwhisk/core/entity/ConcurrencyLimit.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/LogLimit.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/MemoryLimit.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/TimeLimit.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala, tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala, tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala, tests/src/test/scala/org/apache/openwhisk/core/limits/ConcurrencyTests.scala, tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
* Add information whether the action memory / time limits are standard, i.e. default, or not.
* Restructure message and shorten it to make log volume smaller despite adding information.
* The code uses the term "scheduling an activation to an invoker". Change message to use this term.
* Also add more information to message that indicates that an activation could not be scheduled to an invoker because no usable invokers are available. The additional information helps to identify which particular activation was affected.
* The proposed message changes are meant to help operators with understanding the effects of overloading an invoker with more activations than it can process in parallel from a user memory perspective. This can happen in an overload situation - i.e. no invoker has enough …
=> Add action timeout limit to invoker assignment message in load balancer

common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KafkaConsumerConnector.scala
Kafka's consumer.wakeup() is to `shutdown consumer gracefully`.
In KafkaConsumerConnector.scala, has below points, exist `WakupException happend`
* peek(wakup() is called, then execute poll, WakupException happened)
* commit (Actually, when do this action, wakup() is called, WakupException happend)
* metric reporting scheduler (wakup() is called, then execute endOffsets, WakupException happened)
Regarding peek, handle its own way.
Regarding commit and metric reporting scheduler, it is better to close the consumer.
=> Close the consumer when WakeupExcpetion happened

core/cosmosdb/cache-invalidator/build.gradle
close: https://github.com/apache/openwhisk/issues/4574
=> update distDocker plugin import

settings.gradle
=> Update to Scala 2.12.9

common/scala/src/main/scala/org/apache/openwhisk/core/entity/Size.scala
=> add GB unit to ByteSize

docs/actions-new.md, tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
Fixes some typos and amends docs for container proxy tests. I also renamed the newly added test to remove "partition" which is a remnant of a previous implementation.
=> Amend docs for container proxy tests.

tools/owperf/setup.sh
=> update owperf setup function parameters

tools/eclipse/scala.properties
=> change Eclipse indentSpaces to 2

common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
add kind "unknown" for fallbacked activations
=> Add kind "unknown" to fallback activations

common/scala/build.gradle
Updates CosmosDB SDK to 2.5.0 (from v2.4.2)
See [changelog](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-async-java#release-notes) for details. 
One Key change is that when using `Direct` mode the `TCP` mode is now set as default. We can now test switching by default to `Direct/TCP` mode
=> Update CosmosDB SDK to v2.5.0

common/scala/build.gradle
Updates to CosmosDB SDK 2.6.1 which has some more fixes for Direct connectivity support
Recently we updated to v2.5.0 with #4631 which was based on [released versions info at docs](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-async-java#release-notes). However it appeared that there are more version released as per github [changelog](https://github.com/Azure/azure-cosmosdb-java/tree/master/changelog). So now moving to 2.6.1
This also seems to fix some of the [resource leak error I saw in tests](https://travis-ci.org/chetanmeh/incubator-openwhisk/jobs/586383690#L5518) which are not being observed now
=> Update to CosmosDB SDK v2.6.1

tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
It just removes redundant test code in PackagesApiTests
=> Remove redundant test code

core/standalone/README.md, core/standalone/src/main/scala/org/apache/openwhisk/standalone/ApiGwLauncher.scala, core/standalone/src/main/scala/org/apache/openwhisk/standalone/CouchDBLauncher.scala, core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneOpenWhisk.scala
Standalone OpenWhisk now supports quite a few optional features which can be enabled by  various options (`--kafka`, `--api-gw`, `--counchdb`, `--user-events`) etc. 
This PR introduces a `--all` mode which would enable all the above features via single argument and launch all optional services (Kafka, Prometheus, Redis etc)
Run all supported OpenWhisk Standalone features
```
java -jar openwhisk-standalone.jar --all
```
Currently this mode would launching following services (in 7 docker containers)
```
===============================================================
Launched service details
[ 3233  ] http://localhost:3233 (Controller)
[ 6379  ] http://localhost:6379 (whisk-redis)
[ 9000  ] http://localhost:9000 (whisk-apigw, Api Gateway - Api Service )
[ 3234  ] http://localhost:3234 …
```
=> Standalone God mode

.travis.yml, tools/travis/docker.conf, tools/travis/docker.sh, tools/travis/setup-docker.py
=> Fix Travis build pip install issue in pre installation step

tests/src/test/scala/common/TestUtils.java, tests/src/test/scala/common/WhiskProperties.java
This reverts commit 15709b6768679e04d7cd269d99d73b52d003091a from PR #4647.
=> Revert "Remove unused test helpers"

core/monitoring/user-events/compose/grafana/dashboards/global-metrics.json, core/monitoring/user-events/compose/grafana/dashboards/openwhisk_events.json
* This PR changes the user-events Grafana dashboard and fixes some of the issues noticed on zooming in and out on different time intervals. 
* Additionally it will display the `waitTime` in the global graph.
=> User-events grafana dashboards changes

tools/admin/README-NEXT.md
Fixes the command examples used for wskadmin-next as identified in #4687
`wskadmin-next` cli support differs in some forms from the python based `wskadmin` due to difference in argument parsing support used by backing libraries 
1. `wskadmin-next` - [scallop](https://github.com/scallop/scallop)
2. `wskadmin` - [argoarse](https://docs.python.org/3/library/argparse.html)
Base difference
1. `-ns` in `wskadmin` vs `--namespace` in `wskadmin-next` - Python support short args with single `-` while with scallop only supports single letter short form. Hence one need to use wither `-n` or better `--namespace`
2. Argument positioning - Python support options after the trailing input like `user delete userB -ns space1`. With scallop we need to pass all the options first `user delete --namespace …
=> Fix command examples for wskadmin-next

core/monitoring/user-events/build.gradle, core/monitoring/user-events/compose/grafana/dashboards/openwhisk_events.json, core/monitoring/user-events/src/main/resources/application.conf, core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/EventConsumer.scala, core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/KamonRecorder.scala, core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorder.scala, core/monitoring/user-events/src/test/resources/logback-test.xml, core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/ApiTests.scala, core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/KafkaSpecBase.scala, core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorderTests.scala, core/standalone/src/main/resources/logback-standalone.xml, settings.gradle, tests/src/test/resources/logback-test.xml
Updates Alpakka Kafka to 1.1.0. This is currently used by user-events service and comosdb cache invalidator service
Per [release notes](https://doc.akka.io/docs/alpakka-kafka/current/release-notes/1.1.x.html#1-1-0)
> Alpakka Kafka 1.1 changes the internals of how offset commits are sent to the Kafka broker. The new implementation is very beneficial for high-throughput consumers as committing is now connected to the regular polling of the Kafka consumer, which reduces pressure on Kafka.
Further this PR also includes couple of small fixes
1. Fixes inclusion of test library in compile scope by user-events
2. Turns off the very verbose logging from embedded Kafka completely
3. Reduce some of the test timings
=> Updates Alpakka Kafka to 1.1.0

common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskEntity.scala, tests/src/test/scala/org/apache/openwhisk/core/entity/test/WhiskEntityTests.scala
The action can be deleted with wsk trigger delete.
=> Fixed to check entityType when deserializing entity

settings.gradle
Release notes - https://github.com/scala/scala/releases/tag/v2.12.10
=> Update to Scala 2.12.10

tests/build.gradle
We saw some builds failing related to swagger tasks 
```
> Task :tests:generateSwaggerCodeJava FAILED
Execution failed for task ':tests:generateSwaggerCodeJava'.
> Add swagger-codegen-cli to dependencies of the project as follows:
dependencies {
swaggerCodegen 'io.swagger:swagger-codegen-cli:x.x.x'
}
```
These updated versions seem to work better, but I'm not sure why it started.
=> update swagger plugin and swagger codegen cli

common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala, common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
Added more details to the unsupported runtimes exception.
Provided more details for the unsupported runtime exception for the ease of debugging.
=> Added more details for unsupported runtimes exception

.travis.yml
The Scala version in Travis should not be significant to us anyway as gradle should take care of fetching the correct compilers etc.
=> Simplify Travis by removing an explicit mention of the Scala version.

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/StandaloneDockerContainerFactory.scala, core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala
Just a bit of general cleanup I noticed while doing other things.
=> Use Either.toOption and prettify escaped strings in ContainerFactories.

docs/actions.md
=> Remove duplicate `actions list` in `wsk` command

build.gradle, common/scala/build.gradle
This constraints all relevant packages of akka to the versions we specify in all Scala based projects. This should solve the `Detected possible incompatible versions on the classpath` notes we have in our builds.
=> Constraint all akka packages in all builds for a consistent outcome.

core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskWebActionsTests.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
This removes the extensions on web actions. This is a breaking change.
=> Remove path projections on web actions.

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Change ContainerPool buffer processing to be based on state change messages to reduce cpu burn.
Existing message processing in ContainerPool can get into loops of immediately resending Run messagings causing cpu burn and crashing in cases where:
- Run messages arrive but cannot be processed so begin queueing
- First message in queue cannot be processed, and is resent constantly
This change alters the buffer handling to:
- Not resend the same Run message during message processing
- Only resend the head of queue Run message when some other event occurs that may free resources: scheduled to container, completed run in container, container is removed
=> Change ContainerPool buffer processing 

docs/dev/modules.md, tools/dev/src/main/groovy/CategoryManager.groovy
- extend script that builds module list to put archived modules in a separate section.
- regenerate devs/modules.md
=> filter archived github repos into separate section of module list

core/standalone/build.gradle
With this change, the standalone project build uses relative paths instead of absolute paths starting from the root project. With these relative paths, the standalone project can be built as sub-project of different root projects.
Co-authored-by: Georg Bildhauer <bildh@de.ibm.com>
With the current usage of `project.rootProject.getProjectDir()` in Gradle build files, the standalone project can no more be built when imported by another Gradle project. This is fixed by changing all references to relative references.
This is not really a bug fix but a small enhancement that should not change any existing behavior. Only a slight change in the build strategy.
=> Change absolute to relative file references

ansible/group_vars/all
Updates the nginx docker version to pick up security fixes
=> Update nginx docker image to 1.17 pick up security fixes

tools/jenkins/apache/dockerhub.groovy
Add the standalone docker image to docker hub
=> add standalone to dockerhub

core/standalone/README.md, core/standalone/start.sh, core/standalone/waitready
- better readme
- use the nightly image by default in start
- test openwhisk is able to create actions at startup
=> Improved standalone launch script

tools/ubuntu-setup/README.md, tools/ubuntu-setup/misc.sh
@aviweit  -- does this capture our off-list discussion on getting this to work in 18.04?
=> ubuntu 14 => 18 in instructions

core/cosmosdb/cache-invalidator/build.gradle
Updated the gradle dependency for the `cache-invalidator` service to use the Azure CosmosDB SDK `v3.5.0`
The prior version of the Azure CosmosDB SDK `v3.3.0` used by `cache-invalidator` was throwing exceptions which caused the ChangeFeedProcessor to no longer emmit events. The [changes included](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/changelog#350) in CosmosDB SDK `v3.5.0` resolved a number of issues related to the ChangeFeedProcessor
=> Update cache-invalidator to use Azure CosmosSDK to v3.5.0

ansible/group_vars/all, ansible/roles/kafka/tasks/deploy.yml, tests/src/test/scala/services/KafkaConnectorTests.scala
Major jump in kafka docker image tag from 0.11.0.1 to 2.12-2.3.1.
=> upgrade kafka server version from 0.11.0.1 to 2.3.1

core/monitoring/user-events/README.md, core/standalone/README.md, docs/dev/modules.md
I've removed incubator references that haven't been removed yet and verified that all links are working properly.
- Documentation
=> Remove incubator references

docs/actions-rust.md
Adding the following to complete the documentation for rust runtime:
#4443
=> Added documentation for Rust runtime

.github/ISSUE_TEMPLATE/proposal.md, proposals/POEM-1-proposal-for-openwhisk-enhancements.md, proposals/POEM-N-template.md, proposals/README.md
=> Define processes for enhancement proposals

tools/macos/README.md
=> Update brew commands

build.gradle, tests/build.gradle
This release added support for Scala 2.13: https://github.com/scoverage/gradle-scoverage/releases/tag/4.0.0.
Ref #4741
=> Update scoverage plugin to 4.0.1.

common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala, common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupport.scala, common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosTask.scala, tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
Some more compilation fixes, but small enough to just group them into one PR.
Ref #4741.
=> Some small compilation fixes for 2.13 migration.

proposals/POEM-1-proposal-for-openwhisk-enhancements.md, proposals/README.md
=> Fix broken links.

common/scala/src/main/scala/org/apache/openwhisk/core/ack/Ack.scala, common/scala/src/main/scala/org/apache/openwhisk/core/ack/MessagingActiveAck.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/InstanceId.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/LogStoreCollector.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- The ack logic that responds to kafka messages to the controller can be used by other components in the downstream. So move ack logic that is only available in invoker package to common package.
- In our downstream, we are creating a new component called [Scheduler](https://cwiki.apache.org/confluence/display/OPENWHISK/Autonomous+Container+Scheduler+v2). The Scheduler performs a kind of queue, where it also responds to queued stale messages to the controller. As such, the ack logic may be used by other components in the downstream, so it seems more appropriate to include it in a common package. And this change has the advantage that the ack logic can be modified more flexibly downstream.
- `InvokerReactive` is also new and in use, so I moved `LogsCollector` from `InvokerReactive` to …
=> Move the ack implementations to the common package.

tests/src/test/scala/org/apache/openwhisk/core/database/test/CacheConcurrencyTests.scala
I broke this one out of the last PR because the concurrency looked a bit more tricky to get right on the surface. If I read the code correctly though, this should equally replicate the state we had before.
Each individual task used way too big thread pools and the maximum amount of total work we do is `internalIters * 30` (cause the inner loops do 30 iterations), thus a single fixed thread pool of that size should suffice and can be reused in all tasks.
Ref #4741
=> Replace remaining usages of parallel collections with explicit concurrency.

tests/src/test/scala/services/HeadersTests.scala
=> Removed unused import statement

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
Fixing broken compile problem from PR #4857
(not sure why PR build passed?)
=> fix creation logic broken from wait changes

docs/actions-go.md
=> Add -i to docker command, otherwise doesnt work

common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala, core/monitoring/user-events/compose/grafana/dashboards/openwhisk_events.json
-  Status code defined by action developers is captured by this PR #4726. Add Dashboard for User Defined Action Status Code which will be helpful to give insights about the actual error code returned in action (though only available if defined by the user).
- Improvement based on review comment. (https://github.com/apache/openwhisk/commit/39b746f08ad872016b81e7d4950f900f7231d11b#r37443591)
=> Add Dashboard for User Defined Action Status Code

core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
Fix a few typos in a comment section.
=> Fix typos in comments.

core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala, tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
This patch fixes a bug whereby webactions cannot respond to OPTIONS even for default CORS responses because the handler check for authentication first, before checking if the requests if an OPTIONS request.
Actions that opts for the default response are not affected - they are only invoked if the request is not an OPTIONS request as before. Actions which respond to OPTIONS explicitly will be invoked even if not authenticated yet but this should be acceptable since the action cannot respond to OPTIONS otherwise.
- [] Enhancement or new feature (adds new functionality).
=> Allow OPTIONS response on web actions before checking for authentication.

README.md
We've discussed in the past using the standalone controller as the new quick start. This morning I was trying to help someone in the community slack and I had trouble bringing up the compose version of the quick start. Plus it took many minutes to pull all the docker images. By contrast standalone is much lighter weight. 
This is an attempt to replace compose with standalone controller in the welcome docs.
cc @chetanmeh @sciabarra I know we can do even better with the docker self container version. If you can point me to those steps, I can include them.
=> Replace compose with quick-start standalone OpenWhisk.

docs/actions-docker.md
"read ARGS" does not work for web action then should be modified with "ARGS=$@"
=> Update Example (Shell Script)

tools/admin/wskutil.py
=> add verify cert env var to wskadmin

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
=> Remove unnecessary sysout

core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala, tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecManifestTests.scala
=> Remove unused codes

ansible/files/runtimes.json, core/controller/src/main/resources/apiv1swagger.json, docs/actions-new.md, docs/actions-nodejs.md, docs/concurrency.md, tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecManifestTests.scala, tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala, tools/owperf/setup.sh
Remove all references to EOL NodeJS v6 and v8 runtimes.
=> remove nodejs:6 and nodejs:8

proposals/POEM-1-proposal-for-openwhisk-enhancements.md, proposals/POEM-2-function-pulling-container-scheduler.md
A POEM to propose a new scheduler.
=> Add a proposal for a new scheduler

tools/ow-utils/Dockerfile
https://github.com/apache/openwhisk/issues/4936
=> Fix ow-utils image build failed issue

tools/build/citool
Found while using python 3 - a missing bytes to string decode.
=> Decode bytes to string.

README.md
* Updating the project Slack URL
=> Correcting the Slack channel URL

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
This is a sister to #4938 to improve failure handling cases for:
- concurrency enabled actions
- cold start container failures
In a previous PR #4938 we changed the behavior where
- concurrency enabled actions
- init failure occurs
so that any queued activations at the ContainerProxy (because the action supports concurrency), will be aborted if /init fails.
This PR, extends that same behavior to the case where cold start of a container fails.
In both cases (/init fails, cold start for the container fails), we assume that a failure will not resolve by retry of the activation(s). That won't always be true (a transient issue with docker registry), but in our experience it usually true (an invalid image, or inability to launch containers for some longer amount of time than will be resolved in …
=> cold start container failure should abort buffered concurrent activations

common/scala/Dockerfile-debian, core/controller/Dockerfile-debian, core/cosmosdb/cache-invalidator/Dockerfile-debian, core/invoker/Dockerfile-debian, core/monitoring/user-events/Dockerfile-debian, gradle/docker.gradle
Optionally create debian based images.
Some infrastructure components in our operations have trouble with Alpine images, so we need to be able to use some other base image, e.g. Debian.
This PR allows creation of debian (or other) based images for controller, invoker, etc by
* adding additional Dockerfiles named with a suffix e.g. `Dockerfile-debian` 
* using a gradle property to enable use of alternate Dockerfiles by suffix`-PdockerfileSuffix="-debian"`
* use default (`Dockerfile`) if no suffix specified, or not available for that module
There may be a better way to do some of this (e.g. use a different base image, and use build args or a multi stage build), but when some commands (e.g. user management) vary by distribution, it is simpler to just have a different Dockerfile.
=> optionally use debian docker images

ansible/README.md
The use of `<environment>` instead of a variable really hurts the copy-paste-ability and makes it harder to follow along, so I replaced it with `$ENVIRONMENT` which is defined at the top of the file.
Also added languages to some of the code fences for highlighting.
=> Update Ansible README.md [noci]

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainer.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Current behavior is that exception from the api call to create a pod, does NOT attempt to delete the pod that was just referenced. Original thought was that if the api call was unsuccessful, there would be nothing to cleanup. But we've seen other cases where the api call fails, and yet the pod is still created (and therefore becomes orphaned). 
With this PR, on an error from kubernetes api server (whether a response error, or some exception from fabric8 client, doesn't matter), now we attempt to delete the pod which may or may not have been created.
=> Kubernetes - delete pod on api failure

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala
=> Add container name parameter to k8s log api explicitly

core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala, core/standalone/src/main/resources/standalone-kcf.conf, tests/src/test/resources/application.conf.j2, tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
If want to deploy two helm release openwhisk cluster,  when the second helm release cluster's invokerN pod is restarting, it will delete the first helm release's invokerN runtime pods.
Because when invokerN pod is starting, it will delete  runtime pods with label(invoker=invokerN) only. e.g.
https://github.com/apache/openwhisk/blob/master/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala#L65
in order to avoid `delete other helm release invokerN's runtime pod`, it is better to add helm release to invoker pod, and when invoker pod is starting, add label(release=xxxxxx) together with label(invoker=invokerN) to delete runtime pods.
Another brother pr: https://github.com/apache/openwhisk-deploy-kube/pull/639
=> Add release to runtime pod and delete with release

core/controller/src/main/resources/apiv1swagger.json, tests/src/test/scala/system/rest/SwaggerTests.scala
Swagger and API mismatch for action, trigger, rule list, we need to keep `swagger document` and `the actual API return result` consistent
e.g.
Swagger - Get all actions
```json
[
{
"namespace": "string",
"name": "string",
"version": "string",
"publish": true,
"exec": {
"kind": "blackbox", // missing
"code": "string",     // missing
"image": "string",   // missing
"main": "string",     // missing
"binary": true,
"components": [
"string"
]                 // missing
},
"annotations": [
{
"key": "string"
}
],
"parameters": [
{
"key": "string"
}
], // missing
"limits": {
"timeout": 0,
"memory": 0,
"logs": 0,
"concurrency": 0
},
"updated": 0
}
]
```
API
```json
[
{
"namespace": "string",
"name": "string",
"version": "string",
"publish": true,
"exec": {
"binary": true,
},
"annotations": [
{ …
```
=> Fix Swagger and API mismatch for action, trigger, rule list

core/routemgmt/common/apigw-utils.js
Bug fix: addresses issue #4523
=> Switch from hardcoded "https" protocol

core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala, tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskWebActionsTests.scala
=> Actions with require-whisk-auth annotation as boolean false are rejected by controller

ansible/files/runtimes.json
.json doesn't support comments
=> Fix runtimes.json in 1.0.0 branch

tools/admin/wskprop.py
Address minor issue encountered using wskadmin with py3.
=> Python 3 conditioning for wskadmin.

tools/actionProxy/invoke.py
Small fixes for invoke.py and python 3 compatibility.
=> Python 3 fixes.

ansible/group_vars/all
This patch quotes a default value in the ansible configuration which fixes https://github.com/apache/openwhisk-devtools/issues/329.
=> Quote ansible default value.

common/scala/build.gradle
Update outdated Kamon bundle dependencies to 2.1.12 version
=> Updated Kamon bundle dependencies to 2.1.12 version

tests/build.gradle
Upgraded the version of testcontainers
- #5120 Unit Tests failing due to testcontainers
=> #5120: Unit Tests failing due to testcontainers

NOTICE.txt
Just updating the year of NOTICE.txt.
This is to conform to this change: https://github.com/apache/openwhisk-release/pull/391
=> Update the notice year

common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala, core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/ActivationClientProxy.scala, core/scheduler/src/main/protobuf/activation.proto, core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/grpc/ActivationServiceImpl.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/ActivationClientProxyTests.scala, tests/src/test/scala/org/apache/openwhisk/core/scheduler/grpc/test/ActivationServiceImplTests.scala
* FunctionPullContainerProxy creates ActivationClientProxy actor and sends  `StartClient` to ActivationClientProxy
* ActivationClientProxy creates akka grpc client after get `StartClient` message.
* After created akka grpc client, ActivationClientProxy sends `ClientCreationCompleted` to FunctionPullContainerProxy.
* FunctionPullContainerProxy goto(ClientCreated) FSM state and sends `RequestActivation` to ActivationClientProxy
* ActivationClientProxy actor fetches activationMessage from scheduler side's MemroyQueue using akka grpc after got RequestActivation message.
* ActivationClientProxy actor forwards the activationMessage to FunctionPullContainerProxy,
* FunctionPullContainerProxy initializes/runs the activationMessage.
=> [New scheduler] ActivationClientProxy

ansible/roles/invoker/tasks/deploy.yml, tests/src/test/resources/application.conf.j2
They are supposed to be there but are missing.
Since there are default values, it has been working as expected but good to add these configurations.
=> Add missing configurations.

tools/github/debugAction.sh
Upgrade the version of ngrok to v3.
It is required to run the on-demand workflow to debug CI tests.
=> Update ngrok to v3

ansible/files/runtimes-nodeonly.json, ansible/files/runtimes.json, ansible/group_vars/all, core/standalone/README.md, core/standalone/src/main/resources/standalone.conf, core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala, core/standalone/start.sh, docs/actions.md, tools/github/runStandaloneTests.sh, tools/jenkins/apache/dockerhub.groovy, tools/travis/runStandaloneTests.sh
This is to fix the runtime tag in the 2.0.0 branch.
The base branch to merge this change into is the `2.0.0` branch.
=> Fix runtime tags in 2.0.0 branch

.asf.yaml
=> Update .asf.yaml - fix spelling

common/scala/src/main/scala/org/apache/openwhisk/core/ack/Ack.scala, common/scala/src/main/scala/org/apache/openwhisk/core/ack/HealthActionAck.scala, common/scala/src/main/scala/org/apache/openwhisk/core/ack/MessagingActiveAck.scala, common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala, common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskEntity.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala, core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/FPCPoolBalancer.scala, tests/performance/README.md, tests/performance/gatling_tests/src/gatling/scala/org/apache/openwhisk/ColdBlockingInvokeSimulation.scala, tests/src/test/scala/org/apache/openwhisk/core/connector/tests/AcknowledgementMessageTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala, tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala, tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala, tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTestsFixture.scala, tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
=> Fix spelling
