docs/README.md

The previous link was going directly to the Alarm documentation in the catalog page. This one links to the alarm example that includes wiring the trigger to an action.

Fix link to alarm service example.

---

tools/db/createImmortalDBs.sh

Currently script, tries to work with `URL_BASE="https://$USER.cloudant.com"` where `$USER` is the user of local machine (computer host), which doesn't necessary same as `OPEN_WHISK_DB_USERNAME` the actual cloudant account username. Changed script to work with `OPEN_WHISK_DB_USERNAME` instead of `$USER`.

Change base url to use cloudant user.

---

README.md

Includes the documentation fix in #55 as well as new documentation on the use of CouchDB as an alternative to Cloudant.

Pull request #55 and CouchDB documentation

---

core/dispatcher/src/whisk/core/invoker/Invoker.scala
tests/src/common/WskCli.java
tests/src/system/basic/CLIRuleTests.java

Add test that detects lost activation counts leading to inappropriate throttling by creating a dangling rule.  Fix the invoker so that activations have their counts and records generated even if unsuccessful.

WIP: Lost activation count

---

services/kafka/Dockerfile

The `ADD http...` constuct requires network connectivity every single time the image is built, while `RUN` commands get cached. Using `maven` here to do it "cleanly", although `wget` would be another option.

Make `whisk/kafka` build-able from cache

---

core/dispatcher/src/whisk/core/invoker/Invoker.scala

PG builds 115 and 118 verify general correctness.  Note that the failing test is one that is happening in head as well (PG build 119).   Looking at the loadblancer logs for PG 118, we see that the in-flight count is now near 0.

Move global counter manipulation so all transactions will go through this

---

core/loadBalancer/deploy.yml
environments/local/group_vars/all

Signed-off-by: Hoang Anh Le <hoang@de.ibm.com>
initial support for deployment using docker registry. unfortunately the ansible docker module has bugs that prevent us from using the "pull" and "registry" settings (they are ignored) which forces us to write a shell task that does the pull. other components will be updated with registry support as well.

issue #100 provide initial playbook for loadbalancer. supports registry

---

tests/src/system/basic/CLIActionTests.java

This test is white box testing old load balancer behavior and is no longer valid.  Non-functional testing should not be in this suite anyway.  We do have a test for loadbalancer behavior in CLILoadBalancerTests already.

Remove invalid test

---

common/scala/build.gradle
core/controller/build.gradle
core/dispatcher/build.gradle
core/loadBalancer/build.gradle
tests/build.gradle
tests/src/system/basic/CLIActionTests.java

* Updated `scala-library`
* Explicity reference used scala library per project (needed for eclipse to keep down the warnings)
* Removed unused import

Fix warnings in eclipse

---

config/localEnv.sh
config/writePropertyFile.sh
tests/build.gradle
tests/src/common/WhiskProperties.java

This avoid having to disambiguate its location in the presence of multiple whisk.properties files in the directory tree.

Write openwhisk.home to property file. 

---

common/scala/src/whisk/common/ConsulKVReporter.scala
common/scala/src/whisk/common/Curl.scala
common/scala/src/whisk/common/SimpleExec.scala
core/dispatcher/src/whisk/core/container/Container.scala
core/dispatcher/src/whisk/core/container/ContainerPool.scala
core/dispatcher/src/whisk/core/container/ContainerUtils.scala
core/dispatcher/src/whisk/core/container/WhiskContainer.scala

Transaction id was neither propagated nor maintained correctly.  Making the field explicit and mutable (as container warmed up by the system can be used by a different transaction) fixes the missing ???.  
Moreover, even before the recent warmup work, containers were being reused and the lack of updating the implicit transaction id parameter led to associated docker operations being mis-attributed.
Remove the default dont_care parameter for SimpleExec so that caller must supply one.

Fix transaction id to be explicit and mutable within Container

---

common/scala/src/whisk/common/ConsulKVReporter.scala
common/scala/src/whisk/common/Curl.scala
common/scala/src/whisk/common/Logging.scala
common/scala/src/whisk/core/connector/Message.scala
core/dispatcher/src/whisk/core/container/ContainerPool.scala
core/dispatcher/src/whisk/core/container/WhiskContainer.scala
core/dispatcher/src/whisk/core/invoker/Invoker.scala
tests/src/services/KafkaConnectorTests.scala
tests/src/whisk/core/container/test/ContainerPoolTests.scala
tests/src/whisk/core/database/test/DbUtils.scala
tests/src/whisk/core/dispatcher/test/DispatcherTests.scala
tests/src/whisk/core/loadBalancer/LoadBalancerTests.scala

Activity occurs in the invoker (probably others) not necessarily as a result of a transaction.
Background activity can be logged using an `sid_NNN` in the log messages to give greater
information.  Most `dontcare` have been replaced by more meaningful values with the few remaining
cases named to `unknown`.
PPG 350 - passed.

Add notion of sid to extend tid

---

core/controller/src/resources/whiskswagger.json

I wanted to run the tests after the change, but when I'm trying to run gradle test I get the following 
```
* Where:
Build file '/Users/cjolif/Dev/hub/openwhisk/tests/build.gradle' line: 59
A problem occurred evaluating project ':tests'.
> /Users/cjolif/Dev/hub/openwhisk/whisk.properties (No such file or directory)
```

update swagger to specify TriggerLimits is of type object. fixes #241.

---

common/build.xml
common/scala/src/whisk/common/TransactionId.scala
common/scala/src/whisk/core/entity/WhiskPackage.scala
common/scala/src/whisk/http/ErrorResponse.scala
tests/src/system/basic/PackageTests.scala
tests/src/system/basic/WskBasicTests.scala
tests/src/whisk/core/controller/test/PackagesApiTests.scala
tests/src/whisk/core/controller/test/RulesApiTests.scala

Add tests to verify a response code is present on failed API calls.
Remove invalid reference to libJars.
Add custom serializer to JSON to only serialize relevant parts of TransactionId.
Add convenience method to retrieve id from TransactionId metadata object.
Remove evidence ugliness in WhiskPackage.

Add test to confirm presence of code on failed API calls.

---

common/scala/src/whisk/common/ConsulKV.scala
common/scala/src/whisk/common/ConsulServiceCheck.scala
common/scala/src/whisk/common/ConsulServiceHealth.scala
common/scala/src/whisk/common/HttpUtils.scala
core/dispatcher/src/whisk/core/container/WhiskContainer.scala
tests/src/actionContainers/ActionContainer.scala
tests/src/common/TestUtils.java

Pull HTTP client out of the utility class so that multiple requests can reuse the same connection rather than generating and tearing down the connection repeatedly.
This is a transition step to moving to use spray-client instead.

Factor out HTTP client

---

tests/src/whisk/consul/ConsulKVTests.scala
tests/src/whisk/core/controller/test/PackageActionsApiTests.scala
tests/src/whisk/core/controller/test/PackagesApiTests.scala

Fix retry on package test, so that retry is on the view, not on the delete which will succeed if the view is not up to date yet.
Remove generous retries added previously to consul tests which were not in fact needed.

Retry on package view in test

---

core/dispatcher/src/whisk/core/invoker/Invoker.scala
core/nodejsAction/src/service.js
tests/src/actionContainers/NodeJsActionContainerTests.scala

The marker is generated on both streams and logs are re-read until the marker shows up on both streams.
PPG 404 passed except for 2 stray failures.  
Re-running with PPG 406 just in case - 1 other stray.

Extend sentinel processing to stderr

---

tools/cli/wsk

this should apply the correct logic. you can run into this when no ~/.wskprops and no default.props exist.

issue #291 allow api host to be set if nothing else was set yet.

---

catalog/samples/wcbin.js
common/scala/src/whisk/core/database/CouchDbRestClient.scala
common/scala/src/whisk/http/BasicHttpService.scala
core/dispatcher/src/whisk/core/dispatcher/Dispatcher.scala
docs/catalog.md
tests/.pydevproject
tests/src/actionContainers/ActionContainer.scala
tests/src/common/TestUtils.java
tests/src/common/Wsk.scala
tests/src/common/WskCli.java
tests/src/whisk/core/controller/test/AuthorizeTests.scala
tests/src/whisk/core/controller/test/PackageActionsApiTests.scala
tools/cli/wskaction.py

Some error log messages printed the stack trace on separate lines - coalesced them into a single line so that they appear with their correlated transaction id.
Also in this commit, a small to show the activation record completely on a blocking invoke (was previously projecting just the `result`).

Show stack trace on one line

---

docker.gradle

This option is expected to be dropped by docker 1.12. Readding it in for the moment.

Adding -f option to docker tag again

---

build.xml
common/scala/src/whisk/core/entity/WhiskStore.scala
core/dispatcher/src/whisk/core/activator/Activator.scala

Enable new Spray-based Cloudant API.
Use custom thread pool in activator for db operations.
Fail deployment on error to deploy database.

Enable new Spray-based Cloudant API.

---

core/pythonAction/Dockerfile
core/swift3Action/Dockerfile
core/swiftAction/Dockerfile

`pip install gevent` compiles it locally, which takes forever

WIP: Get gevent from apt, not from pip

---

ansible/roles/nginx/tasks/deploy.yml

until now, the port 8443 is not yet exposed so that the port mapping (via ansible docker module) does not work yet. So we have to expose the port 8443 explicitly.

expose port 8443 in nginx

---

ansible/roles/consul/handlers/main.yml
ansible/roles/couchdb/tasks/initdb.yml

issue #208: couchdb should use cloudant initdb task only in openwhisk code structure

---

tests/src/common/TestUtils.java
tests/src/common/Wsk.scala
tests/src/common/WskTestHelpers.scala
tests/src/system/basic/CLIPythonTests.scala
tests/src/system/basic/CLISwiftTests.scala
tests/src/system/basic/PackageTests.scala
tests/src/system/basic/WskBasicTests.scala

This commit adds a test helper which captures a common pattern of extracting activation id, polling for activation to be completed, and then checking the result. This method will always the activation id, activation record, and any command failures should invariants fail. In doing this, turned some unnecessarily blocking activations to non-blocking ones. This makes the tests more focused and reduces likely hood of false failures.
@psuter should also review.
PPG 513.

helper for testing activations

---

ansible/roles/invoker/tasks/deploy.yml

invoker uses the consul server in core machines, not the consul agent yet

---

ansible/roles/invoker/tasks/deploy.yml

invokers use the local consul agent instead of using the first consul server in core machines

---

common/scala/src/whisk/core/entity/ActivationId.scala
tests/src/whisk/core/entity/test/SchemaTests.scala

Treats activation id as string to prevent parsing into an number which will cause the deserialization to fail.

Fixes issue 568

---

tools/ubuntu-setup/docker.sh

After "vagrant up" is done, all the docker commands will be able to
run in the terminal after "vagrant ssh", since DOCKER_HOST is set
as an environment variable.
Closes-Bug: #533

Add DOCKER_HOST into the environment variables

---

tests/src/common/TestUtils.java

`Collections.EMPTY_MAP` is not typesafe which the compiler complains about. Let's keep the repository warning-free.

Getting rid of warning in TestUtils

---

common/scala/src/main/scala/whisk/core/WhiskConfig.scala

This PR adds the address of the edge host to WhiskConfig.
Before this change, it was only possible to get the edge host including a port, but not the address itself.

Add address of edge host to WhiskConfig

---

.gitattributes
tools/go-cli/go-whisk-cli/commands/property.go

'wsk property get' now displays all properties and their values
Also updated .gitattributes for .py files and wsk bash/python files without .py/.sh extensions
- These must retain LF EOL because the python CLI is built on vagrant/linux on Windows

'wsk property get' now displays all properties and their values.  Also updated .gitattributes for .py files'

---

tools/go-cli/build.gradle

Use Groovy instead of ant to detect platform/arch
Fixes #761

Use Groovy instead of ant to detect platform/arch

---

tests/src/system/basic/CLIActionTests.java

These tests have proven non-stable for the moment. Temporarily reverting the switch to use python based CLI again.

Reverting the switch for CLIActionTests suite

---

tests/src/common/Wsk.scala
tests/src/system/basic/WskBasicTests.scala
tools/go-cli/go-whisk-cli/commands/property.go
tools/go-cli/go-whisk/whisk/client.go
tools/go-cli/go-whisk/whisk/namespace.go
tools/go-cli/go-whisk/whisk/sdk.go
tools/go-cli/go-whisk/whisk/trace.go

Check that the auth key is set prior to sending the HTTP request
Fail the CLI if the require auth key is not set
Remove auth key from `sdk install` as it is not needed
Refactor the namespace code to use the common HTTP client code
Fix incorrect argument help text
Fixes #778

CLI to failure when no authorization key configured/provided (prior to sending HTTP request)

---

tools/build/README.md
tools/build/citool

Example use to monitor a travis build, job number N:
> citool monitor N
To monitor same job until completion:
> citool monitor -p N
To save job output to a file:
> citool -o monitor N
Example use to monitor a jenkins build B with job number N:
> citool -u https://jenkins.host:port -b B monitor N
see readme in commit for more examples.

Jenkins/Travis tools script, for monitoring and analyzing jobs from CI.

---

catalog/github/webhook.js

Resolves #702 
Without this, creating a Github trigger with a name like "my trigger" will result in a bad webhook URL being sent to Github.

Make sure that the Github webhook URL is properly encoded before using

---

tools/go-cli/go-whisk-cli/commands/property.go
tools/go-cli/go-whisk-cli/main.go
tools/go-cli/go-whisk/whisk/action.go
tools/go-cli/go-whisk/whisk/activation.go
tools/go-cli/go-whisk/whisk/info.go
tools/go-cli/go-whisk/whisk/namespace.go
tools/go-cli/go-whisk/whisk/package.go
tools/go-cli/go-whisk/whisk/rule.go
tools/go-cli/go-whisk/whisk/sdk.go
tools/go-cli/go-whisk/whisk/trigger.go
tools/go-cli/go-whisk/whisk/wskerror.go

Refactor error messages so that a single "error:" appears at the start of the message
Fixes #806

Refactor Go CLI error messages so that a single "error:" appears at the start of the message

---

tests/src/system/basic/WskBasicTests.scala

Go CLI is no longer returning "error:" as prefix to the server error message

fix test case error message regex test

---

.gitattributes

Use .gitattributes to correct EOL chars for bash scripts not having .sh extension

Use .gitattributes to correct EOL chars for bash scripts not having .sh extension

---

tests/src/system/basic/WskBasicTests.scala
tools/go-cli/go-whisk-cli/commands/property.go

- Process all auth properties that are specified
- Include `ok` message for each property that is set
- Validate new namespace in context of current property values, including those set via same command
- Fixes #889

wsk property command supports setting and deleting multiple properties

---

tools/go-cli/go-whisk-cli/commands/package.go
tools/go-cli/go-whisk-cli/commands/util.go

- Update argument parsing for package refresh to handle no arguments
- Use the namespace from the property file, or _ if a namespace is not provided when parsing the qualified name

Arguments are not Parsed Properly for Package Refresh

---

ansible/roles/consul/tasks/deploy.yml

fixes some problems we have in non-default environment where /var/run/docker.sock is not present.

make /var/run/docker.sock configurable

---

tools/go-cli/go-whisk/whisk/client.go
tools/go-cli/go-whisk/whisk/wskerror.go

- Disable the default error prefix on error objects

Do Not Display Error Prefix by Default

---

tests/src/system/basic/WskBasicTests.scala
tools/go-cli/go-whisk-cli/commands/util.go

- Always add a space after an action, package, rule, or trigger name to separate it from its published type regardless if the name length

Always Separate a Listed Name from its Published Type

---

tools/go-cli/go-whisk-cli/commands/rule.go
tools/go-cli/go-whisk/whisk/action.go
tools/go-cli/go-whisk/whisk/activation.go
tools/go-cli/go-whisk/whisk/client.go
tools/go-cli/go-whisk/whisk/package.go
tools/go-cli/go-whisk/whisk/rule.go
tools/go-cli/go-whisk/whisk/trigger.go
tools/go-cli/go-whisk/whisk/util.go

When encoding URI path parameters, use path encoding via the url.URL class
When encoding query parameters, use QueryEscape()
Fixes #721

Replace QueryEscape() when encoding the URI path

---

tests/src/system/basic/WskBasicTests.scala
tools/go-cli/go-whisk-cli/commands/trigger.go

- If the auth key was not specified via the command line, it would not be sent when triggers were being created, or deleted

Include Auth Key from Properties when Creating and Deleting Triggers

---

catalog/installSystem.sh

Invalid syntax in annotation is causing wsk cli to create the input as a String instead of JSON.

Invalid syntax in annotation for split action

---

tests/src/actionContainers/Swift3ActionContainerTests.scala
tests/src/packages/UtilsTests.scala
tests/src/system/basic/CLISwiftTests.scala
tests/src/system/basic/Swift3WhiskObjectTests.scala

Some of these tests are failed sometimes and breaks the CI pipeline. Ignoring the tests was agreed.

Ignore experimental Swift3 tests

---

ansible/group_vars/all
ansible/postdeploy.yml
ansible/tasks/installOpenwhiskCatalog.yml

Currently, the catalog is installed by default together with
openwhisk. This patch adds a parameter named catalog_source to
determine whether to install the catalog from openwhisk-catalog.
If it is "catalog-repos", install the catalog from all the available
catalog repos. If it is set to any value except "catalog-repos",
openwhisk will not install catalog from the openwhisk-catalog.
The command to install the catalog from openwhisk-catalog is:
"ansible-playbook -i environments/local postdeploy.yml -e catalog_source=catalog-repos".
The script installCatalog.sh in the catalog needs to be able to
parse catalog_auth_key, api_host and catalog_namespace as the arguments.
Closes-Bug: #719

Make the catalog able to install from openwhisk-catalog repos

---

tests/src/common/WskActorSystem.scala
tests/src/services/HeadersTests.scala
tests/src/whisk/common/SchedulerTests.scala
tests/src/whisk/consul/ConsulClientTests.scala
tests/src/whisk/core/container/test/ContainerPoolTests.scala
tests/src/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/whisk/core/database/test/CouchDbRestClientTests.scala
tests/src/whisk/core/entity/test/ConformanceTests.scala
tests/src/whisk/core/entity/test/DatastoreTests.scala
tests/src/whisk/core/entity/test/ViewTests.scala

Eliminates code duplication, and ensures all systems are properly shutdown.

Helper to construct/teardown `ActorSystem`s in tests

---

.gitignore
common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
core/dispatcher/src/main/scala/whisk/core/dispatcher/ActivationFeed.scala
tests/src/services/KafkaConnectorTests.scala
tests/src/whisk/core/dispatcher/test/DispatcherTests.scala
tests/src/whisk/core/dispatcher/test/TestConnector.scala

Modify activation feed so that we grab next batch of messages and commit offsets immediately, essentially marking the activation has having satisfied "at most once" semantics (this is the point at which the activation is considered started); if the commit fails, then messages peeked are peeked again on the next poll.
While the commit is synchronous and will block until it completes, at steady state with enough buffering (i.e., maxPipelineDepth > maxPeek), the latency of the commit should be masked.
Add kafka test where we intentionally fail the commit and then confirm recovery.
Supersedes #990.
PPG 960 approved.

Catch expections in ActivationFeed due to Kafka poll/commit failure and retry (Supersedes #990)

---

tests/src/common/Wsk.scala
tests/src/system/basic/WskBasicTests.scala
tests/src/whisk/core/cli/test/WskBasicUsageTests.scala
tools/go-cli/go-whisk-cli/commands/action.go
tools/go-cli/go-whisk-cli/commands/commands.go
tools/go-cli/go-whisk-cli/commands/package.go
tools/go-cli/go-whisk-cli/commands/trigger.go
tools/go-cli/go-whisk-cli/commands/util.go
tools/go-cli/go-whisk/whisk/action.go
tools/go-cli/go-whisk/whisk/client.go
tools/go-cli/go-whisk/whisk/package.go
tools/go-cli/go-whisk/whisk/trigger.go

Annotations Must be Parsed as Raw JSON
parameter/annotation `key` input value is a string.  It will be converted into a JSON string doing
`\` and `"` escaping.  If it's not a valid JSON string after that, an error is returned.
parameter/annotation `value` input value is expected to be valid JSON.  If it is not valid JSON,
and it is NOT surrounded by either {} or [], it will be surrounded with double quotes making it a JSON
string.  In all cases, if the final value is still not valid JSON, an error is returned.
Replaces PR #953 
Fixes #952 
Fixes #717 
Fixes #718

Annotations Must be Parsed as Raw JSON

---

common/scala/build.gradle
common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/core/database/ArtifactStoreExceptions.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala
core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala
core/controller/src/main/scala/whisk/core/controller/Entities.scala
core/controller/src/main/scala/whisk/core/controller/Namespaces.scala
core/controller/src/main/scala/whisk/core/controller/Rules.scala
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/PackageCollection.scala
core/controller/src/main/scala/whisk/core/entitlement/RemoteEntitlement.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerHealth.scala
tests/src/whisk/core/controller/test/ActionsApiTests.scala
tests/src/whisk/core/controller/test/RulesApiTests.scala
tests/src/whisk/core/controller/test/TriggersApiTests.scala

- Adding documentation for Logging trait
- Removing unnecessary part of the log
- Getting rid of newlines in log messages
- Updating akka to get rid of an unnecessary log message on stdout
- Fix Package error message
- Surface proper message when rule update failed due to trigger absence
- Adding new exception type, fixing entity conformance logs
- Report invoke being too big properly, needs to be short-circuited
- Refactoring remote entitlement service
- more dense code
- adjust log levels related to entitlement
- surface errors reported by the remote entitlement service
- Fix loglevel of conflicts on delete
- Fix loglevel for trigger fire iff action was deleted
Fixes #1045 
Fixes #1044
Every commit fixes exactly one thing for easier reviewability.

Fix logging bits

---

common/scala/src/main/scala/whisk/common/NewHttpUtils.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
core/dispatcher/src/main/scala/whisk/core/container/Container.scala
core/dispatcher/src/main/scala/whisk/core/container/ContainerUtils.scala
core/dispatcher/src/main/scala/whisk/core/container/WhiskContainer.scala
core/dispatcher/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/actionContainers/ActionContainer.scala
tests/src/actionContainers/ActionProxyContainerTests.scala
tests/src/actionContainers/DockerExampleContainerTests.scala
tests/src/actionContainers/JavaActionContainerTests.scala
tests/src/actionContainers/NodeJsActionContainerTests.scala
tests/src/actionContainers/PythonActionContainerTests.scala
tests/src/actionContainers/SwiftActionContainerTests.scala

Stepping stone towards streaming `exec` data from the database to the containers. This commit replicates existing behavior but replaces the blocking Apache HTTP client by akka-http.
This commit also introduces a new helper object, `NewHttpUtils` to make non-pooled, possibly retrying, HTTP requests using the `akka-http` data model. (Candidates for a better object name are welcome.)
FYI @rabbah @markusthoemmes

Use akka-http for requests from the invoker to the containers

---

.gitignore
.project
core/actionProxy/Dockerfile
core/pythonAction/Dockerfile
core/swift3Action/Dockerfile
core/swift3Action/build.gradle
core/swiftAction/Dockerfile
core/swiftAction/build.gradle
sdk/docker/Dockerfile
sdk/docker/README.md
tests/src/actionContainers/ActionProxyContainerTests.scala

Reduce image size for docker actions skeleton from 619.8MB to 86.78MB.
This makes the example docker image size equally smaller.
Use the base image for python actions but not Swift since the latter not yet ready for a diet.
PG1-321 approved (node failing test is due to #1142 and not this pr).

Rebase action proxy (dockerskeleton) on alpine image

---

tests/src/whisk/core/cli/test/WskBasicUsageTests.scala
tools/go-cli/go-whisk-cli/commands/commands.go
tools/go-cli/go-whisk-cli/wski18n/resources/en_US.all.json

- Update argument parsing so that an error occurs if a key/value pair is not passed to -p or -a

Only Accept Key/Value Pairs for Parameters and Annotations

---

common/scala/src/main/scala/whisk/core/entity/ActivationResult.scala
core/dispatcher/src/main/scala/whisk/core/container/ContainerPool.scala
core/dispatcher/src/main/scala/whisk/core/dispatcher/ActivationFeed.scala
core/dispatcher/src/main/scala/whisk/core/invoker/Invoker.scala

Fixes two problems:
1. starting container counter incorrectly incremented when action gets a stem cell container; this should not be the case and over accounts for active containers. Moved the counter into the docker serializer where it will correctly account for the new container. The counter is inside the synchronized region rather than outside may allow more actions to try and make progress but will these will serialize on the docker lock anyway.
2. the activation counting had a race and was off by ~1 (approximately because the initialization was wrong and how many counters are created depends on the number of concurrent activations for a specific user).

Move starting counter to where it should be.

---

core/dispatcher/src/main/scala/whisk/core/container/Container.scala
core/dispatcher/src/main/scala/whisk/core/container/ContainerPool.scala
core/dispatcher/src/main/scala/whisk/core/container/WhiskContainer.scala
core/dispatcher/src/main/scala/whisk/core/invoker/Invoker.scala

The main reason for keeping a reference to the pool from within the container was access to logs, which require pool-specific knowledge.  However every client accessing logs has a reference to the pool anyway and can use it.

Removed pool reference from [Whisk]Containers

---

tests/src/system/basic/WskRuleTests.scala

this should fix confusion / racing between two tests using the same action names `a1to2a` and `a1to2b`

make action names unique in WskRuleTests

---

ansible/group_vars/all
ansible/tasks/installOpenwhiskCatalog.yml

CLI location is changing and this will affect the catalog repository.  Updating the catalog script to allow the CLI path to be passed in as a variable.

Use variable to represent CLI executable path

---

ansible/roles/go-cli/tasks/deploy.yml

old ansible docker module makes problems since docker upgrade. this should work until we use a newer docker ansible module (docker_container module)

docker rm instead of outdated ansible for now.

---

tests/src/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/commands.go
tools/cli/go-whisk-cli/commands/property.go
tools/cli/go-whisk-cli/commands/util.go

- Fix bug that prevents a namespace from being set at the same time the API is set
- Add test to ensure namespace can be set with API host and auth

Allow Namespace to be Set When Setting an API Host

---

core/invoker/src/main/scala/whisk/core/container/Container.scala
core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/container/WhiskContainer.scala

Unit tests still use Akka HTTP.

Revert to Apache HTTP client for invoker->containers communication

---

core/invoker/src/main/scala/whisk/core/container/Container.scala
core/invoker/src/main/scala/whisk/core/container/ContainerUtils.scala

I'd like to request a PG exemption.

Avoid printing object hashes in log messages related to containers

---

common/scala/src/main/scala/whisk/common/TransactionId.scala
core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala
tests/src/whisk/core/container/test/ContainerPoolTests.scala

Do not save container log by default.
Run stem cell container on a scheduled Future (but after killStragglers has finished).
Include toBeRemoved in slack calculation.

3 improvements to invoker

---

tests/dat/actions/invalidInput1.json
tests/dat/actions/invalidInput2.json
tests/dat/actions/invalidInput3.json
tests/dat/actions/invalidInput4.json
tests/dat/actions/validInput1.json
tests/dat/actions/validInput2.json
tests/src/common/Wsk.scala
tests/src/system/basic/WskBasicTests.scala
tests/src/whisk/core/cli/test/JsonArgsForTests.scala
tests/src/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/commands.go
tools/cli/go-whisk-cli/commands/flags.go
tools/cli/go-whisk-cli/commands/package.go
tools/cli/go-whisk-cli/commands/rule.go
tools/cli/go-whisk-cli/commands/trigger.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
tools/cli/go-whisk/whisk/action.go
tools/cli/go-whisk/whisk/activation.go
tools/cli/go-whisk/whisk/client.go
tools/cli/go-whisk/whisk/package.go
tools/cli/go-whisk/whisk/rule.go
tools/cli/go-whisk/whisk/shared.go
tools/cli/go-whisk/whisk/trigger.go

- Pass JSON files to parameters and annotations
- Add tests to ensure file input works as desired
- Refactor parameter and annotation handling
- Use KeyValueArr data type to store annotations and parameters
- Refactor summaries for get commands
- Use KeyValueArr data type to get annotations and parameters
- Refactor parameter and annotation tests
- Order of params and annots are not guaranteed in Go map data structures
- Fixes: #426

Allow JSON to be Input from a File

---

core/swift3Action/Dockerfile
core/swift3Action/buildandrecord.py
core/swift3Action/epilogue.swift
core/swift3Action/spm-build/Whisk.swift
core/swift3Action/spm-build/WhiskJsonUtils.swift
core/swift3Action/swift3runner.py
tests/src/actionContainers/Swift3ActionContainerTests.scala
tests/src/actionContainers/SwiftActionContainerTests.scala

#This PR fixes issues #1377 and #1371 
- dynamically generate build and link script used to create Swift 3 Actions.  This script records the output of the Swift Package Manager when the container is created, and bypasses unneeded build steps during action initialization
- Provide workaround from bug caused by Foundation JSONSerialization bug that causes seg faults in Linux when dictionary contains booleans
- Fix bug in Whisk Object due to unneeded casting and update to use the above workaround
- Update Swift 3 container tests
- remove test that checks to see if JSON object is returned.  Swift 3 compiler appears to do type checks on call graphs and won't compile if an object is not the expected type. Test assumes action will compile but not return a JSON object when it is run.  As of now, …

Dynamically generate swift compile and link script, fix Whisk Object

---

tests/src/actionContainers/PythonActionContainerTests.scala
tests/src/actionContainers/Swift3ActionContainerTests.scala

python test url is now openwhisk.ng.bluemix.net/api/v1
swift test url is now openwhisk.ng.bluemix.net/api/v1

up socket timeout of python action to 120 seconds

---

common/scala/src/main/scala/whisk/core/entity/DefaultRuntimeVersions.scala
core/controller/src/main/resources/whiskswagger.json
core/swift3Action/spm-build/WhiskJsonUtils.swift
tests/dat/actions/invoke.swift
tests/src/system/basic/Swift3WhiskObjectTests.scala
tests/src/system/basic/WskBasicSwiftTests.scala
tools/cli/go-whisk-cli/commands/action.go

This PR fixes #1350 and #1400 
- adds "swift:default" as a kind and sets the default to "swift:3", update CLI to default to swift:3
- adds test for above
- restores Swift3 Whisk Object Tests
PG #412 is blue.  PG #433 which includes #1400 fix is blue.

Issue #1350 Make Swift 3 default

---

core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerHealth.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
tests/src/whisk/core/controller/test/ControllerTestCommon.scala

The first commit extends data structures in the load balancer to track activations in different ways.  We may twiddle these data structures in the future as we enhance load balancing strategy.  The important thing is that we consistently add/remove ActivationEntry into/out of these data structures.  Note that though there are multiple maps, they share the same underlying ActivationEntry.  Because we limit the global number of activations accepted by the controller, these structures are limited.
The second commit exposes an endpoint from the load balancer for Activation Throttle to use so that it no longer has to consult consul for per-invoker and per-subject activation counts which is a big dictionary that is hurting our performance since we must collect it even for inactive subjects. …

Extend load balancer to track activations.  Switch activation throttler from consul to this.

---

tests/src/system/basic/WskActionTests.scala
tests/src/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/commands.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

- Display an error message informing the user to set the API host if it is not set
- Add test to ensure error message is displayed
- Fixes https://github.com/openwhisk/openwhisk/issues/979

Display Better Error When API Host is not Set

---

common/scala/src/main/scala/whisk/common/ConsulClient.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerHealth.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/whisk/core/controller/test/ControllerTestCommon.scala

Switch to information already available in load balancer's new activation maps.  This is a followup to the activation maps we recently begin maintaining.

Remove invoker tracking/publishing per-subject activation counts.

---

tests/src/whisk/consul/ConsulClientTests.scala

- The tests didn't clean up properly, leading to false traces in test debugging.
- Waiting for the correct status should be longer than the status check takes itself. Probably a race condition.

Reorder testexecution to properly clean up, wait longer than check time in consul check

---

core/swift3Action/swift3runner.py

This PR fixes #1434 - add flush statements to the swift 3 runner to force output to stdout and stderr. PG2 476

Add flush statements to Swift 3 runner

---

common/scala/src/main/scala/whisk/core/entity/WhiskTrigger.scala
tests/src/whisk/core/controller/test/RulesApiTests.scala
tests/src/whisk/core/database/test/CacheConcurrencyTests.scala

now that cache properly transacts reads and writes, enable trigger caching again.
pg2/507 and pg1/773 approved.

Enable trigger caching

---

ansible/files/auth_index.json
common/scala/src/main/scala/whisk/core/entity/Identity.scala
common/scala/src/main/scala/whisk/core/entity/Subject.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAuth.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAuthV2.scala
core/controller/src/main/scala/whisk/core/controller/Authenticate.scala
core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala
core/controller/src/main/scala/whisk/core/controller/Backend.scala
core/controller/src/main/scala/whisk/core/controller/Namespaces.scala
core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/RemoteEntitlement.scala
core/controller/src/main/scala/whisk/core/iam/NamespaceProvider.scala
tests/src/whisk/core/controller/test/AuthenticateTests.scala
tests/src/whisk/core/controller/test/AuthenticateV2Tests.scala
tests/src/whisk/core/controller/test/ControllerTestCommon.scala

1. Add the new view
2. Make the Controller read from the view
3. Thread the namespace extracted from the view through the API
The general "_" case now resolves to the namespace infered from the key vs. defaulting to the subject's name. For migration of the API, the "old" keys' namespace default to the subject name which preserves previous behaviour.

Migrate Controller's authentication to the new schema

---

ansible/apigateway.yml
ansible/environments/local/hosts
ansible/environments/mac/hosts.j2.ini
ansible/group_vars/all
ansible/roles/apigateway/tasks/clean.yml
ansible/roles/apigateway/tasks/deploy.yml
ansible/roles/apigateway/tasks/main.yml
tools/travis/build.sh
tools/vagrant/Vagrantfile

This PR adds the ability to deploy the apigateway container from ansible.
This will allow us to test the different environments (travis, mac, vagrant)  to see apigateway comes up OK
Not documented in ansible README or other READMEs on purpose for now, until the other pieces (cli, controller, routemgmtactions) come into play
PG1 881 (result=blue)

apigateway ansible integration

---

ansible/roles/kafka/tasks/deploy.yml

we noticed on some systems nc returns immediately and does not wait for the "iamok" response before closing the connection. the `-q` param forces nc to wait for n seconds until it gets something on stdin.

make netcat wait for response from zookeeper before closing connection

---

core/nodejs6Action/Dockerfile

In order to use the new translator service in watson cloud, we need to
change the version of the npm package in the dockerfile.

Upgrade the npm package of watson-developer-cloud into 2.9.0

---

core/nodejs6Action/Dockerfile
core/nodejsAction/Dockerfile
core/nodejsActionBase/package.json

- Updates NodeJS6 to LTS for 6.x (today [6.9.1](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-10-19-version-691-boron-lts-thealphanerd))
- Updates NodeJS0.12 to 0.1.2.17 to pick up a [security fix](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V012.md#2016-10-18-version-01217-maintenance-rvagg)  
- Updates NPM Packages to latest versions (for nodejs6)
- Add some popular NPM packages (for nodejs6)
- winston (MIT)
- underscore (MIT)
- uuid (MIT)
- validator (MIT)
- redis (MIT)
- marked (MIT)
- glob (ISC)
- Pinned the versions of npm packages for that the proxy server since it was using "^x.x.x"
- log4js needs to remain 0.x since 1.x doesn't support nodejs 0.12 and our proxy is share for now

Update NodeJS runtimes and packages to latest

---

core/invoker/src/main/scala/whisk/core/container/ContainerUtils.scala

nproc ulimit does not work with docker containers. with docker 1.12 we can leverage the pid limit on cgroups using the --pids-limit flag.

replace nproc limit with pids-limit to limit number of forks

---

ansible/README_DISTRIBUTED.md

Adding additional prerequisites for the nova python client, and adding a call to the setup.yml playbook to generate the edge ssl certs.

updating docs with additional prereqs and setup playbook

---

tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/activation.go
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/commands/commands.go
tools/cli/go-whisk-cli/commands/namespace.go
tools/cli/go-whisk-cli/commands/package.go
tools/cli/go-whisk-cli/commands/property.go
tools/cli/go-whisk-cli/commands/rule.go
tools/cli/go-whisk-cli/commands/sdk.go
tools/cli/go-whisk-cli/commands/trigger.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk/whisk/wskerror.go

- Remove unnecessary sprintf() calls that cause strings containing '%' characters to be malformed
Closes: https://github.com/openwhisk/openwhisk/issues/1396

Properly Format Strings Containing Precent Characters

---

core/swift3Action/spm-build/Whisk.swift
tests/src/system/basic/Swift3WhiskObjectTests.scala

Fixes Issue #1705 where Whisk object was failing to invoke actions and triggers in the Swift 3 container. Blue PG 871.  This fix:
- now parses for the protocol prefix in the __OW_API_HOST environment variable
- refactors how we wait for the async call to return.  We leave the dispatch group at the end of the post function call instead of in the callback passed to the post function call.  
I also added a URLSession based function that can replace the KituraNet implementation.  Its more limited right now (can't handle self-signed certificates because URLCredential is not completely implemented in the Linux-based Foundation) so this function is unused right now.

Whisk object in Swift 3 container

---

ansible/files/auth_index.json
ansible/logs.yml
ansible/tasks/initdb.yml
common/scala/src/main/scala/whisk/core/entity/EntityPath.scala
common/scala/src/main/scala/whisk/core/entity/Identity.scala
common/scala/src/main/scala/whisk/core/entity/Parameter.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/Meta.scala
core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
core/controller/src/main/scala/whisk/core/controller/actions/PostActionActivation.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
tests/src/common/Wsk.scala
tests/src/system/rest/RestUtil.scala
tests/src/whisk/core/admin/WskAdminTests.scala
tests/src/whisk/core/cli/test/WskWebActionsTests.scala
tests/src/whisk/core/controller/test/MetaApiTests.scala
tests/src/whisk/core/database/test/DbUtils.scala
tests/src/whisk/core/entity/test/SchemaTests.scala
tools/admin/wskadmin
tools/vagrant/README.md

Adds route to allow web based activations. Actions invoked this way are anonymous in that the
caller is not authenticated. The intended action must be named in the path as a fully qualified
name as in `/experimental/web/some-namespace/some-package/some-action`. The package is optional in that the action may be in the default package. In which case, the string "default" must be used.
If the action doesn't exist (or the namespace is not valid) a `BadRequest` is generated.
Optionally, the result form the action may be projected based on a named property. As in
`/experimental/web/some-namespace/some-package/some-action/some-property`. If the property
does not exist in the result then a `BadRequest` is generated. By convention, the "html" property will attempt to respond with media type …

Allow actions to be accessible from a web browser

---

common/scala/src/main/scala/whisk/core/entity/ActivationEntityLimit.scala
common/scala/src/main/scala/whisk/core/entity/LogLimit.scala
common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Entities.scala
tests/src/whisk/core/controller/test/ActionsApiTests.scala
tests/src/whisk/core/controller/test/PackagesApiTests.scala
tests/src/whisk/core/controller/test/RulesApiTests.scala
tests/src/whisk/core/controller/test/TriggersApiTests.scala

Action and trigger activations are subject to limits on the content payload. This pull request enforces the limit earlier in the pipeline.
PG2//971 approved.
Fixes #1059.

Reject activation if entity size exceeds limit

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Meta.scala
tests/src/whisk/core/controller/test/MetaApiTests.scala

The http web action must respond with either a plain text body or a base64 encoded body.
The header content-type must be set to interpret the reponse if base64 encoded body is given. (This applies to a JSON response as well.) Content-type must be one of known Spray types - no custom headers permitted.
This PR can subsume #1771 - the last commit adds binary support. PG1/1113.
Fixes #567.

Allow for binary data response for http actions.

---

tools/cli/go-whisk-cli/commands/trigger.go

- Just inform the user that a trigger has been updated instead of displaying the trigger in JSON format
Closes https://github.com/openwhisk/openwhisk/issues/1750

Do not Print Trigger After Update

---

common/scala/src/main/scala/whisk/core/entity/ActivationId.scala
common/scala/src/main/scala/whisk/core/entity/EntityPath.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Activations.scala
core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala
core/controller/src/main/scala/whisk/core/controller/Entities.scala
tests/src/whisk/core/controller/test/ActionsApiTests.scala
tests/src/whisk/core/controller/test/ActivationsApiTests.scala
tests/src/whisk/core/entity/test/SchemaTests.scala

Limit namespace, package, and entity names to 256 characters per segment.
Separating this from #1780.
PG2/1005.

Limit entity names.

---

common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
common/scala/src/main/scala/whisk/core/entity/WhiskPackage.scala
common/scala/src/main/scala/whisk/core/entity/WhiskTrigger.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/whisk/core/entity/test/WhiskEntityTests.scala

Constructing new objects results in a loss of the DocumentRevision and thus breaks caching in the invoker.

Fix revision preserving behaviour of WhiskAction

---

tests/src/system/basic/WskBasicTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk/whisk/action.go

- Instead of programmatically obtaining the result field from an activation record for action invocations, get the result from the backend by using the result=true URL parameter
Closes https://github.com/openwhisk/openwhisk/issues/1743

Use Result URL Parameter when Invoking Actions

---

tests/src/whisk/core/controller/test/EntitlementProviderTests.scala

Various entitlement tests often throw java.util.concurrent.TimeoutException: Futures timed out after [1 second].  Increasing the timeout value.

Increase timeout value for entitlement tests

---

ansible/ansible.cfg

This will allow us to provide only partial hashes if we want to test certain settings for individual deployments.
e.g. if we wanted to tweak the coreshare variable:
```
ansible-playbook (...) -e '{ "invoker": {"coreshare": "4"}}'
```
instead of having to replace the entire object as it is without this PR:
```
ansible-playbook (...) -e '{ "invoker": {"port": "12001", "numcore": "2", "coreshare: "4", "serializeDockerOp": "true", "serializeDockerPull": "true}}'
```

merge variable stack instead of replace

---

ansible/roles/apigateway/tasks/deploy.yml

New location of docker image is here now: https://hub.docker.com/r/openwhisk/openwhisk-apigateway/
docker hub doesn't offer a way to rename the github url, and for some reason it doesn't handle the github 301 redirection.

Update new location for apigateway location on docker hub

---

tests/dat/actions/applicationError3.js
tests/src/system/basic/WskBasicTests.scala
tools/cli/go-whisk/whisk/client.go

- Display proper error message during a blocking invocation when result flag is being used
Closes https://github.com/openwhisk/openwhisk/issues/1813

Properly Handle Errors Received from Blocking Invocations

---

ansible/roles/cli/tasks/download_cli.yml

apihost is usually the router which is not deployed at that point in time, therefore using edge only.

fix download. can't use apihost because not deployed yet.

---

common/scala/src/main/scala/whisk/core/entity/ActivationResult.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Meta.scala
tests/src/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/whisk/core/controller/test/MetaApiTests.scala

If the activaiton result is an activation error, treat it like a successful
activation with one distinction: rather than projecting the result per the
path specified in the URL, project only the error field. The resulting JSON
value must be of the expected type otherwise an appropriate error is reported.
This change will allow an http response to set it own status code on error
for example, but also means that the action producing the error response must
be aware of the extension type.
The extension type is not passed to the action - perhaps it should be. Even so,
in the case of a sequence, one would need to forward this type to individual
components to handle the error case (or result) correctly.
@starpit FYI. This adopt's @markusthoemmes' suggestion but does not solve the bigger issue …

Handle application errors in web actions.

---

core/pythonAction/Dockerfile
docs/reference.md
tests/src/actionContainers/PythonActionContainerTests.scala

This is to enable new "produce" actions in the kafka package: https://github.com/openwhisk/openwhisk-package-kafka/pull/131
This change adds approximately 1.7MB to the pythonaction Docker image.

Add kafka_python library to the Python action runtime

---

core/invoker/src/main/scala/whisk/core/container/Container.scala

Part of the runc pieces were prematurely committed.  This restores the intended commit pattern.

Revert code that was not supposed to be part of last commit

---

tests/src/whisk/core/limits/ActionLimitsTests.scala

testcase sometimes failes parsing the log string( because of the spaces after timestamp):
"2017-02-15T10:13:58.82285493Z  stdout: ERROR: opened files =  1011"

fix check in actionLimitTest

---

tests/src/whisk/core/database/test/ReplicatorTests.scala
tools/db/replicateDbs.py

Use the dbPrefix of the environment, where the test runs as part of the dbPrefix for all replicator tests.
Also delete databases in replicator only, if the database is a backup of a db with the current prefix.
PG2#1075 started.

Rework replicator tests to use environment-specific prefix

---

ansible/roles/invoker/tasks/clean.yml

1. give the invoker more time to clean action containers on SIGTERM
2. try to bring runc status in sync with docker status (pause / resume accordingly)
3. print out how many remaining actions there were after invoker clean-up. if the clean up works fine, there should be zero or very few to clean via script.

fix invoker runc cleanup.

---

common/scala/src/main/scala/whisk/core/entity/Exec.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala
core/nodejsActionBase/runner.js
core/nodejsActionBase/src/service.js
tests/src/actionContainers/ActionContainer.scala
tests/src/actionContainers/NodeJs6ActionContainerTests.scala
tests/src/actionContainers/NodeJsActionContainerTests.scala
tests/src/whisk/core/entity/test/SchemaTests.scala
tools/cli/go-whisk-cli/commands/action.go

This PR removes some unnecessary distinctions in the `exec` hierarchy - making the treatments of node, python, and swift actions the same.
PG3/303.

Flatten Exec hiearchy

---

ansible/roles/apigateway/tasks/deploy.yml

Figure out how to re-configure docker hub image `openwhisk/apigateway` to point to new named git location `openwhisk/openwhisk-apigateway`
This is enable and building automatically.
https://hub.docker.com/r/openwhisk/apigateway/
I will delete bad location a week from now 
https://hub.docker.com/r/openwhisk/openwhisk-apigateway/

restoring original location for apigateway container image

---

tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/flags.go

- timeout of 60000, memory of 256, and log of 10 can now be used
Closes: https://github.com/openwhisk/openwhisk/issues/1918

Allow Limits to be Set with Default Values

---

tests/build.gradle

Several repositories need to do this to support more sophisticated testing capabilities (mocking etc.)
This is taken out of a larger PR to resolve a deadlock in our integration.

Bump scalatest version

---

core/nodejsActionBase/runner.js
tests/src/actionContainers/NodeJsActionContainerTests.scala

The change in #1946 introduced a regression such that it did not allow for Node.js zipped actions which contain an `index.js` but not a `package.json`. This is a valid configuration and should be supported.

Fix regression introduced in #1946

---

ansible/roles/invoker/tasks/deploy.yml

@perryibm the shutdown hook did not work because SIGTERM got sent to the shell that runs the invoker JVM instead of the JVM directly. @sven-lange-last and I replaced it with exec to make the JVM the top level process in the invoker container.
In case we need similar behavior in the controller, it can also be applied to the CMD stanza of a Dockerfile.

remove intermediate shell to make shutdown hook great again.

---

core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala

Invoker wasn't able to spawn new pre-warm containers due to a naming issue.

Fix imagename for pre-warm container creation

---

ansible/roles/apigateway/tasks/deploy.yml

the env var apigateway_local_build it's used to skip the pull
This is required when building the image from outside ansible
like the Travis integration in the openwhisk-apigateway repository

only docker pull apigateway from dockerhub in normal mode deploy

---

core/swift3Action/Dockerfile

This makes it easier to compile Swift actions locally for upload to OpenWhisk as zip files containing the Action binary. 
In terms of space, this makes very little difference as the image is based on Ubuntu 14.04. Looking at `docker images` locally, the current image is 1.45GB and one with zip included is 1.46GB.
Closes #1991

Include zip in swift3Action

---

common/scala/src/main/scala/whisk/core/entity/LogLimit.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/invoker/src/main/scala/whisk/core/invoker/ActionLogDriver.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/javaAction/proxy/src/main/java/openwhisk/java/action/Proxy.java
tests/dat/actions/dosLogs.js
tests/src/test/scala/whisk/core/invoker/ActionLogDriverTests.scala
tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

When truncating, read all bytes up to the limit.
Separate log processors into its own trait - add unit tests.
Fix/tighten pre-existing test.

Improve action log driver to truncate more tightly.

---

common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala
tests/src/test/scala/whisk/core/database/test/CacheConcurrencyTests.scala

Fixed bug with @starpit where read listener, under certain conditions: 
1. did not complete the promise at all (if readDone failed to transition cache state)
2. completes promise with a failure when it shouldn't (write finished before read)

Fix bug in cache.

---

docs/webactions.md

I got caught out trying to work out what the package identifier should be for actions without an explicit package. 
This will be a common usecase for people trying out this feature. 
There's a note about using `default` much later in this file that people might not read at first. I've copied this reference and added it to the initial example to highlight this with users.

Doc Fix: Highlight use of default package identifier

---

tools/macos/tweak-dockermachine.sh

docker-machine needs to enable user namespaces to get on-par with other envs.
docker-machine allows to pass additional arguments to dockerd via the EXTRA_ARGS variable.

enable user namespaces on docker-machine

---

core/actionProxy/actionproxy.py
core/swift3Action/swift3runner.py

[actionproxy.py](https://github.com/openwhisk/openwhisk/blob/master/core/actionProxy/actionproxy.py#L130) assumes that subprocess output is a string, which is true in Python 2.  However,
Python 3 default behavior switched to returning bytes instead of strings.  (This [SO answer](http://stackoverflow.com/questions/21689365/python-3-typeerror-must-be-str-not-bytes-with-sys-stdout-write) provides a good explanation).  
If a user creates a Docker action that uses python 3 in their container, for example, invoking the action will fail with an internal error:
```
{
"error": "Internal error."
}
```
After some local debugging in my own Docker container (using python 3), the issue is:
```
Traceback (most recent call last):
File "actionproxy.py", line 207, in run
(code, result) = runner.run(args, …
```

Handle bytes to string conversion in actionproxy.

---

ansible/group_vars/all
common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala

This allows the `:default` designation to work for all kinds, as well as reinforces the idea that all kinds should explicitly state which is the default.

Add explicit defaults for all exec kinds

---

ansible/roles/kafka/tasks/deploy.yml

I've been playing around with Ansible playbooks (awesome way to get started quickly !), and found myself replaying the top-level openwhisk.yml playbook many times to set up my environment properly.
This PR prevents the entire playbook from failing if the Kafka topics already exist. It considers topic creation task as successful if the topic is indeed created, or if it already exists.
It also marks the task as changed only if the topic has been created (that's just nice to have).

Don't fail the entire playbook if topic already exists

---

docs/actions.md

The `--rm` switch will automatically delete the container once it exits, which is tidier.
(I had over 100 items in `docker ps -a` before I found this flag…)

Tweak instructions for Swift executable

---

tools/admin/wskadmin
tools/admin/wskutil.py
tools/build/checkLogs.py
tools/build/citool
tools/build/redo
tools/health/isAlive
tools/health/killComponent
tools/health/kvstore
tools/travis/flake8.sh

Issue #1963 says that flake8 is too chatty so we use flake8's `--ignore=E` option to suppress its most nitpicky formatting complaints.  This lets us focus on more serious issues like the issues that it found in the five other commits of this PR.

Suppress flake8's nitpicky formatting issues

---

tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

This PR is to permit progress on adding python:3 support.
Further CLI enhancements related to kind-awareness planned for/after #1980; in particular `wsk property get` to list supported kinds for deployment.
FYI @cclauss.

Remove 'kinds' from CLI; defer to backend.

---

tests/src/test/scala/system/basic/WskActionTests.scala
tools/cli/go-whisk-cli/commands/action.go

- Parameters and annotations can now be added through the create/update commands when copying an action
Closes https://github.com/openwhisk/openwhisk/issues/2061

Allow Adding Annotations and Parameters During Action Copy

---

.travis.yml

If the tests fail, we don't get logs.

Fix log collection after unsuccessful test

---

tools/build/ASFLicenseHeader.txt
tools/build/ApacheIBMLicenseHeader.txt
tools/build/scanCode.cfg
tools/build/scanCode.py

This version of scancode is fully configurable (using an external .cfg file).  A default scanCode.cfg is provided with all the defaults that reflect all the settings openwhisk uses today.  In addition, the text for the 2 supported licenses are separated out (and loaded by scanCode) after being listed in the .cfg file.  The config file supports the following sections/configurations:
[Licenses] = list of license files to load/scan for
[Inclusions] = filters (wildcard supported) e.g., *.scal, *.py, etc.) with lists of scans to run for those file filters.
[Exclusions] = list of "paths" (dirs) to exclude from tests.  These are now defaulted to all paths 
[Options] = ony 1 option for now...
> LICENSE_SLACK_LENGTH=500
Used when code files (e.g., Python) need to have licenses to appear beyond the …

Update scanCode.py so that it is configuration file driven.

---

tests/dat/actions/hello.js
tests/src/test/scala/system/basic/WskActionTests.scala
tests/src/test/scala/system/basic/WskBasicTests.scala
tests/src/test/scala/system/basic/WskRuleTests.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk/whisk/client.go

- Do not encode &, <, and > to \u0026, \u003c, and \u003e
- Prevents mentioned characters in raw HTTP web action query parameters from being encoded in activation logs

Disable HTML Encoding of JSON Content in CLI

---

common/scala/src/main/scala/whisk/common/Logging.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/ProcessRunner.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/RuncClient.scala
tests/src/test/scala/common/StreamLogging.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/ProcessRunnerTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/RuncClientTests.scala

Provide reactive Docker and Runc client in preparation for reactive container pool implementation.
Closes #2087 
Closes #2088

Provide reactive Docker and Runc client

---

tools/cli/Dockerfile

- Increase build speed by as much as 15%
- More info on Go 1.8: https://blog.golang.org/go1.8

Update from Go 1.7 to 1.8

---

common/scala/Dockerfile
core/controller/build.gradle
core/invoker/build.gradle

Scala's idiomatic error handling makes it "hardish" to exit the JVM on fatal errors (for example if a Future fails with a fatal exception). The added flags just ignore error handling and exit the JVM, which we can recover by a docker auto-restart for example.
I bumped the Java versions because the flag was added in 8u92. Figured we might as well go to latest. It got released in January, so it should be stable.

Exit components on OutOfMemory exceptions

---

tools/cli/go-whisk/whisk/action.go
tools/cli/go-whisk/whisk/activation.go
tools/cli/go-whisk/whisk/api.go
tools/cli/go-whisk/whisk/client.go
tools/cli/go-whisk/whisk/package.go
tools/cli/go-whisk/whisk/rule.go
tools/cli/go-whisk/whisk/trigger.go

Update common HTTP request API to support REST interfaces that do not require an auth header

CLI to support OW REST interfaces that do not require an auth header

---

ansible/environments/distributed/group_vars/all
ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all

All actions, rules, triggers, packages and activations are stored in this database. Because of all the activations, this database becomes really huge over time.
To keep the database with the artifacts, created by the users (actions, ...), small we had the idea to put all activations into another database. The activations-db.
To solve the problem of the migration of existing OpenWhisk deployments, my proposal is to make the split configurable with ansible.
This PR creates this flag. By default, the whisks database will be used to store activations.
After some time, I'll open another PR, that changes the default to use the activations-db.
Again, after some time, I'll open a third PR to remove this flag again. By default, all activations will go into the activations-db.
The reason for …

Add flag to configure split of whisks and activations db.

---

common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
core/invoker/src/main/scala/whisk/core/invoker/ActionLogDriver.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/whisk/core/invoker/ActionLogDriverTests.scala

These bits are rather sensitive and can have quite high volumes of data passing through. Therefore, casting through different collections is to be avoided.

Reduce unnecessary typecasts in log reading + turn off activation caching

---

tests/src/test/scala/common/Wsk.scala

Remove `sealed` qualifier from RunWskCmd trait
- to allow class extension outside of Wsk.scala file

Remove `sealed` qualifier from RunWskCmd trait

---

core/routemgmt/createApi/createApi.js
tests/build.gradle
tests/dat/actions/echo-web-http.js
tests/dat/apigw/testswaggerdoc1V2
tests/dat/apigw/testswaggerdoc2V2
tests/src/test/scala/apigw/healthtests/ApiGwEndToEndTests.scala
tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/commands/wsk.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
tools/cli/go-whisk/whisk/api.go

- Support both 'wsk api-experimental' and 'wsk api' commands (separate PR wil deprecate `api-experimental`)
- 'wsk api' command requires that the target action exist and that it's a web action
- Separate V1 and V2 tests for easy deprecation/removal
Together with PR #2067, replaces PR #2031 
Depends on PR #2067 (don't merge this PR until after #2067 is merged)

API GW V2 - Add 'wsk api` command

---

core/routemgmt/common/apigw-utils.js

API GW swagger specification/implementation change for V2
- No longer use the `set-variable` object with the V2 API GW

API GW V2 swagger generation change (remove auth, content headers)

---

core/nodejs6Action/Dockerfile

This is necessary to pick up recent changes to watson services.
:large_blue_circle:  PG2 1480

update watson-developer-cloud npm to 2.29.0

---

docs/reference.md

Previously, the documentation stated that a docker action must take
input from `stdin`. After reviewing the code in actionproxy.py (see
lines 128-132), it's clear that this statement is incorrect. Instead,
the executable must take it's argument as a single quoted command-line
argument that can be deserialized as a JSON object.
This issue arose in attempting to implement a docker action using python
and several custom packages (not trivially implemented as a native
python action). If the executable truly read from `stdin`, the following
code would be the correct approach:
```python
import sys
import json
in_raw = sys.stdin.read()
try:
js = json.loads(in_raw)
print >> sys.stderr, "successfully interpreted json"
print json.dumps(js, indent=2)
except ValueError:
print >> sys.stderr, "failed …
```

Update doc to more accurately reflect input mechanism for Docker actions

---

core/routemgmt/common/apigw-utils.js
tools/cli/go-whisk-cli/commands/api.go

Fix is to delete all artifacts in the swagger for the specified endpoint

`wsk api delete` command may not completely delete endpoint

---

core/routemgmt/common/apigw-utils.js
tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk/whisk/api.go

- `wsk api create` will now enable basic CORS by default.
- `wsk api get` will now display additional support fields, including the CORS setting
Fixes #2169 
Fixes #2182

wsk api create to enable CORS by default

---

core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala

This should get rid of marker confusion when running sequences. @RSulzmann please confirm.

Move markers to more appropriate places

---

tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/property.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

Fixes https://github.com/openwhisk/openwhisk/issues/2028
wsk property set --auth <xxxxxxx>    should not echo the auth key to the console
changed output string, NLS translation id and text, and the related unit test case

issue 2028 do not print auth key on console

---

ansible/environments/distributed/group_vars/all
ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all
ansible/group_vars/all
ansible/tasks/db/recreateDb.yml

This PR changes the default setting of all environments to use the activations-db for activations, instead of the whisks-db.
It also requires the flag `db_split_actions_and_activations` to be set. It still can be false, but if it is false, you should care about the migration of your activations to the activations-db.
If you don't matter throwing away all your data, just execute the ansible playbook `wipe.yml`, after `db_split_actions_and_activations` is set to true.
If you want to keep all your data, follow the instructions on the following page:
https://gist.github.com/cbickel/37e651965781b27de245eac0ce831a53
PG1#1437

Set default db for activations to activations-db

---

ansible/group_vars/all
ansible/roles/nginx/tasks/deploy.yml
ansible/roles/nginx/templates/nginx.conf.j2
ansible/setup.yml
ansible/templates/whisk.properties.j2

This pr is to make trusted ssl cert configurable.
With this, user can configure ssl certificate, private key and pass phrase for key in `ansible/group_vars/all`
If user configured its own certificate, untrusted certificate generation step is skipped.
This closes #2106

Make nginx ssl configurable

---

ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
core/controller/build.gradle
core/invoker/build.gradle

Currently, JVM settings are hardcoded into our images. The only value we really want to have on those applications is the restart on OOM behavior though. The other settings are highly dependent on the deployment infrastructure.
- `controller|invoker_heap` are used to control the heap of both components.
- `controller|invoker_arguments` are used for free-form JVM arguments.

Make JVM options available at deployment time

---

common/scala/build.gradle
common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala

Caffeine is the successor of ConcurrentLinkedHashMap, which is no longer under active development. spray.caching hasn't upgraded yet, so this is our own implementation of spray.caching using Caffeine.
Benefits are:
- Better performance.
- Usage of SoftReferences to correspond to memory pressure.
For more details, see: https://github.com/ben-manes/caffeine/

Implement a cache backed by Caffeine

---

common/scala/src/main/scala/whisk/core/entity/Exec.scala
common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
core/invoker/src/main/scala/whisk/core/container/package.scala
core/invoker/src/main/scala/whisk/core/containerpool/Container.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
tests/build.gradle
tests/src/test/scala/common/LoggedFunction.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

A proxy that wraps a Container. It is used to keep track of the lifecycle
of a container and to guarantee a contract between the client of the container
and the container itself.
The contract is as follows:
1. Only one job is to be sent to the ContainerProxy at one time. ContainerProxy
will delay all further jobs until the first job is finished for defensiveness
reasons.
2. The next job can be sent to the ContainerProxy after it indicated capacity by
sending NeedWork to its parent.
3. A Remove message can be sent at any point in time. Like multiple jobs though,
it will be delayed until the currently running job has finished.
Closes #2091

Implement a proxy for a container to implement concurrent behavior.

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/dispatcher/ActivationFeed.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
tests/src/test/scala/whisk/core/dispatcher/test/DispatcherTests.scala

This pool fulfills the other half of the ContainerProxy contract. Only
one job (either Start or Run) is sent to a child-actor at any given
time. The pool then waits for a response of that container, indicating
the container is done with the job. Only then will the pool send another
request to that container.
Upon actor creation, the pool will start to prewarm containers according
to the provided prewarmConfig, iff set. Those containers will **not** be
part of the poolsize calculation, which is capped by the poolSize parameter.
Prewarm containers are only used, if they have matching arguments
(kind, memory) and there is space in the pool.
Closes #2090

Implement a containerpool controlling container proxies

---

tests/src/test/scala/system/basic/WskRuleTests.scala

Due to clock skew among invokers, it is possible for an action invoked by a rule _appears_ to start before the trigger which activated the rule was even fired. As such, these tests tend to fail because it is looking for action activations that start strictly after the time the trigger activation started.
This change introduces a "fudge factor" to allow the test to find the expected action activations that appear to start at most 500ms before the trigger activation start time.
Resolves #2195

Add a fudge factor to handle clock skew in the invokers

---

ansible/environments/distributed/group_vars/all
ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all

Fixes https://github.com/openwhisk/openwhisk/issues/2216
"creating CouchDB database fails due to db_prefix grabbing uppercase account name"

Assure db_prefix begins and consists of lowercase chars for valid couchdb name

---

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClientWithFileAccess.scala
core/invoker/src/main/scala/whisk/core/invoker/ActionLogDriver.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala

Prepare new container-pool implementation - see #2086.
Factor out all file-based operations from DockerClient such that the DockerClient can also work with a remote docker host. Two operations are supported:
- Obtain a container's IP address: Read from container's config file in the first place and fall back to using `docker inspect` if file reading doesn't work. The file reading variant is preferable because it's faster than `docker inspect`.
- Obtain a container's stdout / stderr output: Read from container's log output written by the JSON log driver. At the moment, there is no falling back to `docker logs`.

Factor out Docker config and log file handling to DockerClientFileAccess

---

core/invoker/src/main/scala/whisk/core/container/HttpUtils.scala
core/invoker/src/main/scala/whisk/core/containerpool/Container.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
core/invoker/src/main/scala/whisk/core/invoker/ActionLogDriver.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
tests/src/test/scala/whisk/core/invoker/ActionLogDriverTests.scala

This implementation is an abstraction layer for using Docker containers as OpenWhisk action containers - in preparation of a new container pool implementation (#2086). The `DockerContainer` implementation provides a high-level abstraction for the operations required by OpenWhisk:
- Create, destroy, halt, resume a container
- Initialize and run an action inside a container
- Obtain container logs
Closes #2089

Provide DockerContainer implementation

---

tests/dat/apigw/local.api.bad.yaml
tests/dat/apigw/local.api.yaml
tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
tools/cli/go-whisk-cli/Godeps/Godeps.json
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/commands/flags.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

Update the following command:
- `wsk api get --format yaml`  Add a new option `--format` that takes either `json` or `yaml`
- `wsk api create --config-file api.yaml`  The import logic looks at the file extenstion, if .yaml or .yml, the file is treated as YAML; otherwise the file is treated as JSON
Fixes #2170

Add wsk cli support for importing/exporting API configuration in YAML format

---

ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all
ansible/group_vars/all
ansible/templates/whisk.properties.j2
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
common/scala/src/main/scala/whisk/core/entity/DocInfo.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
core/invoker/src/main/scala/whisk/core/container/WhiskContainer.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/dispatcher/test/DispatcherTests.scala
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala

**Note for reviewers:** We can (should?) take the flags out before merging this. It's merely there to test the new pool in Travis for now. Alternatively, we can state that nobody should use local/mac in production and thus it's safeish to let the flag in and immediately switch to the new pool. For production environments though, we need more experience with it.
Makes the new InvokerReactive accessible behind a feature flag `invoker_use_reactive_pool`.
This concludes the work on the new containerpool.

Hook up reactive pool into invoker startup

---

common/scala/src/main/resources/application.conf

This will allow 128 concurrent CouchDB requests in a single connection-pool.

Bump connection-pool limit to 128

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala

Resolves #2245
Only remove a running container to make room for activation in a max'ed out ContainerPool IFF a) the running container is in "Free" state and b) the running container is a DIFFERENT action than the incoming activation

To resolve #2245 - optimize container removal

---

ansible/roles/kafka/tasks/deploy.yml
ansible/roles/redis/tasks/deploy.yml
tools/health/isAlive
tools/health/monitorUtil.py

This is to make health check logic for zookeeper and redis work on Cent OS.
It has been tested on following OSs:
* CentOS 7.3
* OSX 10.11
* Ubuntu 16.04
Ansible deployment worked as expected.
Closes: #1997

Fix health check logic for zookeeper and redis to make it work on CentOS

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala

If the invoker fails to fetch an action from the database it needs to inform the ActivationFeed that it still has resources (it didn't consume a container after all).
Reporting of those errors needs some disambiguation, as an error on fetching the action could also be caused by the user (for example by concurrently deleting the action while invoking it). The InvokerHealth protocol would shutdown the invoker, iff the activation was reported as a WHISK_ERROR. All errors but DocumentNotFound are considered WHISK_ERRORs though.
Also in this commit:
- Loglevel change from error to warn for a missing revision. The InvokerHealth protocol produces ERROR otherwise.
- Some documentation and restructuring of the ContainerPool's setup.

Correctly recover from errors when fetching an action

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala

In particular, the old pool kept containers around for 10 minutes. As the removal strategy does concurrent remove/create anyway keeping containers around for longer shouldn't harm.
Also: Fix a leak with an uncaught message.

Align ContainerProxy with settings of the old container pool

---

common/scala/src/main/scala/whisk/core/entity/Exec.scala

use a Regex to determine isBinaryCode, rather than going through with a full base64 decoding in the controller. this reduces peak memory consumption, and also decreases the latency of zip-action update operations
Fixes #2295 
PG3 665 🔵

Controller memory tuning for zip actions: use Regex rather than Base64.decode

---

core/routemgmt/common/apigw-utils.js
core/routemgmt/common/utils.js
core/routemgmt/createApi/createApi.js
core/routemgmt/deleteApi/deleteApi.js
core/routemgmt/getApi/getApi.js
tests/src/test/scala/whisk/core/apigw/actions/test/ApiGwRoutemgmtActionTests.scala
tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk/whisk/api.go
tools/cli/go-whisk/whisk/client.go

Actions changes:
- Change parameters used (i.e. no longer use __ow_meta_*)
- Resolve()/Reject() responses now in .http format
CLI changes:
- Invoke api gw actions at .http for v1/experimental commands
- Better handling/messaging of error responses

Final conversion of api-experimental to web action (not experimental)

---

tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala

Use unique test API Names for unique basepaths

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/dispatcher/ActivationFeed.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

- The current implementation sends a `ContainerReleased` message to the `ActivationFeed` whenever the `ContainerPool` receives a `NeedWork` message from a warm `ContainerProxy`.
- The current implementation sends `NeedWork` after an activation was completed successfully (correct) but also after the pause grace timeout expired (incorrect). This double message breaks `ActivationFeed` book-keeping.
- The current implementation does not send any `ContainerReleased` or `FailedActivation` message to the `ActivationFeed` if an activation cannot be completed successfully. So even application errors break `ActivationFeed` book-keeping.
Changes:
- This PR decouples `ActivationFeed` notification from the `NeedWork` message sent by the `ContainerProxy` to `ContainerPool`.
- Whenever the …

Fix activation feed book-keeping in reactive pool (#2285)

---

ansible/roles/invoker/tasks/deploy.yml

This closes #2247
It makes possible to scale out of running invoker via ansible.
It assumes there will be only one invoker running on each hosts.
To scale out running invoker, user can just add new hosts in inventory file and re-run the ansible invoker deployment.
Procedures are as follow:
1. First, it checks if there are any running invokers.
2. If there are more than one running invokers, there are some problem. It stops the deployment.
3. If there is only one running invoker, it checks whether index of running invoker is same with the one of the given inventory host.
4. If index is different, there is problem in the order of hosts. It stops the deployment.
5. If index is same, it just skips to run invoker.
6. If there is no ruunning invoker, it starts a new invoker.
One good …

Make invoker be scaled-out via ansible. (#2247)

---

common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala

This PR ensures than when `runtimes.manifest` property is incorrectly configured that the controller prints what the error is in the logs. 
Without this PR we would only see in the logs:
```
[2017-05-17T21:21:53.457Z] [ERROR] [??] [Controller] Bad configuration, cannot start. 
```
With this PR we can see:
```
Exception in thread "main" java.lang.IllegalStateException: Runtimes manifest is set but it's invalid: spray.json.DeserializationException: Object is missing required member 'image'
at whisk.core.entity.ExecManifest$.initialize(ExecManifest.scala:55)
at whisk.core.controller.Controller$.main(Controller.scala:185)
at whisk.core.controller.Controller.main(Controller.scala)
```
This is very helpful when debugging issues with the configuration such as the one mentioned at …

surface errors in runtimes.manifest configuration in the controller logs

---

core/swift3Action/spm-build/Package.swift

Fixes issue #2394.  Pins CCurl version to 0.2.3 to fix potential self-signed certificates issue.

Pin CCurl version in Package.swift

---

tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/activation.go
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/commands/namespace.go
tools/cli/go-whisk-cli/commands/package.go
tools/cli/go-whisk-cli/commands/rule.go
tools/cli/go-whisk-cli/commands/shared.go
tools/cli/go-whisk-cli/commands/trigger.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/commands/wsk.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

- When entity names are passed to list commands display an appropriate error
- Share qualified name parsing error messages between commands
- Move `wsk list` command to `wsk.go`
Closes: https://github.com/openwhisk/openwhisk/issues/2073

Error when Entity Names are Provided to List Commands

---

common/scala/src/main/scala/whisk/core/entity/ActivationId.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
common/scala/src/main/scala/whisk/utils/ExecutionContextFactory.scala
core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
tests/src/test/scala/system/basic/WskSequenceTests.scala
tests/src/test/scala/whisk/core/controller/actions/test/SequenceAccountingTests.scala
tests/src/test/scala/whisk/utils/test/ExecutionContextFactoryTests.scala

Fixes #2386
This PR changes SequenceActions to use foldLeft rather than scanLeft. The change requires the introduction of a new accumulator data structure, to maintain the accumulated state for the reduction. The accumulated state includes an array of handles to logs (for the components), the cumulative duration, and a few other bits needed for creation of the final sequence activation record.
This fix also patches a closely related memory drag, caused by the way timeouts of sequence invocations are handled. See #2294 which patches other parts of the controller for the same kind of timeout drag. This patch needs to be a little different, due to the complex way the SequenceActions impl uses nested Promises.
PG3 625 🔵

Update sequence impl to tune controller memory consumption

---

ansible/group_vars/all
ansible/templates/whisk.properties.j2
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerServiceObjectTests.scala

Currently, the loadbalancer advances from one Invoker to another after a fixed amount of invocations, which isn't aware of any load in the system causing suboptimal behavior.
This only advances away from the home invoker of an action (determined by hash) if that home invoker is "heavily" loaded. We advance further if the next chosen invoker is busy and so forth. If we arrive at the home invoker again, the system is completely loaded and we force schedule to the home invoker. Step sizes are determined by prime numbers and also chosen by hashing to prevent chasing behavior.

Choose target invoker based on specific invoker load.

---

tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala

Using the --web flag during an action update call does not preserve the action annotations.

Add Test to Ensure Preservation of Annotations for Action Web Flag

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

A couple of helpful refactorings for the new ContainerPool:
1. Differentiate between maximum active containers and maximum containers in pool. This can come in handy if you want to increase the poolsize to cache more containers than you run. Currently disabled but contains helpful refactorings so I kept it.
2. Retype scheduling logic: Removes a dead-code situation.
3. Adjust pause grace: Adjusts the pause grace to a more aggressive value, which will still catch bursts bu doesn't gift so much time to a potentially malicious user.

General ContainerPool refactorings.

---

ansible/roles/invoker/tasks/clean.yml
ansible/roles/invoker/tasks/deploy.yml

Using play_hosts seems, like the order is not always the same like in the hosts file.
This PR fixes this issue, by using the hosts file to generate the index for the invokers.

Use hosts to define order of invokers instead of play_hosts

---

tests/src/test/scala/common/TestUtils.java
tests/src/test/scala/common/Wsk.scala

Failing to drain streams properly will deadlock the process launcher.

Drain stdout/stderr in futures to prevent deadlock.

---

tools/cli/go-whisk-cli/commands/activation.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

Make Activation Poll usage inform users that an entity name (action, trigger, or rule) can be provided as an optional argument.
Closes: https://github.com/apache/incubator-openwhisk/issues/2273

Update Usage for Activation Poll

---

common/scala/src/main/scala/whisk/common/Scheduler.scala
common/scala/src/main/scala/whisk/core/connector/Message.scala
common/scala/src/main/scala/whisk/core/entity/InstanceId.scala
common/scala/src/main/scala/whisk/utils/ExecutionContextFactory.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/PostActionActivation.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/common/SchedulerTests.scala
tests/src/test/scala/whisk/core/connector/tests/CompletionMessageTests.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

Fixes an active ack accounting bug in the load balancer for certain failed activations (where the invoker previously did not send an ack for the completed (but failed) activation. 
Fixes #2118.
Fixes #2324.
Fixes #1906.

Send active ack on failed activations

---

docs/webactions.md

- State that .http extensions do not support projections

Update Web Action Doc

---

tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

The test now uses the minimum supported log limit (1M) and creates 10% more log output as the limit. In the past, the test had a limit of 2M and produced 3M logs.
We frequently saw this test failing in mainOpenwhisk in the past few days because it took too
long to PUT the activation record to Cloudant, i.e. more than 60 sec. We suspect that
concurrent load tests in YS0 may have caused the long Cloudant response times because the
Cloudant DB cluster is shared. But we don`t have enough diagnostic data to prove this assumption.
At the same time, making the log portion in the activation record smaller with this change
should also make the Cloudant request faster. This change does only affect limits and sizes but
does not change the test's design.

Action limit test for log truncation produces less log entries

---

core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerServiceObjectTests.scala

The loadbalancer falls back to picking the home invoker for the action iff all invokers are loaded above a defined threshold. That threshold is backed off 3 times to prevent a "all hell breaks loose" scenario in a sustained high load.

Back-off threshold and choose home invoker as default.

---

common/scala/src/main/scala/whisk/common/Scheduler.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
tests/src/test/scala/whisk/core/controller/actions/test/ActivationFinisherTests.scala

Also restore previous behavior of scheduler which explicitly sent initial work message.

Refactor finisher and add unit tests

---

ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all
ansible/roles/invoker/tasks/deploy.yml

Enables easier profiling of local components via JVM standard tooling.
**Note:** Those parameters are only enabled in local envs. for a reason. They don't cope with securing the JMX port.

Start Scala components with JMX enabled locally

---

core/routemgmt/common/apigw-utils.js
tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala

Currently, the CLI generates operationId swagger field values that are usable by coding tools.  The PR alters the operationId algorithm to generate strings that more closely match allowable programmatic variable/method names.
Field description from the Open API 2.0 specification
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject 
>Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

Create swagger operationId values for code tooling consumption

---

ansible/group_vars/all
ansible/roles/kafka/tasks/deploy.yml

make kafka retention attributes configurable.
For each topic the following of the above attributes can be set/changed :
**retention.bytes**	( controls the maximum size a log can grow to before we will discard old log segments to free up space )
**retention.ms**	( controls the maximum time we will retain a log before we will discard old log segments to free up space )
**segment.bytes**	( controls the segment file size for the log. Retention and cleaning is always done a file at a time )
@jeremiaswerner
For our topics (completed, health, invoker) the values (defined for each environment) are:
kafka_topic_completed_logRetentionBytes: 1073741824
kafka_topic_completed_logRetentionMS: 3600000
kafka_topic_completed_logSegmentBytes: 536870912
kafka_topic_health_logRetentionBytes: 1073741824 …

set kafka retention

---

tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala

Apparently, having `Instant.now` both times resulted in undeterministic behavior of the test.

Deterministic container removal for test.

---

docs/use_cases.md

Fix a missing 's' in `docs/use_cases.md`

Fix typo in use_cases.md

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Activations.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
tools/cli/go-whisk-cli/commands/activation.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

- Inform users that 200 activations is the maximum limit for the list CLI command
- Make controller return an error if activation limit is greater than 200
- Closes https://github.com/openwhisk/openwhisk/issues/2097

Updates for Max Activation List Limit

---

common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
core/controller/src/main/scala/whisk/core/controller/actions/PostActionActivation.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/whisk/core/container/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala

- Improves the implementation of ExecutableWhiskAction to conform closer to existing implementations.
- Use ExecutableWhiskAction as early as possible to statically check only the right types reach the Invoker.

Improve ExecutableWhiskAction coverage and general typesafety

---

tools/macos/README.md

There is a missing `=` which causes an error when trying to install Docker 2.2.1

Fix install command in Docker for Mac bash script

---

ansible/group_vars/all
ansible/roles/kafka/tasks/deploy.yml

Kafka is set to 1 gigabyte by default which might not be suitable for all deployments.

Make kafka heap size configurable.

---

tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/activation.go
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/commands/commands.go
tools/cli/go-whisk-cli/commands/flags.go
tools/cli/go-whisk-cli/commands/namespace.go
tools/cli/go-whisk-cli/commands/package.go
tools/cli/go-whisk-cli/commands/property.go
tools/cli/go-whisk-cli/commands/rule.go
tools/cli/go-whisk-cli/commands/sdk.go
tools/cli/go-whisk-cli/commands/shared.go
tools/cli/go-whisk-cli/commands/trigger.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/commands/wsk.go
tools/cli/go-whisk-cli/main.go
tools/cli/go-whisk/whisk/action.go
tools/cli/go-whisk/whisk/activation.go
tools/cli/go-whisk/whisk/api.go
tools/cli/go-whisk/whisk/client.go
tools/cli/go-whisk/whisk/info.go
tools/cli/go-whisk/whisk/namespace.go
tools/cli/go-whisk/whisk/package.go
tools/cli/go-whisk/whisk/rule.go
tools/cli/go-whisk/whisk/sdk.go
tools/cli/go-whisk/whisk/shared.go
tools/cli/go-whisk/whisk/trace.go
tools/cli/go-whisk/whisk/trigger.go
tools/cli/go-whisk/whisk/util.go
tools/cli/go-whisk/whisk/wskerror.go

This is a continuation of updating all source code files to use the ASF License header. 
All scala files were updated as part of this PR:
https://github.com/apache/incubator-openwhisk/pull/2367
This PR performs a similar update for all ".go" (GoLang) source files.
Note: These updates are mainly in the CLI.  We had hoped that the CLI separation would be completed thus negating the need for these updates, but as separation is taking longer there is no need to delay such a simple change.

Phase 1: Update all Go files with ASF License header.

---

ansible/group_vars/all
common/scala/build.gradle
common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/services/KafkaConnectorTests.scala

Kafka allows setting the maximum period between two polls. As we allow for 5 minutes of action execution, in a fully loaded invoker it might take 5 minutes for the consumer to poll again. To prevent rebalances this value is adjusted accordingly.
Bumping Kafka's version is needed because that value is exposed only in 0.10.1+.
ConsumerGroups are removed (or rather: each Invoker/Controller is in it's own ConsumerGroup) to prevent rebalances to impact other consumers. OpenWhisk does not use ConsumerGroup mechanics anyway.

Adjust kafka's maximum poll period.

---

ansible/group_vars/all
ansible/roles/apigateway/tasks/deploy.yml
tests/dat/apigw/endpoints.without.action.swagger.json
tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
tools/cli/go-whisk/whisk/api.go

- `wsk api list` displays action-less APIs without an action names.
- bump API GW version so that action-less APIs can be created via cli/swagger

wsk CLI should tolerate APIs that do not yet have a mapped action

---

tests/src/test/scala/services/KafkaConnectorTests.scala

- current limit of 10 seconds is too small on PG3 - causing build failures
- other PG3 connector test times have recently been observed at 8/9+ seconds

Bump Kafka Connector Test timeout to avoid build breaks

---

ansible/tasks/installOpenwhiskCatalog.yml

* Removes unused parameter
There is a PR for the OpenWhiskCatalog repo to remove an unused parameter from the `installCatalog.sh` script. Once this [#pr](https://github.com/apache/incubator-openwhisk-catalog/pull/231) has been merged, this PR can be merged.

Update install Catalog script.

---

tests/src/test/scala/common/TestUtils.java

This pr adds line to shutdown executor in tests code to prevent jvm process leak.
Reference: https://blog.tier1app.com/2014/09/30/memory-leak-in-java-executor/

Deal with jvm process leak in TestUtils

---

tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/flags.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
tools/cli/go-whisk/whisk/action.go
tools/cli/go-whisk/whisk/shared.go

Adds a `--url` flag to the `action get` command that retrieves non-web action, and web action URLs.

Get Action URL from CLI (Review)

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

The ContainerPool indicates to the ActivationFeed that it can perform more work and as a result gets more messages from the ActivationFeed. In order to properly back-pressure and protect the ContainerPool, it only ever sends such a message iff it changed its internal state to an extent that it is guaranteed to be able to handle more work.
The idea is to send a message to the feed once we remove a container from the busy pool, thus freeing up space to take more load.

Fix order of messages being sent by the ContainerPool.

---

tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/commands/commands.go
tools/cli/go-whisk-cli/commands/property.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
tools/cli/go-whisk/whisk/client.go
tools/cli/go-whisk/whisk/sdk.go
tools/cli/go-whisk/whisk/util.go

- Also move properties file reading/loading to when the command is executed, not at binary load time

Externalize access to some CLI methods to facilitate access across packages

---

tests/src/test/scala/system/basic/WskBasicTests.scala

Using a hardcoded Thread.sleep timeout will inevitably fail in different test environments. Using the test helpers that retry under the hood will make those tests less intermittent failure prone.
The rejection test doesn't actually need to invoke an action.

Harden system tests for --last flag.

---

core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala

Let each controller create its own health action to avoid race condition parallel startup of several controllers.
PG2#1774 is green.

Let each controller create its own health action

---

tools/cli/go-whisk-cli/commands/package.go

The `--shared` flag does not work with `package list`, so remove the option from the CLI.
Closes https://github.com/apache/incubator-openwhisk/issues/2485

Remove Unsupported Shared Flag from Package List (Review)

---

tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

Increase the default test timeout for a single test from 30 to 70 seconds.

Increase the timeout for the actions with big log

---

tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala

This test used to test a situation of self-recovery in case the ActivationFeed sends more messages than the ContainerPool can consume. This has been deemed an error situation and would be a bug in the ActivationFeed, hence the log is flooded with error messages.

Remove ContainerPool test which is no longer applicable.

---

tests/src/test/scala/system/basic/WskBasicTests.scala

View based queries are subject to eventual consistency. In case the test is running against an environment with a clustered database it is subject to random failures.

Adding retries to '--last' test to account for eventual consistency.

---

ansible/roles/cli/tasks/download_cli.yml

This pr makes Ansible consider `mac` environment also while downloading cli binaries.

Consider mac environment along with docker-machine enviornment

---

CONTRIBUTING.md

Hello, 
this PR add minor updates of the documentation:
- adds a note about the formatting standards (fyi @markusthoemmes) 
- fixes broken/wrong links to cli docs. 
regards, Vadim.

Update documentation: a note about formatting, fix links

---

core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerData.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala

Hello, 
this PR contains a companion commit that separates the the load balancer data from its main logic. 
This change will simplify the introduction of the load balancer state that will be shared across several controllers. 
@markusthoemmes could you please have a look?
regards, 
Vadim

Move load balancer data into a separate class

---

common/scala/src/main/scala/whisk/core/connector/Message.scala
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerData.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/connector/tests/CompletionMessageTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerServiceObjectTests.scala

If invokers are coming online/offline frequently today, the list of available invokers changes frequently which causes the hash-based picking algorithm to constantly change home invokers of actions, thus destroying warm-ratios of that action.
This attacks this issue by accepting that invokers are in fact index based and thus they are now managed in an array which's length will not change if an invoker goes offline. For partitioning cases i.e. blackbox containers) the length of the underlying sequence is kept constant by padding them repsectively.

Stabilize loadbalancer under on/off conditions

---

tests/src/test/scala/system/basic/WskBasicTests.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala

Move the tests of the --last flag to BasicUsageTests and invoke the action again if the last activation is not the expected one.

Move tests of --last tag to basicUsageTests

---

core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala

I found a minor bug. 
actionContainerPrefix has been used to killStragglers but current static string value uses "wsk" only.
so current code can affect anything else on the kubernetes environment.
I didn't include additional code for this regarding invokerReactive, because invokerReative is not verified on K8s environment our side
Signed-off-by: keunseob.kim <keunseob.kim@samsung.com>

Fix actionContainerPrefix value

---

common/scala/src/main/scala/whisk/core/entity/Secret.scala

Add a check, that the key of a namespace has at most 64 characters.
PG1#1845 is running.

Add check that key is at most 64 characters

---

ansible/group_vars/all
core/php7.1Action/Dockerfile
core/php7.1Action/build.gradle
core/php7.1Action/composer.json
core/php7.1Action/router.php
core/php7.1Action/runner.php
docs/actions.md
docs/reference.md
settings.gradle
tests/src/test/scala/actionContainers/Php71ActionContainerTests.scala
tools/build/redo
tools/cli/go-whisk-cli/commands/action.go

This adds a new `php:7.1` kind to allow PHP actions like this:
```php
<?php
function main(array $args) : array
{
$name = $args["name"] ?? "stranger";
$greeting = "Hello $name!";
return ["greeting" => $greeting];
}
```
The PHP runtime is based on the official `php:7.1-alpine` one with the following extensions added:
- opcache
- mysqli
- pdo_mysql
- pdo_pgsql
- intl
- bcmath
- zip
- gd
- soap
Two Composer packages are also included:
- `guzzlehttp/guzzle` - A very popular HTTP client
- `ramsey/uuid` - The de facto UUID generator
Suggestions welcome on what should be included in these lists (and of course on the code itself!)
We need a working local installation. The easiest way to do this is with Vagrant, so that's what this set of steps uses.
1. Check out the source code 
$ git clone …

Add PHP 7.1 as a kind

---

.gitignore

After executing the script to create certificates, 3 files will be generated in the nginx-role folder that are currently not added to the gitignore file.

Adopt gitignore to ignore generated certs

---

tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala

The await could have timed out before docker init operation is finished. 
Align both timeouts.

Align await timeout for docker test 

---

common/scala/Dockerfile

Using JDK tools can be useful to debug JRE related problems. The image grows ~200MB.

Using JDK instead of JRE to provide tooling.

---

ansible/environments/docker-machine/group_vars/all
ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all

This is a stepping stone to make the new pool the default for everything.
Communication will be done via dev list.

Enable reactive containerpool for all open environments.

---

core/pythonAction/pythonrunner.py

This allows actions to set/retrieve global variables as an additional optimization during container reuse.

Reuse namespace in the Python 3 action runtime

---

ansible/files/auth_index.json
tests/src/test/scala/whisk/core/admin/WskAdminTests.scala
tools/admin/wskadmin

There was no preservative way of blocking a user from the system temporalily before. This adds the functionality to provide a flag in the user's subject entry to block its keys from further usage.

Add a database flag to completely block a given subject.

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

I made an additional PR due to @rabbah mentioned on #2505 
if the reactive pool is ready to go online, this code is also necessary.
this patch adds a few tiny code to use invoker instance id for creating/deleting container in case of reative poll is enabled.
Signed-off-by: keunseob.kim <keunseob.kim@samsung.com>

Add Invoker instnaceId in invokerReative

---

ansible/files/auth_index.json
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/entity/Identity.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/RateThrottler.scala
tests/src/test/scala/limits/ThrottleTests.scala
tests/src/test/scala/whisk/core/controller/test/RateThrottleTests.scala
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
tools/admin/wskadmin

This adds the ability to override the rate/concurrency related limits of the system on a per-namespace basis to be able to adapt to specific user needs.
Implementation:
User defined throttles are placed in an extra document in couchdb, $namespace/limits. That document is automatically processed by the existing view, thus no extra request is needed. If no such document exist, default limits will apply.
**Todo:**

Add the ability to define user-specific throttles.

---

ansible/roles/invoker/tasks/deploy.yml

As soon as one of the properties contains spaces, the command breaks.

Escape all values when deploying invoker.

---

ansible/README.md
tools/macos/README.md
tools/macos/docker-machine/README.md
tools/ubuntu-setup/ansible.sh

With an older version of `jinja2`, deployment with Ansible fails.

Jinja2 version 2.9.6 required for Ansible template processing

---

ansible/environments/docker-machine/group_vars/all
ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all
ansible/group_vars/all

Custom environments now need to opt-in to the old pool by using `invoker_use_reactive_pool: false` explicitly.

Make reactive containerpool default for all environments.

---

tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/system/basic/WskBasicTests.scala
tests/src/test/scala/system/basic/WskPackageTests.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala

Remove unnecessary baseCommand override in WskAction and always ensure that the CLI exists instead of just doing so in a few test suites.

Clean Up CLI Tests (Review)

---

tests/src/test/scala/limits/ThrottleTests.scala
tests/src/test/scala/whisk/core/admin/WskAdminTests.scala
tools/admin/wskadmin

I noticed that the new throttle tests don't clean up correctly - the limits docs are left in the database. This patch adds `wskadmin limits [get, delete]`, updates the tests to delete the limits after testing, and adds tests for the new admin functions.
PG2/1889 🔵 
Can verify cleanup https://app.box.com/v/openwhisk-travis-logs/file/205104572185.

Clean up limit records

---

ansible/roles/cli/tasks/download_openwhisk_cli.yml
ansible/roles/couchdb/tasks/deploy.yml

Fix bug that one variable can't use another variable which is defined
in same set_fact statement.
ansible version: 2.3.0.0
bug description:
fatal: [172.17.0.1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'instance' is undefined\n\nThe error appears to have been in '/home/irteam/jenkins/workspace/lambda/ansible/roles/couchdb/tasks/deploy.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
above error's codes as followings:
```
- set_fact:
instance: "{{instances | selectattr('name', 'equalto', 'db') | list | first}}"
volume_dir: "{{ instance.volume.fsmount | default( '/mnt/' + …
```

Fix bug on set_fact relative ansible task

---

docs/cli.md
tests/src/test/scala/system/basic/WskSdkTests.scala
tools/cli/go-whisk-cli/commands/flags.go
tools/cli/go-whisk-cli/commands/sdk.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
tools/ubuntu-setup/bashprofile.sh
tools/vagrant/Vagrantfile

This change simply changes the output of the Cobra auto-completion script from a file to STDOUT. Originally, `wsk sdk install autobash` would create the file `wsk_cli_bash_completion.sh`, but now it will print the contents of the Cobra auto-completion script to the terminal. You can now use the command ``eval "`wsk sdk install autobash`"`` to automatically install the script for that instance of the terminal. Adding the eval command to your `.bashrc` or `.profile` will keep you from rerunning this command. Closes #1221

Prints bashauto-completion install script to STDOUT

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala
docs/webactions.md
tests/dat/actions/multipleHeaders.js
tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

This change allows multiple response header values to be set in raw
web actions by using a JSON array as the header value. For example:
```
function main() {
return {
headers: {
"Set-Cookie": ["a=b", "c=d"]
},
code: 200
}
}
```
I have signed the Apache CLA as "Benjamin M. Browning".

Support multiple response header values in raw web actions

---

common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
common/scala/src/main/scala/whisk/core/connector/MessageConsumer.scala

Producing a message can be done with a callback upon receiving the message, effectively acting as a non-blocking API.
Consuming a message is a bit trickier. Adding `blocking` instructs the default dispatcher to create new threads if necessary.

Use non-blocking techniques when interfacing to Kafka.

---

ansible/roles/controller/tasks/deploy.yml
core/controller/src/main/scala/whisk/core/controller/Controller.scala

Readd the number of controllers to the controller.
This value is needed to genrate unique tids across all controllers.
PG4#652 is running.

Add number of controller instances again to the controller

---

ansible/environments/distributed/group_vars/all
ansible/environments/docker-machine/group_vars/all
ansible/environments/local/group_vars/all
ansible/environments/mac/group_vars/all

if `ansible node` and `target node` is not the same node, it will have problem.
```
- include: db/recreateDb.yml
vars:
dbName: "{{ db.whisk.auth }}"
forceRecreation: False
```
the `db.whisk.auth` references varaible : `db_prefix`, above ansible task's `db_prefix` value is `ansible node`'s  `{{ ansible_user_id|lower }}_{{ ansible_hostname|lower }}_`  (Note: it will get `ansible node`'s `user_id` and `hostname`)
```
- name: (re)start controller
docker_container:
name: controller{{ groups['controllers'].index(inventory_hostname) }}
env:
"DB_WHISK_AUTHS": "{{ db.whisk.auth }}"
...
...
```
But above ansible task's  `db.whisk.auth`'s `db_prefix` value is `controller node`'s  `{{ ansible_user_id|lower }}_{{ ansible_hostname|lower }}_`  (Note: it will get `controller node`'s `user_id` and …

Fix bug on ansible variable db_prefix

---

docs/actions.md
docs/packages.md
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/package.go
tools/cli/go-whisk-cli/commands/trigger.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json

This update is intended to clarify the printed summary when one uses `wsk [ENTITY] [ENTITY_NAME] get --summary`.
Here is an example of what the output of this update should look like:
For entities with multiple parameters and no description:
```
$ wsk action get hola -s
action /guest/hola: Returns a result based on parameters testA, testB and testC
(parameters: testA, testB, testC)
```
For entities with a single parameter and no description:
```
$ wsk action get hola -s
action /guest/hola: Returns a result based on parameter testA
(parameters: testA)
```
And entities with no parameters and no description:
```
$ wsk action get hello -s
action /guest/hello
(Warning: /guest/hello has no annotations)
```
Closes https://github.com/apache/incubator-openwhisk/issues/2270

CLI summaries for actions without annotations

---

docs/actions.md
docs/apigateway.md
tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/activation.go
tools/cli/go-whisk-cli/commands/api.go
tools/cli/go-whisk-cli/commands/flags.go
tools/cli/go-whisk-cli/commands/namespace.go
tools/cli/go-whisk-cli/commands/package.go
tools/cli/go-whisk-cli/commands/rule.go
tools/cli/go-whisk-cli/commands/trigger.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk-cli/commands/wsk.go
tools/cli/go-whisk-cli/wski18n/resources/en_US.all.json
tools/cli/go-whisk/whisk/action.go
tools/cli/go-whisk/whisk/activation.go
tools/cli/go-whisk/whisk/api.go
tools/cli/go-whisk/whisk/namespace.go
tools/cli/go-whisk/whisk/package.go
tools/cli/go-whisk/whisk/rule.go
tools/cli/go-whisk/whisk/trigger.go
tools/cli/go-whisk/whisk/util.go

Alphabetize, coauthored by myself and @bpoole16, is intended to allow the user to sort a given list of entities alphabetically. This applies to actions, triggers, rules, packages, and apis.
By default, entities are listed in order from most to least recently updated:
```
$ wsk action list
actions
/guest/packageB/A                  private nodejs:6
/guest/C                                  private nodejs:6
/guest/A                                  private nodejs:6
/guest/packageA/B                  private nodejs:6
/guest/packageA/A                  private nodejs:6
/guest/B                                  private nodejs:6
```
To see the list of entities sorted alphabetically, use the flag `--name-sort` or `-n`:
```
$ wsk action list --name-sort
actions
/guest/A …
```

Alphabetize listings in CLI

---

tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala
tools/db/replicateDbs.py

This PR does a cleanup before the ReplicatorTests starts.
In addition, it fixes the retry method in the replicator-script.
PG4#661 started.

Remove databases of old ReplicatorTests that failed

---

core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerData.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala

LoadbalancerData keeps a lot of data it doesn't need. Upon fetching a copy of this data, it creates copies which can be expensive, the more user are in the system.

Make LoadbalancerData leaner.

---

core/pythonAction/Dockerfile

This version contains important fixes to limit the number of connections made during bootstrapping

Update kafka_python to 1.3.4

---

ansible/roles/invoker/tasks/deploy.yml

The `nodejs6action` container is created by invoker which test the invoker whether worked well, sometimes, 
its name may has `invoker` substring, for example as below
```
37d73d962120        whisk/nodejs6action:latest   "/bin/sh -c 'node --e"   13 minutes ago      Up 13 minutes                                                                          wsk0_3_whisksystem_invokerHealthTestAction0
2581c86d6ada        whisk/invoker:latest         "/bin/sh -c 'exec /in"   13 minutes ago      Up 13 minutes       0.0.0.0:12001->8080/tcp                                            invoker0
```
If above situation happens, and execute `ansible-playbook -i environments/<env>  invoker.yml` again in this node, below ansible task's revokerInfo's length will be greater than 1
```
- name: get running …
```

Add the image filter when get invoker info

---

core/swift3Action/Dockerfile

Build is fine again and binaries are back online.
This reverts commit 49ac756064905da0bcba8ed9978a3e29dd8c04dc.

Revert "Temporalily use published swift3Action. (#2580)"

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala
docs/webactions.md
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

Closes #2606.
The current patches allows an HTTP web action to respond with a JSON value without having to base64 encode it. See issue for more details.
@dubeejw can you take a look.
PG1/1945 & 1946 🔵

Support json response in HTTP web actions without base64 encoding.

---

core/php7.1Action/Dockerfile

Composer installation seems to fail sometimes in the CI build
environment. Move the installation of composer to a separate layer and
separate the download of the file via curl from the installation
process. Finally, run `composer --version` to ensure that it has been
installed correctly.

Install composer in its own layer

---

common/scala/src/main/scala/whisk/http/BasicHttpService.scala

1 second is a rather small timeout for `toStrictEntity`. If a garbage collection hits around it, requests might randomly and unnecessary fail. Bumping that timeout to something quite high shouldn't impact general operations at all.

Bump toStrictEntity timeout to 30 seconds.

---

ansible/environments/distributed/hosts
ansible/environments/docker-machine/group_vars/all
ansible/environments/docker-machine/hosts.j2.ini
ansible/environments/local/group_vars/all
ansible/environments/local/hosts
ansible/environments/mac/group_vars/all
ansible/environments/mac/hosts
ansible/group_vars/all
ansible/logs.yml
ansible/provision_env_dist.yml
ansible/roles/apigateway/tasks/deploy.yml
ansible/roles/controller/tasks/deploy.yml
ansible/roles/couchdb/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
ansible/roles/kafka/tasks/deploy.yml
ansible/roles/nginx/templates/nginx.conf.j2
ansible/roles/redis/tasks/deploy.yml
ansible/roles/registry/tasks/deploy.yml
ansible/roles/whiskhost/tasks/patchKernel.yml
ansible/templates/whisk.properties.j2

This allows deploying multiple controllers and invokers locally to be able to test their scaleout ability.
This PR replaces #2527

Allow multiple controllers and invokers in local environments

---

tests/src/test/scala/common/WskTestHelpers.scala
tests/src/test/scala/system/basic/WskActionTests.scala
tests/src/test/scala/system/basic/WskBasicTests.scala
tests/src/test/scala/system/basic/WskSequenceTests.scala
tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

Rename CliActivationResponse & CliActivation, and change them from inner classes to classes
This PR renames the class CliActivation and CliActivationResponse
and makes them available to be accessed from another package, because
REST call can use both of the classes as well.
The PR also creates RestResult class to save the results of HTTP reopnses for REST.
Partially-closes-bug: #2430

Make the result of response consistent for both Wsk CLI and REST

---

ansible/prereq.yml

Using the same host for different "machines" seems to cause trouble when trying to concurrently install packages.

Apply prereqs serially to prevent installation conflicts.

---

ansible/environments/distributed/group_vars/all
ansible/environments/docker-machine/group_vars/all
ansible/environments/local/group_vars/all
ansible/roles/routemgmt/files/installRouteMgmt.sh
ansible/templates/whisk.properties.j2
docs/apigateway.md

Should I be updating all api_gw_v2 vars to exclude v2 now as well? aka api_gw

remove API GW V1 group vars

---

core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala
tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

I was planning on consolidating things like the following into a single var accross the entire project:
```
apigw_host: "http://{{ groups['apigateway']|first }}:{{apigateway.port.api}}/v1"
apigw_host_v2: "http://{{ groups['apigateway']|first }}:{{apigateway.port.api}}/v2"
```
However, the implications seems to be far reaching, and I am not sure the most efficient way to go about it.
Should I be retaining the v1 in all the routes? should it be all updated to v2? or the version removed entirely?
@csantanapr @mdeuser

experimental web apigw cleanup

---

common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
common/scala/src/main/scala/whisk/core/database/CouchDbStoreProvider.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
common/scala/src/main/scala/whisk/spi/SpiLoader.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
docs/spi.md
tests/src/test/resources/application.conf
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
tests/src/test/scala/whisk/spi/SpiTests.scala

Using `object`s instead of a hollow class as the "factory" for an Spi makes them being singleton by default, which reduces boilerplate to implement an Spi.
The `Dependencies` object is not used anywhere and there might be better alternatives which we can decide on once the need of them comes up. For now, the Spi's interfaces are relatively tightly coupled to their current default implementations anyway.

Simplify Spi implementations.

---

ansible/roles/controller/tasks/clean.yml

In June, we've added the ability to deploy hot-standby controllers (https://github.com/apache/incubator-openwhisk/commit/fdbf073a386c33aed1b06ed93eaea39ee4382c7b).
With this commit, the containername of the controllers has been changed from `controller` to `controller0`, `controller1`, ...
To not break the update of existing deployments we left the cleanup of containers called `controller` in the cleanup script of the controller.
Since the change of renaming the containers is long time ago, we can remove this old code now.

Remove deployment code to remove controllers without indexes

---

tests/src/test/scala/whisk/core/controller/test/AuthenticateTests.scala

This test can be subject to a race condition, where the checks are run before the database has updated its views.

Wait for view in AuthenticateTests.

---

tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala

Replication in CouchDb is hard to control, thus increasing the timeout should not be harmful. The additional assert will make it easier to grasp why a test failed in the future.

Bump replication timeout, abort test with correct message

---

tests/src/test/scala/whisk/core/cli/test/ApiGwTests.scala

This commit is also stashed in #2684 but opened separate PR for expedience.
I think these tests should use the reported error from 2684 to compute how much to settle the throttle. The tests otherwise dont have a correct accounting of tests that came before it.

Restore throttle check before each CLI call.

---

ansible/roles/cli/tasks/clean.yml
ansible/roles/cli/tasks/deploy.yml
ansible/roles/controller/tasks/clean.yml
ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/clean.yml
ansible/roles/invoker/tasks/deploy.yml
ansible/roles/nginx/tasks/clean.yml
ansible/roles/nginx/tasks/deploy.yml
ansible/roles/sdk/tasks/clean.yml
ansible/roles/sdk/tasks/deploy.yml

Surround variables introduced with PR #2669 with double curly braces to force interpolation.
We observed Ansible playbook runs where `become` was not active because variables
were not interpolated such that the value was `false`.

Fix Ansible playbook problems with missing variable interpolation

---

core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala
docs/webactions.md
tests/dat/actions/corsHeaderMod.js
tests/dat/actions/multipleHeaders.js
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

This allows empty json response with http actions.
Add tests for handling partial result for http actions.
Fixes #2674.
- The first commit fixes a bug in the test actions (unrelated to this change, but got exposed by this pr).
- The second commit adds tests coverage for the various corner cases and changes the status code for the empty body response.
- The third commit treats the empty string and a null JSON value for body as the empty content.
- The last commit suppresses the akka-http content negotiation when a code is specified and no body.
FYI @akrabat.

Change response when entity is empty from 200 to 204.

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/RateThrottler.scala
tests/src/test/scala/limits/ThrottleTests.scala
tests/src/test/scala/whisk/core/controller/test/RateThrottleTests.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

Fixes #1385.
Reports error messages as:
`Too many requests in the last minute (count: 120, allowed: 60). (code ...)`
`Too many concurrent requests in flight (count: 30, allowed: 30). (code ...)`
PG2/2032 🔵

Decorate throttled error response with count/limit.

---

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala

The pull-future needs to be removed from the caching Map once the underlying runCmd finishes, either successfully or failed.

Fix endless collapsing of failed pulls.

---

ansible/group_vars/all
ansible/roles/couchdb/tasks/clean.yml
ansible/roles/couchdb/tasks/deploy.yml
tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala

If the cache is disabled in the controller, the following tests are failing:
- Wsk actions should create, and get an action to verify parameter and annotation parsing
- Wsk packages should create, and get a package to verify parameter and annotation parsing
- Wsk triggers should create, and get a trigger to verify parameter and annotation parsing
The reason is, that the number `12345678912.123456789012` is rounded to `12345678912.123457` in the controller.
On writing `12345678912.123457` into CouchDB, the value `12345678912.123456955` is saved.
On getting the document again from CouchDB, the controller returns `12345678912.123456955`. That's why the test is failing.
The cache in the controller has hidden this issue until now.
Increasing to version 2.0 fixes this issue.

Increase CouchDB to version 2.0

---

common/scala/build.gradle
tests/build.gradle

A new version of akka-http was released August 31st. For more information regarding the new release see http://akka.io/blog/news/2017/08/31/akka-http-10.0.10-released.
PG4 785 🔵

Use latest version of Akka HTTP

---

ansible/roles/nginx/templates/nginx.conf.j2

This enables using HTTP keepalive towards the backend so the connections are reused more efficiently.

Make nginx more performant acting as a proxy.

---

tests/src/test/scala/whisk/core/connector/test/MessageFeedTests.scala
tests/src/test/scala/whisk/core/connector/test/TestConnector.scala

The test has intermittent failures because access to the underlying queue is unexpectedly non-threadsafe and non-atomic, meaning a `peek` could grab messages off the queue meanwhile `addAll` is still adding messages. This can (rarely) lead to inconsistent state and thus a failing test.
Fixes https://github.com/apache/incubator-openwhisk/issues/2685.

Synchronize access to MessageFeed testqueue.

---

common/scala/src/main/scala/whisk/common/TransactionId.scala
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerServer.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/database/test/DbUtils.scala

abstract away the assumption that InstanceId must be
an integer in the range 0..numInstances-1 in TransactionCounter.
Small step in preparation for adding invoker elasticity.

do not use InstanceId.int within TransactionCounter

---

tools/build/redo

Add shorthand for applying scala format.
```
> redo -n fmt
apply source code formats
/Users/rabbah/projects/openwhisk/tools/build/../..//gradlew scalafmtAll  --parallel -PdockerHost=192.168.99.100:4243
```

Add scala fmt to redo.

---

tests/src/test/scala/whisk/core/cli/test/WskConfigTests.scala
tools/cli/go-whisk-cli/commands/util.go

line 864 url.Parse caused failure.
Fixes #2411.

Correct unable to set apihost issue.

---

tests/src/test/scala/whisk/core/cli/test/WskConfigTests.scala
tools/cli/go-whisk-cli/commands/property.go

Also fix test framework to not generate an empty string WSK_CONFIG_FILE env value by default

Cli should ignore a config file env variable value of empty string

---

tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala

The strip logs test checked both stdout and stderr for stripped timestamps but was expecting stdout to come first and stderr second. I observed twice in Travis (here's [one](https://s3.amazonaws.com/archive.travis-ci.org/jobs/276129446/log.txt?X-Amz-Expires=30&X-Amz-Date=20170916T025333Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJRYRXRSVGNKPKO5A/20170916/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=e2a846eacf2284a8b7788eb7bf76b733849b7dfa8db4efcf0af3c372f8916869) that the streams may be flushed in the opposite order so relax the test accordingly.
```
Exception occurred during test execution: org.scalatest.exceptions.TestFailedException:
"this is std[err
this is stdout]
" was not equal to "this is std[out
this is stderr]
"
```

Remove heisenbug from test.

---

core/invoker/build.gradle
core/invoker/src/main/scala/whisk/core/containerpool/docker/ProcessRunner.scala

**Note:** Measurements of the impacts of this are not yet done. I thought it makes sense to open the PR though for feedback.
`scala.sys.Process` only has a blocking interface which blocks one thread for the runtime of the command. Furthermore, each of those processes open another thread to handle the output streams of the started process. Under load, the system churns through a **lot** of threads, which can cause efficiency problems.
NuProcess is supposed to fix this by providing an epoll interface, to make waiting on process completion asynchronous and its own (small) threadpool to maintain state and handle streams.

Use an asynchronous process runner to spawn container commands.

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

Do not fail with content-type is set but the entity is empty. Also extend handling of application-json content to permit first class values e.g., array wont be base64 encoded.
Closes #2764.
FYI @akrabat.

Fix parsing of application-json content type.

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala
tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

Manually adds content-type sent to web action into the web action's __ow_headers.
Closes https://github.com/apache/incubator-openwhisk/issues/2690

Display content-type in __ow_headers for web actions

---

docs/about.md

Passing --result to invoke action is a better feedback to confirm that it actually executed the function and got back the expected result.

Added --result to invoke action

---

ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala

Extend Ansible deploy playbook for controller role such that it passes the blackbox fraction
setting as environment variable when running the controller container. Make the blackbox fraction
a required property of the LoadBalancerService such that the setting is read from the environment.
Allow overriding of the default blackbox fraction in Ansible.
All this is needed to vary the proportion between managed and blackbox invokers to accomodate
usage in production.
I tested the change by adding the setting `controller_blackbox_fraction: 0.5` to file `ansible/environments/docker-machine/group_vars/all` and re-deploying the controller. As a result, the controller creates the following log entry indicating that the setting was picked up properly:
```
[2017-09-15T12:55:35.122Z] [INFO] [#sid_120] …
```

Make blackbox invoker fraction configurable via Ansible

---

common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/Activations.scala
core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala
core/controller/src/main/scala/whisk/core/controller/Namespaces.scala
core/controller/src/main/scala/whisk/core/controller/Packages.scala
core/controller/src/main/scala/whisk/core/controller/Rules.scala
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/PackageActionsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
tests/src/test/scala/whisk/core/controller/test/migration/SequenceActionApiMigrationTests.scala
tests/src/test/scala/whisk/core/database/test/DbUtils.scala
tests/src/test/scala/whisk/core/entity/test/ViewTests.scala

The views computed in the database have some redundancies. This will remove one entire view which is not necessary now that activations are not in the same database as the rest of the assets. It also removes a custom (read expensive) reduction for packages which we don't use either.
Replaces https://github.com/apache/incubator-openwhisk/pull/2691 - rebased to master and reformated code. Preserving old prs for the incremental commits and Travis ✅.

Remove redundant view which predates db split into activations and assets.

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala
docs/webactions.md
tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

Instead of hardcoding the header value for `Access-Control-Allow-Headers`, echo back the request headers from the request when `Access-Control-Request-Headers` is present.
Closes #2653.
FYI @akrabat

Echo Access-Control-Request-Headers as Access-Control-Allow-Headers 

---

tests/src/test/scala/system/basic/WskSdkTests.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/action.go
tools/cli/go-whisk-cli/commands/commands.go
tools/cli/go-whisk-cli/commands/property.go
tools/cli/go-whisk-cli/commands/util.go
tools/cli/go-whisk/whisk/action.go
tools/cli/go-whisk/whisk/sdk.go
tools/cli/go-whisk/whisk/util.go

Reuse the getURLBase utility method when computing the URL for sdk
downloads and action URLs.
This fixes #2720 and fixes #2719.

Don't assume apihost is https for sdk and action urls

---

ansible/group_vars/all
ansible/roles/kafka/tasks/deploy.yml

Don't keep messages for the Cache Invalidation Kafka, that are older than 5 minutes.

Keep Cache invalidation messages in Kafka only for 5 minutes

---

common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/common/TransactionId.scala

Logging is **the** hotspot in our application today. This takes a first stab at making the overhead a bit smaller by respecting the set log-level as early as currently possible and not do any extranous throwaway computation.
It also reduces a bit of unnecessary boxing for the sake of just trying to keep a single space out of the message.

Make logging hot paths lighter.

---

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala

"Thread.sleep" unnecessarily blocks the Thread instead of scheduling the retry.
Part of a general mission of reducing blocking in our Invoker code.

Remove "Thread.sleep" from log reading retries.

---

common/scala/src/main/scala/whisk/core/entitlement/Privilege.scala
common/scala/src/main/scala/whisk/core/entity/Identity.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/Activations.scala
core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala
core/controller/src/main/scala/whisk/core/controller/Entities.scala
core/controller/src/main/scala/whisk/core/controller/Namespaces.scala
core/controller/src/main/scala/whisk/core/entitlement/ActionCollection.scala
core/controller/src/main/scala/whisk/core/entitlement/Collection.scala
core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/PackageCollection.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala

Enumerations are a mess in Scala and generally ADTs are more flexible and easier to grasp. Additionally, the current use of `Enumeration` in `Privilege` results in thread-contention because one of its inner parts `ofName` is `synchronized` and used heavily on our hot path.

Drop using an Enumeration for Privilege.

---

tools/travis/build.sh

Swift 3.1.1 build is safe to remove, since we're not running any tests there anyway and it buys 4 minutes of time in the process.
Kicked off a dev-list discussion here to solve the underlying root cause more efficiently: https://lists.apache.org/thread.html/f81150a4f19c3c6f0a4a4505ca13ac044e7b85bda01faf3f29f64614@%3Cdev.openwhisk.apache.org%3E

Removing 'Swift 3.1.1' from build.

---

common/scala/build.gradle
common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
common/scala/src/main/scala/whisk/core/entity/ActivationId.scala
common/scala/src/main/scala/whisk/core/entity/UUID.scala
core/controller/build.gradle

Java's UUID.randomUUID() is known the be `synchronized` and blocking which causes thread-contention and thus performance problems.
`SecureRandom.nextBytes` is the synchronized piece, so using a `ThreadLocal` instance resolves thread contention there. Switching Java's randomness source to the non-blocking `/dev/urandom` resolves blocking of the computation itself.
Switching to `/dev/urandom` is [not a problem](https://unix.stackexchange.com/a/324210).
Supposed to fix #2747.

Compute UUIDs in a non-blocking fashion.

---

tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

There was a question that came up suspecting raw actions of not receiving a JSON entity as expected. This test adds additional coverage to make sure that the controller is treating the JSON value opaquely.

Add test cases to ensure raw encoding of entity does not modify JSON format.

---

core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala

The Loadbalancer has a buffer of, if the last activations of an invoker has been successful.
This PR treats an activation as unsuccessful, if the active ack times out.
This will take the invoker unhealthy, if it does not respond with active acks anymore.
PG4#714 is running

Treat a timed out active ack as failed activation in invokerhealth protocol

---

ansible/files/activations_design_document_for_activations_db.json
ansible/files/logCleanup_design_document_for_activations_db.json

Sequence activation logs are system generated, have bounded size, and provide causality tracking between activations. Exclude them from log deletion.
Here is the update view for convenience:
```js
function (doc) {
if (doc.activationId !== undefined && doc.logs && doc.logs.length > 0) try {
var deleteLogs = true;
for (i = 0; i < doc.annotations.length; i++) {
var a = doc.annotations[i];
if (a.key == "kind") {
deleteLogs = a.value != "sequence";
break;
}
}
if (deleteLogs) {
emit(doc.start, doc._id);
}
} catch (e) {}
}
```
Closes #2800.

Exclude sequence actions from log cleanup view.

---

core/swift3Action/Dockerfile

Work around missing github repo by basing the Swift 3 action container image
on a known-to-work image available on public DockerHub: https://hub.docker.com/r/openwhisk/swift3action/.
With this approach, the actual Docker build of the image won't be kicked off
any more but an existing image will be pulled and used.
Since 2017-09-28 morning CEST, github repo https://github.com/IBM-Swift/swift-watson-sdk.git
is no more available causing a build break. The Swift 3.1.1 action container image
already addresses this problem by no more using the deprecated prereq.
The Swift 3 action container image must either be fixed or removed.

Fix build break of Swift 3 action container image

---

ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
common/scala/build.gradle
common/scala/src/main/scala/whisk/common/Config.scala
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/controller/build.gradle
core/controller/src/main/resources/application.conf
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/loadBalancer/DistributedLoadBalancerData.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerData.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerDataLocal.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LocalLoadBalancerData.scala
core/controller/src/main/scala/whisk/core/loadBalancer/SeedNodesProvider.scala
core/controller/src/main/scala/whisk/core/loadBalancer/SharedDataService.scala
docs/README.md
docs/deploy.md
tests/build.gradle
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/SeedNodesProviderTest.scala
tests/src/test/scala/whisk/core/loadBalancer/test/SharedDataServiceTests.scala

Hello, 
this PR is a WIP to share the state across multiple controllers to scale out the controllers in OpenWhisk. 
It will allow us to share Activations per namespaces and invokers across several controllers using [Akka Distributed framework](http://doc.akka.io/docs/akka/snapshot/scala/distributed-data.html). The TrieMaps were replaced by PNCounterMaps, which are updated locally without waiting for the replication across other nodes in the cluster. 
UPDATED.
I have a couple of things to mention:
* Parsing of the seed-nodes is defined in a separate method due to a well known akka config issue https://github.com/akka/akka/issues/23600. 
* The old LoadBalancerData implementation is still in place, so in case of emergency we can turn off akka replication across Controllers. 
Any other todos …

Share bookkeeping data across controllers

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala

Removes timeout-access from headers:
```
> curl -k -X POST https://guest.localhost/default/echo.json -H "Content-Type: application/json" -d '["a"]'
{
"__ow_method": "post",
"__ow_query": "",
"__ow_body": "WyJhIl0=",
"__ow_headers": {
"host": "controllers",
"user-agent": "curl/7.43.0",
"accept": "*/*",
"timeout-access": "<function1>" <---- this one
},
"__ow_path": ""
}
```
Fixes #2636.
For reference: https://github.com/akka/akka-http/issues/64

Remove synthetic header.

---

common/scala/src/main/scala/whisk/core/containerpool/Container.scala
common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
common/scala/src/main/scala/whisk/core/entity/ActivationResult.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClientWithFileAccess.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

If a user-container runs out of memory, the HTTP connections is abruptly aborted and the user has no chance to get further evidence into why her action failed.
Docker actually provides that information so it can be checked on an abrupt connection termination whether the container was indeed aborted by the OOM killer.
Fixes: #2652

Notify the user if a container is killed due to memory exhaustion.

---

tests/src/test/scala/system/basic/WskConsoleTests.scala

Use activation start times as time base when polling for activations since a point in time - before, local system time was used. If there is a clock mismatch between the local system and the system which records activations (=invokers), poll results can be empty.
Other queries use relative times, i.e. return activations since the specified number of seconds. For these relative times, a start and end time is taken based on the local system time and the time difference in seconds is computed. It is important to use start and end time from the same time source.
In addition, use some time contigency to make tests more robust.
Provide more debug output in case an assertion fails.

Make console tests more robust

---

ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
core/controller/build.gradle
core/invoker/build.gradle

The new options ensure that the controller / invoker JVM crashes if the garbage collector is no more able to free up space. The resulting error log is written into the `/logs` directory which is visible on the system hosting the controller / invoker Docker container. The name of the error log file is fixed such that only one single file is kept even if multiple crashes occur.
Consolidated all options in `deploy.yml` because `-XX:ErrorFile` refers to the `/logs` directory mounted into the container. If this directory is changed, `-XX:ErrorFile` must be updated as well.
`-XX:+UseGCOverheadLimit`
Enables the use of a policy that limits the proportion of time spent by the JVM on GC before an OutOfMemoryError exception is thrown. This option is enabled, by default and the parallel GC will …

Improve garbage collector out-out-memory handling and debugging

---

ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
ansible/tasks/db/checkDb.yml

This PR adds a check to the deployment playbooks of the controller and the invoker to check if all reuqired databases exist.
Otherwise the deployment will fail.
PG3#1170 is 🔵 .

Add check to controller and invoker that required databases exist

---

ansible/group_vars/all
ansible/roles/invoker/tasks/deploy.yml
ansible/templates/whisk.properties.j2
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
docs/deploy.md
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala

Restore config option to use docker pause/unpause instead of
docker-runc pause/unpause in the invoker.  Works around problem
of incompatible versions of docker-runc in invoker container and
hosting environment.

option to use docker pause/unpause instead of docker-runc pause/unpause

---

ansible/roles/invoker/tasks/deploy.yml
ansible/templates/whisk.properties.j2
common/scala/build.gradle
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala

A prototype of one possible approach for dynamic invoker registration.
The invoker's instanceId is not provided on the command line on
startup.  Instead, the invoker dynamically requests an id from
the controller during its startup via the message bus (kafka).
Once it receives an id, invoker startup continues unchanged.
On the plus side, this protocol maintains the property that invokers
are densely assigned ids starting from 0.  On the minus side, it takes
an extra round of messages thus mildly delaying system startup.
An alternative approach would be to use randomly generated UUIDs as
the invoker's id and adapt the load balancer algorithm accordingly.
Using UUIDs as invoker ids might make some aspects of operations
slightly more annoying as well, as the invokers would not have
stable …

first stage of support for dynamic invoker id assignment

---

common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/core/database/ArtifactStore.scala
common/scala/src/main/scala/whisk/core/database/Batcher.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
common/scala/src/main/scala/whisk/core/entity/DocInfo.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/common/LoggedFunction.scala
tests/src/test/scala/whisk/core/database/test/BatcherTests.scala
tests/src/test/scala/whisk/core/database/test/CouchDbRestClientTests.scala

Writing activations in the Invoker is not time critical and can be greatly optimized by batching the activations to reduce the number of connections used towards the database. That enables a lot of optimizations on the database side and is in general a good practice.
Signed-off-by: Christian Bickel <cbickel@de.ibm.com>

Implement bulk write of activations in the Invoker.

---

ansible/roles/invoker/tasks/deploy.yml
ansible/templates/whisk.properties.j2

As a redis is optional for an invoker, the deployment should also work without any redis in the hosts file.

Make redis optional on deployment

---

tests/src/test/scala/common/TestUtils.java
tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/common/rest/WskRest.scala

Almost all the test cases in OpenWhisk are currently running based
on the wsk CLI binary. In order to separate the CLI out of OpenWhisk
core repository, we need to call REST API of OpenWhisk to access
OpenWhisk services instead of calling the wsk CLI binary command.
This PR adds the basic REST implementation for all the test cases
to use. One basic principle is to keep the changes to the existing
test cases as few as possible, so we add WskRest.scala as an equivalent
class to Wsk.scala and WskRestTestHelpers.scala as an equivalent file
to WskTestHelpers.scala for REST.
All the replacement of binary with REST will happen in an increamental fashion.
This PR only changes one existing test case in WskActionTests.scala, and
reimplements it in WskRestActionTests.scala. All the other test cases …

Add the fundamental framework of REST invocation for test cases

---

common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala

Make REDIS_HOST_NAME and REDIS_HOST_PORT optional for the invoker
and only trap as a configuration error when the invoker actually
tries to perform dynamicId assignment.

Invokers only require Redis if using dynamic Id assignment

---

ansible/roles/nginx/files/genssl.sh

`genssl.sh` shows the usage even if the right number of arguments are given. Over in [devtools/docker-compose](https://github.com/apache/incubator-openwhisk-devtools/tree/master/docker-compose) that gives a usage warning from the Makefile, even though everything is fine.
- 1 argument is required, exit otherwise – without CN does not make sense AFAICS, and it seems always called with at least 1 arg
- document optional 2nd argument

fix genssl.sh usage output

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

This matches the activation annotations for sequences which have a kind sequence appended.
@markusthoemmes is there a good place to unit test this or shall I add an integration test instead?

Add action kind to activation record.

---

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala

Remove all Docker containers on the system that match the naming filter `wsk<invoker instance number>_` at startup and shutdown. In the past, only running containers matching the filter were removed - paused containers are considered to be running. The new strategy will also remove containers that are stopped or could never be started properly for any reason. From time to time, we see action containers that are not running but should be cleaned up.
If Docker commands used to remove containers (`docker ps`, `docker-runc resume` and `docker rm`) do not return within 30 seconds during startup, abort startup and let Docker re-start the invoker container. We have seen systems with heavy load where Docker commands take too long to complete. In that situation, we need a defined behavior, i.e. …

Make Docker action container cleanup during invoker startup / shutdown more robust

---

core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala

Build break was introduced by following PRs which have a semantic conflict:
1. https://github.com/apache/incubator-openwhisk/pull/2871
2. https://github.com/apache/incubator-openwhisk/pull/2858

Fix invoker build break

---

docs/actions.md

Explains to users how to save code from an existing action.

Add documentation for save action feature

---

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala

If `docker run` fails with exit code 125 and prints a valid container ID to stdout, a broken Docker container was left behind. This PR detects the described situation and immediately removes the broken container to save disk space. In addition, the Docker daemon seems to slow down with the number of containers, so cleaning up broken containers can also have a positive performance impact.
The main root cause for broken containers is a failure when extracting the container's file system - for example, due to missing disk space or exhausted inodes. This PR does fully resolve low disk space or exhausted inodes but it can help relax such situations. For example, if a container with a very large file system cannot be created, cleaning it up may enable the creation of a smaller container.

Remove broken containers if docker run fails

---

core/nodejs6Action/Dockerfile
docs/reference.md

update nodejs runtime to pickup openwhisk client-js 3.9.0

---

tools/ubuntu-setup/ansible.sh
tools/ubuntu-setup/scala.sh
tools/vagrant/Vagrantfile

Fixes #2901
Related to #2891 
Fix to ansible error with crypto is `sudo pip install --upgrade setuptools`
We have mismatch version of scala, update to match `2.8.11`
Try using an official ubuntu 14 image from provider virtual box
Ubuntu 14 is LTS until April 2019 according to this site: https://wiki.ubuntu.com/Releases
So I proposed we keep using Ubuntu trusty, since it's the version we use CI/CD in Travis

fix ansible install errors in vagrant

---

tests/src/test/resources/application.conf
tests/src/test/scala/common/rest/WskRest.scala

- `WhiskProperties.getApiHostForAction` should be used instead of `WhiskProperties.getBaseControllerAddress` for WskRest.
- Disables certificate checking for WskRest tests.

Use proper host for Wsk REST tests

---

core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala

This slipped in with the Redis changes and I don't think it's needed b/c the invoker already starts with an `id`. 
if `id arg` is provided, use it, and do NOT require INVOKER_NAME or REDIS_HOST configs; if `id arg` is NOT provided, then DO require INVOKER_NAME AND REDIS_HOST configs
Relates to: #2872 and https://github.com/apache/incubator-openwhisk-devtools/pull/62

make INVOKER_NAME optional

---

common/scala/src/main/scala/whisk/core/database/ArtifactStore.scala
common/scala/src/main/scala/whisk/core/database/ArtifactStoreExceptions.scala
common/scala/src/main/scala/whisk/core/database/ArtifactStoreProvider.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/database/CouchDbStoreProvider.scala
common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
common/scala/src/main/scala/whisk/core/entity/DocInfo.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/cli/test/SequenceMigrationTests.scala
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala
tests/src/test/scala/whisk/core/entity/test/ViewTests.scala

Move the mechanism of batching activations to the CouchDbRestStore, to have it also in the Controller in place.
Currently batching is only enabled for activations.
Dependant on #2812

Move batching to CouchDbRestStore

---

tools/cli/Dockerfile

- Fix for security issue https://github.com/golang/go/issues/22125

Bump go cli to 1.8.4

---

tools/macos/docker-machine/tweak-dockermachine.sh

Ping appears to be disabled for `repo.tinycorelinux.net`. The tweak script attempts to ping `repo.tinycorelinux.net` when it fails, it attempts to ping `ftp.gtlib.gatech.edu`, which works. However, when the script tries to download Python from `ftp.gtlib.gatech.edu` that download fails.
This patch attempts a curl request against `repo.tinycorelinux.net` to see if it is responsive instead of pinging it, and no longer uses `ftp.gtlib.gatech.edu`.
Fixes https://github.com/apache/incubator-openwhisk/issues/2892

Fix Python download for tweak-dockermachine

---

tests/src/test/scala/system/basic/WskBasicJavaTests.scala
tests/src/test/scala/system/basic/WskBasicNodeTests.scala
tests/src/test/scala/system/basic/WskBasicPythonTests.scala
tests/src/test/scala/system/basic/WskBasicSwift3Tests.scala
tests/src/test/scala/system/basic/WskCliBasicJavaTests.scala
tests/src/test/scala/system/basic/WskCliBasicNodeTests.scala
tests/src/test/scala/system/basic/WskCliBasicPythonTests.scala
tests/src/test/scala/system/basic/WskCliBasicSwift311Tests.scala
tests/src/test/scala/system/basic/WskCliBasicSwift3Tests.scala
tests/src/test/scala/system/basic/WskCliUnicodeJavaTests.scala
tests/src/test/scala/system/basic/WskCliUnicodeNodeTests.scala
tests/src/test/scala/system/basic/WskCliUnicodePython2Tests.scala
tests/src/test/scala/system/basic/WskCliUnicodePython3Tests.scala
tests/src/test/scala/system/basic/WskCliUnicodeSwift311Tests.scala
tests/src/test/scala/system/basic/WskCliUnicodeSwift3Tests.scala
tests/src/test/scala/system/basic/WskConsoleTests.scala
tests/src/test/scala/system/basic/WskRestBasicJavaTests.scala
tests/src/test/scala/system/basic/WskRestBasicNodeTests.scala
tests/src/test/scala/system/basic/WskRestBasicPythonTests.scala
tests/src/test/scala/system/basic/WskRestBasicSwift311Tests.scala
tests/src/test/scala/system/basic/WskRestBasicSwift3Tests.scala
tests/src/test/scala/system/basic/WskRestUnicodeJavaTests.scala
tests/src/test/scala/system/basic/WskRestUnicodeNodeTests.scala
tests/src/test/scala/system/basic/WskRestUnicodePython2Tests.scala
tests/src/test/scala/system/basic/WskRestUnicodePython3Tests.scala
tests/src/test/scala/system/basic/WskRestUnicodeSwift311Tests.scala
tests/src/test/scala/system/basic/WskRestUnicodeSwift3Tests.scala
tests/src/test/scala/system/basic/WskUnicodeTests.scala

Swift3, Swift311, Python, Node and Java are not cli related tests.
We do not have to maintain them as cli test suites, so a straight
replacement of wsk with wskrest will be sufficient for them.

Replace basic runtimes with REST implementation

---

common/scala/src/main/scala/whisk/common/TransactionId.scala

Hello, 
this change enables emitting counter metrics for started and failed transaction, since in some InfluxDB/Grafana versions histogram values cannot be counted.
regards, Vadim.

Emit counter metrics for start and error cases

---

docs/feeds.md
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tools/cli/go-whisk-cli/commands/trigger.go

This PR is to add support for retrieving the status and configuration of a feed trigger
Support has been implemented in the feed providers with the following:
https://github.com/apache/incubator-openwhisk-package-kafka/pull/217 <-- Merged
https://github.com/apache/incubator-openwhisk-package-cloudant/pull/137 <-- Merged
https://github.com/apache/incubator-openwhisk-package-alarms/pull/101 <-- Merged

WIP Support retrieving status and configuration of feed triggers in CLI

---

docs/actions.md

Update example that has place name overwritten by 'Washington, DC'

Fix the example of default parameters

---

common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/database/CouchDbStoreProvider.scala
common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala
common/scala/src/main/scala/whisk/core/entity/DocumentReader.scala
common/scala/src/main/scala/whisk/core/entity/Exec.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/PostActionActivation.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala

Creates new datatype called WhiskActionMetadata that drops code property from its Exec data type for action invocations. This prevents action code from being loaded into memory.

Reduce memory consumption for invocations of cached actions

---

tests/src/test/resources/application.conf
tests/src/test/scala/common/WhiskProperties.java
tests/src/test/scala/common/rest/WskRest.scala
tests/src/test/scala/ha/ShootComponentsTests.scala
tests/src/test/scala/limits/ThrottleTests.scala
tests/src/test/scala/services/HeadersTests.scala
tests/src/test/scala/system/rest/ActionSchemaTests.scala
tests/src/test/scala/whisk/core/admin/WskAdminTests.scala
tests/src/test/scala/whisk/core/database/test/CacheConcurrencyTests.scala
tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala
tests/src/test/scala/whisk/core/limits/MaxActionDurationTests.scala

The test cases changed in this PR are non-CLI test cases, which should use
the REST only to access the openwhisk services. This PR replaces the Wsk
with WskRest in order to make it happen.

Re-implement the non-cli test cases with REST

---

tests/src/test/scala/whisk/core/cli/test/BaseApiGwTests.scala

- to avoid affecting any downstream tests that are action invocation heavy

Completely settle throttle after the API GW test suite is run

---

tests/src/test/scala/whisk/core/cli/test/WskApiGwTests.scala

The PRs before replace all the rest of the wsk inplementation with REST
implementation for test cases in openwhisk. This PR cleans up some
leftover for the WskRest migration work. After this PR, no more test
case needs to be changed any longer, and cli in openwhisk core is ready
to departure.

Clean up all the test cases

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Packages.scala
tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala

Updates to existing packages named "default" are still permitted.
Fixes #1785

Reject requests to create packages having the name 'default'

---

common/scala/src/main/resources/application.conf
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala

At the moment we divide the number of parallel requests across 3 stores that use CouchDB client: entity, authstore and activationStore, thanks to the fact that the number of requests is shared across all flow materialisations as per this doc:
https://doc.akka.io/docs/akka-http/current/scala/http/configuration.html
This PR should help to prevent dropping the connections if the number of parallel requests to couchdb exceeds the max number of open connections.  
> Common causes of pool overload: 
There are peaks in the request rate (prevent peaks by tuning the client application or increase max-open-requests to buffer short-term peaks)
https://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html
@bwmcadams please correct me if this is not correct.  
Thanks.

Increase the number of max open requests

---

ansible/roles/invoker/tasks/clean.yml

If deploy mutilple invoker instances on one physical node, and  execute below `remove remaining actions`, exist problems
```
TASK [invoker : remove remaining actions] **************************************
Wednesday 15 November 2017  14:58:47 +0900 (0:00:00.618)       0:00:08.693 **** 
changed: [invoker0]
TASK [invoker : remove invoker log directory] **********************************
Wednesday 15 November 2017  15:08:45 +0900 (0:09:57.545)       0:10:06.239 **** 
changed: [invoker0]
```
1. `remove remaining actions` task will costs much time to execute(about cost 10 mins), becuase when remove `invoker0`, the task will remove action container `wsk0_, wsk1_, and so on`, on the other hand, `wsk1` is removed by `invoker1's stop hook` default, so that's the reason why it will cost much time. …

Fix bug when remove invoker

---

tests/src/test/resources/application.conf

A blocking request will be open for at most 60 seconds before it falls back to a non-blocking request. The default idle-timeout is at 60 seconds so a racy failure happens in tests, where a blocking fallback is provoked.

Bump idle-timeout for HTTP clients in test.

---

ansible/group_vars/all

This PR is going to enable controller HA and clustering. 
It means 2 things:
* nginx will dispatch requests to controllers in the round-robin fashion
* The state of the load balancer will be replicated and [ditributed load balancer data](https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/loadBalancer/DistributedLoadBalancerData.scala) will be used. 
@cbickel

Enable controller HA by default

---

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala

Docker < 1.13.1 has a known problem: if more than 10 containers are created (`docker run`) concurrently, there is a good chance that some of them will fail. See https://github.com/moby/moby/issues/29369
Use a semaphore to make sure that at most 10 `docker run` commands are active the same time.

At most 10 `docker run` commands are allowed in parallel

---

ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
common/scala/Dockerfile
common/scala/build.gradle
common/scala/src/main/resources/application.conf
common/scala/transformEnvironment.sh
core/controller/Dockerfile
core/controller/init.sh
core/controller/src/main/resources/application.conf
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
core/invoker/Dockerfile
core/invoker/init.sh
docs/dev/configuration.md
settings.gradle

The goal of this is to eventually provide all configuration through TypesafeConfig files and keep defaults very close to the component itself vs. keeping them in ansible. That will enable different deployment methods much more easily and also facilitate quick local testing. For instance the controller should be startable only given CouchDb and Kafka connection data.
This adds the ability to configure the main components (controller/invoker) via pureconfig case-classes vs. using WhiskConfig.
**Benefits are:**
- Automatic type derivation
- Static loading of config vs. passing one instance around
- Proper scoping of configuration
- It's the standard in Scala (based on TypesafeConfig)
**Implementation:**
TypesafeConfig reads JSON-like configuration files, which we can nest as we please. Those …

Configure components via pureconfig.

---

tests/src/test/scala/common/rest/WskRest.scala

This PR sets the idle timeout to 5 minutes in order to give enough
time for sequence tests to finish.

Add the idle timeout configuration to the Akka client

---

ansible/roles/nginx/templates/nginx.conf.j2
core/controller/src/main/resources/application.conf

Lower the timeouts of the controller to match the proxy_read_timeout in nginx.
If the nginx proxy_read_timeout is lower than the controller timeout, this can result in issues with long requests.

Adapt timeouts of controller and nginx.

---

ansible/group_vars/all
ansible/roles/couchdb/tasks/deploy.yml
ansible/templates/whisk.properties.j2
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
tests/src/test/scala/common/WhiskProperties.java
tests/src/test/scala/ha/ShootComponentsTests.scala

This pr is to deploy couchdb cluster.
From the version 2.0, CouchDB officially supports clustering.
Notable changes are as follow:
`klaemo/couchdb` is superseded by `apache/couchdb`.
Accordingly version is also updated to 2.1
Since we need one coordinator node to setup CouchDB cluster, first host in db group becomes coordinator node.
Important factors for CouchDB cluster are the number of shards and the number of quorums.
Corresponding environment variables are introduced.
Note: Please be informed that, current version of `apache/couchdb:2.1` does not support these values, so I created a pull request for this.
Once this pr is merged, those environment variables will be available.
https://github.com/apache/couchdb-docker/pull/32
This pr also can address the problem reported by this issue: …

Add couchdb clustering

---

ansible/group_vars/all

Reverts the removal of the second controller for local env.

Disable controller.ha if only 1 controller is deployed.

---

ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml

There were some missing properties that prevented invokers from sending out metrics via kamon. I've added them and removed the unused ones in invokers and controllers.

Fix kamon env vars

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala

if its type of an action has changed or cannot be deserialized because of a runtime-manifest/schema mismatch with controller, report a different error that is more useful.

Tweak error message for failing to invoke an action

---

core/controller/src/main/scala/whisk/core/controller/Triggers.scala
tests/src/test/scala/common/rest/WskRest.scala
tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala

Currently, trigger fire requests are blocked by db writes (storing trigger activation).  In times of extreme db latency, a storm of trigger fire retries can occur - further stressing the system.  This PR relaxes the trigger fire response dependency on the trigger activation db write avoiding unnecessary trigger retries when activation writes are excessively backed up.
- Return 202 for trigger fire requests.  Still include activation id in response body as before
- asynchronously write the trigger activation record to the db
- db write failures continue to be logged to the backend log

Return 202 for trigger fire requests

---

core/controller/src/main/resources/apiv1swagger.json

Successful POST `/namespaces/{namespace}/triggers/{triggerName}` responds with 202 instead of 200
Related to PR #3031

Update trigger fire REST API swagger

---

ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
common/scala/src/main/resources/reference.conf
common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationLogStore.scala
common/scala/src/main/scala/whisk/core/containerpool/logging/LogRotatorSink.scala
common/scala/src/main/scala/whisk/core/containerpool/logging/LogStore.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationFileLogStoreTests.scala
tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

Includes #2878.
Adds a new LogStore which reads the whole file in memory and stores the logs in the activation entry. At the same time it pipes all user-written logs to a file in an enriched format (which is why the extra fields need to be added to the interface).
The written file can then be read by any other instance asynchronously.

Add LogStore which stores to database and file simultaneously.

---

core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala

This PR adjusts the controller side time out defining the allowed run-time for actions to handle 
edge case scenarios correctly in which the synchronization of controllers in a HA setup does not work fast enough.

Adjust controller side action time-out to avoid invokers marked as unhealthy 

---

core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala

It is not necessary, that all our invoker-topics are in one consumer group. This PR assigns each topic its own consumer-group.

Give every invoker-topic it's own consumergroup

---

common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/database/test/DbUtils.scala
tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala

Currently when an entity that has an attachment is created or updated, the corresponding entity is not cached. This change caches the created entity.
For instance, creating or updating a java action will create a database entry of the entity and the entity will be cached. Immediately after the jar file is added as an attachment in the DB and the previously cached entity is removed from the cache. That means quickly making a call after action creation, such as action get would have to fetch the entire entity from the DB instead of the local cache.
Instead these  changes will not remove the cached entity when a DB attachment is added to the entity.

Do not cache invalidate when adding a DB attachment

---

common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationFileLogStoreTests.scala

Correlation should happen based on a unique identifier.

Add namespaceId to the activation record as well to enable correlation.

---

ansible/roles/invoker/tasks/clean.yml

[Ubuntu 14.04 has a well-known bug](https://github.com/moby/moby/issues/22513) that leaves orphaned `ifstate.veth*` files in `/run/network` when creating / removing a virtual ethernet interface pair with `ip link add name veth1 type veth peer name veth2` and `ip link delete veth1`. Docker containers use these `veth` pairs: when a Docker container is created, Docker creates a pair and removes it when the container is removed. If a lot of containers are created, the file system where `/run/network` resides, runs out of inodes so that no more containers can be created.
Invokers running on Ubuntu 14.04 VMs can be affected by the described situation if a lot of cold invocations are run.
Remove orphaned `ifstate.veth*` files older than 60 minutes in `/run/network` on Ubuntu 14.04 when cleaning …

Clean orphaned ifstate.veth* files on Ubuntu 14.04

---

ansible/roles/invoker/tasks/clean.yml

The initial version failed if no Docker containers were running because an invalid regular expression was constructed for `find` command.
With this change, the regular expression for filtering active virtual ethernet interfaces is only included active interfaces can be found. If Docker containers are running, there are always active interfaces. If no Docker containers are running, there may be no actives interfaces.
Also see https://github.com/apache/incubator-openwhisk/pull/3007 for a discussion and test results.

Don't fail if no Docker containers running

---

common/scala/src/main/scala/whisk/core/WhiskConfig.scala

I should have removed these when we switched to using zookeeper
as the persistent store for invoker id assignment.  They are not used.

cleanup: remove unused redis host/port from WhiskConfig

---

actionRuntimes/actionProxy/invoke.py

A zip or tgz (more generally archive format) is specific to a runtime. Allow this script to work with zip or tgz files.
See https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/16 for example.

Allow invoke helper to work with tgz files.

---

tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala

A code parameter is not needed for `js6MetaData()`.

Remove unneeded code reference from WhiskActionMetaData test helper

---

common/scala/src/main/scala/whisk/core/entity/Exec.scala
core/controller/src/main/resources/apiv1swagger.json
core/controller/src/main/scala/whisk/core/controller/Actions.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala

Provides optional query parameter for getting an action that specifies whether or not action code should be fetched and returned. When the query parameter is present, WhiskActionMetadata will be used to fetch the action. Otherwise, WhiskAction will be used to retrieve the action.
Fetch the action with the code as is today:
`https://192.168.99.100/api/v1/namespaces/_/actions/actionName`
or
`https://192.168.99.100/api/v1/namespaces/_/actions/actionName?code=true`
Fetch action metadata without code:
`https://192.168.99.100/api/v1/namespaces/_/actions/actionName?code=false`
Depends on https://github.com/apache/incubator-openwhisk/pull/2730.

Optionally fetch code when getting an action

---

ansible/roles/nginx/tasks/clean.yml

Some weeks ago, I moved all config files to `wskconf`. To delete config files in the old directory, I added the code, that I remove again in this PR.

Remove obsolete code to remove old config directory of nginx.

---

common/scala/.dockerignore
core/controller/.dockerignore
core/invoker/.dockerignore

Adds .dockerignore files to 3 docker images which also have scala code. This ensures that build context send to docker daemon only includes required files.
This is based on recommended docker best practice of [using a .dockerignore file][1]. 
Below are the size of build context send prior and post change
- common:scala
Sending build context to Docker daemon  30.32MB //current
Sending build context to Docker daemon  6.144kB  //post change
- :core:controller
Sending build context to Docker daemon  65.54MB //current
Sending build context to Docker daemon  48.74MB //post change
- :core:invoker
Sending build context to Docker daemon  49.87MB //current
Sending build context to Docker daemon  45.46MB //post change
This leads to decent saving for common for now. Going forward once Maven artifacts …

Add dockerignore files to reduce size of build context

---

ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
common/scala/src/main/resources/logback.xml

This PR makes the log level configurable via ansible.
The log level is configurable for the controller (`controller_loglevel) `
the invoker (`invoker_loglevel`) 
or for both components (`whisk_loglevel`).
The default log level is still set to INFO level.

Make the log level configurable via ansible

---

core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala

Active ack messages are inspected to check whether an invoker has a lot of system-level errors. Timeout of an active ack is treated as such an error. The active ack timeout time is coupled to the "promise" that there is no waiting queue on an invoker at all (diluted because of clustering). This promise is non-existent as of today and thus active ack timeout should not be seen as system-level error from the invoker.

Decouple health checking from active ack messages.

---

tests/src/test/resources/application.conf
tests/src/test/scala/common/rest/WskRest.scala

This PR makes sure the idle timeout is long enough for the action invocation to complete. By default, the idle timeout for a client connection is 1 minute. This PR changes it to 90 seconds in order to give enough time for the action call to finish. As an Akka client,  the idle timeout needs to be configured for both of clientConnectionSettings and connectionPoolSettings.
Closes: #3016

Change the idle timeout to 90 seconds for client connection settings

---

ansible/roles/couchdb/tasks/deploy.yml

This pr is to disable `reduce_limit` on all nodes.
Currently, it is only disabled in coordinator node.
I thought this configuration is cluster-wide, but it was not.
So it should be disabled on all nodes respectively.

Disable reduce limits on all nodes

---

ansible/environments/docker-machine/group_vars/all
ansible/environments/local/group_vars/all
ansible/group_vars/all
common/scala/src/main/scala/whisk/common/TransactionId.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/entity/Exec.scala
common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala

This is a proposed patch to address the feature request in #2852.
The presence of an property `bypassPullForLocalImages` in the runtime manifest will toggle the feature on or off allowing a docker pull to be skipped if the docker action's image name has a prefix matches the local docker build prefix.
See https://github.com/apache/incubator-openwhisk/pull/3052/files#diff-d895f19f56edd5b725a1696b7b9d8877R196 for an example. 
@alexkli can you take a look?

Allow for a docker pull bypass for docker actions where the prefix maches the invoker's docker prefix

---

ansible/roles/routemgmt/files/installRouteMgmt.sh

If GW_USER, GW_PWD, or GW_HOST_V2 are already set in the environment
when running installRouteMgmt.sh then use the value from the
environment bypassing the values in whisk.properties.
This is useful for downstream deployments such as kube to avoid
the need to generate a whisk.properties just to run this script.

optional bypass of whisk.properties when setting GW_ values

---

.gitignore
ansible/README.md
ansible/couchdb.yml
ansible/environments/docker-machine/group_vars/all
ansible/environments/docker-machine/hosts.j2.ini
ansible/environments/local/hosts.j2.ini
ansible/setup.yml
tools/build/redo
tools/travis/build.sh

When using docker-machine, the DOCKER_HOST env var is typically set. Tweak the auto detection for the MacOS to avoid having to use -t.
Also address #2758, and add `-e mode=HA` to deploy multiple core component instances.
Closes https://github.com/apache/incubator-openwhisk/issues/2758.

auto detect docker-for-mac

---

actionRuntimes/actionProxy/invoke.py

Fixes base64 encoding to omit newlines.
```
> docker run -p 8080:8080  java8action &
[1] 71893
> ./actionRuntimes/actionProxy/invoke.py init hello.HelloJava tests/dat/actions/helloJava.jar 
OK
> ./actionRuntimes/actionProxy/invoke.py run '{"name":"J"}'
{"greeting":"Hello J!"}
```
Closes #3116.

Add support for Java actions.

---

common/scala/src/main/scala/whisk/core/connector/Message.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala

The property `activationNamespace` in an activation message is redundant with the `user` identity that is also part of the message. We don't need to pass in on the control plane as a result.

Remove redundant property from activation message.

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala

While collecting a container to remove, the filter checks the action and invocation namespace and excludes those matching the new action from the candidate list. But this check is not necessary - any container in the free pool matching the new action and namespace would be reused and the remove method is not reached in this case.
We could keep these checks as defensive checks. Otherwise it is deadcode and unnecessary overhead.
Tentatively remove, update comment and tests.
For historical context: https://github.com/apache/incubator-openwhisk/pull/2246 but this scheduling heuristic has changed since.

Remove obsolete filter when determining container to remove.

---

common/scala/src/main/scala/whisk/utils/ExecutionContextFactory.scala

the akka after implementation creates an actor, but opaquely. thus, we have no opportunity to cancel any timeout futures. this PR adjusts the after impl to expose and utilize the Cancellables
the consequence of this drag is that WhiskActivations, and a bunch of related artifacts, hang around until various timeouts expire.
PG3 1567 🔵 
PG3 1568 🔵

fix memory drag in PrimitiveActions, and clean up withAlternateAfterTimeout

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala

Refine error message so that internal connection errors don't generate a misleading error response.

Refine error message on failure to fetch action in invoker.

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

The current handshake between the container proxy and the container pool conflates container removal and job completion. The former does not necessarily indicate there is free capacity in the pool since there are conditions under which the job is rescheduled: resume failure, container aging, container reclamation.
pg3/1585 🔵

Separate container removal from job completion.

---

ansible/files/runtimes.json
ansible/group_vars/all

Move definition of default runtimes manifest out of
group_vars/all to an external .json file to make it
easier to share this configuration information with
non-ansible deployments such as kube/mesos/etc.

externalize runtimesManifestDefault to runtimes.json

---

ansible/group_vars/all
ansible/roles/cli/files/createContentJson.sh
ansible/roles/cli/tasks/cli_remote_mode.yml
ansible/roles/cli/tasks/deploy.yml
ansible/roles/cli/tasks/download_cli.yml
ansible/roles/cli/tasks/download_openwhisk_cli.yml

Separated from #3133 .  
It was also necessary to fiddle with the CLI download capabilities, now that the CLI is being automatically compiled for s390x. The result is not quite as dynamic as one might wish, yet, but it appears to get the job done.
This change is likely temporary -- responsibility for determining CLI build architectures is being moved toward the CLI build process in a separate repository -- the hope is eventually the list of all possible architectures will disappear from here.

Support CLI for s390x linux

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Packages.scala
tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala

Fixes #2964.
Disable update on package with a reserved name. A `get` and `delete` of the package is still allowed. Packages that preexist with a reserved name will continue to work: can add actions to them, or invoke actions in them. But the package itself can't be updated.

Disallow create and update of package with reserved names.

---

common/scala/src/main/scala/whisk/http/BasicHttpService.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Activations.scala
tests/src/test/scala/common/WskActorSystem.scala
tests/src/test/scala/services/KafkaConnectorTests.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/database/test/CacheConcurrencyTests.scala
tests/src/test/scala/whisk/core/database/test/CouchDbRestClientTests.scala
tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala
tests/src/test/scala/whisk/core/entity/test/ViewTests.scala

No semantic change is intended here. This is cleaning up some incorrect uses of `after`.
Some additional unit tests are added for checking that empty activation views are handled correctly.
The commits are mutually exclusive for review.

Cleanup test assets between unit tests using afterEach

---

common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala

As suggested by @rabbah in review of another PR, introduce
a singleton to hold the various String keys used to load
config data via PureConfig to make it easier to find all
uses of a particular piece of configuration data.

singleton to hold PureConfig keys

---

ansible/templates/whisk.properties.j2

The number of invoker instances may be a dynamic property of
the deployment; we shouldn't be exposing it in whisk.properties.
Closes #2867

remove invoker.instances from whisk.properties template

---

core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClientWithFileAccess.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/ProcessRunner.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/RuncClient.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/ProcessRunnerTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/RuncClientTests.scala

Docker can cause hanging commands which never finish. Essentially those break the invoker and it needs to be restarted to recover. This adds a timeout to each of those commands to detect this problem.

Bound docker/runc commands in their allowed runtime.

---

common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala
common/scala/src/main/scala/whisk/core/entity/Identity.scala

Currently the cache uses an `expireAfterWrite` policy to invalidate entries. The current policy invalidates entities five minutes after entities are cached even if they are accessed within that time period. 
Using an `expireAfterAccess` policy with a time of five minutes will keep entities in the cache that are accessed within that timeframe. This prevents unnecessary database reads for entities that are used frequently.  
For documentation see: https://github.com/ben-manes/caffeine/wiki/Eviction.

Use cache invalidation policy based on access time

---

core/invoker/build.gradle

Currently invoker module pulls in log4j jars via transitive dependency on zookeeper
```
$./gradlew :core:invoker:dependencies
+--- org.apache.zookeeper:zookeeper:3.4.11
|    +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.25
|    +--- org.slf4j:slf4j-log4j12:1.6.1
|    |    +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.25
|    |    \--- log4j:log4j:1.2.16
|    +--- log4j:log4j:1.2.16
|    +--- jline:jline:0.9.94
|    |    \--- junit:junit:3.8.1
|    +--- org.apache.yetus:audience-annotations:0.5.0
|    \--- io.netty:netty:3.10.5.Final
```
This causes following warning logs in invoker logs and test runs
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/invoker/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in …
```

Avoid packaging log4j dependencies in invoker

---

ansible/README.md
ansible/files/whisks_design_document_for_activations_db_filters_v2.1.0.json
ansible/files/whisks_design_document_for_activations_db_v2.1.0.json
ansible/files/whisks_design_document_for_all_entities_db_v2.1.0.json
ansible/files/whisks_design_document_for_entities_db_v2.1.0.json
ansible/roles/couchdb/tasks/deploy.yml
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala
common/scala/src/main/scala/whisk/core/entity/WhiskPackage.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/Packages.scala
core/controller/src/main/scala/whisk/core/controller/Rules.scala
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
tests/src/test/scala/whisk/core/entity/test/ViewTests.scala
tools/db/README.md

The view for actions is enriched to include limits, and if an action is binary or not. I imagine that as the exec blob is moved to an attachment, the view computation becomes simpler and includes the entire doc. This would avoid having to add some annotation on the document which then become redundant (`kind` for example). I've done this for rules in the proposed patch herein.
In addition, add a `count` reducer to all the views in service of providing an API to return entity (including activation) counts.
The first commit adds the new views as `v2.1.0` as they add fields but don't remove any existing ones.

Enrich entity views, and add count reducer

---

core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala

This PR replaces PR #3126 
In certain cases when invoker is overloaded it will reschedule activations in the container pool.
In order to prevent log message overflood we print out every 10 seconds and log additional information such as user namespace, action, retries count, etc.

 Throttle log messages when rescheduling containers (update) 

---

ansible/boot_instances_dist.yml
ansible/environments/distributed/group_vars/all
ansible/environments/docker-machine/group_vars/all
ansible/environments/local/group_vars/all
ansible/group_vars/all
ansible/provision_env_dist.yml
ansible/roles/cli/tasks/download_cli.yml
ansible/roles/couchdb/tasks/deploy.yml
ansible/setup.yml

Starting with Ansible 2.4 the `inventory_dir` variable is not available anymore
(see: https://docs.ansible.com/ansible/2.4/porting_guide_2.4.html#inventory)
This PR changes the Ansible scripts to use an variable defined on environment level instead 
This change is tested with Ansible 2.3 for backward compatibility

Use environment level defined directory if inventory_dir is not defined

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala

The error message returned by a failing container startup contains internal information (like the internally configured images, various exception messages). Returning a sanitized string is better design in general here.
All error cases are logged fine for operators to find the root-cause of the failing run.

Sanitize error message returned by a failed container startup.

---

common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala
common/scala/src/main/scala/whisk/core/entity/WhiskPackage.scala
common/scala/src/main/scala/whisk/core/entity/WhiskRule.scala
common/scala/src/main/scala/whisk/core/entity/WhiskTrigger.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/entity/test/MigrationEntities.scala
tests/src/test/scala/whisk/core/entity/test/WhiskEntityTests.scala

Adds a `type` property to the document json based on `entityType` method
This PR is second attempt for #3161. See the issue for more details. It adds a type property based onexplicitly defined `entityType` method value

Add type property to entity documents - Take 2

---

core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
tests/src/test/scala/limits/ThrottleTests.scala

Suggested fix for #3176.
The entitlement check for reference entities in sequences (https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/controller/Actions.scala#L382-L401) include checks against throttles (https://github.com/apache/incubator-openwhisk/blob/master/core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala#L221-L223) instead of simply checking for read/activate privileges. This result in the sequence being incorrectly accounted for twice (if non-empty).
This patch adds the ability to check privileges without impacting throttles and uses the new option for the checking referenced entities in sequences.
The added flexibility to the `Entitlement` `check` method is also necessary to correctly entitle action …

Avoid repeated throttle check for sequences

---

ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
common/scala/src/main/resources/application.conf
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/entity/Limits.scala
common/scala/src/main/scala/whisk/core/entity/MemoryLimit.scala
tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala

Some actions requires more than the current hard limit of 512MB of memory.
This PR makes memory limits (min / max / default) configurable per system deployment, via environment variables.

Make memory limits as config variables

---

common/scala/build.gradle
common/scala/src/main/resources/application.conf
common/scala/src/main/scala/whisk/core/entity/MemoryLimit.scala
common/scala/src/main/scala/whisk/core/entity/Size.scala

Some additions to @duynguyen's work (Thanks for doing this 🎉 )
TypesafeConfig supports size-in-bytes values (lightbend/config:HOCON.md@master#size-in-bytes-format). Instead of relying on our custom parsing code, this makes `ByteSize` compatible with the format specified by TypesafeConfig.
In addition it adds support for `ByteSize` to be directly deserialized by PureConfig, making for denser, more readable configuration parsing.

 Support size-in-bytes readings per PureConfig.

---

docs/actions.md

switching to bash for instructions on creating python zip with virtualenv
I got burned this week when using a customer docker runtime, because `sh` doesn't support `source` in debian jessie.
reading the generated script `virtualenv/bin/activate` it looks like is intended for bash

docs: Use bash instead of sh when building virtualenv

---

ansible/group_vars/all
ansible/roles/nginx/templates/nginx.conf.j2
common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/common/TransactionId.scala
common/scala/src/main/scala/whisk/http/BasicHttpService.scala
docs/logging.md
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala

This PR replaces PR #2990 (please see this PR for discussions and comments)
This will allow to change log level on per request/user basis for OW transactions.
If a specific header is provided in the http request to the controller, it will log messages on the debug level for that given transaction id.
@vvraskin 
regards, Vadim and Martin.

Change log level dynamically (updated)

---

ansible/group_vars/all
ansible/roles/kafka/tasks/deploy.yml
tests/src/test/resources/application.conf
tests/src/test/scala/services/KafkaConnectorTests.scala

So far, we had automatic topic creation - the broker would automatically create a topic if a producer sent a message to a topic or a consumer tried to receive messages from a topic. In that case, topic would be created automatically with default settings. These default settings are not always what we need. In the end, this is a race condition during deployment. If we manage to create a topic with desired settings before it gets auto-created with default settings, we are fine. Otherwise, we may see undesired effects.
This change disables automatic topic creation.

No automatic topic creation in Kafka

---

common/scala/src/main/resources/reference.conf
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancer.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
tests/src/test/scala/whisk/core/loadBalancer/test/ContainerPoolBalancerObjectTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala

Leveraging SpiLoader dynamic object loading adding capability to load LoadBalancer dynamically, based on a value specified in reference.conf. Similar to MessagingProvider, ArtifactStoreProvider...etc.
changes in code:
reference.conf: added LoadBalancerProvider
Controller: using SpiLoader to load LoadBalancer instance and its
requiredProperties
RestAPIs: use LoadBalancer trait instead of LoadBalancerService class
LoadBalancerService:
added LoadBalancerProvider trait implementing Spi
added allInvokers method to LoadBalancer trait

Dynamic LoadBalancer load using SpiLoader

---

ansible/roles/invoker/tasks/deploy.yml
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerArgsConfigTest.scala

also add "extra" container args to pureconfig
The main motivation here was to allow all action containers to some additional env vars (same value used for all containers). To get there, I moved network + dns args to pureconfig as well. 
There are still more container args that could be refactored, or it would be possible to move everything to the "extra-args" config.  These are left as an exercise for another time.

move network + dns container args to pureconfig

---

ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
ansible/roles/kafka/tasks/deploy.yml
common/scala/src/main/resources/application.conf
common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/entity/ActivationEntityLimit.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

The maximum payload allowed to flow through the system is hardcoded today. Several pieces (kafka for instance) need to be adjusted to allow a larger payload.
**Note:** After travis passes happily, the default can be reset to 1 MB to not change anything here.

Make payload limit configurable.

---

tests/src/test/scala/system/basic/WskBasicTests.scala
tests/src/test/scala/system/basic/WskRestRuleTests.scala
tests/src/test/scala/whisk/core/cli/test/WskRestEntitlementTests.scala

This rewrites the test cases in WskBasicTests by implementing them in REST interface.

Rewrite wsk basic tests

---

common/scala/src/main/scala/whisk/common/Scheduler.scala
common/scala/src/main/scala/whisk/common/TransactionId.scala
common/scala/src/main/scala/whisk/core/connector/MessageConsumer.scala
common/scala/src/main/scala/whisk/core/containerpool/Container.scala
common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala
core/controller/src/main/scala/whisk/core/controller/Authenticate.scala
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/controller/src/main/scala/whisk/core/controller/Packages.scala
core/controller/src/main/scala/whisk/core/controller/Rules.scala
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/PackageCollection.scala
core/controller/src/main/scala/whisk/core/entitlement/RateThrottler.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/RuncClient.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/common/SimpleExec.scala
tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala

This PR should provide a relief for controller while under load. We have reduced the number of log lines, which based on our performance measurements provides a 4x improvement on the throughput for long running tests and 2.5x throughput improvement for the short running tests. 
Here we also have made slight modification in the way log metrics are emitted. They could still be emitted in the following cases: 
* metricsLog is explicitely set to true
* the transaction timeout of 60 seconds is reached
* debug log level was selected
@mhenke1

Reduce the number of logs on info level

---

common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/common/TransactionId.scala

A lot of log messages are logged at debug level and use string interpolation. By moving the message into a closure, for debug level messages which are generally not logged, the interpolation is deferred and then eschewed.
Apply the same to other logging methods and transaction markers.

Move log message into a closure to defer string interpolation.

---

common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala

With enhanced kafka message sizes this debug message writes an enormous amount of data.
Since enough information is printed out in error cases, we can simply remove it.

Remove kafka related debug message

---

docs/annotations.md

the annotations were renamed to add a `Time` suffix.

Correct the names of two annotations.

---

build.gradle
common/scala/build.gradle
core/controller/build.gradle
core/invoker/build.gradle
tests/build.gradle

- Adds `maven` plugin to build.gradle files for common, controller and
invoker.
- Enables support for generating source jars
- Uses `org.apache.openwhisk` as groupId
- Uses `0.0.1-SNAPSHOT` as current version
PR for #3060

Add maven plugin to build.grade

---

common/scala/src/main/scala/whisk/core/entity/DocInfo.scala
common/scala/src/main/scala/whisk/core/entity/FullyQualifiedEntityName.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala

ArgNormalizer uses a try/catch pattern when parsing entity names. in two common cases, the arg to be normalized is known to be a string. we can fast-path this case. i called this `DocId.direct()`
the expense of this can be witnessed from call stack samples: you will see `fillInStackTrace` due to exceptions being thrown by spray's json parser.
preliminary experiments show that this results in more stable performance, i.e. with improvements principally to p99 latency numbers.
```
p25   p50   p75    p90    p99     max
master     20ms  23ms  28ms   40ms   270ms  1.7s
this PR    18ms  21ms  26ms   35ms   85ms   1.4s
```
test protocol: using wrk -t8 -c800; wipe.yml, then warmup 60s, then timed run 120s
endpoint: blocking invokes of echo action
deployment: environments/local, local couchdb, …

reduce fillInStackTrace expenses due to ArgNormalizer

---

ansible/roles/nginx/templates/nginx.conf.j2

Per nginx' documentation, using `proxy_set_header` on subsequent levels will override all the values from the previous level. This moves all of those directives to the same level.
The relevant bit here is that HTTP keepalive is broken due to the new header.
@mhenke1 @vvraskin could you please give this a glance?

Fix nginx' performance regression.

---

core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala

This piece of logic clutters the loadbalancer's code for no good reason. We should externalize it.
This will make a subsequent refactoring of the loadbalancer much easier to grasp and keep that future pull-request smaller (easier to review), hence the chunking.

Externalize InvokerPool initialization logic.

---

tests/src/test/scala/ha/ShootComponentsTests.scala

- Adjusts the value of allowed failures slightly.
- Corrects no longer valid comment.
- Uses the right value for limit calculation.

Make HA tests for controller more lenient.

---

common/scala/src/main/scala/whisk/core/connector/Message.scala

The parsing of `Either` relies on parsing failures in its generalized form. In this specialized case we can circumenvent this and parse only once, without throwing any forced error messages.
Fixes #3228
@starpit Want to have a look? I took the liberty to open the PR.

Efficiently parse CompletionMessage.

---

ansible/group_vars/all
ansible/roles/controller/tasks/clean.yml
ansible/roles/controller/tasks/deploy.yml

- Define variables for frequently referenced operations in controller role
- Move controller.jmxremote.jvmArgs to deploy.yml

Refactor controller role to use variables for hostname and host index

---

tests/src/test/scala/services/KafkaConnectorTests.scala

1. Reimplemented one of the Kafka tests to follow a more linear structure for readability.
2. Retry the sendAndReceiveMessage loops until the message just sent is part of the result.
This failed in a travis build on master.

Rewrite Kafka test and accomodate for eventual consistency.

---

tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala

This test forgot to remove a replication document after the test.
This PR fixes this.

Cleanup replication doc after testing replay of database.

---

core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala

Writing a large chunk of logs can take quite some time to process. The standard timeout for this process is 2 seconds today. It is bounded, because an action developer might break the action proxy to make sentinels not appear at all which would cause us to infinitely wait on sentinels.
As we process logs after an activation has run though, we can safely rely on the time **between** two logs not exceeding a certain threshold. That way, the complete processing is not bounded by some arbitrary timeout (which can even be too short for large volumes) and is still tight enough to exit early if sentinels really are missing.
Furthermore, an error line is inserted if this timeout hits to inform the user that something might've gone wrong.

Wait for logs based on intervals not based on total processing time.

---

common/scala/src/main/scala/whisk/core/entity/Exec.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala

This PR adds a binary, image, and main properties to a WhiskActionMetaData.
Values that should be shown in WhiskActionMetaData:
- string exec
- kind, binary, main
- attach exec
- kind, binary, main
- blackbox exec
- kind, image, binary, main
- sequence exec
- kind, components

Add binary, image, and main properties to WhiskActionMetaData

---

ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
common/scala/src/main/scala/whisk/common/ForcableSemaphore.scala
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/entitlement/RateThrottler.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancer.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
docs/deploy.md
tests/src/test/scala/limits/ThrottleTests.scala
tests/src/test/scala/whisk/common/ForcableSemaphoreTests.scala
tests/src/test/scala/whisk/core/controller/test/RateThrottleTests.scala
tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala

The current ContainerPoolBalancer suffers a couple of problems and bottlenecks:
1. **Inconsistent state:** The data-structures keeping the state for that loadbalancer are not thread-safely handled, meaning there can be queuing to some invokers even though there is free capacity on other invokers.
2. **Asynchronously shared state:** Sharing the state is needed for a high-available deployment of multiple controllers and for horizontal scale in those. Said state-sharing makes point 1 even worse and isn't anywhere fast enough to be able to efficiently schedule quick bursts.
3. **Bottlenecks:** Getting the state from the outside (like for the ActivationThrottle) is a very costly operation (at least in the sharedstate case) and actually bottlenecks the whole invocation path. Getting the current …

Add a loadbalancer with local state and horizontal invoker sharding.

---

common/scala/src/main/scala/whisk/core/entity/Parameter.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala

Mainly aims to reduce boilerplate in code which tries to extract non-primitive data from parameters/annotations. Any supported json-format (for example case classes) can be loaded safely from parameters.

Replace asString and asBool with generic method.

---

ansible/tasks/installOpenwhiskCatalog.yml

This parameter was originally used to optionally skip a package when there are two provided. We refactored this recently to instead use a better (more generic) solution of passing in environment variables for a catalog, which could be used for anything. PR #3144. This additional parameter can now be removed -- it's not set anywhere other than as a default value here, nor is it used anywhere.

Removing unused param

---

core/controller/src/main/resources/apiv1swagger.json
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
tests/src/test/scala/system/basic/WskBasicTests.scala
tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala

Augment existing GET trigger payload with a new field, `rules` that describes the trigger's matched rules and the rule status.
```
{
"namespace": "guest",
"name": "trig-with-inactive-rule",
"version": "0.0.1",
"limits": {},
"publish": false,
"rules": {
"guest/inactiverule": {
"action": {
"name": "web-echo-env",
"path": "guest"
},
"status": "inactive"
}
}
}
```
Fixes #3239

GET trigger now returns matched rules in JSON payload

---

tests/src/test/scala/whisk/core/containerpool/logging/LogDriverLogStoreTests.scala
tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationFileLogStoreTests.scala
tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala

The following test suites were not being run: SplunkLogStoreTests, LogDriverLogStoreTests, DockerToActivationLogStoreTests, DockerToActivationFileLogStoreTests.

Run container pool logging tests

---

core/controller/src/main/scala/whisk/core/controller/Rules.scala
tests/src/test/scala/system/basic/WskRuleTests.scala
tests/src/test/scala/whisk/core/controller/test/RulesApiTests.scala

Fixes two rule bugs:
1. Updating a rule with `wsk rule update` always returned a status of `active`.
2. After updating a rule with `wsk rule update` the status would be `inactive` when the rule is fetched with `wsk rule get`.
Closes https://github.com/apache/incubator-openwhisk/issues/1840

Preserve rule status when rule is updated

---

docs/actions.md
docs/parameters.md

(original ticket against IBM Cloud Functions docs: https://github.com/IBM-Bluemix-Docs/openwhisk/issues/19)
The parameters documentation was mostly under the "JavaScript" section, and the use of package parameters wasn't covered.  This moves the parameters documentation to its own page, links to it from each language section in the actions page, and adds some documentation for package parameters.
I've sent the ICLA through, but just now this moment so I won't be listed yet.

Move parameter docs to separate page, add package params docs

---

tests/src/test/scala/whisk/core/cli/test/Swift311Tests.scala

This test is prone to failure because of the expected test duration exceeds 45 seconds. The time limit instead should be based on the action's `timeout` property, which by default is 60 seconds. Also, don't count the time it takes to fetch the action's activation.
Test failure example:
`Test duration exceeds expectation (ms) 48629 was not less than or equal to 45000`

Remove expected duration from Swift test

---

ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
ansible/roles/nginx/templates/nginx.conf.j2
ansible/templates/whisk.properties.j2
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
tests/src/test/scala/limits/ThrottleTests.scala

If several controllers are specified, use always all of them.
This PR deprecates the availability of an hot standby controller.
PG3#1839 🔵 .

Use always all available controllers.

---

tests/src/test/scala/common/WskTestHelpers.scala
tests/src/test/scala/whisk/core/cli/test/Swift311Tests.scala

- This test is prone to errors because compiling swift apparently is subject to a lot variance (seen up to 1 minute).
- Refactor of some test helpers.

Bump swift test-timeout to 2 minutes.

---

tests/build.gradle

Currently the `createKeystore` in tests is linked with `compileTestScala`. This poses problem in cases where the build is triggered with test execution disabled.
```
Execution failed for task ':tests:createKeystore'.
> java.io.FileNotFoundException: /path/to/openwhisk/whisk.properties (No such file or directory)
```
This would be the case for example where core is build just to install the test artifacts to Maven repository and where whisk.properties is yet not generated. (see apache/incubator-openwhisk-runtime-docker#17)
This PR disables this task if `test` is disabled

Disable createKeystore if test execution is disabled

---

common/scala/src/main/scala/whisk/core/database/ArtifactStoreProvider.scala
common/scala/src/main/scala/whisk/core/database/CouchDbStoreProvider.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala

For implementing custom `ArtifactStore` and computing views on client side for databases other than CouchDB the `ArtifactStore` would need access to the entity type. 
The logic in custom ArtifactStoreProvider would be similar to one present [here][1] just that this PR uses `ClassTag` instead of `Manifest` as [Manifest are now deprecated post Scala 2.10][2]
To enable that `ArtifactStoreProvider` should have an implicit parameter for `ClassTag`
[1]: https://github.com/apache/incubator-openwhisk/commit/9be13e2c6d581f42b60351f05a11e4aa71ca31d9#diff-9399daa47aa3257bb6bcb49425f4389dR110
[2]: https://docs.scala-lang.org/overviews/reflection/typetags-manifests.html#typetags-and-manifests

Add implicit ClassTag for entity type

---

common/scala/src/main/scala/whisk/common/Logging.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala

We introduced some very finely granulated metrics.
On using a commonly used monitoring backend, it can be easily overloaded with a huge amount of users and different actions on the OpenWhisk system.

Remove finely granulated metrics.

---

ansible/environments/local/group_vars/all

`runc` fails on docker-for-mac; use docker pause/resume instead.

For MacOSX using docker-for-mac, do not use runc.

---

tools/db/README.md
tools/db/moveCodeToAttachment.py

Updates actions in database to move code from being inlined in the document to an attachment. The associated code for Java actions are already attachments. These changes Base64 encode Java attachments. In addition, the old exec.jar field is removed from Java actions.
Depends on https://github.com/apache/incubator-openwhisk/pull/2847

Convert inline code to attachment in database

---

build.gradle

The releases can be still be done to lower version but post release the next snapshot version should always be 1.0.0-SNAPSHOT.
This allows other repositories which run tests against runtime based on current master to be pinned to 1.0.0-SNAPSHOT and would not require any change if release has been made from master result in increase of version number for released artifacts

Switch snapshot version to 1.0.0-SNAPSHOT

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/resources/apiv1swagger.json
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
tests/src/test/scala/system/basic/WskBasicTests.scala
tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala

- log trigger activation entry for disabled rules (but at least one active rule is needed to create a trigger activation record)
- if trigger has no associated active rule(s); return a 204.  also no trigger activation record is created
Closes #3304.

Handle trigger activations with inactive rules

---

tests/src/test/scala/common/WskTestHelpers.scala

A former rework of the AssetCleaner has changed the return type of the asset Cleaner. This PR adds it again.
PG5#110 is running.

Let the AssetCleaner return the result of the test.

---

common/scala/src/main/scala/whisk/core/entity/FullyQualifiedEntityName.scala
common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
docs/conductors.md
tests/src/test/scala/system/basic/WskBasicNode6Tests.scala
tests/src/test/scala/system/basic/WskConductorTests.scala
tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala

I updated the document for conductor actions to specify that the action name for a continuation should be a fully qualified name. I however also added a conversion from string to a FQN with sensible defaults. This makes for slightly more convenient return results and avoids potentially confusing error messages when referencing a packages action but neglecting to specify the namespace. We have in the past resisted doing this and required the clients to resolve the names fully. 
@tardieu can you review and comment?

Attempt to resolve action name from conductor to a fully qualified name for added convenience.

---

tests/src/test/scala/common/WskTestHelpers.scala
tests/src/test/scala/system/basic/WskRuleTests.scala
tests/src/test/scala/system/basic/WskSequenceTests.scala

Relying on views is brittle and will fail if the database is under high load. We don't need to rely on those anymore.

Rework rule tests to not rely on views anymore.

---

common/scala/src/main/scala/whisk/common/TransactionId.scala
core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala

When logging only a metric, skip the message unless the log level is enabled.
Lowered log level on two messages.
Add log message for compositions.
@vvraskin can you review?
pg3/1873 🏃

Remove two log messages, tweak logging with metrics, add log message for conductors

---

tests/src/test/scala/whisk/core/entity/test/ViewTests.scala

- currently the ViewTests suite is using two similar views inside a single test.  sometimes the two views (whiskActivation.view, hiskActivation.filtersView) become out of in-sync (db delays) resulting in a test failure.  the fix is to consolidate the test to use just one view.

Fix view mismatch in test

---

core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
tests/src/test/scala/whisk/core/loadBalancer/test/ContainerPoolBalancerObjectTests.scala

When all invokers's load is saturated, the lb will chose the head invoker
to execute the remaining action only, so it is necessary to make sure all
invokers have equal opportunity to exectue actions even if all invoker's
load is saturated.

improve loadbalancer's schedule algorithm

---

common/scala/build.gradle
common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/invoker/Dockerfile
core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala

We've had this working in a fork for a few months now, but have held off submitting due to performance limits imposed by our inability to `suspend/resume` containers like the Docker provider. However, @dgrove-oss has some ideas around this and asked us to go ahead and open the PR.
One other limitation is that the k8s API doesn't distinguish between `stdout` and `stderr` for logged messages. So in our impl, all messages (even those sent to `stderr`) appear to go to `stdout`. See https://github.com/kubernetes/kubernetes/issues/28167
I squashed a bunch of commits for this but wanted to maintain a bit of history for posterity. If you'd prefer a single commit, that's cool, too.

Kubernetes ContainerFactoryProvider implementation

---

tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala

When getting a package including actions a view is invoked. We need to wait on that view to make the test resilient against intermittent failures.

Make package test resilient against eventual consistency.

---

tools/build/redo

Set up a '-e' flag to `redo` for ansible arguments and limit '-a' flag to gradle arguments so './redo deploy' can accept both.

Add '-e' to redo for ansible variables and change '-a' to gradle arguments only.

---

build.gradle
tools/build/README.md

PR for #3312. With this the scan result would only be published on CI setups
However with this change now following warning is seen
```
WARNING: The build scan plugin was applied after other plugins.
The captured data is more comprehensive when the build scan plugin is applied first.
Please see https://gradle.com/scans/help/plugin-late-apply for how to resolve this problem.
```
From changes done in this PR its ensured that this plugin comes first but still the warning is seen. For now it appears a [bug in gradle](gradle/gradle#3341) which was fixed in 4.3 (we use 4.1). I tried with current 4.5 and warning disappears.
@markusthoemmes Not sure sure if changes here affect down stream projects (like the issue seen with coverage pr)
Apart from the noisy warning things work fine

Configure Gradle build scan plugin

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

Proposed fix for https://github.com/apache/incubator-openwhisk/issues/3321.
I partially confirmed the reported issue. The code and previous test confirms a missing body is an instance of JsObject, not JsArray. I'm not sure yet where the JsArray comes from; it may be PHP actions specific. A node test shows the type is not an array.
@akrabat FYI for node and python below.

Normalize a missing body for raw actions to JsString.empty.

---

common/scala/src/main/scala/whisk/core/entity/Parameter.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala

Web actions can carry a final annotation which makes their parameters with predefined values immutable. This patch makes the same behavior applicable for a POST invoke as well.
The relevant change is the third commit. The first two, staged this way, introduce semantic preserving changes and a new test. Suggest https://github.com/apache/incubator-openwhisk/pull/3333/files?w=1

Make parameters with defined values final 

---

core/controller/src/main/scala/whisk/core/controller/Triggers.scala
tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala

Feedback solicited.
Since a feed is already handled entirely on the client side today, should we just remove the restriction on the backend entirely?
Note the existing code is buggy - you can update an existing trigger with an attached feed, and de-associate it from the feed by specifying a new annotation. Further, if there's no feed attached, why prohibit an update that attaches a feed?
So either we should tighten the backend check, or remove it entirely, since clients like the CLI currently handle feed differently and route some API calls directly to the feed vs the controller. See https://github.com/apache/incubator-openwhisk-cli/issues/225 for example.
Closes https://github.com/apache/incubator-openwhisk/issues/3297

Remove restriction on updating a trigger with a new feed.

---

ansible/callbacks/logformatter.py

Here is a sample output:
```
TASK [cli : download cli (linux) amd64 to Nginx directory] *****************************************************************************************************************************************************************
Sunday 25 February 2018  10:38:38 -0500 (0:00:00.228)       0:00:08.284 ******* 
fatal: [172.17.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: …
```

Extract message from callback and add it to pretty printed text.

---

ansible/group_vars/all
ansible/roles/cli/tasks/copy_local_openwhisk_cli.yml
ansible/roles/cli/tasks/deploy.yml
tools/build/redo

Changes to ansible build so that it will work appropriately for local CLI build.  Assumption is 'incubator-openwhisk-cli' is in the same directory as 'incubator-openwhisk'.  Also added environment variable `OPENWHISK_CLI_MODE` which will be checked if `cli_installation_mode` is not explicitly set for ansible.
Changes to travis will follow; keeping the two areas separate for now.
First of two fixes for #3329 
P.S.  Sorry about the extra commits.  I appear to have gotten sloppy with my branches -- please squash when merging.

Cli ansible fix

---

common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
common/scala/src/main/scala/whisk/core/entity/InstanceId.scala
core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

This is to enable a deployment case where we briefly want to allow an invoker to run local to another running invoker; To enable this, the "cleanup" should not kill the action containers created by the previously existing invoker. As long as each invoker has a different prefix, they won't destroy each other's containers at startup.

adding namePrefix config to ContainerArgsConfig

---

common/scala/src/main/scala/whisk/core/database/CloudantRestClient.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
common/scala/src/main/scala/whisk/http/PoolingRestClient.scala
common/scala/src/main/scala/whisk/http/RestClient.scala
tests/src/test/scala/whisk/core/database/test/ExtendedCouchDbRestClient.scala

Moves the REST client from CouchDbRestClient to its own class that can be reused by other classes that need a generic REST client.

Generic Pooling REST Client

---

ansible/README.md
tests/src/test/scala/actionContainers/ActionContainer.scala
tests/src/test/scala/actionContainers/DockerExampleContainerTests.scala

Running container unit tests on docker-for-mac does not work because the 172. network is not reachable. Instead detect "local" mode and use port forwarding instead.
@akrabat FYI.

Allow container tests to run without a proxy.

---

tests/build.gradle

Some of our important tests do **not** run today because the exclude of "*Cli*" also covers "Client" tests, which is not suspected.
For posterity, this impacts:
```
tests/src/test/scala/whisk/core/database/test/CouchDbRestClientTests.scala
tests/src/test/scala/whisk/core/database/test/ExtendedCouchDbRestClient.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/RuncClientTests.scala
tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
```

Narrow exclude to run needed tests.

---

common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala

Use internal kafka consumer metrics to monitor kafka queue for a particular topic.
@markusthoemmes

Monitor kafka queue for all consumers

---

tests/src/test/scala/actionContainers/DockerExampleContainerTests.scala

This test fails in different environments with different exceptions. This commit only aims to resolve the immediate issue. A proper RCA for test-hardening will need to be conducted.

Soften DockerExampleContainerTests.

---

ansible/roles/cli/tasks/copy_local_openwhisk_cli.yml

The updates to the copy of the 'wsk' or 'wsk.exe' executable from the Nginx downloads to the $OPENWHISK_HOME/bin directory did not set the mode to executable for that binary.  This PR changes that behavior.
This is in support of #3329

Set mode of wsk to executable

---

common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala

replace(String, String) and replaceAll(String, String) will compile regex patterns implicitly. This creates a lot of unnecessary garbage.

Remove usages of replace and replaceAll on the hotpath.

---

core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala

We can implement suspend and resume for KubernetesContainerPool by delegating the operations to an invoker-agent that runs as a DaemonSet on every invoker node.  The invoker-agent interacts with the local docker/containerd engine to pause/unpause containers as directed by the invoker.
This PR contains the OpenWhisk core changes to implement this design.  It assumes an invoker-agent as implemented in https://github.com/apache/incubator-openwhisk-deploy-kube/pull/155.  The main changes in this PR are:
1.  Add configuration for the invoker-agent to application.conf (default to disabled).
2. Implement suspend/resume by delegating to the invoker-agent
3. Change the implementation of container creation to use the kubeRestClient to create the containers instead of using the kubectl command line. …

implement suspend/resume for KubernetesContainer

---

tests/src/test/scala/common/WskTestHelpers.scala
tests/src/test/scala/limits/ThrottleTests.scala

This test suite will fail if the subjects are not properly deleted in a previous run. Attempts to wipe the subjects before running the suite to compensate for past failures.
Closes https://github.com/apache/incubator-openwhisk/issues/3136.

Sanitize test subjects before tests.

---

ansible/roles/controller/tasks/deploy.yml
ansible/roles/invoker/tasks/deploy.yml
common/scala/src/main/resources/application.conf
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/entity/TimeLimit.scala

In the same vain the memory limits are settable, this should be decidable per deployment.

Make action-time-limit's system bounds configurable.

---

tests/src/test/scala/whisk/core/admin/WskAdminTests.scala
tools/admin/wskadmin

This patch allows wskadmin to block or unblock a list of subjects, separated by a comma (which is not a valid token for subject names). The first commit is a semantic preserving change. The second commit adds:
```
+    for subject in args.subject.split(","):
+        subject = subject.strip()
+        if len(subject) > 0:
```
around the existing code: https://github.com/apache/incubator-openwhisk/pull/3348/files?w=1

Allow wskadmin user block/unblock to accept a list of subject to block

---

core/controller/Dockerfile
core/invoker/Dockerfile

This PR has two changes
Currently 
* controller - The tar file is copied but not removed thus increasing the size
* invoker - Copies the tar and then removes it after untarring it
Instead of doing this use ADD command which has an implicit support for untar. See [ADD vs COPY][1]
> Consequently, the best use for ADD is local tar file auto-extraction into the image, as in ADD rootfs.tar.xz /.
With this change size of controller images drops to 281MB from 361MB (~80MB reduction)
```diff
-CMD ["init.sh", "0"]
+CMD ["./init.sh", "0"]
``` 
When I am extending the controller image for building a custom image for embedding custom ArtifactStore
```
FROM whisk/controller
COPY build/docker /controller/
```
The startup failed with
```
docker: Error response from daemon: oci runtime error: …
```

Use Docker ADD command to untar

---

common/scala/src/main/resources/application.conf

We commit manually everywhere in our code. Some tests also rely on the manual commits to be the only ones around. We should be able to turn this off safely. If not we have a bug.

Turn off Kafka auto-commits.

---

common/scala/src/main/scala/whisk/core/entity/AuthKey.scala
common/scala/src/main/scala/whisk/core/entity/Secret.scala
common/scala/src/main/scala/whisk/core/entity/UUID.scala
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala

Like in the case of ActivationIds, for AuthKeys we do not care if the user really gives us a UUID. For the system internal it doesn't matter.

Make AuthKey parsing leaner.

---

ansible/roles/cli/tasks/deploy.yml

This PR fixes the deployment of the CLI if the edge is not on the same machine like the ansible-host.
This PR fixes the deployment of the CLI if the edge is not on the same machine like the ansible-host.

Fix deployment of the CLI if edge is on a remote machine.

---

ansible/files/namespace_throttlings_design_document_for_subjects_db.json
ansible/roles/invoker/tasks/deploy.yml
ansible/tasks/initdb.yml
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
core/invoker/src/main/scala/whisk/core/invoker/NamespaceBlacklist.scala
tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala

This commit adds a check to the invoker, if the current namespace is allowed to execute actions.
This check is already done in the controller, but if the action is already in the queue and throttled afterwards, there is no chance to get this action out of the queue.
With this commit, the invoker checks as well if the action is allowed to be executed. If it is not, it will be refused immediately. This will clean up the queue very fast.

Add namespace-blacklist to invoker.

---

core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala

Making this configurable -- and defaulting to something that may not
be the ns in which the invoker is running -- is more trouble than it's
worth, I think.

Remove namespace configuration; use invoker's instead

---

tests/src/test/scala/whisk/core/database/test/CleanUpWhisksDbSkriptTests.scala
tools/db/cleanUpWhisks.py

Python script for cleanup that runs over all documents in the whisks database and checks if its namespace  still exists. The document will be marked for deletion or deleted if already marked for certain period of time if its namespace does not exists.

Cleanup script for unused entities in the whisks database.

---

core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClientWithInvokerAgent.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesInvokerAgentLogStore.scala
tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala

1. refactor KubernetesClient to move invokerAgent into a subclass to get a better separation of concerns. 
2. add an implementation of a forwarding LogStoreProvider for Kubernetes that uses the invokerAgent to remotely extract the user action logs and enrich them with additional per-activation metadata to prepare them for ingestion by a logging service. Logs are never processed by the invoker; all processing is remote.

refactor KubernetesClient to separate invokerAgent; add forwarding LogStoreProvider

---

.gitignore
ansible/group_vars/all
ansible/roles/controller/tasks/deploy.yml
ansible/roles/nginx/tasks/deploy.yml
ansible/roles/nginx/templates/nginx.conf.j2
ansible/setup.yml
ansible/templates/whisk.properties.j2
common/scala/src/main/scala/whisk/common/Https.scala
common/scala/src/main/scala/whisk/http/BasicHttpService.scala
core/controller/src/main/resources/application.conf
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/resources/application.conf.j2
tests/src/test/scala/common/rest/WskRest.scala
tests/src/test/scala/ha/CacheInvalidationTests.scala
tests/src/test/scala/ha/ShootComponentsTests.scala
tests/src/test/scala/services/HeadersTests.scala
tools/travis/setup.sh

This PR will enable SSL between nginx and controllers. A couple of things that must be considered: 
* certs for local and docker-machine environments are self-signed
* certs are regenerated during OW deployment
* the default protocol will be https
@mhenke1

Enable ssl on the path between edge and controllers

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
core/invoker/src/main/scala/whisk/core/invoker/NamespaceBlacklist.scala

We need to send an active-ack in every case a message is parseable. Otherwise the loadbalancer data will not reflect what's actually happening.
~~- [ ] I opened an issue to propose and discuss this change (#????)~~
~~- [ ] I added tests to cover my changes.~~
~~- [ ] My changes require further changes to the documentation.~~
~~- [ ] I updated the documentation where necessary.~~

Send active-ack in any case of a parseable message.

---

ansible/README.md
ansible/roles/cli/tasks/deploy.yml
tools/macos/README.md
tools/macos/docker-machine/README.md
tools/ubuntu-setup/ansible.sh

Bump ansible version in the documentation and vagrant setup.
Apart from that I have adapted the cli deploy step in ansible to use unzip instead of unarchive module, due to some issues on MacOS, e.g. https://github.com/ansible/ansible-modules-core/issues/3631
- [x ] Deployment
- [x ] Documentation

Bump ansible version

---

ansible/group_vars/all
core/routemgmt/common/apigw-utils.js
core/routemgmt/createApi/createApi.js

In support of creating APIs with secured (`require-whisk-auth` annotation with number or string) web-actions
- swagger update causes `X-Require-Whisk-Auth` header injection during action invocation
- use apigateway to v0.9.10 that handles `X-Require-Whisk-Auth header injection
- local testing with v0.9.10 apigateway

swagger generation update

---

core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala

- Fixed an issue where empty results from K8S log HTTP could cause a downstream error propagation
- Moved the last entry timestamp update up before the CompleteAfterOccurrences stage.
When it was below, it meant that we never saw the activation marker Lines
missing the marker lines meant the last timestamp we saved was only from
valid logging, and we kept refetching the past activation lines
- On occasions Kubernetes didn't have invoker logs ready at request, it
would simply stop; fixed code to retry. However, there's no pause If no results
come back from Kubernetes, retry until they do.
Switched K8S Logging Graph Stage to a Timer based one.
- With this, added a retry scheduler to delay 100 ms when the logs come back empty.
- I opened an issue, #3439, describing the problem.

Fixes Kubernetes logging issues from #3439 re: activation logs where timestamp errors caused logging failures

---

ansible/files/genssl.sh
ansible/setup.yml

For some use cases it might be helpful to use pre-generated certs for controller keystore. 
Thus skip ssl key/cert generation step and use pre-defined values in the form:
controller-openwhisk-server-cert.pem
controller-openwhisk-server-key.pem
- [x ] Controller
- [x ] Deployment

Generate keystore without generating certificates

---

tests/src/test/resources/application.conf.j2

application.conf will fail when an invalid formed password is passed
- [x ] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [ x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).

Add quotes to avoid parsing errors of application.conf

---

ansible/README.md

Update the outdated default value of limits. Also, remove the unused
section of environment/mac/group_vars/all, the detailed description in each feild is now pointed to the
default group vars.

Fix outdated `limit section` in ansible doc

---

tests/src/test/scala/common/BaseWsk.scala
tests/src/test/scala/common/Wsk.scala
tests/src/test/scala/common/rest/WskRest.scala

Test framework preparation to support a new CLI option, --web-secure, that will be used
to manage the require-whisk-auth annotation for web actions.
- related openwhisk PR https://github.com/apache/incubator-openwhisk/pull/3388
- related openwhisk cli PR https://github.com/apache/incubator-openwhisk-cli/pull/244

wsk test framework update to support --web-secure cli option

---

ansible/roles/couchdb/tasks/deploy.yml

Add a step to the 'ansible/roles/couchdb/deploy.yml' playbook that will create a `_users` database when the couchdb is set up as a singleton instance and the version is 2.0+.  As of version 2.0, the `_users` database is no longer created automatically.  When it does not exist, an error messge is periodically emitted, which in turn creates noise in the log file.

Create '_users' database for singleton ephemeral couchdb v 2+

---

common/scala/src/main/scala/whisk/common/Logging.scala
core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala

1. `padTo` (used when generating the list of semaphores for all invokers) does not recompute the value each time it adds an element to the underlying list. That resulted in **all** invokers-state being backed by the same Semaphore and thus not doing anything properly really.
2. The stepsizes need to be calculated for the list of invokers they are used to step to. Therefore we need a seperate list of step-sizes for the managed and the blackbox invoker list.
3. The assumption should be, that we freed our resources (and thus updated the state) **before** we return the request to the user. A minor change in code order is warranted here.
4. In the overload case we need to take the index we want to schedule to out of the `healthyInvokers` list, rather than using the `random` value directly. The …

Fix several loadbalancer bugs.

---

tests/src/test/scala/whisk/core/admin/WskAdminTests.scala

Fix up testsuite `block and unblock a user respectively` fails when
`testspace` contains pre-existing users.
The change clean up **all** users under namespace `testspace`, `testspace1` and `testspace2`.
To reproduce this, create a pre-existed user under `testspace`.
```bash
./bin/wskadmin user create test-123 -ns testspace
```
The test should be passed now.
Sorry for creating pr twice, I forgot to reopen previous pr #3469  and force push to squash the redundant commit. 
Refer to #3469 , seems like the test can be passed after trying couple times. 
No idea how's going on travis uncertainly got failed.

Ensure clean up testspace under wskadmin test.

---

tests/src/test/scala/whisk/core/cli/test/WskEntitlementTests.scala

It provides a fix for test failure on mainWhisk/8244. 
Given current round robin load balancing for controllers and cache invalidation, a race condition might occur for the mentioned test. For example, a trigger for a broken feed was deleted on one controller, but cache invalidation didn't yet make it and we already check for 404 response code.

Retry in feed tests to avoid race condition

---

.gitignore
tools/dev/README.md
tools/dev/build.gradle
tools/dev/src/main/groovy/intellijRunConfig.groovy

Script which generates the run configuration for Controller and Invoker to enable launching them from within IDE. This allows faster development and debugging as time spent in rebuilding and restarting docker containers can be avoided
The script can be run via below command (requires OpenWhisk running)
./gradlew -p tools/dev intellij
The script also supports customizing the generated config with local overrides via custom config file (see README.md for details)
For now using this script Controller can be launched from within the IDE. Invoker posses some [problem](apache/incubator-openwhisk#3195)

Script to generate IntelliJ Run Configuration for Controller and Invoker

---

core/controller/src/main/scala/whisk/core/controller/WebActions.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

Add an additional option to parse status code from string to int, throws
out illegal code if parsing failed. Also, add a relevant test code.
Refer to #2971, changes support status code written in string from an action.

Support string based status code from actions.

---

ansible/group_vars/all
ansible/roles/kafka/tasks/deploy.yml

Increasing the number of network threads in kafka solves the performance bottleneck on some deployments where the number of invokers is high. 
If one deploys kafka with the default value of network threads (3), it would have only a couple of CPU that are fully utilized amid others that are idling, which could reduce the throughput for blocking and non-blocking invocations, it could setback even more dramatically if encryption is enabled.

Configure the number of network threads in kafka

---

core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala

This PR adds the ability to configure, if a controller should join the the akka cluster or not.
This cluster is necessary to detect if other controllers are joining or crashing.
PG2#2942 is 🔵 .

Only join cluster if seed nodes are provided.

---

core/controller/src/main/resources/application.conf
core/controller/src/main/resources/reference.conf

Fixes #3482 by moving the config to reference.conf such that it can be overridden in application.conf in test in deterministic way. See issue for more details. With this change PR #3249 can become green again

Move controller config to reference.conf

---

common/scala/src/main/scala/whisk/core/entity/DocInfo.scala

Some normal results of API `_bulk_docs` can not be deserialization to BulkEntityResult
some items in the return jsArray of `_bulk_docs` may not contain filed `rev`, this lead to a spray json error

wrap filed rev of BulkEntityResult using Option

---

common/scala/src/main/scala/whisk/core/WhiskConfig.scala
core/invoker/src/main/resources/application.conf
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala

Previously, the `idleTimeout` and `pauseGrace` settings for `ContainerProxy` have hardcoded defaults. This code changes to use pureconfig entries, allowing the defaults to be changed in configuration.
Tests have been added to the `ContainerProxyTests` to verify the changes (and config parsing).

Fixes #3470 - Changed hardcoded timeouts for idle containers and pause grace to config entries

---

ansible/group_vars/all
ansible/roles/apigateway/tasks/deploy.yml
ansible/roles/couchdb/tasks/deploy.yml
ansible/roles/kafka/tasks/deploy.yml

This is an incremental implementation of #3133 to reduce risk and complexity as we implement multi-architecture OpenWhisk.  This PR includes these changes:
- Add the ability to override image names to the ansible playbooks -- in support of overrides of images for multi-platform deployments.
- Bump Nginx version to 1.12 -- latest stable version, available as a multi-platform manifest from DockerHub (current Nginx 1.11 is not).
- Move responsiblity for docker pull to the docker module, reducing ansible steps and complexity -- improved maintainability.

Ansible image name overrides and bump NGinx to 1.12

---

ansible/files/genssl.sh

Generating certificates will fail if spaces are in arguments passed to openssl commands.

Allow spaces when generating keystore and certificates

---

.travis.yml
performance/README.md
performance/gatling_tests/build.gradle
performance/gatling_tests/src/gatling/resources/conf/logback.xml
performance/gatling_tests/src/gatling/resources/data/nodeJSAction.js
performance/gatling_tests/src/gatling/scala/ApiV1Simulation.scala
performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskActionBuilder.scala
performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskDsl.scala
performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskProtocolBuilder.scala
performance/gatling_tests/src/gatling/scala/extension/whisk/Predef.scala
performance/preparation/deploy.sh
settings.gradle

This PR adds a gatling test suite with a wrapper to easily create new gatling tests.
In addition I added a first test, which tests the throughput of the endpoint `api/v1`. With this test it would be possible to catch regressions that are caused by some wrong configuration in nginx, like we had in the past.
This PR will replace #3427.

Add gatling as performance test suite.

---

actionRuntimes/nodejs6Action/Dockerfile
actionRuntimes/nodejs8Action/Dockerfile
docs/reference.md

bump nodejs6 from 6.14.0 -> 6.14.1, nodejs8 from 8.11.0 -> 8.11.1
Bumping the nodejs version for both NodeJs 6 and NodeJS 8 runtimes, 
NodeJS 6 is moving from 6.14.0 to 6.14.1
NodeJS 8 is moving from 8.11.0 -> 8.11.1

bump nodejs6 from 6.14.0 -> 6.14.1, nodejs8 from 8.11.0 -> 8.11.1

---

tests/src/test/scala/actionContainers/ActionContainer.scala

On very busy machines, creating a container can take quite long. For the sake of testing, its of no use to fail the test on a relatively tight timeout. Bumping this to 60 seconds should not harm the tests significance.

 Bump timeout for creating a container to 60 seconds in tests.

---

LICENSE.txt
licenses/LICENSE-akka.txt
licenses/LICENSE-akkaalpakka.txt
licenses/LICENSE-akkahttp.txt
licenses/LICENSE-apachecommonscodec.txt
licenses/LICENSE-apachecommonscollections.txt
licenses/LICENSE-apachecommonsio.txt
licenses/LICENSE-apachehttpcomponentsclient.txt
licenses/LICENSE-caffeine.txt
licenses/LICENSE-curatorrecipes.txt
licenses/LICENSE-javauuidgenerator.txt
licenses/LICENSE-jsr305.txt
licenses/LICENSE-kamoncore.txt
licenses/LICENSE-kamonstatsd.txt
licenses/LICENSE-kubernetesclient.txt
licenses/LICENSE-logbackclassic.txt
licenses/LICENSE-mesosactor.txt
licenses/LICENSE-pureconfig.txt
licenses/LICENSE-scala.txt
licenses/LICENSE-slf4j.txt
licenses/LICENSE-sprayjson.txt
licenses/LICENSE-zookeeper.txt

This PR includes all the dependencies as they are found in all the
build.gradle files, except for the ones under tests and
performace/gatling_tests.
Partially-closes: apache/incubator-openwhisk-release#109

Add the licenses of the dependencies into LICENSE

---

common/scala/src/main/resources/application.conf
common/scala/src/main/scala/whisk/core/WhiskConfig.scala
common/scala/src/main/scala/whisk/core/entity/Limits.scala
common/scala/src/main/scala/whisk/core/entity/LogLimit.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala

Enables the per-action log-limit configuration to be read from config (min/max/std values respectively). It also skips the entire log-collecting process if that limit is set to 0 (no logs allowed).

Skip log collection if the log-limit is set to "0".

---

tests/src/test/scala/system/basic/WskActivationTests.scala

There are SPIs in active development which exchange the backend of the "activation logs" call. This backend is not necessarily consistent with the activations database itself, hence the test needs to poll "activation logs" for a set amount of time.

Bump timeout of activation logs test.

---

tests/src/test/scala/whisk/core/database/test/DbUtils.scala
tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala

The view based retry logic is a bit deep and overloaded. To bump the retries and make all those tests more stable this bumps the general retry count for all those tests.

Bump retries for view based tests.

---

common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala

Kafka's clients rely on Properties for passing the configuration in. That's cumbersome to use in Scala so it's pushed to a central method now.
Also using the implicit JavaConversions is discouraged (as it can be quite surprising). Exchanged that with the explicit JavaConverters.

Refactor Kafka clients for more generalized configuration reading.

---

build.gradle
common/scala/build.gradle
core/controller/build.gradle
core/invoker/build.gradle
settings.gradle
tests/build.gradle
tools/travis/build.sh

Adds scoverage plugin to instrument and collect coverage data. Also configures a `aggregateCoverage` task to generate a combined report
This PR enables collections of coverage data for tests run in vm and do not hit controller or invoker dockers containers.
You can see the coverage stats at [codecov][1] for my fork. With just the lean set (used for travis ci) we get a coverage of ~ 72%. The build time for test phase increased by ~ 2 min (27m 17s to 29m 23s)
Codecov integration can be enabled with simple change in `build.sh` for travis.
```diff
diff --git a/tools/travis/build.sh b/tools/travis/build.sh
index 4870acb72a..fdd77b7c67 100755
--- a/tools/travis/build.sh
+++ b/tools/travis/build.sh
@@ -40,10 +40,12 @@ $ANSIBLE_CMD openwhisk.yml
cd $ROOTDIR
cat whisk.properties
-TERM=dumb …
```

#3243 - Use gradle scoverage to collect test coverage stats

---

ansible/roles/routemgmt/tasks/deploy.yml
ansible/tasks/installOpenwhiskCatalog.yml

Update API GW and Catalog package deployment ansible tasks to use `whisk_api_host_name` before defaulting to the `['edge']` host
Maintain consistency with other deployment scripts (i.e. nginx) that leverage `whisk_api_host_name`

use whisk_api_host_name as part of api host ansible selection

---

tests/src/test/scala/whisk/core/database/test/CacheConcurrencyTests.scala

Variable `scriptPath` is not used and the fixture `CacheConcurrencyTests.sh` does not exist.

Remove unused variable from cache concurrency tests

---

tools/travis/build.sh

All .md and .sh files are now updated to conform to ASF license/policies as of merge of PR [3598](https://github.com/apache/incubator-openwhisk/pull/3598).  This PR will point to the latest .cfg  that enforces .md and .sh checking.
Now that
- [ x] General tooling
- [ x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).

Update build to use latest scancode .cfg for .md and .sh

---

core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala

The overcommit of limits needs to be relative to the actual size of the cluster to appropriately scale those limits.

Make limit overcommit relative to the actual cluster size.

---

ansible/group_vars/all
ansible/roles/kafka/tasks/deploy.yml

At the moment we use the default setting for Kafka SSL which allows all cipher suites available on JVM. 
With this change we restrict it to only 6 of them which were derived as a join of these two lists:
*  supported suites on jvm8
* recommended ciphers from https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices
Actually the list originally included 9 items, I have excluded the DHE based ciphers, since by default they allow 1024 bit keys, which is a potential attack vector for the MITM attack. (https://weakdh.org/)

Limit cipher suites used for Kafka SSL

---

actionRuntimes/nodejs6Action/Dockerfile
actionRuntimes/nodejs8Action/Dockerfile
docs/reference.md

This PR bumps the NodejS runtimes versions level to bring in the latest updates to that runtime. 
NodeJS6 is bumped from `1.8.1` to `1.9.0`
NodeJS8 is bumped from `1.5.1` to `1.6.0`
The main change is an update to the packages to bring in the latest version of the "openwhisk" NPM package, which will be at v3.15.0
A diff of these changes can be found below:
NodeJS6/NodeJS8 changes comparison: https://github.com/apache/incubator-openwhisk-runtime-nodejs/compare/8@1.5.1...8@1.6.0

bump nodejs6 1.8.1 -> 1.9.0, bump nodejs8 1.5.1 -> 1.6.0

---

common/scala/src/main/scala/whisk/http/LenientSprayJsonSupport.scala
core/controller/src/main/scala/whisk/core/controller/WebActions.scala
tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala

WebActions support various different input formats (like FormData). Only allowing `application/json` to be parsed and handled as JSON is an unnecessary limitation since there are many "+json" custom formats out there which boil down to JSON as well.

Support "+json" content-types as WebAction input.

---

common/scala/src/main/scala/whisk/http/ErrorResponse.scala
core/controller/src/main/scala/whisk/core/controller/Actions.scala
core/controller/src/main/scala/whisk/core/controller/Activations.scala
core/controller/src/main/scala/whisk/core/controller/Packages.scala
core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
core/controller/src/main/scala/whisk/core/controller/Rules.scala
core/controller/src/main/scala/whisk/core/controller/Triggers.scala
core/controller/src/main/scala/whisk/core/entitlement/Collection.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala
tests/src/test/scala/whisk/core/controller/test/RulesApiTests.scala
tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala

Properly terminates list requests when `skip` is a negative value or negative integer. Also adds tests for `limit` being a non-integer for list requests.
Fixes https://github.com/apache/incubator-openwhisk/issues/3611

Terminate route for invalid list skip values

---

actionRuntimes/actionProxy/invoke.py
performance/gatling_tests/src/gatling/resources/data/pythonAction.py
tests/dat/actions/sleep.py
tools/admin/wskadmin

I noticed in travis builds there are several python related warnings from the flake8 - so I removed them.
```
/tests/dat/actions/sleep.py:12:1: F401 'sys' imported but unused
./performance/gatling_tests/src/gatling/resources/data/pythonAction.py:4:1: F401 'sys' imported but unused
./actionRuntimes/actionProxy/invoke.py:39:1: F401 'traceback' imported but unused
3     F401 'traceback' imported but unused
./tools/admin/wskadmin:534:5: F841 local variable 'argsDict' is assigned to but never used
./tools/admin/wskadmin:553:5: F841 local variable 'argsDict' is assigned to but never used
2     F841 local variable 'argsDict' is assigned to but never used
```

remove unused imports or dead variables as reported in travis build.

---

common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/database/test/DbUtils.scala

Caches attachments with corresponding actions when an action is created/updated. The attachment is also cached on a fetch if it is not already cached.
Depends on https://github.com/apache/incubator-openwhisk/pull/2832
Closes https://github.com/apache/incubator-openwhisk/issues/2672

Cache database attachments

---

README.md

`master` is broken due to trailing whitespace.
@mrutkows did scanCode's config change without updating the main repo?

Fix README.md's scanCode issues.

---

.travis.yml
ansible/logs.yml
common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala
tests/README.md
tests/build.gradle
tools/build/checkLogs.py
tools/build/redo
tools/travis/README.md
tools/travis/checkAndUploadLogs.sh
tools/travis/distDocker.sh
tools/travis/runSystemTests.sh
tools/travis/runTests.sh
tools/travis/runUnitTests.sh
tools/travis/scan.sh
tools/travis/setupPrereq.sh
tools/travis/setupSystem.sh

Splits the Travis build to have 2 separate jobs for running tests
This PR splits the travis setup in 2 parts 
1. Test requiring only database
2. Test requiring complete OpenWhisk system
See discussions in #3572 for details
This PR introduces a notion of `testSets` which define set of filters for which test to execute. It defines 3 sets for now
1. `REQUIRE_ONLY_DB` - Test which just need database to be up
2. `REQUIRE_SYSTEM` - Test which require whole OpenWhisk runtime up. Excludes tests under 1
3. `LEAN` - Include all lean test i.e. current master
`checkLogs.py` currently performs some log sanity check like checking if db, controller logs are non empty. With this PR for `REQUIRE_ONLY_DB` controller logs would not be there. So it has been modified to support `tags`. Each check specify set …

Split test jobs in Travis

---

ansible/environments/vagrant/group_vars/all
tools/vagrant/Vagrantfile

On windows using vagrant can't create soft links to the windows filesystem.
Making deployment use remote CLI download
Closes #3649

switching vagrant to use cli remote mode

---

actionRuntimes/actionProxy/invoke.py

The invoke.py script infers a binary init artifact based on the file extension but sometimes the binary has no extension or one that is not recognized by the script. Rather than make changes to the set of extensions, add a binary option to the init commands.
example use: `invoke.py init -b main.exe`
The presence of the flag overrides any extension that might be set otherwise.

Allow for init to specify if artifact should be treated as binary 

---

tests/src/test/resources/logback-test.xml

Currently in test runs following log entry is seen multiple times (500+) 
```
whisk.common.UserEventTests STANDARD_OUT
[2018-05-14T17:46:49.927Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:49.966Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:50.041Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:50.135Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:50.247Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:50.354Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:50.443Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:50.524Z] [INFO] Slf4jLogger started
[2018-05-14T17:46:50.605Z] [INFO] Slf4jLogger started
```
This PR avoid this noise by disabling [akka.event.slf4j.Slf4jLogger](https://github.com/akka/akka/blob/ac64a7bb98edefc027f018bc92326ff680b4a640/akka-slf4j/src/main/scala/akka/event/slf4j/Slf4 …

Disable Slf4jLogger startup log in test runs

---

common/scala/src/main/scala/whisk/core/entity/Size.scala
tests/src/test/scala/whisk/core/entity/test/SizeTests.scala

Constructing a ByteSize form String will accept MB or M, KB or K (and is case insenstive).
This is to match the toString method which writes out the units as MB or KB (so that a serialized value can be parsed back to the identity).

Fixes asymmetry between reading and writing of ByteSize.

---

actionRuntimes/nodejs6Action/Dockerfile
actionRuntimes/nodejs8Action/Dockerfile
docs/reference.md

Updating the NodeJS runtime version for NodeJS 6 and NodeJS 8. 
NodeJS 6 went from `6.14.1` to `6.14.2`
NodeJS 8 went from `8.11.1` to `8.11.2`
Diff of changes can be seen here:
NodeJS 6: https://github.com/apache/incubator-openwhisk-runtime-nodejs/compare/6@1.9.0...6@1.9.1
NodeJS 8: https://github.com/apache/incubator-openwhisk-runtime-nodejs/compare/8@1.6.0...8@1.6.1

bump reference for NodeJS images, updating NodeJS6 & NodeJS8

---

tests/src/test/scala/common/WskTestHelpers.scala

Without printing the stack trace the original error will be overlayed by the error on the cleanup operation which is performed always at the end as part of the withAssetCleaner code.

Print stack trace in catch block for withAssetCleaner to improve debugging

---

docs/README.md
docs/reference.md
docs/use_cases.md
tools/db/README.md

- Refer to IBM Cloud (Functions) instead of Bluemix in docs
- Remove reference to standalone cloudant.com from DB docs

Update Bluemix references in docs

---

docs/about.md
docs/actions.md

1. In about.md, the activation records should be stored into activations
instead of whisks database.
2. Fix an outdated/broken node-js reference link in actions.md.

Fix outdated docs in about.md and actions.md

---

common/scala/src/main/resources/logback.xml
tests/dat/actions/unicode/build.gradle
tests/performance/gatling_tests/src/gatling/resources/conf/logback.xml
tests/src/test/resources/logback-test.xml

Reverts apache/incubator-openwhisk#3702
The PR above breaks the logging of all our components. After this, all our logs do not appear anymore.
This affects all our components and gatling tests.
Therefore this PR reverts this commit.

Revert "Add ASF license to optional XML files and last gradle file."

---

common/scala/src/main/scala/whisk/core/database/ArtifactStore.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala
common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala
common/scala/src/main/scala/whisk/core/entity/Attachments.scala
common/scala/src/main/scala/whisk/core/entity/Exec.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala
core/controller/src/main/scala/whisk/core/controller/Rules.scala
core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
tests/src/test/scala/whisk/core/database/test/AttachmentTests.scala
tests/src/test/scala/whisk/core/database/test/DbUtils.scala
tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreBehavior.scala
tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala

This PR implements the approach B of #3500 by adding a new `putAndAttach` method to `ArtifactStore`
This PR adds a new `ArtifactStore#putAndAttach` method and removes the `ArtifactStore#attach` method. Following are the main changes
For old attachment to be removed we need access to old attachment name. To facilitate that refactoring has been done to pass in old document to `put` method. As for update we were anyway reading existing document first (to know the revision) this change does not introduce any extra calls
For `WhiskActivation` refactoring was reduced by passing `None` for old document as so activations are not updated
See inline comments in code for details
The attachmentName stored in document would be a Uri consisting of scheme and path. So the format would be …

Immutable attachments via putAndAttach

---

LICENSE.txt
common/scala/src/main/scala/whisk/core/database/ConcurrentMapBackedCache.scala
common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala
licenses/LICENSE-spray.txt

The source code file called ConcurrentMapBackedCache.scala uses the source
code of Spray.
Closes: apache/incubator-openwhisk-release#152

Add the license and notice for ConcurrentMapBackedCache.scala

---

ansible/files/runtimes.json
common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
common/scala/src/main/scala/whisk/core/entity/Size.scala
core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala

This PR replaces #3232 and makes stem cell containers configurable from the runtime manifest. See the changes to runtimes.json for an example (or the new tests). It is possible to have multiple stem cells per runtime kind. For example:
```
{ "runtimes": {
"node": [
{
"kind": "nodejs:6",
"image": {
"name": "nodejsaction"
},
"stemCells": [{
"count": 1,
"memory": "128 MB"
}]
}, {
"kind": "nodejs:8",
"default": true,
"image": {
"name": "nodejsaction"
},
"stemCells": [{
"count": 1,
"memory": "128 MB"
}, {
"count": 1,
"memory": "256 MB"
}]
}
]...
```
This PR improves #3232 with stricter types on the `StemCell` configuration, filters configrations for runtimes for the ones that exists to make it easier to work with stem cells in the invoker.
Closes #2401.
Labelled breaking change because it will …

Make stemcells configurable by deployment 

---

common/scala/Dockerfile

Fixes Invoker docker build failure by updating the `wget` version
Travis builds are currently failing (both [master][1] and PRs) due to failure in invoker docker build with following errors
```
Step 6/11 : RUN wget --no-verbose https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/bin/kubectl
---> Running in ddbe33270513
Connecting to storage.googleapis.com (173.194.198.128:443)
ssl_client: storage.googleapis.com: TLS connect failed
wget: error getting response: Connection reset by peer
The command '/bin/sh -c wget --no-verbose https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/bin/kubectl' returned a …
```

Update wget to fix travis builds

---

common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
tests/src/test/scala/whisk/core/database/test/AttachmentCompatibilityTests.scala

Immutable attachments support #3502 introduced a regression due to which attachment name created using old scheme were not getting read.
This PR fixes that by checking if attachment names are as per old scheme or generated via new scheme. If using old scheme then attachment names do not use the URI format.

Fix attachment name compatibility issue

---

README.md
tools/macos/README.md
tools/ubuntu-setup/README.md
tools/ubuntu-setup/all.sh
tools/ubuntu-setup/java8.sh
tools/vagrant/Vagrantfile

Our documents need to be changed to point according to the usage of
Open JDK or Oracle JDK. This PR adds the instructions to install
either of them as the Java environment of OpenWhisk.
Partially-closes: apache/incubator-openwhisk-release#169

Update the document regarding Open JDK and Oracle JDK

---

common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala

* In the past, sleep time between connection retries has been 100 ms. This has been lowered to 10 ms with #3710. On a loaded invoker, 50 ms makes more sense.
* Reduce log volume on loaded invoker.

Relax connection retry in invoker

---

common/scala/Dockerfile

This PR changes to use the docker image with Open JDK from adoptopenjdk,
since the image from openjdk is missing package libc6-compat, and using
an old-version nodejs.

Switch to use adoptopenjdk/openjdk8:jdk8u172-b11-alpine for scala

---

README.md

With the recent improvements to the Helm-based deployment of OpenWhisk on
Kubernetes, I think the user experience of deploying it is smooth enough we should
make this option more visible.  Added a 1 paragraph section on Kubernetes deployment
to the main README.md with a link to the deploy-kube repo for details.
- [ x ] Documentation

Add brief Kubernetes Setup section to main README.md

---

actionRuntimes/php7.1Action/Dockerfile
docs/reference.md

Updating the PHP 7.1 runtime version from 7.1.9 to 7.1.18.
See https://github.com/apache/incubator-openwhisk-runtime-php/compare/7.1@1.0.0...7.1@1.0.1 for differences.

Bump reference for PHP 7.1 image

---

common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
tests/src/test/scala/actionContainers/ActionContainer.scala

support for tests in https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/41
Enable ActionContainer test execute concurrent /run requests on containers, to support testing containers that enable concurrency activation processing.

enable concurrent runs on ActionContainer test utility 

---

tools/db/cleanUpActivations.py
tools/db/deleteLogsFromActivations.py
tools/db/replicateDbs.py

The map in python2 and python3 is not compatible on subscription.
Therefore, this caused an error subscription thrown from couchdb.client in python3.
Signed-off-by: tz70s <su3g4284zo6y7@gmail.com>
See #3466 for better improvement on compatibility between python2, and 3.
Focus on this proposed change, I think it'll be better to doc the python version limitation on theses tools.
For example, couchdb bindings on python is currently not actively maintained, the latest version only support on 3.4. I'm not that sure there would be any breaking changes from 3.4 to 3.6, though.

Makes db tools python2 and python3 compatible

---

ansible/roles/kafka/tasks/deploy.yml

Current ansible processing looks for a docker log text string to determine if Kafka's running.  Unfortunately, this string can (and has) changed between versions of kafka.
Kafka registers its brokers with zookeeperer, so this this task checks the zookeeper node to determine whether kafka has started -- a likely to be much more forward-compatible approach.

Check zookeeper (not log) to see that kafka's running

---

common/scala/src/main/scala/whisk/common/CausedBy.scala
common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
core/controller/src/main/scala/whisk/core/controller/Controller.scala
core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
tests/src/test/scala/services/KafkaConnectorTests.scala

ensureTopic returns a `Boolean` value of whether it successfully created a topic or not.
This changes that behavior to actually return the Exception in case of an error. That enables the client-side code to handle (or log) that failure appropriately while maintaining the ease of checking a successful result by using `isSuccess`.

Refactor `ensureTopic` to expose failure details.

---

common/scala/src/main/scala/whisk/utils/Retry.scala
tests/src/test/scala/common/TestUtils.java
tests/src/test/scala/common/Wsk.scala

Allows the CLI test framework to perform retries when a network error occurs.

Add retries to CLI test framework for network errors

---

core/invoker/Dockerfile

As it is currently not possible to download the docker-cli on building the invoker image, this PR should unblock travis again.

Mitigate build problem of invoker.

---

common/scala/src/main/resources/reference.conf
common/scala/src/main/scala/whisk/core/connector/MessageConsumer.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala

- Rest of system continues to use the default system dispatcher
Refs #2954
This reopens the previous  #2956 PR; fork-join-executor wasn't the right choice previously and it is using Thread Pool dispatchers now, which are the correct way to handle this kind of IO separation with Akka. Defaults are set to what should be a reasonable starting point, especially given that couch and kafka now have their own separate execution pools from the "Default"/main system.
Kafka and CouchDB clients each get their own dispatchers
* This should prevent all of the akka based stuff from competing constantly for threads
* Kafka and Couch can be tuned now based on individual needs
* Using thread-pool dispatchers, which are best suited for these processes (default is fork-join)
- Dispatchers are defined in …

Introduce separate Akka dispatchers for CouchDB and Kafka Clients (#2954)

---

common/scala/src/main/scala/whisk/common/Logging.scala
common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala

This adds reporting of the time a message resides in kafka from being created to being read by a consumer. This is a very helpful metric for operators to determine the current state of a system.

Report metrics of kafka's queue time.

---

tests/src/test/scala/services/HeadersTests.scala

HeadersTest currently logs the complete in memory representation of config in console. This PR disables the logging of config as its not required

Avoid logging complete configuration in test

---

common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala

Like writing and reading from Kafka, creating topics can be subject to a battery of transient errors. Retrying those errors is safe and keeps us sane.

Retry `ensureTopic` on transient, retriable exceptions.

---

common/scala/src/main/scala/whisk/utils/Retry.scala

There is an initial wait in the retry method that should not be needed. With the initial pause the retry method takes twice as long to retry than what would be expected.

Remove unnecessary pause in retry method
