- common/scala/src/main/scala/whisk/utils/Retry.scala
- tests/src/test/scala/common/TestUtils.java
- tests/src/test/scala/common/Wsk.scala
This PR addresses a small bug introduced in https://github.com/apache/incubator-openwhisk/pull/3694 which prevents a test from dictating that it does not care about the exit code. Using the `common.retry` method which requires the retried function to throw an exception makes it difficult to restore the previous behavior while also allowing for retry on network hiccups.
I did not open an issue but there is extensive discussion in this PR https://github.com/apache/incubator-openwhisk-cli/pull/327.
> Allow command runner to retry on network exit with custom retry

- core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
For small N, allow the managed invokers to overlap with blackbox invokers.
As an example, for a blackbox fraction of 10%, and two invokers, the blackbox
pool will have size 1, but the managed pool will utilize both invokers.
> Allow invoker pools to overlap for small N.

- ansible/files/runtimes.json
- ansible/group_vars/all
- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/whisk/core/WhiskConfig.scala
- common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
- common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala
- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
- core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
- core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
- tests/src/test/scala/whisk/core/WhiskConfigTests.scala
- tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
- tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
- tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala
The invoker playbook ignores an image prefix when pre-fetching the blackbox images. This patch splits the blackbox tasks so that ones that do not have a prefix may be skipped (as today), but those that specify a prefix are always pulled, using the specified prefix in the image name.
Fixes https://github.com/apache/incubator-openwhisk/issues/3679.
> Adjust invoker playbook to pull docker images when a prefix and tag is specified.

- ansible/roles/invoker/tasks/deploy.yml
I think there is a very minor logic problem with ansible variable `skip_pull_runtimes` in invoker role
This would allow to skip runtimes pull in runtime repos, and use the runtime built for the repo specific repo.
> skip pull runtimes when skip_pull_runtimes is true

- README.md
- tools/ubuntu-setup/java8.sh
Vagrant installation is broken, due to a hang waiting for acceptance of the Oracle JDK license. This PR adds an acceptance script, and updates the top-level README.md, which erroneously references OpenJDK as being the default for Vagrant.
Truthfully, I'm not sure if a modification to tools/ubuntu-setup is the right place for a Vagrant-specific modification? Unless the Oracle JDK is used there, as well.
Fixes #3765
> Fixes for vagrant installation versus oracle jdk

- tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
Exec.serdes very implicitly relies on a manifest to be loaded, which makes the test-instances of Exec take values from there as well. The hard-coded versions of those in ExecHelper need to respect those values as well to be correctly assertable.
> Make test-instances of Exec depend on the loaded manifest.

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/whisk/core/database/AttachmentInliner.scala
- common/scala/src/main/scala/whisk/core/database/AttachmentSupport.scala
- common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
- common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala
- common/scala/src/main/scala/whisk/core/database/memory/MemoryAttachmentStore.scala
- tests/src/test/scala/whisk/core/database/test/AttachmentInlinerTests.scala
- tests/src/test/scala/whisk/core/database/test/AttachmentSupportTests.scala
- tests/src/test/scala/whisk/core/database/test/DbUtils.scala
- tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
This PR modifies the current attachment inlining logic to work at `ByteString` level and avoid converting ByteString to bytes and back. This fixes #3770
So far the inlining logic was converting a stream of `ByteString` to byte array and then working at byte level. This was causing the upload to slow down and also reverse conversion of stream of bytes to `ByteString` was not working as expected.
Instead of doing that it now uses approach mentioned [here](https://groups.google.com/forum/#!topic/akka-user/FdQAAzcwrqM) and works at `ByteString` level. 
See [this commit](https://github.com/apache/incubator-openwhisk/pull/3777/commits/a36bfb14a47bf3773b5dce13790c57f159874467) for this specific change
1. Do a `prefixAndTail` of 1 element
2. If extracted byteString prefix 
1. is empty then stream …
> Avoid converting ByteString to bytes in attachment inlining flow

- tools/actionProxy/build.gradle
add build gradle file for actionproxy image tool
missed from PR #3745
> add build gradle file for actionproxy image tool

- ansible/environments/distributed/group_vars/all
- ansible/environments/docker-machine/group_vars/all
- ansible/environments/local/group_vars/all
- ansible/environments/vagrant/group_vars/all
- ansible/group_vars/all
- ansible/logs.yml
- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- ansible/templates/whisk.properties.j2
- common/scala/src/main/scala/whisk/core/WhiskConfig.scala
- core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/actionContainers/ActionContainer.scala
This PR moves the version information to pureconfig. In addition, it removes the deployment variable `whisk_version_name` as it is only used to determine which type of deployment it is.
> Move version information to pureconfig and remove `whisk_version_name`.

- tests/src/test/scala/whisk/core/database/UserCommandTests.scala
- tools/admin/src/main/scala/whisk/core/database/UserCommand.scala
Scala based `user create foo` command which sets a random auth key is printing wrong key in output.
This happens because in case authkey is not provided then current impl was generating the key multiple times. So they key which gets saved in db differs from one printed in output.
This PR fixes that by generating the key only once if none provided
> Avoid regenerating auth key multiple times

- tests/build.gradle
Fixes #3819 by only using scoverage related artifacts.
Post this change the modified classpath looks like. This ensures **only** scoverage instrumented classes come first in the classpath and rest of the classpath is normal testRuntimeClasspath
```
/Users/travis/openwhisk/common/scala/build/classes/java/scoverage
/Users/travis/openwhisk/common/scala/build/classes/scala/scoverage
/Users/travis/openwhisk/common/scala/build/resources/scoverage
/Users/travis/.gradle/caches/modules-2/files-2.1/org.scoverage/scalac-scoverage-plugin_2.11/1.3.1/9b5637564eec011cac1aceab345c8de6b5a4e336/scalac-scoverage-plugin_2.11-1.3.1.jar
/Users/travis/.gradle/caches/modules-2/files-2.1/org.scoverage/scalac-scoverage-runtime_2.11/1.3.1/6f98957ae5ade845d20ac31e34f4142ddbb268a9/scalac-scoverage-runtime_2.11-1.3.1.j …
```
> Use only scoverage related artifcats in modified classpath

- tests/src/test/scala/common/LoggedFunction.scala
- tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
`stubFunctions` don't seem to play nicely with retry logic because the `verify` handler will be attached more than once. Switching to a manual stub should help here.
Fixes #3809
> Don't use stubbed functions in InvokerSupervisionTests.

- ansible/roles/apigateway/tasks/deploy.yml
- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/couchdb/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- ansible/roles/kafka/tasks/deploy.yml
- ansible/roles/nginx/tasks/deploy.yml
- ansible/roles/redis/tasks/deploy.yml
- ansible/roles/registry/tasks/deploy.yml
- ansible/roles/zookeeper/tasks/deploy.yml
`retries` and `delays` in ansible only applies to tasks/plugins that have `until` present
The `retries` and `delays` curently present are being ignored, this PR adds the `until` and changes to the new form of `loop` from `whith_items`
Ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#do-until-loops
`If the until parameter isn’t defined, the value for the retries parameter is forced to 1.`
> add register and until to ansible invoker pull runtime images tasks

- tools/admin/wskutil.py
This fails ever so often in Travis for no good reason. Bumping to 60 seconds shouldn't harm.
> Bump wskadmin's request timeout.

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-php.md
- docs/webactions.md
This PR adds PHP 7.2 as a new kind and sets the default PHP runtime to version 7.2.
I have not provided runtime tests here as they are in the runtime-php repository and they are being removed anyway via https://github.com/apache/incubator-openwhisk/pull/3467. I'm not sure which additional tests are needed in this repo.
https://github.com/apache/incubator-openwhisk-runtime-php/pull/28 needs to be merged and the relevant Docker containers built and uploaded to the Docker Hub first.
> Add support for PHP 7.2 runtime

- common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala
- tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
`EsSearchResult` will now be able to get the total number of hits from a search.
> Allow Elasticsearch client to retrieve hit count

- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
We need to enforce that /init is only called once for a given instance of a runtime. Adding to `BasicActionRunnerTests` means that all the action runtimes can be consistent.
- [X ] Rodric opened an issue to propose and discuss this change (#3839)
> Add an action runner test to ensure /init is only called once.

- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
- tools/build/redo
Shifts tests which are part of the system package (but slated for removal as part of #3737, #3840) to container unit tests which also checks that the runtimes provide a consistent handling of different capabilities and error scenarios.
> Add test for empty initializer. Document other tests.

- common/scala/build.gradle
- common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
**Notice:** This has been quite an odyssey to fix and we needed to roll back the change the last time. Please consider trying the changes out in an environment where you can assert latency and stability for different runtimes etc.
I myself have run:
- 3x Latency simulation (important, caught a regression last time) => **no regression**
- 3x Warm action simulation => **no regression**
- 1x Cold action simulation => **no regression**
- Explicitly consume and close the response's entity in any case (even if ignored) to make sure the connections get released properly and are not leaked.
- Use optimized path for consuming the entire entity into a string if its length is within bounds.
- Don't reuse connections.
To the last point: Reusing connections when a runtime doesn't support it adds a …
> Properly consume and optimize reading of http entities, drop connection reuse.

- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/controller/tasks/join_akka_cluster.yml
Refactors `controller_env` to a generic name of `env` so that deploy script plugins can be used interchangeably for deploying other components. For instance, these changes allow the same plugin to be used for the controller and invoker if need be.
Related to https://github.com/apache/incubator-openwhisk/pull/3785.
> Generic plugins for deployment

- docs/actions-new.md
- docs/actions-swift.md
- docs/actions.md
We have received contributions to add PHP, [Go](https://github.com/apache/incubator-openwhisk-runtime-go), Ruby (#3725) and on the Apache [dev list](https://lists.apache.org/thread.html/a3fc28c2c1577bbbfbb3d88541ec11287a578db45f245705bef395eb@%3Cdev.openwhisk.apache.org%3E) a new runtime for [Ballerina](http://ballerina.io).
This PR documents the steps required to add a new runtime to this repo so that it is available to the OpenWhisk deployment. Comments appreciated and welcome, particularly from those who have contributed runtimes recently (@sciabarracom @remore @akrabat).
cc @csantanapr 
I'm happy to accept additional improvements to this write up via pull requests and all contributions will receive due credit.
> Document adding a new runtime kind.

- ansible/files/runtimes.json
PR 63 in runtime-java added log sentinels, so we can now
update runtime.json accordingly.
> Java runtime now has log sentinels

- tests/src/test/scala/system/basic/WskUnicodeTests.scala
- tests/src/test/scala/system/rest/RestUtil.scala
Some deployments which add kinds that are not part of the openwhisk manifest will have a dependence on this repo because of the way the sniff tests looks for a test function. Instead of failing the test if a file is missing, skip it instead. It would still be possible to test the kinds by extending the class and overriding `getFileLocation`.
> Bypass system test for runtime kind if test file is not found.

- common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala
- tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchLogStoreTests.scala
- tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
Using the `from` parameter, Elasticsearch can paginate query results. Such functionality is needed for an Elasticsearch activation store in order to implement the `skip` logic that currently exists in the activation list REST APIs.
> Allow Elasticsearch client to skip query result hits

- tests/performance/wrk_tests/post.lua
Add an Apache license header to post.lua used by the wrk based performance tests
After this PR is merged the wrk checks can be re-enabled via this PR
https://github.com/apache/incubator-openwhisk-utilities/pull/49
Add an Apache license header to post.lua used by the wrk based performance tests
to make scancode happy
> Add missing license header for wrk lua file

- tools/build/citool
- tools/build/redo
- tools/travis/flake8.sh
See title.
Also enabled Flake8 to exit non-zero if there are warnings, seems like there is no harm to that right now. We can always disable that again if it really gets in the way.
> Fix warnings in python scripts.

- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
Some language runtimes doesn't write to standard error. Hence testEcho should be able to avoid checking for standard error.
> Adding enforceEmptyErrorStream check to testEcho

- common/scala/src/main/scala/whisk/common/Logging.scala
- core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
Today, the hostname of the invoker is used for the metrics, sent by kamon. This PR changes this behaviour to use the instance of the invoker instead.
> Use invoker id for metrics instead of the hostname.

- ansible/group_vars/all
- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- ansible/tasks/db/checkDb.yml
- ansible/tasks/db/createUsers.yml
- ansible/tasks/db/grantPermissions.yml
- ansible/tasks/initdb.yml
- ansible/tasks/recreateViews.yml
- ansible/tasks/wipeDatabase.yml
- ansible/templates/db_local.ini.j2
With this PR, each deployed component will get it's own database credentials. On doing this, we are able to set the permissions for each component.
E.g. the invoker does not need write access to the subjects- and the whisks db.
The database users and the permission handling is done on wipedb and initdb.
The db-prefix is part of the usernames. This is to avoid clashes if several Openwhisk instances use the same couchdb/cloudant instance.
> Use separate db users for deployed components.

- common/scala/build.gradle
- common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
- tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala
Today we have a very basic way of parsing docker image names, which even prohibit the use of ports in the domain names and/or providing a fully-qualified digest to pull.
This parser implements the full specification of docker image names to allow OpenWhisk to take all kinds of image references possible.
> Implement full specification of docker image names.

- tests/src/test/scala/system/basic/WskRestBasicTests.scala
Controller caching can cause some test activity to fail due to the delay in distributing recent entity changes across all controllers.  To avoid intermittent failures, retries have been added to tests that periodically fail.  This is one more retry addition to fix a recent failure.
> Add retry in WskRestBasicTests to avoid intermittent test failures

- common/scala/src/main/scala/whisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
`CosmosDBArtifactStore` should close the configured `AttachmentStore` instance upon shutdown
Due to this currently testcases are not cleaning up the db created in Cosmos
> Shutdown AttachmentStore in CosmosDBArtifactStore

- core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
- core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
- tests/src/test/scala/whisk/core/controller/test/EntitlementProviderTests.scala
- tests/src/test/scala/whisk/core/controller/test/PackageActionsApiTests.scala
- tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Pass the user identity also to the `grant`, `revoke` and `entitled` methods of the entitlement provider.
This PR makes the method signatures of the entitlement providers uniform in the way that not only the user subject is passed to this method, but the whole user object.
This change makes it easier to implement entitlement providers that need more data about the user that the subject name.
> Unify Entitlement SPI signatures

- common/scala/src/main/scala/whisk/common/TransactionId.scala
- common/scala/src/main/scala/whisk/http/BasicHttpService.scala
Request headers should be compared case insensitive. We noticed X-Request-Id was being ignored at controller, due to the configured header being X-Request-ID
> make request id header name comparison case insensitive

- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
- docs/actions-docker.md
- tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
A `docker pull` can fail due to various reasons. One of them is network throttling by the image registry. Since we try to pull on each blackbox invocation, high volume load can cause lots of errors due to failing pulls unnecessarily.
Instead, we try to run the container even if the pull failed in the first place. If the image is available locally, the container will start just fine and recover the error gracefully. If the image is not available locally, the run will fail as well and return the same error as the docker pull would've returned.
This behavior will only be enabled for blackbox actions that specify a tag. Blackbox actions not using a tag *or* using "latest" as a tag will exhibit the very same behavior as today. That is: There will always be a pull before each container start …
> Recover image pulls by trying to run the container anyways.

- ansible/roles/couchdb/tasks/deploy.yml
- ansible/tasks/gen_erl_cookie.yml
Set identical erlang magic cookie for couchdb
This commit try to set an identical erlang magic cookie for each couchdb container, so that they  can rejoin the cluster after being restarted
> Set erlang magic cookie for couchdb

- core/controller/src/main/scala/whisk/core/controller/BasicAuthenticationDirective.scala
- core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
Unauthenticated web actions will use the authentication provider configured in the SPI to create the namespace based Identity
Unauthenticated web actions do create a namespace based identity that is used to entitle the call.
This change makes them use the configured authentication provider to construct this identity.
> Use the authz provider to retrieve the identity of the namespace

- ansible/group_vars/all
- ansible/roles/controller/tasks/deploy.yml
- core/controller/src/main/resources/reference.conf
- core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
This PR introduces a configurable multiplicator to influence the forced active ack timeout period.
In rare condition one can see that the load balancer put activations into queues of invokers falsely 
identified to have free capacity because forced active acks  are send out for activation that are waiting in the queue to be executed. With increasing  the timeout the loadbalancer can be influenced to distribute the load wider in this cases. 
- [x ] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
[PG3:2420 succeeded]
> introduce timeout factor to control invoker queue behavior

- docs/metrics.md
OpenWhisk generates quite a few metrics via [Kamon](http://kamon.io). This PR aims to document all currently generated metrics such that system administrators can configure the right metrics for monitoring
See [here](https://github.com/chetanmeh/incubator-openwhisk/blob/metrics-docs/docs/metrics.md#metric-details) for the rendered HTML version of doc
> Document metrics generated within OpenWhisk

- ansible/README.md
- ansible/group_vars/all
- ansible/roles/controller/tasks/deploy.yml
- ansible/templates/whisk.properties.j2
- common/scala/src/main/scala/whisk/common/Logging.scala
- common/scala/src/main/scala/whisk/common/RingBuffer.scala
- common/scala/src/main/scala/whisk/core/WhiskConfig.scala
- core/controller/src/main/scala/whisk/core/controller/Actions.scala
- core/controller/src/main/scala/whisk/core/controller/Controller.scala
- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
- core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
- core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
- core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
- core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- tests/performance/preparation/deploy.sh
- tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
- tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
This is a fairly big change but bear with me!
Today, we have an arbitrary system-wide limit of maximum concurrent connections. In general that is fine, but it doesn't have a direct correlation to what's actually happening in the system.
This adds a new state to each monitored invoker: Overloaded. An invoker will go into overloaded state if active-acks are starting to timeout. Eventually, if the system is really overloaded, all Invokers will be in overloaded state which will cause the loadbalancer to return a failure. This failure now results in a `503 - System overloaded` message back to the user.
> Throttle the system based on active-ack timeouts.

- core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
- docs/conductors.md
- tests/src/test/scala/system/basic/WskConductorTests.scala
- tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala
Conductor actions currently abort when they fail to execute a component action with no possibility to catch the error and recover. This PR makes it possible to handle several failure scenarios.
With this PR, the following failure scenarios can now be handled by the conductor action code:
- parsing failure,
- resolution failure,
- entitlement check failure,
- excessive number of component action activations.
With this PR, a conductor action can reliably invoke a callback upon completion, whereas currently a simple typo in the name of a component action aborts the execution and prevents the callback to run.
The unit and system tests for conductor actions have been updated to confirm that the conductor action invocation does not abort in these scenarios.
The documentation of conductor …
> Do not abort conductor action execution when component action is invalid, not found, not accessible or when composition is too long

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
- common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
- common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
- tests/src/test/scala/services/KafkaConnectorTests.scala
The `max.poll.interval.ms` setting needs to be high enough to not be thrown off by all actions in the system consuming the maximum duration of their respective action timeout, ideally also adding enough slack to account for image pulls taking long, or docker runs being very slow.
The name of the setting was also misspelled so we've been running on the default.
> Fix max.poll.interval.ms setting of KafkaConsumer.

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-ruby.md
- docs/actions.md
- docs/parameters.md
- tests/dat/actions/unicode.tests/ruby-2.5.txt
This PR adds a new ruby:2.5 kind to allow Ruby methods like this:
```
def main(param)
{ :result => param.upcase }
end
```
This PR is quite similar to #2415, but this time I did it in Ruby. I do believe there are certain number of developers who'd love to pick Ruby as a primary language (see #2046 for an instance).
Currently Ruby runtime is tentatively hosted at [remore/openwhisk-runtime-ruby](https://github.com/remore/openwhisk-runtime-ruby), but needless to say I'd love to move/transfer this to anywhere The Apache Software Foundation manage.
#2046 is most likely related
> Add Ruby2.5 runtime support

- common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
Do not rely on LogRotatorSink to create user log files. Instead manually create the user log files with custom permissions.
> Manually create user log files

- common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
* We schedule a wake-up thread once to wake up the long `poll()` call if it takes too long. Make sure that this wake-up thread is cancelled as soon as possible once the `poll()` has returned - no matter whether it was successful or not. Otherwise the wake-up will be remembered by the consumer and applied on the next `poll()`. See https://kafka.apache.org/11/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#endOffsets-java.util.Collection-
* Catch failures when closing the old consumer during re-creation. In the past, re-creation was interrupted when closing failed and no new consumer was created.
* Add more logging such that unexpected or error conditions no more happen unnoticed.
> Improve robustness of KafkaConsumerConnector

- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
Small cleanup: As best as I can tell, this envvar is set when deploying the
invoker/controller but the value is never actually used.
> eliminate setting of COMPONENT_NAME

- ansible/roles/invoker/tasks/deploy.yml
- docs/actions-ruby.md
- tests/src/test/resources/application.conf.j2
- tools/travis/README.md
This change is to allow for a small convenience: `redo invoker -e skip_pull_runtimes=true` and `redo invoker -xd -e "{skip_pull_runtimes: True}"` will now be accepted (this is because passing boolean variables through ansible requires using JSON.
> Allow non-json skip_pull_runtimes to be passed as True.

- core/routemgmt/common/apigw-utils.js
- tests/dat/apigw/testswaggerdoc1
- tests/src/test/scala/whisk/core/cli/test/ApiGwRestBasicTests.scala
Fixes #3888
An exception is thrown when an managing an existing API that has the `set-variable` object appearing prior to the `invoke` stanza.  This `set-variable` stanza is set when the target web action has been secured with the `require-whisk-auth` annotation, and this stanza typically follows the `invoke` stanza; however, when reversed an exception was thrown.
> Fix for exception being thrown during api creation

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
- common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
Currently, the KafkaConsumer warns about a misconfiguration because we added a fantasy value to the kafka config itself. There is a value to control the window size of metrics reporting which roughly fits the needs of the value we need, thus switching to that value also gets rid of the warning in the log.
> Adjust Kafka's config to not contain any more warnings.

- tests/performance/README.md
- tests/performance/gatling_tests/src/gatling/scala/ApiV1Simulation.scala
- tests/performance/gatling_tests/src/gatling/scala/BlockingInvokeOneActionSimulation.scala
- tests/performance/gatling_tests/src/gatling/scala/ColdBlockingInvokeSimulation.scala
- tests/performance/gatling_tests/src/gatling/scala/LatencySimulation.scala
Today the gatling tests hard code the amount and percentage of errors, like:
https://github.com/apache/incubator-openwhisk/blob/master/tests/performance/gatling_tests/src/gatling/scala/ColdBlockingInvokeSimulation.scala#L88
The PR is making the number of errors and percentage configurable per environment variable. For example during long running tests with lot of requests a certain amount of failure rate is acceptable.
I can extend this to other tests once first review is ok. Give me a ping...
I've run a test that the parameters are recognised as expected.
```
OPENWHISK_HOST="xxxxxx" USERS="10" REQUESTS_PER_SEC="10" MAX_ERRORS_ALLOWED="1" MAX_ERRORS_ALLOWED_PERCENTAGE="0.1" ./gradlew gatlingRun-ColdBlockingInvokeSimulation
```
Result
```
Invoke action: mean requests per second is greater …
```
> make error count and percentage configurable for gatling tests

- docs/actions-node.md
The NodeJS Runtime for Openwhisk was recently updated to include the latest version of the "openwhisk" NPM package.  The documentation listing the NodeJS runtime's dependencies should be updated to reflect that change.
> update documentation for nodejs runtime

- ansible/README.md
- ansible/README_DISTRIBUTED.md
- ansible/apigateway.yml
- ansible/downloadcli.yml
- ansible/openwhisk.yml
- ansible/roles/cli-install/tasks/clean.yml
- ansible/roles/cli-install/tasks/deploy.yml
- ansible/roles/couchdb/tasks/deploy.yml
- ansible/roles/routemgmt/files/installRouteMgmt.sh
- ansible/roles/routemgmt/files/uninstallRouteMgmt.sh
- docs/actions-ruby.md
- tools/build/redo
- tools/travis/setupSystem.sh
- tools/vagrant/Vagrantfile
API gateway is missing from `redo` aka `wskdev`. Add it and also separate the `wsk` download into its own playbook. Fix bug in script which failed silently if `binary` did not exist.
> Separate routemgmt.yml out from  openwhisk.yml playbook

- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
- core/routemgmt/common/apigw-utils.js
- tests/dat/actions/echo-web-http.js
- tests/dat/actions/jsonStringWebAction.js
- tests/src/test/scala/whisk/core/cli/test/ApiGwRestBasicTests.scala
- tests/src/test/scala/whisk/core/cli/test/ApiGwRestTests.scala
- tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
- tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
For legacy reasons, we required web actions to return a base 64 encoded string when returning JSON. This PR removes the requirement to base64 encode JSON if returning the result as string. This is based on a slack discussion with @csantanapr (as reported from an end-user).
> Allow raw JSON string as response for webaction without base64 encoding.

- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/whisk/core/WhiskConfig.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
This PR makes the amount of parallel docker runs configurable.
In addition, it reduces the amount of checks, if the database already exists during deployment.
PG5#346 is running.
> Make amount of parallel docker runs configurable.

- .travis.yml
- tools/travis/distDocker.sh
- tools/travis/setup.sh
Gradle wrapper and dependency downloads are subject to intermittent failures, which can get annoying when you want to test your branches reliably. This adds the travis caching feature to cache the wrapper and caches. Moreover, it retries those downloads to be resilient against hiccups.
> Make gradle and dependency downloads more stable.

- tools/admin/src/main/resources/application.conf
`wskadmin-next` fails to start with configuration exception. This config is required for each independent component which depends on common module to provide tracing name.
This does not get caught in test as there the combined config from controller and invoker provide required missing config.
Fixes #3957
> Add tracing component name to wskadmin-next

- common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
- common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
- common/scala/src/main/scala/whisk/utils/Exceptions.scala
When we have general failures in our Kafka clients, we try to recreate them. If that recreation fails for some reason, the component might be broken forever, but it doesn't contain enough debug information now to fix this. This adds that debug information.
> Log possible errors around creation of kafka clients.

- common/scala/build.gradle
- core/invoker/Dockerfile
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
- tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
1. Upgrade to latest released version of the fabric8 Kubernetes client
to get access to an implementation of node affinity. Use that implementation
to optionally add a scheduling affinity to the pods created for actions
to bind them to worker nodes labeled as invoker nodes.
2. implement the container removal operation via the kube rest client
instead of via an exec to the kubectl cli.  This eliminates the last
usage of kubectl in the KubernetesClient and allows the kubectl
executable to be removed from the invoker Docker image.
> k8s: implement invoker-node affinity and eliminate usage of kubectl

- tests/src/test/scala/whisk/core/database/test/DbUtils.scala
- tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreSubjectQueryBehaviors.scala
- tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala
It's better to use the ArtifactStore than a specified DB client in `whisk.core.invoker.test.NamespaceBlacklistTests`,
now we can test this piece of codes with a different database backend other than CouchDB
> Use ArtifactStore to manipulate data in NamespaceBlacklistTests

- core/controller/src/main/scala/whisk/core/controller/BasicAuthenticationDirective.scala
- core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
Add implicit parameters to the authentication provider interface to allow datastore access
This PR add the actor system and the execution context as implicit parameters 
to the authentication provider interface to allow access to provider specific data sources.
> Add implicit parameters when getting the namespace identity 

- common/scala/src/main/resources/application.conf
- core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
In systems with a lot of invokers, all Kafka-consumers are slowing down Kafka if they are ideling.
I did some tests with the fetch.max.wait.ms-parameter.
I produce messages to one topic. Each consumer has it’s own topic. So if there are 100 consumers, 99 of them are idling.
I used the command kafka-producer-perf-test.sh --topic invoker0 --num-records 100000 --throughput 999999999 --record-size 600 --producer-props bootstrap.servers=localhost:9072 for the test.
|               |           20ms           |           100ms          |           500ms          |          1000ms          |
|:-------------:|:------------------------:|:------------------------:|:------------------------:|:------------------------:|
|  1 consumers  | 39698.292973 records/sec | 40225.261464 records/sec | …
> Bump fetch.max.wait of Kafka-consumers to lower the load on Kafka in large systems.

- ansible/files/runtimes.json
- common/scala/src/main/scala/whisk/core/entity/Exec.scala
- common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
- tests/performance/gatling_tests/src/gatling/scala/ColdBlockingInvokeSimulation.scala
- tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/whisk/core/database/test/AttachmentCompatibilityTests.scala
- tests/src/test/scala/whisk/core/database/test/CacheConcurrencyTests.scala
- tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
- tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
- tests/src/test/scala/whisk/core/entity/test/ExecTests.scala
- tools/db/moveCodeToAttachment.py
Treats action code as attachment for all kinds in default runtime.
Supersedes #3286. 
This PR builds on #3286 and enables use of attachment mode for all kinds. Some key aspects are
1. Binary code (like zip/jar) is stored in raw form (NOT Base64 encoded) in attachment
2. Change is backward compatible in reading code
3. Upon update or new action being created the code would be stored as attachment
4. `attachmentType` property of runtime.json is now not used. Instead one of the below is used
- `text/plain(UTF-8)` - For plain string which are not base64 encoded
- `application/octet-stream` - For codes which are Base64 string. Such codes are stored in raw form in persistent store
Note that with support for attachment inlining (#3709) it may happen that small code is still stored as part of …
> Treat action code as attachments

- common/scala/src/main/resources/s3-reference.conf
- common/scala/src/main/scala/whisk/core/database/s3/S3AttachmentStore.scala
- tests/src/test/scala/whisk/core/database/s3/S3Minio.scala
- tests/src/test/scala/whisk/core/database/s3/S3WithPrefixTests.scala
Enable configuring a common parent folder under which all attachments stored. This enables sharing same bucket with multiple clusters
Currently the attachments are stored with path structure `whiskentity/<namespace>/<docId>/<name>`. With this PR it would be possible to also specify a parent path under which this path would be created. So path structure would be like `<prefix>/whiskentity/<namespace>/<docId>/<name>`
The prefix can be specified via `prefix` setting (optional)
```
whisk {
s3 {
alpakka {
aws {
credentials {
provider = static
access-key-id = "$accessKey"
secret-access-key = "$secretAccessKey"
}
region {
provider = static
default-region = us-west-2
}
}
endpoint-url = "http://localhost:$port"
}
bucket = "openwhisk"
prefix = "dev-cluster"
}
}
```
> Support storing attachment in a sub folder in S3 bucket

- core/controller/src/main/scala/whisk/core/controller/Actions.scala
- core/controller/src/main/scala/whisk/core/controller/Entities.scala
- core/controller/src/main/scala/whisk/core/controller/Triggers.scala
- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
- tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
- tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
- tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
This closes #3582 
This change will add activation id in the response headers.
Since same logic needs to be used in both collection API and web action API, I created dedicated trait for custom headers.
> Activation id in header

- common/scala/src/main/scala/whisk/common/Logging.scala
- core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
- docs/metrics.md
Adds a log message when an activation record is retrieved from the activation store for blocking invocations. This will help us determine how often the DB polling flow is used to retrieve blocking invocation activations.
> Log activation retrieval from activation store for block invocations

- common/scala/transformEnvironment.sh
Enables support for passing typesafe config string as part of environment variables. 
Currently to configure OpenWhisk settings in Controller and Invoker one needs to reverse map the typesafe config to environment variable following specific convention. For example setting `whisk.loadbalancer.invoker-busy-threshold` would need env name like `CONFIG_whisk_loadbalancer_invokerBusyThreshold`. This currently works but poses following problems
1. Mapping config name to env name has some transformation involved and is a manual process
2. Flattening the config tree in env variables obscures the config and makes it tricky to get the context
3. Mapping list entries in config to env variable is tricky
It would be better to have a way where we can pass in the config from a file in typesafe config …
> Simplify configuring OpenWhisk

- tools/ansibleRunner/Dockerfile
- tools/ansibleRunner/README.md
- tools/ansibleRunner/build.gradle
- tools/scriptRunner/Dockerfile
- tools/scriptRunner/README.md
- tools/scriptRunner/build.gradle
- tools/scriptRunner/init.sh
Define alpine based utility images that execute bash scripts and ansible
playbooks mounted into /task by Kubernetes/Dockers/Mesos/OpenShift.
By defining these images as part of the OpenWhisk core project, we can
reduce the number of bespoke Docker images in downstream deployment projects.
> utility Docker images to run ansible playbooks and bash scripts

- core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
Add maximum length of  pod name checking and fixing code.
In case of kubenetes deployment environment, invokers make container and pool using kubernetes api.
thus action containers are created as a pod.
so naming rule for action container have to follow K8s policy.
the name of pod must be no more than 63 characters in kubernetes.
however there is no checking code for maximum length of pod name.
This problem causes significant problems that actions are not invoked.
> Add length of podName checking code for K8s

- common/scala/src/main/scala/whisk/core/containerpool/Container.scala
- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
- tests/src/test/scala/actionContainers/ActionContainer.scala
- tests/src/test/scala/system/basic/WskRestBasicTests.scala
- tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
- tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
- tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Previously, kubernetes container depends on sentinel message defined by
docker container object. Not ideal for separated SPI impl, put this to a
share place instead.
> Refactor sentinel message into shared place.

- docs/cli.md
The existing description of updating bash on macOS tells users to install an updated bash by installing `bash-completion` via brew. The `bash-completion` package is not bash itself; it is a set of completion definitions for various programs. To actually get a newer bash, users should do `brew install bash` instead.
This PR also adds a line to clarify that the updated bash is installed in `/usr/local/bin` (as opposed to updating the system default bash).
> Fix macOS bash update instructions in docs/cli.md

- common/scala/src/main/scala/whisk/core/entity/Attachments.scala
- common/scala/src/main/scala/whisk/core/entity/Exec.scala
- common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
- tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/whisk/core/database/test/AttachmentCompatibilityTests.scala
- tests/src/test/scala/whisk/core/database/test/DbUtils.scala
- tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreBehaviorBase.scala
- tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
- tests/src/test/scala/whisk/core/entity/test/ExecTests.scala
Treats blackbox action code as attachment
This is next installment in the [attachment saga](#3944) (previous in this series #3945). With this change code related to blackbox action would also be stored as attachment.
1. Change is backward compatible in reading code
2. Upon update or new action being created the code would be stored as attachment
> Treat blackbox action code as attachment

- ansible/README.md
- ansible/group_vars/all
- ansible/roles/apigateway/tasks/deploy.yml
- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/couchdb/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- ansible/roles/kafka/tasks/deploy.yml
- ansible/roles/nginx/tasks/deploy.yml
- ansible/roles/redis/tasks/deploy.yml
- ansible/roles/zookeeper/tasks/deploy.yml
This makes it easy to analyze when errors were happened from logs
All components except CouchDB will print local datetime in their logs, so I think it's better to add an variable in ansible to set the timezone for these components
For CouchDB, seems it's not possible to make it use local time in its logs: https://serverfault.com/questions/335232/how-to-change-couchdb-time-zone-setting-in-log-file
> Add an variable to set the timezone for all of components

- common/scala/src/main/scala/whisk/core/containerpool/AkkaContainerClient.scala
- common/scala/src/main/scala/whisk/core/containerpool/ApacheBlockingContainerClient.scala
- common/scala/src/main/scala/whisk/core/containerpool/Container.scala
- common/scala/src/main/scala/whisk/core/containerpool/ContainerClient.scala
- common/scala/src/main/scala/whisk/core/mesos/MesosTask.scala
- common/scala/src/main/scala/whisk/http/PoolingRestClient.scala
- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
- tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
- tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
Instead of restricting connection reuse, destroy connection pool on Container.pause.
Partly from discussion at https://github.com/apache/incubator-openwhisk/pull/3969#issuecomment-413590542
and partly to enable connection reuse to prep for concurrent activations (#2795)
we should not constraint connection handling at the client, but rather dispose the connection pool at time of pause (since it may leave the client pool in a bad state if the container is paused then resumed) 
(replaces the fix added in #3969 )
> close connections and reset pool on Container.pause

- common/scala/src/main/scala/whisk/core/WhiskConfig.scala
- common/scala/src/main/scala/whisk/core/entity/Identity.scala
- common/scala/src/main/scala/whisk/http/ErrorResponse.scala
- core/controller/src/main/scala/whisk/core/controller/Actions.scala
- core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
- core/controller/src/main/scala/whisk/core/entitlement/KindRestrictor.scala
- tests/src/test/scala/whisk/core/controller/test/EntitlementProviderTests.scala
- tests/src/test/scala/whisk/core/controller/test/KindRestrictorTests.scala
Currently, all kinds supported by the system are able to be created within any namespace to which a client has access. As new action kinds are added to the system, there is a need to restrict the creation of new actions to a particular _whitelist_ of accepted namespaces.
> Restrict allowed namespaces when creating action of certain kinds

- common/scala/build.gradle
This change upgrades caffeine to the latest version 2.6.2
This change upgrades caffeine to the latest version.
Main reason for this change is to make the expiration per entry interfaces available
with the latest fixes. Though openwhisk does exploit this feature (yet),
authentication SPI implementations can use this feature to cache tokens based on their
expiry date.
The selected version is also the one required b the latest version of `scaffeine`
which might be a worthwhile way to scala-fy the usage of caffeine in openwhisk.
> Upgrade caffeine to get multi expiry support with the latest fixes

- tests/dat/actions/ping.js
- tests/src/test/scala/system/basic/WskActionTests.scala
As discussed on #4013 the test now asserts on absence of successful ping response
Fixes #4013
> Ping test should check for absence of ping response

- tests/src/test/scala/whisk/core/database/UserCommandTests.scala
- tools/admin/README-NEXT.md
- tools/admin/src/main/scala/whisk/core/database/UserCommand.scala
This PR enhances the [wskadmin-next](https://github.com/apache/incubator-openwhisk/blob/master/tools/admin/README-NEXT.md) tooling with `--force` and `--revoke` flags that allow updating user auth key.
Currently wskadmin (and next) allow adding a namespace with or without specific auth key.
In some cases, it is handy to allow updating existing namespace with specific auth key, or regenerating new key.
There are 2 flags being added in this PR:
- `--revoke`, abbreviated `-r`: regenerate a new key for the user / namespace, UUID remains the same
- `--force`, abbreviated `-f`:
- with `--auth uuid:key`: the new auth value is updated for the user
- without `--auth`: an auth of new UUID and key is randomly generated
- #3965
> Allow updating auth key for user with wskadmin-next

- .gitignore
- ansible/README.md
- ansible/couchdb.yml
- ansible/group_vars/all
- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- ansible/setup.yml
- common/scala/src/main/scala/whisk/common/Https.scala
- common/scala/src/main/scala/whisk/http/BasicHttpService.scala
- core/controller/src/main/scala/whisk/core/controller/Controller.scala
- core/controller/src/main/scala/whisk/core/controller/Triggers.scala
- core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
- tests/src/test/resources/application.conf.j2
- tools/vagrant/README.md
This PR adds SSL to the invoker to secure the ping-endpoint. In addition it tidies up some controller-ssl-settings.
> Secure the invoker with ssl.

- docs/actions.md
More accurate description of blocking calls and the situation when _application error_ is returned upon invoking an action.
> Docs fixes for action invocations

- core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
- docs/rest_api.md
- docs/webactions.md
- tests/src/test/scala/services/HeadersTests.scala
- tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
- tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
This PR updates the REST and Web Action endpoints to change the Allowed-Headers response to `"*"`, and to add an Allowed-Methods header. It also updates the related tests to check for conformance.
Fixes #4009
> CORS headers work

- tests/performance/gatling_tests/src/gatling/resources/conf/logback.xml
- tests/performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskProtocolBuilder.scala
This PR does couple of fixes in gatling test runs
Currently gatling test presume that `OPENWHISK_HOST` is just the host. With this change it would be possible to pass complete url without needing to extract the host separately. This simplifies invoking it in existing CI setup
```
OPENWHISK_HOST="https://172.17.0.1:443" CONNECTIONS="100" REQUESTS_PER_SEC="1" ./gradlew gatlingRun-ApiV1Simulation
```
Currently following [warning is seen in logs](https://travis-ci.org/apache/incubator-openwhisk/jobs/430454430#L2887)
```
> Task :tests:performance:gatling_tests:gatlingRun-ApiV1Simulation
10:12:19,372 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:12:19,372 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource …
```
> Enable passing absolute url to gatling test and few other fixes

- core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
This PR enhances the debugging, if there are waiting activations in the invoker.
In addition it changes the type of the log message to warn, if the message is printed by intention.
> Add additional debug information if activations have to wait in the invoker.

- tools/scriptRunner/Dockerfile
script runner container used in kubernetes deployment requires nodejs
some of the catalog scripts need to npm install and then zip actions
> script runner now has nodejs

- common/scala/src/main/scala/whisk/core/connector/Message.scala
- common/scala/src/main/scala/whisk/core/entity/Parameter.scala
- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
- core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
- docs/metrics.md
- tests/src/test/scala/whisk/core/connector/test/EventMessageTests.scala
- tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala
1. The `causedBy` annotation is actually an optional String vs. a boolean flag.
2. The `name` field is actually intended to contain the fully-qualified name of the action vs. a composite of the invocation namespace and an action name (which doesn't really represent anything).
> Adjust activation metric schema to reflect reality.

- common/scala/src/main/scala/whisk/core/containerpool/Container.scala
- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
On profiling the invoker I saw, that the lookup of the config blocks the invoker-threads on the beginning of a burst.
The reason is, that the config is read on every container-creation. It is enough to read this configuration once.
I also verified, that the threads are not blocked after the change.
> Don't lookup config on every container-creation.

- common/scala/transformEnvironment.sh
This PR extends #3984 by adding support for passing base64 encoded config via environment variable
With #3984 support was added for passing in typesafe config as env variable. Some env like Marathon based support specifying env value only as json value which makes it tricky to pass typesafe config which includes new lines.
To support such env this PR adds support for passing base64 encoded config via `OPENWHISK_ENCODED_CONFIG`
```yml
- name: Load config from template
set_fact:
openwhisk_config: "{{ lookup('template', 'config.j2') }}"
- name: populate environment variables for controller
set_fact:
env:
"OPENWHISK_ENCODED_CONFIG": "{{ openwhisk_config | b64encode }}"
```
> Support passing base64 encoded config via env

- common/scala/src/main/scala/whisk/common/TransactionId.scala
- common/scala/src/main/scala/whisk/common/tracing/OpenTracingProvider.scala
- core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
- tests/src/test/scala/common/TestHelpers.scala
- tests/src/test/scala/common/WskTracingTests.scala
Prior error message doesn't put error tag into failed trace.
This is nice to have and useful on trouble shooting within request context via modern UI in Jaegar or Zipkin.
With a minor change in primitive action flow which didn't enclose with failed trace.
I'm not sure folks are consistent with tracing system because of conflicting goals that we already have transid in log. IMHO, at least, it shouldn't make traces confused once if user decides to take it into system: whether there's an accurate error message existed or not, we should know which one get failed.
Semantics followed by: 
https://github.com/opentracing/specification/blob/master/semantic_conventions.md
Snapshots in Jaegar:
> Put error message as tag into failed trace.

- common/scala/src/main/scala/whisk/core/connector/Message.scala
- core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
- core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
- core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/whisk/common/UserEventTests.scala
Currently, only the invoker sends activation-events to the user-metric-topic. With this PR, the controller will write activations of sequences as well.
This PR is based on #4006.
> Send activations of sequences to events topic.

- tools/ansibleRunner/Dockerfile
When building on a new machine (no cached docker images), building the ansibleRunner failed with the error:
```
> Task :tools:ansibleRunner:distDocker
Wed Sep 26 17:00:49 EDT 2018: Executing 'docker build -t ansible-runner /Users/dgrove/code/openwhisk/openwhisk/tools/ansibleRunner'
Collecting jinja2 (from ansible==2.5.2)
Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
Collecting PyYAML (from ansible==2.5.2)
Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
Collecting paramiko (from ansible==2.5.2)
Downloading https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa94 …
```
> upgrade pip before installing ansible

- README.md
Goes along with https://github.com/apache/incubator-openwhisk-deploy-kube/pull/307.
I've been using the Kubernetes built-in to Docker 18.06 for a few days; so far it is working really nicely.
> Add mention of Kubernetes support in Docker for Mac 18.06

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/whisk/core/containerpool/logging/SplunkLogStore.scala
- tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
Existing SplunkLogStore suffers from:
- inaccurate queries, where cases when activation timestamp varies from log collection delay > 5 seconds
- inconsistent log output (compared to DockerToActivationLogStore)
This PR addresses these by:
- adding a config to indicate the splunk query offset, where query will be `<activation start> - offset` and `<activation end> + offset`
- refactoring splunk api results to be formatted same as DockerToActivationLogStore
> improve splunk query; use consistent format for log output

- tools/ansibleRunner/Dockerfile
The switch from alpine to jessie-slim changed where ansible-playbook
is installed; I forgot to update the default CMD in the Dockerfile
accordingly in my previous commit.
> fix bug in default CMD introduced in PR-4052

- tests/src/test/scala/whisk/core/database/LimitsCommandTests.scala
- tools/admin/src/main/scala/whisk/core/database/LimitsCommand.scala
`limits` command in `wskadmin-next` currently uses incorrect names i.e. order of name is incorrect. Thus `firesPerMinute` was being set as `concurrentInvocations`
Thanks to @asteed  for noticing this!
> Ensure that limits are set properly

- common/scala/src/main/scala/whisk/core/database/StoreUtils.scala
Sometime the exception message is null which leads to log message like `'activations' internal error, failure: 'null'`
```
[2018-10-11T06:46:11.034Z] [ERROR] [#tid_bASVetECuqu481V6WTm0f35UhQzqV2Zd] [StoreUtils] [QUERY] 'activations' internal error, failure: 'null' [marker:database_queryView_error:120:120]
```
To get more context of the actual exception it would be useful to also include the exception class. Post this the log would be like
```
[2018-10-12T09:00:39.758Z] [ERROR] [#tid_sid_testing] [StoreUtils] Test null [RuntimeException] [marker:database_getDocumentAttachment_error:739:29]
```
> Include exception class in failure message from ArtifactStore

- common/scala/src/main/resources/application.conf
- tests/src/test/scala/common/WhiskProperties.java
- tests/src/test/scala/system/basic/WskActionTests.scala
With current setup reading code attachment more than 8 MB results in error (#4028). Increase `max-content-length` to 50 MB allows reading code attachments upto maximum allowed 48 MB
Akka uses [max-content-length][1] to ensure limits on incoming request entities. By default it is 8 MB while OpenWhisk allows max code upto 48 MB. To enable such large action code as attachment increase the max-content-length to 50 MB
This PR also adds a system basic test to ensure that such large actions can be created. Due to constrained resource on travis test only create action code upto 10 MB. However it can be increased via config by setting system property `whisk.action.size.max` (in MB)
This test would also help to validate if the proxy and other settings are properly configured. See #3712 for details …
> Increase max-content-length to 50 MB

- common/scala/transformEnvironment.sh
Change config location to work with non root user support which was added in #3579
With the invoker and controller now having a new user (though invoker is still running as root), we need to put the config file within the new user's home directory to maintain the access when not using the root user.
> Change config location to work with non root user

- core/routemgmt/common/apigw-utils.js
- tests/src/test/scala/whisk/core/cli/test/ApiGwRestTests.scala
Closes #4055 
Bug creating api for apigateway doesn't append request.path
Issue #4055
> apigateway should always append request.path if response type is http

- ansible/roles/nginx/tasks/deploy.yml
>  Fixes jinja warning from controller playbook

- core/controller/src/main/scala/whisk/core/controller/CorsSettings.scala
- core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
- core/controller/src/main/scala/whisk/core/controller/WebActions.scala
- docs/rest_api.md
- docs/webactions.md
- tests/src/test/scala/services/HeadersTests.scala
- tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
- tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
As summarized in #4045, the previous #4010 PR, which changed Access-Control-Allow-Headers from a 2-element list to a wildcard was misguided. Despite whatwg introducing wildcard support in 2016, only Chrome as of yet supports this feature. So, for now, we need to back off to a specifically enumerated list of allowed headers. This PR reverts the wildcard change, but expands the list from the initial 2 to include a few more common headers, e.g. User-Agent.
Fixes #4045
> update Access-Control-Allow-Headers to enumerate rather than wildcard

- tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
These two tests are failing intermittently in our pipeline and travis. But unfortunately I'm not able to reproduce the problem locally.
But my theory, why these tests fail is the following:
The two commands `suspend` and `resume` are returning Futures. My theory is, that these asynchronous calls are not finished, when we check if the methods inside these methods have been called.
> Fix mock-verification in Container-tests.

- common/scala/src/main/scala/whisk/common/Logging.scala
- core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
- core/invoker/src/main/scala/whisk/core/containerpool/docker/ProcessRunner.scala
- docs/metrics.md
- tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
- tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
- tests/src/test/scala/whisk/core/containerpool/docker/test/ProcessRunnerTests.scala
- tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Provide more diagnostic information for Docker command failures as well as timeouts. Also emit new counter metrics for timed out Docker commands.
This change improves diagnostic information for failing Docker commands as well as timed out Docker commands:
* For all failures (including timeouts), a textual representation for exit status values is logged.
* Timeouts are explicitly detected and reported using a specialized exception allowing for a better timeout handling on higher layers of the Docker container implementation.
This change introduces a set of new counter metrics that are emitted if a Docker command is terminated because of a timeout. A high number of such timeout occurrences is usually an indication for highly loaded invokers. The new metrics help to identify such invokers.
> Diagnostic info + metrics for Docker command failures and timeouts

- tests/src/test/scala/system/basic/WskActionTests.scala
PR #3950 broke CLI tests in repo https://github.com/apache/incubator-openwhisk-cli because these tests override `val wsk` with a CLI specific implementation of type `Wsk` instead of `WskRestOperations`.
This change makes sure that `val wsk` has the common parent class `WskOperations`.
> Fix broken CLI tests

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-go.md
- tests/dat/actions/unicode.tests/go-1.11.txt
Tests and config to include the go runtime
> changes to include gloang runtime

- ansible/group_vars/all
the performance test stage has being failing lately in travis, intermittently 
running locally with default setting the rps on many runs is always 1 request per second.
increasing the memory I got around 7rps
```
OPENWHISK_HOST="172.17.0.1" USERS="1" REQUESTS_PER_SEC="1" ./gradlew gatlingRun-ColdBlockingInvokeSimulation
```
> increase default invoker memory available for user actions to 2GB

- ansible/files/runtimes.json
fix go indentation in runtimes.json
> fix go indent in runtimes.json

- core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
- tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
If an user invokes an action blockingly today, the invoker executes the activation and sends back the result to the controller, which passes it back to the client. If it is not possible to pass the result back to the controller, it will try to get it from the database. And here's the problem. If the controller receives the result of the activation from the invoker, there are no logs included. If it polls it from the database, the logs are included. This should be unified to never return logs.
> Always return activation without log on blocking invoke.

- ansible/roles/controller/tasks/deploy.yml
With the change https://github.com/apache/incubator-openwhisk/pull/3579, controller logs file was not being created due to lack of permissions when OW is deployed on docker-machine. This is because ansible is not able to create a folder with full permissions within a mounted folder in docker-machine. However creating a file with full permissions through ansible does work.
> Fix controller logs in docker-machine

- ansible/group_vars/all
Redis 4.0 was GA in mid-2017 and is the current maintained production stream for Redis.
> update from redis 3.2 to 4.0

- common/scala/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
Spray Json released a new version 1.3.5 which has [few security fixes](https://discuss.lightbend.com/t/spray-json-1-3-5-security-fix-released/2663)
> Update to Spray-json 1.3.5 security fix release

- common/scala/build.gradle
- common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosTask.scala
When task launch times out, cleanup tasks that were sent to mesos (or not yet sent).
Also updating mesos-actor which includes a fix for accepting resources that are not assigned to the frameworks role.
> update mesos-actor; cleanup orphaned failed task launches

- common/scala/src/main/scala/org/apache/openwhisk/core/database/MultipleReadersSingleWriterCache.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Identity.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreSubjectQueryBehaviors.scala
Cache negative auth responses to avoid going to the DB with every identical call 
Since negative auth responses (Identity.get) are not cached, 
all requests with a non existing namespace or an invalid authkey will perform queries to the subject db.
A user can influence OW performance by issuing a high number of those calls.
ThIs PR changes that behavior in the way, that negative auth results are cached as None value.
Subsequent Identical calls will only use the cache (for the 5 minutes cache period).
The external interface and behavior of the Identity.get methods stays unchanged.
> Cache empty auth results to reduce db load

- common/scala/build.gradle
Excludes some of the transitive dependencies which are not used at runtime saving 14MB in disk space. 
Some of the dependencies can be excluded from build as they would not be used. The dependencies were analyzed via following command
```
./gradlew :core:controller:dependencies --configuration runtime
```
pureconfig transitively pulls in scala compiler  pureconfig/pureconfig#433
```
+--- com.github.pureconfig:pureconfig_2.12:0.9.0
|    +--- org.scala-lang:scala-library:2.12.4 -> 2.12.7
|    +--- com.github.pureconfig:pureconfig-macros_2.12:0.9.0
|    |    +--- org.scala-lang:scala-compiler:2.12.4
|    |    |    +--- org.scala-lang:scala-library:2.12.4 -> 2.12.7
|    |    |    +--- org.scala-lang:scala-reflect:2.12.4
|    |    |    |    \--- org.scala-lang:scala-library:2.12.4 -> 2.12.7
| …
```
> Exclude unused transitive dependencies

- docs/actions.md
When trying to get the action activation, we tried to copy&paste a sample from here. There is a typo in one place, the correct parameter is called `activation` not `activations`.
> Fix typo (activations->activation)

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-nodejs.md
- docs/actions.md
- docs/concurrency.md
- tests/dat/actions/unicode.tests/nodejs-10.txt
Add nodejs:10 to default set of runtimes
> Add nodejs:10 to default set of runtimes for ansible/vagrant

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
To send metrics on system overload condition in order to visualise it as graph on Metrics dashboard.
> Send system overload metric from Controller

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
On invoking an action blocking, a ResultMessage and afterwards a CompletionMessage will be sent from the invoker to the controller. The CompletionMessage is always very small. Currently those two messages are sent asynchronously. If log-collection is very fast, they are sent to Kafka at the same point in time.
This could result into the condition, that the loadbalancer receives the completion-ack before the result ack. This will make the response to the customer slower, as the controller first needs to go against Kafka.
This PR will ensure, that the completion message will be sent after the reult message has been published successfully to Kafka.
> Ensure, that Result-ack is sent before Completion-ack.

- ansible/group_vars/all
The default tag for all openwhisk project docker images on the master branch should be `latest` so that we are always testing against our own latest code.  Operators can override to pin versions as desired in their own deployments.
> Use `latest` as default tag for apigateway

- tests/src/test/scala/common/WskCliOperations.scala
This fixed the `WskCliOperations` test utility which currently accepts concurrency parameter, but does not pass it to wsk cli.
> missed the -c arg for wsk cli tests around concurrency

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
In order to keep the Invoker health test's action with a minimalistic memory, the value of memory limit is changed from the standard memory config to the minimum available memory. This helps in consuming the resource in minimal way possible and would suppress the Rescheduling run message occurrence due to health test.
> Reduce invoker health action memory limit to 128MB

- tests/build.gradle
As part of package rename done in #4073 the pattern for system basic tests was incorrectly set to `             "org/apache/openwhisk/testEntities/system/basic/**` instead of `system/basic/**`. As the package name for system basic test was not changed this PR reverts the change in pattern there
> Fix pattern for system basic tests

- common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Packages.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/PackageCollection.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
We ran across an issue where a package binding can contain a reference to itself. When this happens, any attempt at reading the package results in an infinite loop, eventually leading to the controller falling over. This can occur by simply performing the following commands using the `wsk` tool.
```bash
$ wsk package create target
$ wsk package bind target binding
$ wsk package bind binding binding
```
There are two changes contained in this PR
1. Prevent allowing an incoming binding update to point to itself as a reference, which previously created an invalid data record.
2. Prevent following a package's binding reference when it points to itself which causes the infinite loop.
> Protect Package Bindings from containing circular references

- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/KindRestrictor.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/KindRestrictorTests.scala
When performing `KindRestrictor.check()`, merge the contents of both the namespace's `allowedKinds` limit with the system's default `whitelist` of allowed kinds.
Originally, the namespace's value for the `allowedKinds` limit was used _instead of_ the value of the default `whitelist` set for the system. However, while crafting a deployment plan enabling whitelist support, we ran into concerns around maintaining these per-namespace whitelists as the system and user/namespace population grows.
The most notable scenario of concern is when a kind is added or removed from the OW system's runtime manifest. After these are added to the manifest, any existing default `whitelist` will need to be updated to include/exclude the new kind. This is an expected maintenance operation. However, in addition …
> Update KindRestrictor to merge namespace and default whitelists

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
As `processCompeltion` and `processResult` is executed asynchronously, it's better to ensure `ResultMessage` will be processed in any case
> Ensure ResultMessage is processed

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- tests/src/main/scala/org/apache/openwhisk/GradleWorkaround.scala
Updates to version 4.10.2 (from 4.8.1). This brings some improvement in [maven publishing](https://docs.gradle.org/4.9/release-notes.html) which would be useful for us in publishing our artifacts
See release notes [here](https://gradle.org/releases/)
> Update to Gradle 4.10.2

- tools/scriptRunner/Dockerfile
Prepare for wskdeploy being used to install catalog
by including wskdeploy cli in this image (which is used
to install the catalog in the kube-deploy project).
> add wskdeploy to scriptRunner Dockerfile

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/Collection.scala
Make limits related to list operation against entities configurable. 
Currently the queries related to collections (used while doing list operation) make use of hard coded limits. 
For example if `limit=0` in list operation then it uses 200 has the default value. This is used in `wsk activation poll` which by default generates a GET request like
```
/api/v1/namespaces/_/activations?docs=true&limit=0&since=1542422386538&skip=0
```
Currently the poll command once started "probably" sticks to start time and we have seen user leaving such poll running for days (often left in one of the numerous tabs!) which causes the system to pull similar 200 records over and over.
Further in our case (using CosmosDB) which does client side merging of query results a sorted query gets executed like below
1. …
> Make query limits configurable

- ansible/group_vars/all
- ansible/roles/apigateway/tasks/deploy.yml
- ansible/roles/redis/tasks/deploy.yml
Currently default openwhisk (apigateway) setup doesn't secure Redis with password.
This PR adds password protection to Redis ansible
> Making Redis password protected

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
When enabling `ActionLimits.concurrency`, the ActionsApi was not updated to propagate specified concurrency limit during action updates (concurrency limit was only set during create)
This PR fixes that, and adds a test.
> Concurrency limit updates

- common/scala/build.gradle
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosContainerFactory.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
In case of mesos master failover, we need to reconnect to master by re-subscribing.
> mesos - expose config for setting heartbeatMaxFailures to reconnect after master failover

- docs/actions-dotnet.md
wsk CLI uses .zip to indicate in the metadata of the action to say `binary:true`
> update dotnet doc to use .zip with wsk cli

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-new.md
- docs/actions-php.md
- tests/dat/actions/unicode.tests/php-7.3.txt
Add support for the new PHP 7.3 runtime.
> Add PHP 7.3 runtime

- common/scala/src/main/scala/org/apache/openwhisk/core/database/DocumentFactory.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
@tysonnorris notices with concurrent action invocation scenario that same attachment is being fetched multiple times in case of cache miss. 
If multiple request try to load an action with attachment which is not present in cache then currently it leads to multiple request to load the same attachment from backing store. This PR adds a new test which demonstrate this behavior. This test would try to concurrently read action (5 threads). Without fix you would see logs like below which show that attachment is being read multiple times
```
db logs [2018-12-17T08:50:49.800Z] [DEBUG] [#tid_7] [LocalEntitlementProvider] checking user 'anon-nKWrAIa7elnkH4XMmEEsb75ZB9v' has privilege 'READ' for 'actions/anon-nKWrAIa7elnkH4XMmEEsb75ZB9v/action_tests_name2'
[2018-12-17T08:50:49.800Z] [DEBUG] [#tid_6] …
```
> Ensure cache gets properly updated with concurrent access for action with attachments

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
- docs/reference.md
Makes the exec hard coded 48 MB limit configurable. 
In our setups we may want to reduce the max size at controller level hence need to make it configurable. 
Note that for supporting higher value changes in other places would also be needed. See #3712 for more details
> Make exec aka code max size configurable

- ansible/logs.yml
- tests/performance/gatling_tests/src/gatling/resources/conf/logback.xml
High volume of Gatling failure logs from `io.gatling.http.ahc` category causes the Travis to terminate the build. Avoid that by routing those logs to a file
In many travis runs its being seen if the performance test fail for some reason then they may flood the logs so much that Travis [terminates the build](https://travis-ci.org/apache/incubator-openwhisk/jobs/461548522)
To enable investigating such issues we need server logs and hence need travis to complete. To enable that logs are now routed to a file and that file is made part of log collection
> Route Gatling failure logs to file

- tools/admin/build.gradle
After the openwhisk package renames from `whisk.*` to `org.apache.openwhisk.*` the main classname for `wskadmin-next` needs to be updated to reflect the change.
> Update main class for `wskadmin-next` due to package renames

- common/scala/build.gradle
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
Updates Kamon to 1.x release (1.1.3) from current 0.6 version
Going forward I would like to enable metrics reporting via Prometheus. [Kamon Prometheus][1] support was added with Kamon 1.0 series. Hence the need to update Kamon
[Kamon 1.0][2] was a major release involving some breaking changes which needs some [migration work][3]
[1]: https://kamon.io/documentation/1.x/reporters/prometheus/
[2]: https://kamon.io/teamblog/2018/01/18/kamon-1.0.0-is-out/
[3]: https://kamon.io/documentation/1.x/recipes/migrating-from-kamon-0.6/
> Update to Kamon 1.1.3 from 0.6 series

- common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KafkaMessagingProvider.scala
The KafkaMessagingProvider does not handle KafkaExceptions that are thrown when creating the admin client. Not handling these exceptions kills the invokers main thread (see stack trace below).
```
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:370)
at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:52)
at org.apache.openwhisk.connector.kafka.KafkaMessagingProvider$.ensureTopic(KafkaMessagingProvider.scala:63)
at org.apache.openwhisk.core.invoker.Invoker$.main(Invoker.scala:156)
at org.apache.openwhisk.core.invoker.Invoker.main(Invoker.scala)
```
> Handle kafka exception thrown when creating the admin client

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
Fixes #4203. 
This PR implements the following recommendation for Kamon usage
> When possible, define and refine your metrics up front, as a static member or instance members on the instrumented components of your services. This saves a bit of time in looking up instruments.
Now the Metric instances are stored as part of `LogMarkerToken` and reused for later updates
> Optimize Kamon metric update flow

- common/scala/src/main/scala/org/apache/openwhisk/http/BasicHttpService.scala
The authentication SPI can be used to provides multiple parallel ways to authenticate against Open Whisk by combining different authentication directives (e.g Basic and Bearer authentication).
The unmatched authentication directives (only one directives will match for agiven request) 
are adding additional authentication rejections to the overall list of rejection collected for a given request.
Depending on the evaluation sequence of the additional validation rejections will overshadow meaningful validation rejections following the matched case.
This patch gives those validation rejections priority over the authentication rejections. 
In this way a meaningful error messages are returned to the user. 
An equivalent mechanism is already implemented for content type related rejections.
> Correct rejection behavior in the multi authentication case

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreProvider.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBUtil.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfigTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBTestSupport.scala
Currently same CosmosDB client is used for all collections. This PR enables configuring separate client having different config on per collection basis.
Depending on requirements it may be required to configure `AsyncDocumentClient` on per collection basis. For e.g. to use different config for each collection use following config
```
cosmosdb {
endpoint          =  "https://<account>.documents.azure.com:443/"
key               =  "secret"             # Access key
db                =  "openwhisk"            # Database name
throughput        = 1000          # Throughput configured for each collection within this db
consistency-level = "Session"
connection-policy {
max-pool-size = 1000
using-multiple-write-locations = false
preferred-locations = []
retry-options { …
```
> Enable configuring CosmosDB client per collection

- common/scala/build.gradle
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
Enables capturing jvm metrics and exposing them via [Kamon System Metrics][1] module. This would help to understand the GC usage
This PR only enables the JVM level metrics and not the host level metrics. Such metrics would help to understand the GC nature of Controller and Invoker processes
```
gauges:
{ 'statsd.timestamp_lag': 0,
'openwhisk-statsd.controller0.jvm_memory_buffer-pool_usage.component.system-metrics.measure.capacity.pool.mapped': 0,
'openwhisk-statsd.controller0.jvm_memory_buffer-pool_usage.component.system-metrics.measure.used.pool.mapped': 0,
'openwhisk-statsd.controller0.jvm_memory_buffer-pool_usage.component.system-metrics.measure.capacity.pool.direct': 472638,
'openwhisk-statsd.controller0.jvm_memory_buffer-pool_usage.component.system-metrics.measure.used.pool.direct': …
```
> Enable Kamon System Metrics module

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainerFactory.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerClientTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerArgsConfigTest.scala
Allow configuration of the --dns-search and --dns-opt (--dns-option)
arguments to the docker run command of the DockerContainerFactory.
Motivated by better support of event providers in Kubernetes when
using the DockerContainerFactory.
> additional container factory dns configuration

- core/routemgmt/common/apigw-utils.js
When creating an API with a specified namespace, the "wsk api create" command will override the namespace with the "__ow_user" value which is not the intended namespace.
> during api create, correctly handle non-default (i.e. "_") namespaces

- tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
- tools/db/replicateDbs.py
When using `replicateDbs.py`, document update conflict errors may occur when the `_replicator` database already contains a document of the same name that is being replicated. When replicating a document that already exists in `_replicator`, these changes add the `_rev` ID from the existing document to the document being replicated.
Stack trace from test failure:
```
org.apache.openwhisk.core.database.test.ReplicatorTests > Database replication script should continuously update a database STANDARD_OUT
Removing database: replicatortest_whisk_local_database_for_continous_replication
Creating database: replicatortest_whisk_local_database_for_continous_replication
Running replicator: omitted, omitted, replicatortest_whisk_local_, 10 minutes, true, List(), List()
expected exit code = 0
exit …
```
> Avoid Database Replicator Failures

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosTask.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainer.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
In testing concurrent actions (multiple activations in same container) we noticed that when a container is used after `Container.suspend()`, the http connection may be re-created multiple times (and may have side affects of losing connections each time a new one is created.
This PR addresses this by:
- using a separate function for creating the connection - this will be invoked first during /init
- same function will be invoked again during `Container.resume()` (which means that subclasses must invoke `super.resume()`)
This way the subsequent + multiple calls to /run will arrive after connection has already been recreated.
I extended the ContainerProxyTests to assert connection state (exists or not) after `suspend()` and after `resume()`.
> recreate http client on resume()

- common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Identity.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/SequenceActions.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/limits/ThrottleTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/admin/WskAdminTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/LimitsCommandTests.scala
- tools/admin/README-NEXT.md
- tools/admin/README.md
- tools/admin/src/main/scala/org/apache/openwhisk/core/database/LimitsCommand.scala
- tools/admin/wskadmin
With this PR, operators will be able to disable storing of activations into activations store.
The flag is implemented like the per-namespace-limits. It can be set with wskadmin.
This PR was the initial idea of #4078. In the meantime, the idea in the other PR changed, to implement a throttle instead of a switch. But as this is a completely new type of rate-limit (which does not only allow or deny requests) that's a bit bigger to implement. So I'll go with a staged approach here and implement it as switch first.
If someone needs a throttle instead of completely switching off the writes to the DB, this can be brought up again and the throttle can be built up on the solution we already have.
> Add limit to not store activations for a limitted namespace.

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
To send metrics on system overload condition, capacity in flight v/s total and count of healthy, unhealthy, unresponsive and down invokers (managed and blackbox separately) in order to visualise it as graph on Metrics dashboard.
> Send capacity, system overload metrics for managed and blackbox invokers separately

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PollingFromDbTests.scala
Complete blocking activations immediately when a Left(activationId) is returned and controllerActivationConfig.pollingFromDb is false, otherwise this invocation will wait until timeout
> Complete blocking activations immediately

- ansible/group_vars/all
- ansible/roles/cli-install/tasks/deploy.yml
- ansible/roles/nginx/tasks/deploy.yml
- ansible/roles/nginx/templates/nginx.conf.j2
- tests/src/test/scala/system/rest/GoCLINginxTests.scala
Reverts apache/incubator-openwhisk#4252
We got reports from a downstream that this change broke based on some assumptions where they get the `wsk` binary location.
```
line 52: /home/<user>/workspace/Playground2/open/bin/wsk
```
Reverting to take another look and maybe put a verification step to make sure Travis catches this
> Revert "Mount an optional html directory for serving static content."

- ansible/group_vars/all
Bump the ephemeral CouchDB version to 2.3.  Version 2.1 apache image (in current use) fails when mounting external data storage file systems set up with different uids than the docker daemon.
> Bump ephemeral couchdb to v2.3

- ansible/roles/redis/tasks/deploy.yml
Rather than `echo`ing to `nc`, take advantage of `docker run` to use `redis-cli` to test that redis is running during the ansible deployment.
> Use redis-cli (via docker) to test status of Redis in ansible PING-PONG

- ansible/group_vars/all
- ansible/roles/nginx/tasks/deploy.yml
This PR cleans up some config parameters in `group_vars/all`-file of ansible, taht are not used anymore.
> Remove unused ansible parameters in group_vars/all file.

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreProvider.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupport.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfigTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupportTests.scala
Enables specifying [Time to live][1] at collection (or container level). 
For collection like `Activations` its desirable to expire the activations after some time. For CouchDB this is done by running a [cleaner script][2]. For CosmosDB we can make use of the [TTL][1] support which allows auto removal of entries after the TTL time has passed after their last modified time.
So to specify TTL for activations
```
whisk {
cosmosdb {
collections {
WhiskActivation {
time-to-live = 30 days
}
}
}
}
```
This PR also now sets the default TTL to -1 which allow us to later specify TTL at individual item level if required.
[1]: https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live
[2]: https://github.com/apache/incubator-openwhisk/blob/master/tools/db/cleanUpActivations.py
> Add support for TTL at collection level with CosmosDB

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/limits/ConcurrencyTests.scala
Move concurrent activation count tracking from ContainerProxy -> ContainerPool, so that prewam/cold -> warm can be tracked as `WarmingData` and receive activations to avoid spawning extra containers.
This adds a new ContainerData `WarmingData`, used for routing concurrent incoming activations to a ContainerProxy that is initing (from prewarm or cold), up to max concurrency.
> Track activation counts in ContainerPool (not ContainerProxy)

- ansible/group_vars/all
- ansible/roles/couchdb/tasks/deploy.yml
For example:
`wskdev couchdb -d -e"db_persist_path=/home/couchd/openwhisk"`
~Also should fix #4236.~ (fix moved to #4262).
> Allow persisted couchdb directory mount.

- common/scala/build.gradle
PR to enable Prometheus (#4227) support excluded the dependency on [Nano HTTP](https://github.com/NanoHttpd/nanohttpd) server. This causes `NoClassDefFoundError` upon shutdown. 
```
[2019-02-13T11:33:00.245Z] [INFO] [#tid_sid_unknown] [Invoker] Shutting down Kamon with coordinated shutdown
Exception in thread "kamon.prometheus.PrometheusReporter" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: fi/iki/elonen/NanoHTTPD
at kamon.prometheus.PrometheusReporter.stopEmbeddedServer(PrometheusReporter.scala:91)
at kamon.prometheus.PrometheusReporter.stop(PrometheusReporter.scala:48)
at kamon.ReporterRegistry$Default.$anonfun$stopMetricReporter$2(ReporterRegistry.scala:279)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at …
```
> Include nanohttpd to avoid class not found error on stop

- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Add additional debug information for intermittently failing ContainerProxyTests
The `ContainerProxyTests` are failing intermittently in the pipeline. All of these intermittent test failures have either a wrong initialisation-time or it is missing completely.
Our theory currently is, that the Buffer in `acker` is called in the wrong order, as these calls are made asynchronously. If that theory is correct, this can be proven with this additional output.
Unfortunatly I was not able to reproduce the error locally.
> Add additional debug information for intermittently failing ContainerProxyTests

- ansible/roles/routemgmt/files/installRouteMgmt.sh
- core/routemgmt/createApi/package.json
- core/routemgmt/deleteApi/package.json
- core/routemgmt/getApi/package.json
Modify the apimgmt package's actions to support nodejs:10
Modify the apimgmt package's actions to support nodejs:10, which will soon be the default nodejs runtime for nodejs actions. The nodejs:10 runtime no longer provides the NPM packages the nodejs:6 runtime did, so each apimgmt action must be packaged (zipped) with its dependent NPM packages.
Existing test cases will be sufficient to validate the new packaging is correct.
> package nodejs dependencies into routemgmt actions

- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
As the active ack is sent asynchronously in the invoker, it could happen, that the order of them is wrong in the ContainerProxyTest. This has been proven with the following debug information: https://github.com/apache/incubator-openwhisk/pull/4278
This PR makes these tests more stable by not relying on the order of active acks.
> Make ContainerProxyTests more stable.

- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
Disables some of test which are failing with switch to CosmosDB v2.4.0. These tests are now being tracked with #4286
Fixes #4283
> Disable test failing with CosmosDB v2.4.0

- common/scala/src/main/scala/org/apache/openwhisk/common/ConfigMXBean.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- tests/src/test/scala/org/apache/openwhisk/common/ConfigMXBeanTests.scala
This PR adds an MBean which enables dumping the typesafe config including details from where config is getting picked up. This is useful to troubleshoot config issues and confirm if the intended config is being picked up properly.
This PR registers an MBean which enables fetching typesafe config at specific path like `whisk.kafka`. It acceps a second boolean param which enables dumping of location information from where config value was picked up
```scala
trait ConfigMXBean {
def getConfig(path: String, originComment: Boolean): String
}
```
The MBean is registered with name `org.apache.openwhisk:name=config`
```bash
$ docker exec -it xxx bash # Open bash shell to controller docker container
#calling operation getConfig of mbean org.apache.openwhisk:name=config with params [whisk.spi, …
```
> MBean to dump config information at a path

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfigTests.scala
Enables configuring the connection mode via configuration. It currently defaults to `Gateway`. See [ConnectionMode](https://github.com/Azure/azure-cosmosdb-java/blob/master/commons/src/main/java/com/microsoft/azure/cosmosdb/ConnectionMode.java) for details
Fixes #4269
> Enable configuring Connection Mode for CosmosDB

- tools/jenkins/apache/dockerhub.groovy
This attempts to fix Jenkins failure:
```
> Task :common:scala:compileScala
/home/jenkins/jenkins-slave/workspace/OpenWhisk-DockerHub/common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala:79: Cannot find JsonReader or JsonFormat type class for Map[String,Set[org.apache.openwhisk.core.entity.ExecManifest.RuntimeManifest]]
.map(_.convertTo[Map[String, Set[RuntimeManifest]]].map {
^
/home/jenkins/jenkins-slave/workspace/OpenWhisk-DockerHub/common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala:81: type mismatch;
found   : Any
required: String
Note: implicit value runtimeManifestSerdes is not applicable here because it comes after the application point and it lacks an explicit result type
RuntimeFamily(name, versions.map { mf =>
^ …
```
> Run a clean step before build.

- tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecHelpers.scala
Modifies `YARNContainerFactoryTests` to use the runtime tags provided in a deployment's runtime manifest instead of using the `latest` tag. Using the `latest` tag for runtimes is problematic as a deployment may use tags other than `latest`.
Failure example:
```
java.util.NoSuchElementException: key not found: ImageName(nodejs6action,Some(openwhisk),Some(latest))
at scala.collection.MapLike.default(MapLike.scala:231)
at scala.collection.MapLike.default$(MapLike.scala:230)
at scala.collection.AbstractMap.default(Map.scala:59)
at scala.collection.MapLike.apply(MapLike.scala:140)
at scala.collection.MapLike.apply$(MapLike.scala:139)
at scala.collection.AbstractMap.apply(Map.scala:59)
at org.apache.openwhisk.core.yarn.YARNContainerFactory.createContainer(YARNContainerFactory.scala:131)
at …
```
> Use runtime tags specified in runtime manifest for YARNContainerFactoryTests

- tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecHelpers.scala
Restores the intent of using a custom manifest with YARN container tests. This decouples the YARN tests from runtimes supported by a deployment. Seeing https://github.com/apache/incubator-openwhisk/pull/4305#pullrequestreview-207940815 for additional information.
> Use custom runtime manifest for YARN tests

- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
Collect and logs CosmosDB query metrics when extra logging is enabled
Fixes #4268
if a request is performed with `X-OW-EXTRA-LOGGING` header set to `on` like below
```
curl -k --user "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP" \
-H "X-OW-EXTRA-LOGGING: on" \
"https://172.17.0.1:10001/api/v1/namespaces/_/activations?limit=30&skip=0"
```
Then in the logs following entries would logged which provide detailed insight into how query is executed by CosmosDB
```
[2019-02-13T14:11:48.689Z] [INFO] [#tid_FUn23vWbEbEQBFi5rIcioaZJkB4a2Wfw] [CosmosDBArtifactStore] [QueryMetricsEnabled] Collection [subjects] - Query [SELECT r AS view FROM root r JOIN n in r.namespaces WHERE (NOT(IS_DEFINED(r.blocked)) OR r.blocked = false) AND ((r.uuid = @uuid …
```
> Collect and log CosmosDB query metrics when extra logging is enabled

- tests/src/test/scala/system/basic/WskRestRuleTests.scala
If there is an deployment with several controllers, the test `Whisk rules should preserve rule status when a rule is updated` fails intermittently. The reason is, that there are several modifications on the rule. These modifications are already retried. But enabling and disabling the rule also modifies the database document. But that change is currently not retried.
This PR puts the enabling/disabling of the rule into the retry block as well to make this test more stable against our eventual consistency.
Co-authored-by: Somaya Jamil <jamilsom@de.ibm.com>
> Make WskRestRuleTests more stable.

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBUtil.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfigTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBStoreBehaviorBase.scala
Enables storing the clusterId information as part of document json in db.
For Multi Region deployments (#4277) we need to differentiate which cluster made change to a document while emitting the cache invalidation event. This PR enables storing a `_clusterId` attribute which can be configured to uniquely identify current cluster. 
Later this attribute can be used by the cache invalidation service to filter out changes which are done by same cluster and only convert those changes from other cluster to local cache invalidation kafka topic
> Record clusterId performing change in CosmosDB

- common/scala/build.gradle
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
Updates CosmosDB to 2.4.2 (from 2.4.0) as it has some [fixes related to cross partition queries](https://github.com/Azure/azure-cosmosdb-java/tree/master/changelog#242)
Couple of changes in this PR
1. Update to CosmosDB SDK 2.4.2
2. Removes support for storing attachment in ComsosDB and requires an external AttachmentStore to be configured. (Fixes #4286)
3. Reduces the configured throughput for test runs to 400 from current 1000. Would save some money!
> Update CosmosDB to 2.4.2

- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/controller/templates/config.j2
- ansible/roles/invoker/tasks/deploy.yml
- ansible/roles/invoker/templates/config.j2
This PR builds up on #4039 to allow passing config string as part of ansible deployment step
PR #4039 enabled support for passing config string encoded as base64 via `OPENWHISK_ENCODED_CONFIG` env variable. This PR extends that and adds base empty templates which can be modified to pass in such config in ansible deployments. Currently the config templates are empty and we can decide later to port existing or newer config via this mechanism
> Enable passing config string as part of ansible scripts

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Parameter.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- docs/actions.md
- docs/annotations.md
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackageActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
- tests/src/test/scala/system/basic/WskActionTests.scala
- tests/src/test/scala/system/basic/WskRestBasicTests.scala
See https://github.com/apache/incubator-openwhisk/issues/4226. Note that this is a breaking change - actions that are deployed need to be updated to add this annotation.
Closes #4226.
> Add an annotations to inject the API key into the action context.

- tests/src/test/scala/system/basic/WskConsoleTests.scala
A CLI test suite that inherits from `WskConsoleTests` is failing due to recent API key security changes. Updating the `show repeated activations` console test to include an API key in the corresponding test action as that action uses the OpenWhisk Node.js client.
Test failure:
```
system.basic.WskCliConsoleTests > Wsk Activation Console should show repeated activations STANDARD_OUT
check failed for activation 89bebcccd79b4c61bebcccd79bbc61a4: {"activationId":"89bebcccd79b4c61bebcccd79bbc61a4","annotations":[{"key":"path","value":"guest/countdown-1552068139417"},{"key":"waitTime","value":27},{"key":"kind","value":"nodejs:6"},{"key":"timeout","value":false},{"key":"limits","value":{"concurrency":1,"logs":10,"memory":256,"timeout":60000}},{"key":"initTime","value":271}],"duration":302,"end":1 …
```
> Set API key annotation for a WskConsole test

- common/scala/src/main/scala/org/apache/openwhisk/http/BasicRasService.scala
Disables the info level logging for `/metrics` endpoint
Currently if we enable the Prometheus support (#4227) then following logs are logged upon each pull by Prometheus. This creates noise and hence should be disabled by logging such data at debug level like its being done for health check endpoint (`/ping`)
```
[2019-03-11T09:47:00.149Z] [INFO] [#tid_ZjiVLdaB6c3EZjFAMM13cgsyBpZiDj4Z] [BasicHttpService] [marker:http_get.404_count:35:35]
[2019-03-11T09:47:08.266Z] [INFO] [#tid_5Rs71DH03wKCwGPG6wGrgaStDNQGTpNB] GET /metrics 
[2019-03-11T09:47:08.272Z] [INFO] [#tid_5Rs71DH03wKCwGPG6wGrgaStDNQGTpNB] [BasicHttpService] [marker:http_get.200_count:2:2]
[2019-03-11T09:47:08.844Z] [INFO] [#tid_RsMjOrwwPCwgzandGi2PxIGg7alOtlMk] GET /metrics 
[2019-03-11T09:47:08.852Z] [INFO] …
```
> Disable info level logging for Prometheus Metrics endpoint

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KafkaConsumerConnector.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
This PR introduces an abstraction for [Kamon Gauge](https://kamon.io/docs/latest/core/metrics/#gauges)
As mentioned in #4311 at some places we are using Histogram to track metric which should instead be tracked as Gauge. This PR converts such usage to Gauge based
> Use Gauge metric instead of Histogram where applicable

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/FeatureFlags.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
Enables support for feature flags which for now is used to enable or disable support for `provide-api-key` (#4284)
With #4284 support was added for `provide-api-key` annotation. In some cases we may want to enable this feature later. This PR introduces a feature flag support which allow disabling such feature based on config. To disable this feature use config like below
```
whisk {
feature-flags {
require-api-key-annotation = false
}
}
```
> Feature flag support to turn on/off support for provide-api-key annotation

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/SplunkLogStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/SplunkLogStoreTests.scala
There is currently an issue with `SplunkLogStore` that assumes that all JSON objects received from Splunk API should always contain these fields: `log_timestamp`, `log_stream` and `log_message`.
The problem occurs when trying to get the logs using: 
```
wsk activation logs $activation_id
```
as Splunk sometimes sends empty JSON objects. 
This PR handles the `NoSuchElementException`, displays an error message and allows the retrieval of all the other log messages for that particular activation. 
More details about the the issue here: #4347
> Fixes the issue of failing to read empty Splunk JSON objects

- tests/src/test/scala/system/basic/WskSequenceTests.scala
A test entitled `propagate execution error (timeout) from atomic action to sequence` is failing intermittently with an abnormal initialization error instead of an action timeout error. Since the action that is meant to fail will never complete the init phase, the socket responsible for performing the init may timeout resulting in the abnormal initialization error instead of an action timeout error. Changes here allow for either error message to be returned in the activation record.
Invoker log showing the init socket connection timing out:
```
[2019-03-14T04:00:22.911Z] [INFO] [#tid_36f2cb1fe73426dfa3a4f5738e4e990a] [ContainerPool] containerStart containerState: recreatedPrewarm container: Some(ContainerId(0a2e30bb9aa6a91767c247c3ff59c2a0ad81c698815a2ebccd4e67573c7d8aaf)) activations: 1 …
```
> Fix intermittent test failure related to sequence execution error propagation

- ansible/group_vars/all
- ansible/roles/nginx/tasks/deploy.yml
- ansible/roles/nginx/templates/nginx.conf.j2
- ansible/setup.yml
This PR allows SSL certificates for the openwhisk nginx to be copied from an arbitrary path, and provides overrides for the certificate names. I believe these were intended by past changes there were some gaps. For example, the `ssl.path` value was not properly used in the nginx script and the files had to be copied into the ansible directory. Also the certificate names could not be easily overriden (one would have to specify a full json value).
As part of, I removed an unused exposed port, and redirected http to https as well.
> Redirect http to https and other nginx config cleanup.

- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosContainerFactory.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainerFactory.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
This PR moves the config of the runtimes-registry to pureconfig. In addition it adds the ability to provide credentials for this registry. They are not used yet in the default implementations of the container factory. But they can be used in the SPIs.
> Move runtimesRegistry to pureconfig.

- ansible/environments/jenkins/group_vars/all
- tools/jenkins/Jenkinsfile
A private docker registry has been set up for the VMs dedicated to
OpenWhisk deployment. This PR adds the feature to  push the controller
and invoker images into this private registry, so that they can be
accessed by all the VMs.
> Add the private docker registry for three VMs under Apache

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/NamespaceBlacklist.scala
Co-authored-by: steffenrost <srost@de.ibm.com>
CouchDB has introduced a limit check for querying the database view, for the query parameter `limit`. In OpenWhisk it was first set to Scala `Int.Max` value. Since this exceeds the allowed range by couchDB, the query calls using the max value have been reported failing with `http Response: 400 Bad Request`. 
For ref: https://github.com/apache/couchdb/commit/1fdfe466223380d1ee7c82e21283e161290aed87#diff-2bd31f00dcfba780c6c65bc69c256854 
Changed the query parameter `limit` to max allowed by couchDB.
> Adapt limit to query db view as per couch db change

- tools/ow-utils/Dockerfile
- tools/ow-utils/README.md
wskdeploy is now distributed as a subcommand of wsk (wsk project),
so no need to include a wskdeploy executable.
> Remove separate wskdeploy executable from ow-utils

- ansible/group_vars/all
- ansible/roles/controller/tasks/deploy.yml
- ansible/templates/whisk.properties.j2
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/common/WhiskProperties.java
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
- tests/src/test/scala/system/basic/WskActionTests.scala
- tests/src/test/scala/system/basic/WskRestBasicTests.scala
This tests make the unit and system tests working in the case the new`provide-api-key`feature is disabled (it is enabled per default). 
Disablement of the feature can now be controlled by an Ansible variable named 
`whisk.feature_flags-require_api_key_annotation`.
A successful run with the feature disabled can be found [here](https://travis-ci.org/apache/incubator-openwhisk/builds/510850362)
> Make tests working in case the "provide-api-key" feature is disabled

- ansible/roles/couchdb/tasks/deploy.yml
This is to enable CouchDB `persist_path` in a distributed environment as well.
OW operators can freely redeploy CouchDB without any issue as it supports idempotency.
Also, in case new hosts are added in the inventory_host, they will also join the cluster on redeployment.
This is a subsequent PR from https://github.com/apache/incubator-openwhisk/pull/4250
> Enable couchdb persist_path in a distributed environment as well

- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
This PR changes the result comparison of two testcases to comparing sets instead of JsArrays. 
This is introduced by seeing unstable results in some environments.
> Improve Robustness of WskRestBasicUsageTests

- docs/actions-new.md
Remove first 'a': 
"The value is a typically a string describing the language" --> "The value is typically a string describing the language"
> Fix readme typo

- common/scala/src/main/resources/reference.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
This is to allow multiple invoker implementations.
This is also a starting point to add new scheduler implementations described in https://cwiki.apache.org/confluence/display/OPENWHISK/New+architecture+proposal
> Add SPI for invoker

- ansible/files/runtimes.json
- docs/actions-nodejs.md
Changing default Node.js version to 10 as discussed on mailing list.
Fixes #4265
Once this is merged, we can merge #4450?
Update runtimes.json with v10 as the default, rather than v6.
> Changing default Node.js version to 10

- ansible/files/runtimes.json
If we are switching the default runtime to nodejs:10,
we should change the default stemcell configuration to match.
> switch stemcells from nodejs:6 to nodejs:10

- common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactStoreExceptions.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestStore.scala
This PR cleans the error handling in the CouchDBRestStore so that metrics and logs are not send twice. It also cleans a case were a success metric was send in an error situation.
> Adjust error handling in the Cloudant Rest Store

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-nodejs.md
- docs/concurrency.md
- tests/dat/actions/unicode.tests/nodejs-12.txt
Updated runtimes definition to include new Node.js v12 runtime image.
- Updated runtimes manifest
- Added API documentation
- Minor updates to docs
- Added automated test case
https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/124
> Updating runtimes to include new Node.js v12 image.

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
The minimum value for `--cpu-shares` is 2.
However, if the `userMemory` is too high or the `reservedMemory` is too low, the result of the previous calculation might be 1. And this issue causes the following issues: https://github.com/apache/incubator-openwhisk/issues/4476#issuecomment-491664067
So I set the minimum value to 2.
> Limit the minimum to the cpu-share value

- .travis.yml
- ansible/environments/jenkins/group_vars/openwhisk-vm1-he-de
- ansible/environments/jenkins/group_vars/openwhisk-vm2-he-de
- ansible/environments/jenkins/group_vars/openwhisk-vm3-he-de
- ansible/group_vars/all
- ansible/roles/invoker/tasks/clean.yml
- ansible/roles/invoker/tasks/deploy.yml
- core/controller/Dockerfile
- core/invoker/Dockerfile
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tools/macos/README.md
- tools/macos/docker-machine/README.md
- tools/travis/docker.sh
- tools/travis/setup.sh
- tools/ubuntu-setup/docker.sh
With this change, it is required to install Docker=18.06.3 on target servers.
This is a breaking change.
> Update docker client version to 18.06.3

- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupport.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/IndexingPolicy.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/IndexingPolicyTests.scala
`activations` collection currently uses `lazy` indexing policy. Per MicrosoftDocs/azure-docs#23875 this is deprecated and should be avoided.
> Lazy mode performs updates to the index at a much lower priority level when the engine is not doing any other work. Because of this query performance can be highly unpredictable. It can also result in higher cost queries because the query engine has to do more work because it can't answer the query from the index. For these reasons we recommend against customers using it.
This PR switches to consistent indexing policy. 
Further it also removes logic to automatically update the indexing policy if the collection already exists. Instead it would now log a warning log
```
[2019-05-17T14:47:36.102Z] [WARN] Indexing policy for collection [activations] …
```
> Switch to consistent indexing policy for CosmosDB

- common/scala/build.gradle
- common/scala/src/main/resources/s3-reference.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/IndexingPolicy.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/s3/S3AttachmentStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupportTests.scala
Updates the Alpakka S3 connector to v1.0 from 0.19 release
Updates the Alpakka S3 connector to stable release. It brings in support for retries and other changes. With 1.0 there is now no `S3Client` and instead custom config is to be provided via stream attributes
> Update to Alpakka S3 Connector v1.0 release

- tests/src/test/resources/application.conf.j2
This PR adds missing quotes around some of the template variables for `application.conf`. 
Without them certain characters in  path names might lead to build brakes
> Add quotes to avoid build brakes

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CollectionResourceUsage.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CollectionResourceUsageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
This PR enables support for #4489 by collecting and exposing stats related to collections in CosmosDB
Now a new config option is exposed  which would allow collecting the collection stats at given frequency. By default this is set at 10 min frequency
```
whisk {
cosmosdb {
record-usage-frequency = 10 m
}
}
```
Once enabled it would do following things
```
[2019-05-22T15:50:15.945Z] [INFO] [#tid_sid_unknown] [CosmosDBArtifactStore] Collection usage stats for [whisks] are documentSize: 380 KB,indexSize: 11 KB,documentsCount: 42,collectionSizeQuota: 10 GB
[2019-05-22T15:50:23.869Z] [INFO] [#tid_sid_unknown] [CosmosDBArtifactStore] Collection usage stats for [subjects] are documentSize: 162 KB,indexSize: 0 bytes,documentsCount: 3,collectionSizeQuota: 10 GB
[2019-05-22T15:50:34.354Z] [INFO] …
```
> Track collection usage metrics for CosmosDB

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala
- tests/src/test/scala/common/StreamLogging.scala
- tests/src/test/scala/common/WskCliOperations.scala
- tests/src/test/scala/org/apache/openwhisk/core/admin/WskAdminTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
- tests/src/test/scala/system/basic/WskRuleTests.scala
As mentioned in #4181 compilation fails with JDK 11 with errors like
```
> Task :core:invoker:compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
/home/rahullfo/IdeaProjects/incubator-openwhisk/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala:164: value toSeq is not a member of java.util.stream.Stream[String]
runCmd(cmd, config.timeouts.ps).map(_.lines.toSeq.map(ContainerId.apply))
^
/home/rahullfo/IdeaProjects/incubator-openwhisk/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala:164: missing argument list for method apply in object ContainerId
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by …
```
> Make project compile with JDK 11

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KafkaConsumerConnector.scala
- common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KamonMetricsReporter.scala
Tracks Kafka client metrics via Kamon for monitoring
Currently Kafka metrics are not getting tracked via Kamon. Due to this we do not gain any insight into the Kafka interactions. Out of the box Kafka [tracks quite a few metrics][1] on client side these metrics are exposed via JMX
It also support custom [MetricsReporter][2] to listen to such metrics. This PR makes use of same reporter support to publish the metrics to Kamon (based on approach taken in [kamon-metrics-reporter][3])
`KamonMetricsReporter` needs to be enabled via config and provided a set of metric names to track.
```
whisk {
kafka {
common {
metric-reporters = "org.apache.openwhisk.connector.kafka.KamonMetricsReporter"
}
metrics {
// Name of metrics which should be tracked via Kamon
names = [
// …
```
> Track Kafka client side metrics via Kamon

- common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala
- common/scala/src/main/scala/org/apache/openwhisk/common/WhiskInstants.scala
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/connector/tests/AcknowledgementMessageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreBehaviorBase.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreCRUDBehaviors.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/DatastoreTests.scala
This PR changes `java.lang.Instant` creation to use milli second precision.
As mentioned in [comment](https://github.com/apache/incubator-openwhisk/issues/4217#issuecomment-496469481) for #4217 with JDK 11 `Instant` is created with microsecond precision. This PR adds extension method to `Instant` to allow creating it with milli second precision
This PR is part of work being done for #4217 to enable JDK 11 support for OpenWhisk
> Use Instant with milli second precision

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskActivation.scala
- common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala
This changes make sure the Scala compiler can compile the code base correctly under all circumstances. There are no functional changes in this PR.
- Add a few explicit types for implicit values that are used before the definition point. This is known to [work only by accident](https://contributors.scala-lang.org/t/implicits-with-inferred-return-type-lead-to-undefined-behavior/615)
- Changed the visibility of an object that also compiles only due to a [bug in the Scala compiler](https://github.com/scala/bug/issues/11554).
> Fix a few compilation accidents

- tests/src/test/scala/apigw/healthtests/ApiGwEndToEndTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/BaseApiGwTests.scala
The API GW Test are able to drive OW into throttling. Though some code existed to 
throttle down these tests these tests were failing constantly on faster machines
with 429 returned by OW.
The test code controlling the throttle was correct in throttling the test execution in isolation,
but was of course not able to overview invocations for the given namspace that do happen 
before tests were executing.
Since this limitations does naturally exist, this change simplifies down the throttling logic
to enhance code maintainability and introduces a wait period before executing the tests to ensure 
that the API GW test do not run into throttling driven by prior invokes in the same namespace.
> Settle throttle before running the API GW Tests

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- tests/src/test/scala/invokerShoot/ShootInvokerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
- tests/src/test/scala/system/basic/WskConsoleTests.scala
- tests/src/test/scala/system/basic/WskRestBasicTests.scala
While reviewing another PR I noticed we had some remaining instances of JsBoolean(true/false). This patch removes them all.
> Replace JsBoolean() with JsTrue/False.

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/SplunkLogStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/SplunkLogStoreTests.scala
As mentioned in #4347 there is a current issue of retrieval large log messages stored in Splunk. 
This artifice suggested by the Splunk support, will fix this problem and will allow the retrieval of messages larger than 10KB in size.
The solution is to extract the `log_message` value from the `_row` field and store it in a new field using `spath`. More documentation on `spath` [here](https://docs.splunk.com/Documentation/Splunk/7.3.0/SearchReference/Spath). 
There is no need to have `activation_id` in a new field using `spath` as it can be easily retrieved from the already existing one, that is why I have replaced `activation_id` with `log_message` in the `spath` command.
> Change API call to Splunk to allow retrieval of large log messages

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
* Whenever invoker or controller cluster status changes, the ShardingContainerPoolBalancer updates its state. If a new invoker registers, it is added to the load balancer status with its user memory capacity and a book-keeping semaphor is created to be used for scheduling load. If the controller cluster size changes, all invoker book-keeping semaphors are updated to reflect the user memory shard size managed by each controller.
* This change logs more diagnostic information when the ShardingContainerPoolBalancer updates its state due to invoker or controller cluster size changes.
* The additional information helps with understanding how much user memory is available on invokers and is available on the controller's shard.
* This change only introduces log message extensions and should NOT …
> Log more diagnostic info when invoker / controller cluster status changes

- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneServerFixture.scala
In case the StandaloneServerTests are not able to access the standalone jar file in the beforeAll method, all following REST tests are failing still trying to access OW locally over the standalone port.
The reason for this behavior is that the `WHISK_SERVER`property is only reset to the original value 
in case the standalone server got started successfully.
> Always reset WHISK_SERVER property after StandaloneServerTests

- .gitignore
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala
- core/routemgmt/createApi/package.json
- core/routemgmt/deleteApi/package.json
- core/routemgmt/getApi/package.json
- docs/webactions.md
The routemgmt packages copies some files around and zips them up. These files then show up in the git status. This patch ignores them.
> Ignore route management artifacts from deployment.

- ansible/files/runtimes-nodeonly.json
- ansible/files/runtimes.json
Master branch of OpenWhisk should default to using
the most recent runtimes built from the master branch
of the corresponding git repos. This image is now
being published using the tag `nightly` instead of `latest`.
> switch to `nightly` docker image tag for runtimes

- core/controller/src/main/resources/application.conf
- tests/dat/actions/echo-web-http-head.js
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskWebActionsTests.scala
Akka http client by default treats any http HEAD request as GET unless the configuration sets it otherwise. There are use cases where user expects HEAD to be responded as HEAD and without a response body unlike GET.
https://github.com/akka/akka-http/issues/2088 mentions that the default is set to treat a HEAD as a GET request by the Akka client.
Update the controller configuration to process HEAD and GET requests as they are expected.
> Akka http server responds HEAD request as GET

- Jenkinsfile
Builds and install the various Gradle module as part of Jenkins build
Standalone server test need access to the standalone jar which needs to be pre built before tests are run. This was done for Travis and not for Jenkins.  With this PR the required jars are also now built as part of Jenkins build
> Run Gradle install for Jenkins build to install Standalone jar

- tools/admin/wskadmin
This PR is a small consistency fix for the `wskadmin` tool. If the `wskadmin` tool is called to get the currently set limits on a given namespace, it should not print out `Failed to get limits ..` if the limits document is deleted on the database but handle it the same way as if the limits document does not exists (`No limits found, default system limits apply`). This is more consistent as the message shown by `wskadmin` should be the same for both cases. 
In addition, both cases (missing and deleted limits document) shouldn't be treated as error in my opinion and hence the `wskadmin` shouldn't return with a non-zero code, but this is open to discussion.
This code change changes the messages printed by the `wskadmin` tool for deleted namespace limits documents.
> Handle deleted limits document for get operation the same way as missing limits document

- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/controller/src/main/resources/application.conf
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/RestAPIs.scala
- core/standalone/build.gradle
- core/standalone/src/main/resources/standalone.conf
Package the swagger docs as part of standalone jar such that clients can use it as they would for standard OpenWhisk server
Packages the swagger docs as part of jar. It makes the swagger ui path configurable and adapts it for standalone case where the ui files are served from classpath resource compared to filesystem 
Due to akka/akka-http#2247 the path needs to account for how Spring Boot would package the files
> Package swagger docs as part of standalone jar

- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
Accept a lower number of file descriptors available for Node.js action code with the default Node.js action runtime.
* We see test `org.apache.openwhisk.core.limits.ActionLimitsTests.Action limits should fail to invoke an action when it exceeds nofile limit` failing permanently on Docker 18.09.3-ce systems - while they work properly on Docker 17.05.0-ce.
* The test tries to open more files than allowed from within an action.
* The test expects that at least max open files (=1024) - 20 = 1004 can be opened.
* The test failed because only 1003 files could be opened.
* The test makes sure that it's always a cold invocation, so the failure was not caused by open files carried over from an earlier invocation.
More details below...
> Lower minimum number of available file descriptors in action limit tests

- ansible/roles/prereq/tasks/deploy.yml
The docker python version is too old in the role. Latest docker-compose
starts to crash due to the version being too old.
> Bump docker python version to 4.0.2

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- docs/metrics.md
Forced completion acks can be a source of overloaded invokers because forced acks free up invoker slots in the load balancer. If the invoker is just "late" with running an activation so that the invoker sends the result / completion ack after the completion ack timeout has been reached in the load balancer, the load balancer may send new activations to the invoker while it is still fully occupied. As a result, these new activations have to wait for a container and can cause forced completion acks in turn. This mechanism can lead to a never-ending chain reaction if an invoker has a constant stream of workload.
Goal of this change is to improve visibility and diagnostic information so that this mechanism can be better understood and fixed in the next step.
* Add metrics for forced …
> Add more diagnostic information to completion ack processing

- common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosContainerFactory.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
Fixes #4521 where we observed out of memory during test runs because MesosContainerFactory continues to retry failed subscribe thus filling up the in memory logger
In #4521 it was observed that `MesosContainerFactory` continues to execute the subscribe task even after test finishes. Ideally upon close of actor system such subscribe efforts should stop automatically. However somehow the threads continue to remain active.
So now we close the factory and disable subscribe upon close after each test run. With this its confirmed there were no stray away threads running and thus no memory leakage should happen due to this
> Disable MesosContainerFactory from subscribing after close

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainer.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Pod creating timeout for some reason,such as mount a nonexistent nfs volume,
both k8s and invoker does't delete the 'ContainerCreating' pod.
> Delete pod when creating timeout

- core/standalone/src/main/resources/standalone.conf
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneOpenWhisk.scala
The setSysOps are override the standalone.conf since standalone.conf
is evaluated first. The will prevent us from using a custom config files
on these parameters. Moving these options from code into
standalone.conf, so a custom config files can potentially override them.
> Remove configureOSSpecificOpts in standalone and move the config options to standalone.conf

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/DockerToActivationLogStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivationResult.scala
- common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/test/DockerToActivationFileLogStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
* So far, log collection for managed Docker action containers waits for sentinels - even if a developer error occurs. Only if an action exceeded its init or run timeout, sentinel waiting will be disabled.
* This change disables sentinel waiting for all developer errors because a managed action runtime may not be able to write sentinels at all in developer error situations. With this change, missing sentinels are handled in a more robust way.
* Without sentinel waiting, the Docker action container log file is only read until file end is reached. No re-reads are performed if the sentinel has not been found yet. On busy systems, this may lead to a few missing log lines in case of developer errors.
> Action container log collection does not wait for sentinel on developer error

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- docs/actions-new.md
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Enable passing the transaction_id to action containers to corelate requests made from within actions across different actions in a sequence or composition 
This change is part of #4585
Passes a new attribute `transaction_id` as part of `/run` call which would be exposed as env entry `__OW_TRANSACTION_ID`
> Pass transactionId to action container

- core/standalone/README.md
- core/standalone/build.gradle
- core/standalone/src/main/resources/standalone.conf
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/ApiGwLauncher.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/CouchDBLauncher.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneOpenWhisk.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneCouchTests.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneServerFixture.scala
Enable using CouchDB with standalone mode (#4516). This would be useful for cases where users would like to save there changes upon restarts.
Enables launching CouchDB with `--couchdb` option
```
java -jar openwhisk-standalone.jar --couchdb
```
With this flag following tasks would be performed
1. CouchDB server would be started. By default at port 5984. If thats busy then at some random port
2. CouchDB would be configured with required databases and views
3. DB files would stored under `~/.openwhisk/standalone` folder
4. Launching with `--clean` option would lead to recreating the db
> CouchDB support in OpenWhisk Standalone mode

- common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationFileStorage.scala
Introduce individual field set for activation records in user logs.
We need to handle activation records (i.e., activation metadata) and user logs differently in activation logs. Therefore we need individual field sets for storing these entries in `ActivationFileStorage` that we use in our Activation Store SPI imlementation.
- Controller (for sequences)
- Invoker
Small change with low risk: add one function `activationToFileExtended`in `org.apache.openwhisk.core.database.ActivationFileStorage` that is basically the same as `activationToFile`but allows to define different sets of additional fields for activation_record and user_log. The proposed change does not replace the existing function `activationToFile` but adds the desired new function in order to not change the interface of …
> Allow individual field sets for activation_record and user_log

- core/standalone/src/main/resources/standalone.conf
Updates the gateway version from a nightly build to released version which has the fix for apache/openwhisk-apigateway#347
> Update api gateway to released 0.11.0 in standalone mode

- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneOpenWhisk.scala
Reduces startup in dev mode from ~ 12-14 secs to ~7 secs
Currently the base standalone server starts in ~ 12-14 seconds. Some of this time is spent in pre flight checks and doing explicit pulls for some of the images used. This is useful for end user so as to ensure that system has required support.
However for regular development it adds up to startup time. So added a `--dev-mode` flag which disables the preflight checks and disabled explicit pulls. This should be fine for people developing on core codebase.
```
java -jar openwhisk-standalone.jar --dev-mode
```
> Add dev mode flag to speed up startup during development

- .asf.yaml
Experiment with new ASF feature of using a per-repo yaml
file to configure github metadata for a project.
See https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories for what is supported.   
I suggest we experiment in the main repo to verify it works and get to a core set of tags.  Then we can replicate across all the repos & add additional per-repo tags as well
> Add asf.yaml to configure github metadata

- .asf.yaml
See if this works; looks like the example yaml on cwiki
had the wrong indentation level for the labels...
> fix indent on labels in .asf.yaml

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- tests/src/test/scala/common/LoggedFunction.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Pass the action instance (for cold start case) as an optional argument to ContainerFactory
For enabling integration with other execution env like AWS Lambda (#4412) we need to make available the action instance to the `ContainerFactory` such that it can map the invocation to a pre deployed function/lambda definition.
This PR extends the `ContainerFactory` trait to support another method which takes an optional action instance. This would be set for the cold start case. For prewarm case this would be None
This change would be backward compatible and only those Factory implementation which need access to action would need to implement the new method
> Pass an optional action instance to ContainerFactory

- ansible/roles/controller/tasks/deploy.yml
Missing type description makes ansible confused of Controller task "populate environment variables for controller".
* MacOS version 10.15 Beta (19A487m)
* ansible version 2.8.4
* Python version 2.7.16
* Docker version 18.09.1
* local deployment
> fix: controller ambiguous task env setting

- ansible/roles/kafka/tasks/deploy.yml
- ansible/roles/zookeeper/tasks/deploy.yml
Add docker image pull (or not) options to kafka and zookeeper deployment.
If the docker tagged(especially the "latest") image is already in environment machine, adding this option could speed up deployment.
> Add ansible deploy options

- common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationFileStorage.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
Add the possibility to decide whether results should be included in the action log on a per-call basis for each activation individually.
Action results may contain sensible data that should not be logged. There is a system configuration flag (`writeResultToFile`) that can be used to switch on or off the result inclusion in logs. But this is a global switch that holds for all activations. In our case we want to able to decide per activation whether or not the result should be included in the log. In our special case we want results to be included in case of errors (in other words, 'Does the result contain an error field?'). But also other decision logic may be applicable. 
- Controller (for sequences)
- Invoker
Small, low risk change: add one optional, boolean parameter to the method …
> Allow decision about action result inclusion in logs on a per call basis

- core/standalone/README.md
- core/standalone/build.gradle
- core/standalone/src/main/resources/logback-standalone.xml
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/KafkaLauncher.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneOpenWhisk.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneKafkaTests.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneSanityTestSupport.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneServerFixture.scala
Adds support for launching Embedded Kafka and Kafka Drop UI
This PR adds support for launching an [embedded-kafka][1]. This is mostly meant to enable local development for features which need Kafka support (like User Event or Activation Persister Service etc). In this mode an inprocess Kafka Server (v2.1.1 currently) and Zookeeper Server
```
$ ./gradlew :core:standalone:build
$ java -jar bin/openwhisk-standalone.jar --kafka
$ ./gradlew :core:standalone:bootRun --args='--kafka'
```
Key aspects
* Kafka version 2.1.1 is being used while we run with 0.11.0.1. Tried to use that but then it causes class compatability issue with newer version of Kafka client being used
* This mode is also useful to simulate some of the integration test scenarios with Activation Persister Service
* Kafka Server …
> Embedded Kafka support in OpenWhisk Standalone mode

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/org/apache/openwhisk/core/connector/tests/AcknowledgementMessageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Combines active ack and slot release when both are available. If completion message carries a result, process the active ack.
There are two commits in this patch. The first is semantic preserving/refactoring. The fix is in the second commit.
Closes #4614.
Closes #4636.
> Combines active ack and slot release when both are available.

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ApacheBlockingContainerClient.scala
- core/standalone/src/main/resources/standalone.conf
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneServerTests.scala
In local setups on Mac using Standalone OpenWhisk mode sometime few test fail. Also some times some steps in compositions are seen to fail. In all such cases the failure happens due to failure during initialization due to `NoHttpResponseException`
For some container upon retry the init seems to pass fine. This PR modifies the `ApacheBlockingContainerClient` logic to enable retry for `NoHttpResponseException` based on explicit config.
By default `NoHttpResponseException` would not be retried. However if config is enabled then retry would be performed. For standalone case this config is enabled.
With this change all test now pass on Mac in a reliable way. This is also needed for some conductor related test in #4632
> Retry NoHttpResponseException for standalone mode in ApacheContainerClient

- core/monitoring/user-events/build.gradle
Add maven plugin to the user-events build gradle in order to inherit the install task for proper publishing of the jar to the maven repo/local cache.
Without the maven plugin the user-events jar is not properly published during builds to the maven repo/local .m2 cache. As a result downstream repo builds fail, e.g. for the openwhisk-cli
> add missing install task for proper maven publishing (build break in cli repo)

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/org/apache/openwhisk/common/UserEventTests.scala
- tests/src/test/scala/org/apache/openwhisk/common/UserEventsITTests.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneServerFixture.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneUserEventTests.scala
This fixes a bug introduced in a previous PR which drops user events on completion messages that do not carry a result (which is needed for user event generation).
Best to review this ignoring white space.
It appears there are no tests that caught the bug and so some tests are needed. 
@sven-lange-last perhaps to verify the fix you can suggest a test to add 🙏
> Revert erroneous change which drops user events on some completions.

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationFileStorage.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/test/DockerToActivationFileLogStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
Add **namespace** field to activation log while using `DockerToActivationFileLogStore`
Currently there is no **namespace** field  but a **namespaceId** in the activation log while save activation logs to a separate file, while I think add **namesapce** will be more convenient for users when they process the log file, such as using Logstash to send logs to different indices(e.g. `openwhisk-%{namespace}`) in ElasticSearch
> Add namespace field to activation log

- docs/annotations.md
Move the description of the default value of `provide-api-key` for new actions to the beginning of the description, before explaining the behavior when not specified in an existing action. This is to avoid confusion about the value of `provide-api-key` when not provided.
Related to [this suggestion](https://github.com/apache/openwhisk-catalog/issues/309#issuecomment-536907037) (not a direct issue).
> Rephrase description of `provide-api-key`

- common/scala/src/main/scala/org/apache/openwhisk/core/database/StoreUtils.scala
At times we are seeing some failures in AryifactStore operations where real cause is a nested exception. 
```
[2019-09-30T13:35:36.747Z] [ERROR] [#tid_fpdgvAqVk3C2AHr1oWhrD0XSJM9mjgP3] [StoreUtils] [GET] 'whisks' internal error, doc: 'id: someaction, rev: "3b00580c-0000-0100-0000-5d91f9f40000"', failure: 'Boxed Error' [ExecutionException] [marker:database_getDocument_error:9:5]
```
This PR now also includes the complete stacktrace as string after a new line (so as to preserve semantics for any log based triggers/alerts). With this the log looks like below
```
[2019-10-01T04:41:19.247Z] [ERROR] [#tid_sid_testing] [StoreUtils] [GET] 'whisks' internal error, doc: 'id: someAction, rev: 3b00580c-0000-0100-0000-5d91f9f40000', failure: 'Boxed Error' [ExecutionException] …
```
> Dump complete exception stacktrace upon failure in StoreUtil

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreProvider.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/RetryMetricsCollector.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
This PR enables capturing stats related to document size and RU used for get and put operation. 
With this PR the `get` and `put` operation would include the document size and RU used
```
[2019-09-30T11:29:53.553Z] [INFO] [#tid_1] [CosmosDBArtifactStore] [PUT] 'subjects' completed document: 'id: anon-OIPNjW7IigJetLxDwwlPwlcG2Fl, rev: null', size=235, ru=7.05 [marker:database_saveDocument_finish:9308:685]
```
Further the PR also add a histogram for document size.
```
histogram_cosmosdb_doc_size_bytes_bucket{collection="activations",le="512.0"} 0.0
histogram_cosmosdb_doc_size_bytes_bucket{collection="activations",le="1024.0"} 0.0
histogram_cosmosdb_doc_size_bytes_bucket{collection="activations",le="2048.0"} 0.0
histogram_cosmosdb_doc_size_bytes_bucket{collection="activations",le="4096.0"} …
```
> Capture document size, RU usage, retry stats for get and put in CosmosDB

- core/monitoring/user-events/init.sh
JVM option does not affect the user-events application, because the environment variable is invalid
So I changed the name from `CACHE_INVALIDATOR_OPTS` to `USER_EVENTS_OPTS`
> Fix invalid environment variable for User Events JVM option

- .travis.yml
- ansible/downloadcli-github.yml
- tests/build.gradle
- tools/travis/runStandaloneTests.sh
- tools/travis/runUnitTests.sh
Currently the system test profile time is hovering around 50 mins. This PR moves out the standalo ne test to a new profile
> Move out standalone server tests to a new Travis profile

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskStore.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/ApiUtils.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/Entitlement.scala
In some places we were using `package` object but not placing them in `package.scala` files. This PR makes them as normal object
Due to the way currently some package objects were defined they were causing warnings to be issued from the [Hydra Scala Compiler](https://triplequote.com/hydra)
```
Information:scalac: Using 2 Hydra workers to compile Scala sources.
Information:02/10/19, 4:18 PM - Build completed with 8 errors and 2 warnings in 11 s 498 ms
Warning:scalac: /path/to/openwhisk/core/controller/src/main/scala/org/apache/openwhisk/core/controller/ApiUtils.scala:73: warning: package object PostProcess must be placed inside org/apache/openwhisk/core/controller/PostProcess/package.scala
package object PostProcess {
^
Warning:scalac: …
```
> Make package object as simple object

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/MessagingActiveAck.scala
This is based on discussion in #4641 and to simplify adding test for changes to be introduced in #4632
This PR refactors out the logic related to active in a separate class which enables implementing unit test for the same. This also abstracts out the user event flow such that it can be tested independently of its default configuration
There is no functional change in this PR
> Refactor the ActiveAck implemenation to simplify testing

- core/cosmosdb/cache-invalidator/build.gradle
- core/monitoring/user-events/build.gradle
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/KafkaSpecBase.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/KamonRecorderTests.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/OpenWhiskEventsTests.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorderTests.scala
- settings.gradle
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/cache/CacheInvalidatorTests.scala
- tools/travis/runStandaloneTests.sh
Currently [Alpakka Kafka](https://doc.akka.io/docs/alpakka-kafka/current/home.html) is used in 2 places cache invalidator and user event service.
This PR unifies the version and updates it to 1.0.5. 
Further it also enables test for user-event which were so far not enabled as they were part of the module itself. These tests are enabled in new Standalone Mode profile in Travis
> Unify Alpakka Kafka version across modules

- core/standalone/README.md
- core/standalone/build.gradle
- core/standalone/src/main/resources/standalone.conf
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneOpenWhisk.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/Unzip.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/UserEventLauncher.scala
Adds support for launching User Event service along with preconfigured Grafana and Prometheus instances. 
This PR adds support for launching [User Event service](https://github.com/apache/openwhisk/blob/master/core/monitoring/user-events/README.md) with pre configured Grafana dashboard
To give it a try download a [pre built jar](https://github.com/chetanmeh/incubator-openwhisk/releases/download/v0.13/openwhisk-standalone.jar) and then launch it as below and access http://localhost:3000 to see the dashboards
```
java -jar openwhisk-standalone.jar --user-events
```
Key aspects
1. Launches a User Event service which listens to `events` topic
2. Launches a Prometheus server with default at http://localhost:9090
3. Launches a Grafana server with default at http://localhost:3000
The Grafana …
> User Events support in OpenWhisk Standalone mode

- ansible/files/runtimes.json
- docs/actions-go.md
openwhisk-runtime-go PR#109 changed the name used to publish docker
images from actionloop-golang-VERSION to action-golang-VERSION. This
PR updates the core system runtime.json and documentation to use the
new names. All old images are still available on dockerhub and will
not be removed or renamed, so this should be a non-disruptive change.
> GoLang docker image: actionloop-golang ==> action-golang

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KafkaMetrics.scala
- common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KamonMetricsReporter.scala
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/EventConsumer.scala
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/OpenWhiskEvents.scala
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusEventsApi.scala
- tests/src/test/scala/org/apache/openwhisk/connector/kafka/KafkaMetricsTests.scala
This PR expose the metrics related to specific Kafka producer or consumer over `/metrics/kafka` endpoint. 
For now this feature is enabled for User Event service where the event consumer's Kafka consumer instance  metrics are exposed. Such metrics can provide insight into the Kafka consumers processing stats.
The http endpoint is not exposed to end user and meant for developers and system admins to understand the performance characteristics of the consumer at any given time by direct access
It also registers the `KamonMetricsReporter` (introduced via #4481) with the User Event consumer to expose some of those metrics as Kamon metrics
A typical response for the `/metrics/kafka` endpoint is like below ( > 100 entries)
```json
[
{
"description": "The number of responses received per second", …
```
> Expose Kafka metrics for User Event consumer as json endpoint

- tests/src/test/scala/common/TestUtils.java
- tests/src/test/scala/common/WhiskProperties.java
Removes code that appears dead in this project/tests.
Closes #3863.
> Remove deadcode from test helpers.

- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneKCFTests.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneServerFixture.scala
- tools/travis/runStandaloneTests.sh
Adds a basic sanity test based for KubernetesContainerFactory using Standalone mode
This PR creates a small k8s setup based on [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) using approach taken in apache/openwhisk-deploy-kube#535. Here we just create base kind cluster with no OpenWhisk related components installed.
Later the Standalone server is used and configured to connect to this kind cluster (#4671) to run a basic invocation test
> Standalone based sanity test for KubernetesContainerFactory

- common/scala/src/main/scala/org/apache/openwhisk/core/database/memory/NoopActivationStore.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/LogbackConfigurator.scala
Adds a `NoopActivationStore` which does not store the activation and acts like `/dev/null` for the activation response. 
To simplify local performance testing of the overhead of the control plane flow (invocation logic path in Controller/Invoker) it would be useful have an `ActivationStore` which does not store the activation result. 
This ensures that one can run say 10k activations without worrying about the storage cost. 
Below steps demonstrate one way of using this store with Standalone OpenWhisk server
Create a `standalone-perf.conf` with below content
```
include classpath("standalone.conf")
whisk {
spi {
LogStoreProvider = "org.apache.openwhisk.core.containerpool.logging.LogDriverLogStoreProvider"
ActivationStoreProvider = …
```
> Add NoopActivationStore to simplify local performance testing

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
Drop the NET_RAW and NET_ADMIN capabilities from the containers
created to execute user actions (matches DockerContainerFactory).
> KubernetesContainerFactory: security context for user actions

- core/standalone/README.md
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneOpenWhisk.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/UserEventLauncher.scala
With #4656 support was added in standalone mode to launch the User Event service along with required Prometheus and Grafana service. This PR adds support for reusing an existing user-event service (say running with IDE) for faster local developement
To enable fast local development of user-event service the Standalone OpenWhisk now support connecting to an existing running service instead of launching a new one via Docker
First launch the standalone server with Kafka and pass the port where user-event service would be running (9095 by default)
```
java -jar openwhisk-standalone.jar --dev-user-events-port 9095 --kafka --kafka-ui
```
Then launch the `org.apache.openwhisk.core.monitoring.metrics.Main` via IDE with env set to `KAFKA_HOSTS=localhost:9092`
After this one can do normal action …
> Enable Standalone User Event Dev mode

- tools/jenkins/apache/dockerhub.groovy
Attempt to gain better control over Jenkins execution environment
by restricting job to run on one of the openwhisk VMs.
Running on general pool of machines, the build fails (eg https://builds.apache.org/view/O/view/OpenWhisk/job/OpenWhisk-DockerHub/2135/).
Running on one of our machines, the build succeeds (eg https://builds.apache.org/view/O/view/OpenWhisk/job/OpenWhisk-csantanapr/49/console)
> restrict Jenkins dockerhub publish job to run on openwhisk VMs

- common/scala/build.gradle
- common/scala/src/main/scala/org/apache/openwhisk/common/ConfigMapValue.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala
- settings.gradle
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/common/ConfigMapValueTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubeClientSupport.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/WhiskPodBuilderTests.scala
- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneKCFTests.scala
This PR adds support for providing a base Pod template to customize the action Pod created by KubernetesContainerFactory (KCF)
Sometime back we [discussed a usecase on DL][1] to configure a private registry for action containers. This PR now enables that usecase via an optional `pod-template` config
Provide the base pod template via config like below
Pod template yaml stored at "/pod-template.yaml` 
```yaml
---
apiVersion: "v1"
kind: "Pod"
metadata:
annotations:
allow-outbound : "true"
```
```
whisk {
spi {
ContainerFactoryProvider = "org.apache.openwhisk.core.containerpool.kubernetes.KubernetesContainerFactoryProvider"
}
kubernetes {
pod-template = "file:/pod-template.yaml"
}
}
```
When KCF would create an action container POD it would use the above template as base and add the changes …
> Pod template support with KubernetesContainerFactory

- common/scala/build.gradle
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala
To move forward with activation poll uqery optimization for CosmosDB (#4684) we need to collect some mertics. This PR collects 2 such metrics
This PR adds 2 new metrics which are computed for the activation list query used in `wsk activation poll` command
1. `histogram_cosmosdb_query_resultDelta_seconds` - Records the time delta between current time and the `start` time of the last activation entry in returned list of activations. This helps in determining how much recent activation results are being returned to end users for the poll command
2. `histogram_cosmosdb_query_sinceDelta_seconds` - Records the time delta between current time and the `since` time specified in list query used by activation poll
Below are the stats as recorded for Prometheus
``` …
```
> Cosmosdb query metrics for activation poll query

- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
A fix for #4711 
This change forces the k8s client to use a particular namespace when communicating with the API server.
> Fixes #4711 - add a namespace configuration option to KCF

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- docs/actions-new.md
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
As discussed [here](https://lists.apache.org/thread.html/ef18f833671a3266d4cde3bf4eaff379596d03b3e147a785a9b06941@%3Cdev.openwhisk.apache.org%3E), it changes the container proxy to provide an environment at init time (`/init`).
But I couldn't move the entire context from /run to /init to maintain backward compatibility.
Put environment variables in the env field. and runtimes can use this value.
```
{
"value": {
"name" : String,
"main" : String,
"code" : String,
"binary": Boolean,
"env": Map[String, String] = {
"__OW_NAMESPACE",
"__OW_ACTION_NAME",
"__OW_ACTIVATION_ID",
"__OW_TRANSACTION_ID",
"__OW_DEADLINE"
}
}
}
```
The namespace, action_name, activation_id, transaction_id, and deadline fields are uppercased and prefixed with "`__OW_`" by runtimes …
> Provide environment at init time

- tests/src/test/scala/common/rest/WskRestOperations.scala
In our tests we encounter every now and then failing tests that fail because the HttpEntity.toStrict timed out after 5 seconds. In order to avoid these timeouts I propose to increase the defined timeout from 5 to 30 seconds.
This code change increase the timeout value `toStrictTimeout` from 5 to 30 seconds. Intention is to avoid the following error: `org.scalatest.exceptions.TestFailedException: The future returned an exception of type: java.util.concurrent.TimeoutException, with message: HttpEntity.toStrict timed out after 5 seconds while still waiting for outstanding data.`
> Increase toStrictTimeout value to omit intermittent timeout exceptions

- tools/ow-utils/Dockerfile
- tools/ow-utils/build.gradle
Add tools/data from the core repo to ow-utils docker image to enable
it to be used for dynamic generation of ssl certificates. This will
enable us to dynamically generate self-signed certificates for nginx
(and potentially other components) as cluster-configuration job
in openwhisk-deploy-kube.
> enhance ow-utils to enable certificate generation

- common/scala/build.gradle
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala
fastparse in version 1.x.x is not available for Scala 2.13, so this updates it to the latest and greatest with rather minor impact.
Ref #4741
See dev-list discussion on Scala 2.13 here: https://lists.apache.org/thread.html/c8e2fa40b646dccc6e3a6cbca2370904477f5dd8dbb315173f055a2c@%3Cdev.openwhisk.apache.org%3E
> Update fastparse to version 2.1.3.

- common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala
I used to love to write "smart" code like `Some(descending).filter(identity)`. Coming back to it now, I hate it though. It feels unreadable, especially if there are simpler yet similar terse alternatives.
> Simplify Option.filter(identity) pattern to something actually readable.

- core/standalone/build.gradle
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/ServerStartupCheck.scala
- tools/admin/build.gradle
- tools/admin/src/main/scala/org/apache/openwhisk/core/database/LimitsCommand.scala
- tools/admin/src/main/scala/org/apache/openwhisk/core/database/UserCommand.scala
Not all scala projects had the compiler flags we usually use so some warnings went under the radar. This fixes this.
> Enable strict compile options on all scala projects and fix warnings.

- common/scala/build.gradle
alpakka-file isn't available for Scala 2.13 prior to 1.1.x. See https://mvnrepository.com/artifact/com.lightbend.akka/akka-stream-alpakka-file.
Ref #4741
See dev-list discussion on Scala 2.13 here: https://lists.apache.org/thread.html/c8e2fa40b646dccc6e3a6cbca2370904477f5dd8dbb315173f055a2c@%3Cdev.openwhisk.apache.org%3E
> Update alpakka-file to version 1.1.2.

- settings.gradle
Akka isn't available for Scala 2.13 prior to 2.5.24. See https://mvnrepository.com/artifact/com.typesafe.akka/akka-actor. We might as well bump through all the minor versions though.
Ref #4741
See dev-list discussion on Scala 2.13 here: https://lists.apache.org/thread.html/c8e2fa40b646dccc6e3a6cbca2370904477f5dd8dbb315173f055a2c@%3Cdev.openwhisk.apache.org%3E
> Update akka libraries to version 2.5.26.

- common/scala/build.gradle
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/RxObservableImplicits.scala
RxScala has been abandoned: https://github.com/ReactiveX/RxScala/issues/244. To unblock the move to Scala 2.13, this removes all usages of it and replaces it with Java interoperable code.
Ref #4741
> Remove usages of rxscala and replace with Java based code.

- build.gradle
- common/scala/build.gradle
- core/controller/build.gradle
- core/cosmosdb/cache-invalidator/build.gradle
- core/invoker/build.gradle
- core/monitoring/user-events/build.gradle
- core/standalone/build.gradle
- tests/build.gradle
- tests/dat/actions/unicode.tests/src/java/unicode/build.gradle
- tests/performance/gatling_tests/build.gradle
- tools/admin/build.gradle
- tools/dev/build.gradle
1. Removes redundant compiler option settings and centralizes them.
2. Makes use of the `plugins` mechanism throughout.
> Centralize settings in the build process to avoid duplication.

- settings.gradle
akka-http itself does work with Scala 2.13 in version 10.1.8 but other upgrade don't seem to like the interop with an older version. See #4746 and #4749 for reference.
Ref #4741
> Update akka-http to 10.1.10.

- core/monitoring/user-events/compose/grafana/dashboards/global-metrics.json
- core/monitoring/user-events/compose/grafana/dashboards/openwhisk_events.json
* Add chart to display `request response size`. 
* Split the error dashboard into `System errors` and `Development errors`. This should make more clear for the developer if the errors are actionable or not. In case of the `System errors`, system admins need to notified.
> Add response size and dev errors to user-events dashboard

- common/scala/build.gradle
alpakka-s3 isn't available for Scala 2.13 prior to 1.1.x. See https://mvnrepository.com/artifact/com.lightbend.akka/akka-stream-alpakka-s3.
Ref #4741
See dev-list discussion on Scala 2.13 here: https://lists.apache.org/thread.html/c8e2fa40b646dccc6e3a6cbca2370904477f5dd8dbb315173f055a2c@%3Cdev.openwhisk.apache.org%3E
> Update alpakka-s3 to 1.1.2.

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskEntity.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskPackage.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskRule.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskTrigger.scala
- core/controller/src/main/resources/apiv1swagger.json
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackageActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/RulesApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/TriggersApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/WhiskEntityTests.scala
Since an action API doesn't serialize the `updated` value of the action entity, users can't know when the action was updated.
It changes the action API to serialize and provide the `updated` value of the action
https://github.com/apache/openwhisk/issues/4228
> Serialize `updated` value of entity document in response

- core/standalone/build.gradle
Standalone compilation was failing on windows os with below error. 
```
Task :core:standalone:copyGWActions FAILED
* Where:
Build file 'C:\Users\Administrator\openwhisk\core\standalone\build.gradle' line: 59
Execution failed for task ':core:standalone:copyGWActions'.
> Execute failed: java.io.IOException: Cannot run program "npm" (in directory "C:\Users\Administrator\openwhisk\core\routemgmt\createApi"): CreateProcess error=2, The system cannot find the file specified
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
This is because "npm" is not found on windows as it is placed as "npm.cmd".
> Specify npm command based on os for standalone compilation

- tools/dev/src/main/groovy/intellijRunConfig.groovy
Because the module name is incorrect, the IntelliJ utility script doesn't make valid run configurations. 
So it fixes the invalid module name.
> Fix invalid module name in intellijRunConfig script

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Entities.scala
- settings.gradle
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/RulesApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/TriggersApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
update to akka-http 10.1.11 (from 10.1.10) to avoid noisy errors in logs (see https://github.com/akka/akka-http/issues/2728)
> update to akka-http 10.1.11

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivationResult.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ActivationResponseTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
Keep the container running even if the action produced truncated response.
If a container sometimes produces replies that are greater than the allowed max size, that container cannot be reused. However, treating this in a similar fashion to unhandled exception or other developer error seems too heavy handed. Layer concurrency on this and you get a lot of failed activations and container churn due to a only slightly misbehaving action.
> Keep container running for truncated responses

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/standalone/README.md
- docs/actions-new.md
- docs/actions.md
- tests/dat/actions/helloContext.js
- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
This PR adds the `__OW_ACTION_VERSION` property to the execution environment. This is for example useful when an action caches some data, so it could add the version number to the cache keys so that deploying a new version of the action would automatically "invalidate" the previous cache entries.
See #4758
> Add __OW_ACTION_VERSION in action metadata

- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
- tools/actionProxy/invoke.py
I recently observed that some runtimes may not be properly exporting the `__OW_API_HOST` context property. Unlike other environment variables, this one is set by on the container startup (e.g., `docker run -e`). The test is adjusted so that the `api_host` is not passed in the run payload to make sure the container environment is used.
> Make sure the API host env var is send only via docker run for test.

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/RetryMetricsCollector.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/memory/MemoryViewMapper.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Attachments.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ConcurrencyLimit.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/LogLimit.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/MemoryLimit.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNRESTUtil.scala
- common/scala/src/main/scala/org/apache/openwhisk/utils/ExecutionContextFactory.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorderTests.scala
- tests/src/test/scala/common/WskTestHelpers.scala
- tests/src/test/scala/common/rest/SwaggerValidator.scala
- tests/src/test/scala/invokerShoot/ShootInvokerTests.scala
- tests/src/test/scala/org/apache/openwhisk/common/UserEventTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/MockYARNRM.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/AttachmentStoreBehaviors.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala
- tests/src/test/scala/system/basic/WskActionTests.scala
- tests/src/test/scala/system/basic/WskPackageTests.scala
- tests/src/test/scala/system/basic/WskSequenceTests.scala
- tools/admin/src/main/scala/org/apache/openwhisk/core/cli/Main.scala
This fixes a bunch of things that are deprecated on Scala 2.13:
- Unicode arrows are deprecated.
- View bounds are deprecated.
- Value functions may no longer have an empty argument list.
- Remove usage of the procedure syntax.
Ref #4741.
> Fix some Scala 2.13 deprecations.

- tests/build.gradle
scalatest isn't available for Scala 2.13 prior to 4.3.0. See https://mvnrepository.com/artifact/org.scalamock/scalamock
Ref #4741.
> Update scalamock to 4.4.0.

- core/monitoring/user-events/build.gradle
- core/standalone/build.gradle
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/DatastoreTests.scala
scalatest isn't available for Scala 2.13 prior to 3.0.8. See https://mvnrepository.com/artifact/org.scalatest/scalatest
Ref #4741.
> Upgrade scalatest to 3.0.8.

- core/standalone/build.gradle
- tools/admin/build.gradle
scallop isn't available for Scala 2.13 prior to 3.3.0. See https://mvnrepository.com/artifact/org.rogach/scallop.
Ref #4741.
> Update Scallop to 3.3.2.

- core/controller/build.gradle
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- settings.gradle
akka-management and discovery isn't available for Scala 2.13 prior to 1.0.0. See https://mvnrepository.com/artifact/com.lightbend.akka.management/akka-management-cluster-bootstrap.
Ref #4741.
> Update akka-management and discovery to 1.0.5.

- core/standalone/build.gradle
embedded-kafka isn't available for Scala 2.13 prior to 2.4.0. See https://mvnrepository.com/artifact/io.github.embeddedkafka/embedded-kafka
Ref #4741.
> Update embedded-kafka to 2.4.0.

- ansible/files/runtimes.json
EOL of NodeJS 6 was April 2019.  We should move forward on removing support for nodejs:6 kind from Apache OpenWhisk
> mark nodejs:6 as deprecated

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-new.md
- docs/actions-php.md
- tests/dat/actions/unicode.tests/php-7.4.txt
Add PHP 7.4 runtime:
* Update list of runtimes.
* Update Swagger description
* Update docs
* Add unicode.tests file
Note that this requires https://github.com/apache/openwhisk-runtime-php/pull/79 to be merged first.
(Note: I'm not sure which section updating a runtime falls into!)
> Add PHP 7.4 runtime

- tests/build.gradle
- tests/src/test/scala/system/basic/WskActivationLogsTests.scala
- tests/src/test/scala/system/basic/WskActivationTests.scala
Split the existing WskActivationTests into two tests, one for logs and
one for the rest of the activation apis (currently only results). This
enables a clean exclusion of the logs portion of the tests when using
the KubernetesContainerFactory (which is not able to distinguish the
stdout and stderr streams due to deficiencies in how container logs
are exposed through the Kubernetes API).
> Separate test cases for the logs and results APIs of activation

- ansible/ansible.cfg
The default timeout is 10 seconds, which I was hitting consistently on some older servers.
> Extend ansible gather_timeout to 60 seconds

- ansible/files/runtimes.json
We've released 1.14.0 of openwhisk-runtime-dotnet which added support for .NET Core 3.1.  Add the new kind to the default list of runtimes.
> add dotnet:3.1 runtime kind

- common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KafkaMessagingProvider.scala
this allows lower privilege users to be set for the controller
and invoker.
Topics in Kafka are not part of the overall functioning of OW. In other words, there is no dynamic topic creation during the normal functioning of any OW component. Therefore there is not reason to have a credential that is powerful enough to make changes to Kafka deployed in the controller or invoker.
This commit allows those pieces to function with "least privilege" under normal operation, meaning you can now set ACLs for their topics in advance and allow them only rights to read / write the topics in question.
> Check to see if the user can see the topic before creating it,

- tests/dat/actions/echo.json
- tests/dat/actions/word_count.json
- tests/src/test/scala/org/apache/openwhisk/core/admin/WskAdminTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/EntitlementProviderTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/KindRestrictorTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/LimitsCommandTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/AttachmentCompatibilityTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecManifestTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecTests.scala
- tests/src/test/scala/system/rest/JsonSchemaTests.scala
NodeJS 6 is long past EOL.  Need to remove uses of nodejs:6 kind from master branch...
> change tests to use nodejs:10 instead of nodejs:6

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/AkkaContainerClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ApacheBlockingContainerClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosTask.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNTask.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- core/monitoring/user-events/compose/grafana/dashboards/global-metrics.json
- core/monitoring/user-events/compose/grafana/dashboards/openwhisk_events.json
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/AkkaContainerClientTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/ApacheBlockingContainerClientTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
To validate state of containers before use.
In our deployment case (mesos/kubernetes) there are occasional cases where prewarm/warm containers fail outside of the usage of ContainerProxy, but ContainerProxy/ContainerPool are not aware of these failures. When this happens, when eventually the containers are used, there is a guarantee of failing the activation, since ContainerProxy assumes the prewarm/warm container is running fine, and it just sees a failure for /init or /run. 
This may be more pertinent to ContainerFactory impls that launch containers on hosts other than the invoker (mesos, k8s, yarn), but since it is also possible for docker containers local to invoker to be interrupted by some other system, it may be useful in all cases as a preventative measure. 
This PR introduces a …
> Add healthcheck for Invoker -> Action Container 

- ansible/files/runtimes.json
EOL of NodeJS v8 was Dec 31, 2019.
> deprecate nodejs:8 kind

- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala
A performance improvement was made to the `activations` collection in CosmosDB to index on the soft delete path `_deleted`. This change improved performance on queries and reduces the RU usage in CosmosDB.
To align with this change, the `ActivationViewMapper`'s `IndexingPolicy` was updated to add the new path to `includePaths`. This is used to verify that the acitvations collection's policy in CosmosDB is as expected in openwhisk upon connecting.
> Add '_deleted' to includePaths for CosmosDB IndexingPolicy validation

- common/scala/src/main/scala/org/apache/openwhisk/core/database/DocumentHandler.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskPackage.scala
- tests/src/test/scala/invokerShoot/ShootInvokerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/system/basic/WskActionTests.scala
Scala 2.13 makes both of these return views rather than strict maps. We don't need view semantics in any of these places, so we're safe to use the proposed alternative code as seen in https://docs.scala-lang.org/overviews/core/collections-migration-213.html#what-are-the-breaking-changes.
> Force filterKeys and mapValues to return a Map.

- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupport.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Scala 2.13 dropped `to[Type]` in favor of `to(Type)` which isn't backwards compatible. To circumvent cross-compilation issues, this just changes the very little occurrences we had of that to actually use explicit typing to not need the casts at all.
Ref #4741
> Replace to[Type] calls with explicit types.

- common/scala/src/main/scala/org/apache/openwhisk/core/database/RemoteCacheInvalidation.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosContainerFactory.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNTask.scala
- tools/admin/src/main/scala/org/apache/openwhisk/core/database/UserCommand.scala
Scala 2.13 forbids this and it has been ugly every since. Using the "proper" Unit value works just as well.
Ref #4741
> Remove usages of Unit as a value.

- common/scala/Dockerfile
Downstream tests showed major performance degradation with OpenJDK in latency and warm invocation tests which disappeared when using OpenJ9 instead.
OpenJ9 is Apache licensed.
Please see [this mail thread](https://lists.apache.org/thread.html/r6578ef3129e036911adf261382e304e145782d0633f13ff3dc9898eb%40%3Cdev.openwhisk.apache.org%3E) for more details
> Use JDK 11 OpenJ9 to overcome observed performance degredations

- tests/src/test/scala/common/ConcurrencyHelpers.scala
- tests/src/test/scala/limits/ThrottleTests.scala
- tests/src/test/scala/org/apache/openwhisk/common/ForcibleSemaphoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/common/NestedSemaphoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/common/ResizableSemaphoreTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/limits/MaxActionDurationTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Scala 2.13 puts parallel collections into a separate module that's not compatible with Scala 2.12. To avoid having to work around things and to keep cross-compilation compatibility this just exchanges the approach for concurrency in tests to not use parallel collections at all.
Ref #4741
> Replace parallel collections with future based concurrency in tests.

- ansible/group_vars/all
- common/scala/build.gradle
- core/monitoring/user-events/build.gradle
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/EventConsumer.scala
- settings.gradle
- tests/build.gradle
The rabbit hole started with embeddedkafka only being available on Scala 2.13 at version 2.4.0.
1. Our Kafka clients and the used Kafka version doesn't match. That's not necessarily an issue but I think we should use matching versions unless we've seen issues there.
2. Updated akka-kafka to the latest and greatest.
Ref #4741
> Update Kafka version to 2.4.0, make kafka related dependencies consistent.

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala
- tests/src/test/scala/common/RunCliCmd.scala
- tests/src/test/scala/common/rest/SwaggerValidator.scala
- tests/src/test/scala/org/apache/openwhisk/common/SchedulerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupportTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/CouchDbRestClientTests.scala
A selection of small compilation differences between 2.12 to 2.13, most notably:
- Removing the last Unit values
- Fix usages of mutable collections as `Seq` to explicitly call that out (`toSeq`).
- Infix and Postfix notation removal in places where the 2.13 compiler stumbles.
**Note:** This is the last PR needed to make 2.13 fully compilable 😀 
Ref #4741
> Fix slight compilation differences between Scala 2.12 -> 2.13.

- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/RecordingLeakDetectorFactory.java
This class yields an annoying compiler warning like:
```
Note: /Users/mthoemme/dev/openwhisk/tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/RecordingLeakDetectorFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
Sadly, we need to override the method as it is abstract. Suppressing the warning should be fine in that case.
> Fix deprecated override warning in ResourceLeakDetector.

- common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBUtil.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBUtilTest.scala
Scala 2.13 didn't like the type shenanigans going on here and my head hurt trying to understand it too. Reimplemented a hopefully equally correct version with no shenanigans.
Ref #4741
> Simplify Cosmos query string generation.

- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/WhiskPodBuilderTests.scala
Allow kubernetes operators to specify configuration to cause pods to request cpu (resources in addition to memory resources) based on scaling the configured action memory.
> Kcf - optional cpu resource scaling based on action memory

- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/WhiskPodBuilderTests.scala
If enabled, when action pods are created, also creates a PodDisruptionBudget with minavailable=1
Also deletes the PodDisruptionBudget when pod is deleted.
This prevents the action pod from being terminated if the kubernetes node goes into maintenance and is drained. Depending on the PDB configured for the invoker, invokers can still be terminated, which should terminate the action pods that way.
> enable optional use of PodDisruptionBudget for action pods

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
instead of fabric8 client waitUntilReady. See discussion in #4812
This allows more precision for config specified at `whisk.kubernetes.timeouts.run`
> change the kubernetes pod wait logic to use akka after pattern 

- core/standalone/build.gradle
- tools/admin/build.gradle
Scala 2.13 compilation breaks horribly if these are not set accordingly. Arguably, they are kinda wrong anyway as the top-level is supposed to set the compiler flags and these projects clearly depend on the scala library.
Ref #4741
> Fix scala usage in :tools:admin and :core:standalone.

- common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationFileStorage.scala
`toIterator` is deprecated in 2.13 and it's an alias anyway.
Ref #4741
> Use 'iterator' instead of 'toIterator'.

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/DockerToActivationLogStore.scala
Stripping both leading and trailing spaces incorrectly alters the formatting of the logs produced by actions. This changes the stripping only to trailing new line or return character.
> Strip only trailing line ender from log lines produced by actions.

- .travis.yml
- settings.gradle
Running a build with the `OW_SCALA_VERSION` environment variable set now allows you to switch between building with 2.12 and 2.13 to allow for a smooth migration in downstream systems to 2.13 and to allow us to try it out "in the wild" more easily.
Ref #4741
> Allow build to use either Scala 2.12 or 2.13 and test that in CI.

- common/scala/src/main/scala/org/apache/openwhisk/common/Prometheus.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivationResult.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Attachments.scala
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusEventsApi.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/ExtendedCouchDbRestClient.scala
Since Scala 2.12, [Either has been right biased](https://www.scala-lang.org/api/2.12.0/scala/util/Either.html) so explicitly calling `.right` before mapping etc is not necessary. Scala 2.13 deprecates this usage so... let's get rid of it now.
This also removes usages of `.right.get` for the same reason and to drop potential error cases where there are none.
No semantic change intended.
Ref #4741
> Remove explicit right biasing of Eithers.

- .travis.yml
- I had already removed the not-needed Scala stanza in #4737 but it got added back, possibly due to merge issues?
- Removed `sudo:`, it has no effect.
- Added explicit `os:` stanza.
- Fixed bad indentation.
> Fix warnings in travis file, remove scala again.

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/KamonRecorderTests.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorderTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/connector/test/EventMessageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ActivationCompatTests.scala
This change adds the activationId to messages on the events topic of type `Activation`. This is useful for external services that listen in on the events topic that may want to make reference to the activations
it is consuming.
> add activationId to events message

- gradle/docker.gradle
A set of logic in docker.gradle to test for old versions of docker for the `docker tag -f` flag breaks because it assumes a docker binary.  I added conditional logic to only apply this logic if the version line returned by the program begins with 'Docker'.
> Allow docker.gradle to succeed using 'dockerBinary=podman'

- tools/ow-utils/Dockerfile
Add the jq cli to the ow-utils to enable easy parsing of
results curls against the Kubernetes API server.  This will
simplify the definition of init containers used to wait
for services to be ready before dependent pods are started.
> Add jq to ow-utils image

- core/controller/src/main/resources/apiv1swagger.json
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Limits.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/RestAPIs.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/Collection.scala
- docs/actions-docker.md
- docs/rest_api.md
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/LimitsApiTests.scala
This PR creates a limits api that will return the limits set for the namespace.
/namespaces/_/limits
In the future, it's extendable to return individual limits by entity such as 
/namespaces/_/limits/invocationsPerMinute
although that is not implemented in this PR.
Only Get is supported as setting limits is an admin operation. This allows clients to see what their namespace's limits are set to without going through an admin for the information. Also, since the route goes through the controller we can return the system defaults for invocationsPerMinute, concurrentInvocations, and firesPerMinute rather than just saying the system defaults apply if nothing is set in couchdb.
> Add Get Namespace Limits API

- core/monitoring/user-events/src/main/resources/application.conf
- core/monitoring/user-events/src/main/resources/reference.conf
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/EventConsumer.scala
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/OpenWhiskEvents.scala
- core/monitoring/user-events/src/test/resources/application.conf
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorderTests.scala
If there is a problem with the Kafka consumer, it no longer sends metrics. Because there is no error handling for user-events's Kafka consumer.
https://doc.akka.io/docs/alpakka-kafka/current/errorhandling.html
So I've added RestartSource to restart a failing consumer.
- no related issue
-  User events
- Enhancement or new feature (adds new functionality).
> Add RestartSource to restart failing Kafka consumer for user-events service

- ansible/files/runtimes.json
- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecManifestTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecTests.scala
As we already know, when invoker starts up, will create some prewarmed containers in prewarmedpool in advance.
If the prewarmed containers are not used for sometime, the prewarmed containers will exist forever.
it may lead to `waste of resources`
so there has need to provide some mechanism to save memory resources, e.g.
* If the prewarmed containers are not used for sometime, should delete them automatically.
* When cold start happened, we should supplement a prewarmed container which matched the kind/memory in runtime.
Node: Current, i didn't add test cases, after some reviews, i will add it.
https://github.com/apache/openwhisk/issues/4725#issuecomment-572824267
> Adjust prewarm container dynamically

- core/monitoring/user-events/compose/grafana/dashboards/global-metrics.json
Adding prewarm-related metrics to global metrics dashboard.
With reactive prewarm configs in use, it is useful to have more prewarm metrics in the global metrics grafana dashboard.
> add prewarm metrics to global-metrics.json 

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/AkkaContainerClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ApacheBlockingContainerClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivationEntityLimit.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/AkkaContainerClientTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/ApacheBlockingContainerClientTests.scala
By default activation responses can be 1MB in size and they will be truncated to 1MB in case the size is bigger. 
This PR makes the truncation length configurable too. This means that the response size could be configured to 1MB for example, but the truncation length can be 512KB. 
The reason for this change is the fact that once the response is truncated, it does not make a lot of sense to store the entire payload to the database. 
As an example, for the following configuration:
```
whisk {
activation {
payload {
max = 512
truncation = 10
}
}
}
```
the response of a truncated activation result will have the following format:
```
{
"error": "The action produced a response that exceeded the allowed length: 600 > 512 bytes. The truncated response was: {\"body\":\"H"
}
```
and the database …
> Make activation response truncation length configurable 

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/InstanceId.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ControllerInstanceIdTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/InvokerInstanceIdTests.scala
1. `instanceType` json field added
- It is necessary when another component is added to distinguish json values of invoker and controller.
2. Add test case for serde `InstanceId`
3. Change `AcknowledegmentMessage` interface
- The `AcknowledegmentMessage` may not always respond to the invoker
no related issue
> Change AcknowledegmentMessage interface

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
Initial impl of reactive prewarm did not derive the ttl for a replacement prewarm (when a prewarm is used). This fixes that so new prewarms have the appropriate ttl.
Also added a test to exercise this ttl workflow for prewarm replacement.
> Reactive prewarm - use proper ttl when replacing a prewarm

- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/WhiskPodBuilderTests.scala
This will allow the deployment to limit the total amount of ephemeral disk given to a pod when it's created. This prevents an attacker from overwhelming the node with disk writes.
> Add the ability to limit the amount of disk given to the action pod in k8s

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainer.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/Fabric8ClientTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubeClientSupport.scala
In a previous PR, I attempted to introduce exception handling for when the kubernetes client call `kubeRestClient.pods.inNamespace(namespace).create(pod)` directly throws an exception using logic like:
```
try {
kubeRestClient.pods.inNamespace(namespace).create(pod)
...
} catch {
case e: Throwable =>
throw e
}
```
But this doesn't return a Future.failed as desired for handling in `KubernetesContainer.create`, rather it just exits the `create()` function, and the activation is never completed with the failure information.
This PR addresses that by capturing the exception via `Try` and explicitly returning an appropriate `Future.failed`. 
Also added tests for this exception handling, and exception handling around timeout while waiting for pod to become ready.
> kubernetes: fix exception handing when api-server connection fails

- tests/build.gradle
A few of these tests fail almost 100% of the time when run on
Kubernetes.  Disabling to unblock merging of deploy-kube PRs.
We should eventually investigate the root cause and do a real fix.
> disable PackageTests and SequenceTests for KubernetesContainerFactory

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala
This is what I get when I try and spell ephemeral off the top of my head.
Fix a typo.
> Fix typo in k8s config case class

- core/cosmosdb/cache-invalidator/src/main/resources/application.conf
- core/cosmosdb/cache-invalidator/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/cache/CacheInvalidator.scala
- core/cosmosdb/cache-invalidator/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/cache/ChangeFeedConsumer.scala
- core/cosmosdb/cache-invalidator/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/cache/KafkaEventProducer.scala
- core/cosmosdb/cache-invalidator/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/cache/Main.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/cache/CacheInvalidatorTests.scala
The cosmosdb cache invalidator needs to be more defensive about downstream sdk errors like:
* cosmosdb failures at startup
* kafka producer failures during processing
These types of issues are most commonly related to configuration problems, so this refactoring mainly addresses these issues by exiting the application when these failure scenarios occur. 
Deployments should handle termination by restarting the application, but typically the configuration issues will not be resolvable until the configuration is repaired, and exiting the application is aimed to bring increased visibility to the configuration problems as they happen.
> CosmosDB cache invalidator refactor

- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/EventConsumer.scala
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/KamonRecorder.scala
- core/monitoring/user-events/src/main/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorder.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/KamonRecorderTests.scala
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/PrometheusRecorderTests.scala
If a namespace is in `ignore-namespace` configuration, user-events service still sends activation metrics though they are not incremented in case of counter or not updated in case of the histogram. Even though the value of metrics is not updated, it still creates a large amount of time series in case of canary service or load is creating unique actions and eventually can cause high cardinality.
> activation metrics are recorded for namespace even if set to ignore by user-events service.

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
Make k8s read action logs correctly
> Make k8s read action logs correctly

- ansible/environments/local/group_vars/all
This changes it to use /var/tmp instead of the more volatile /tmp
Change the variables to have the nginx container use /var/tmp for config storage instead of /tmp
> Fix issue with nginx container not restarting on reboot

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
When enabling reactive prewarm configs, if batches of prewarms are removed at the same time across invokers, we end up with a herd of container deletion and creation at the same time, especially if invokers startup at the same time.  This can cause scheduling challenges particularly in mesos or kubernetes. Given that these prewarm containers are not in use, we should try to alleviate any extra issues the prewarm state changes may cause, and allow them to linger slightly longer, if there is a benefit to the scheduling system. 
This PR adds some configs and sensible defaults to allow the reactive prewarm config affects to be varied across invokers to smooth out deletion and rescheduling of prewarm containers:
```
prewarm-expiration-check-interval: 1 minute # period to check for prewarm …
```
> Prewarm eviction variance

- common/scala/build.gradle
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/azblob/AzureBlobAttachmentStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/azblob/AzureBlob.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/azblob/AzureBlobAttachmentStoreBehaviorBase.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/azblob/AzureBlobAttachmentStoreITTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/azblob/AzureBlobConfigTest.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/AttachmentStoreBehaviors.scala
Adds `AzureBlobAttachmentStore` as an `AttachmentStore` implementation backed by [Azure Blob](https://azure.microsoft.com/en-in/services/storage/blobs/)
Fixes #4666
`azure-storage-blob:12.0.0` is now based on [Project Reactor][1]. `AzureBlobAttachmentStore` uses the library via the Reaxtive Stream support (Publisher/Subscriber) from Akka and Project Reactor and thus enables non blocking reads and writes
This library adds following dependencies
To enable this one needs to configure
```
whisk {
azure-blob {
#}
}
}
```
`AzureBlobAttachmentStoreITTests` enables integration test which run against the Azure Blob service. It needs following env settings
* `AZ_ENDPOINT` - Endpoint url
* `AZ_ACCOUNT_NAME` - Name of storage account
* `AZ_ACCOUNT_KEY` - Account key
* `AZ_CONTAINER_NAME` - Optional. …
> AttachmentStore implementation based on Azure Blob

- tools/jenkins/apache/dockerhub.groovy
Apache Jenkins service is migrating to a new CloudBees instance.  The dedicated OpenWhisk nodes are not being migrated.  Attempt to use a generic ubuntu worker node for the job to periodically build docker images from the core repo.
> attempt to migrate dockerhub Jenkins job to generic ubuntu nodes

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/azblob/AzureBlobAttachmentStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/azblob/AzureBlob.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/azblob/AzureBlobAttachmentStoreCDNTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/AttachmentStoreBehaviors.scala
This PR introduces Azure CDN support within AzureBlobAttachmentStore, to improve latency of `readAttachment()` in cases where attachment blob store resides in a different region than where the OW system is operating.
It is very similar to CloudFront support within S3AttachmentStore
> Support for azure cdn with AzureBlobAttachmentStore

- docs/actions-go.md
Readme appears to have an incorrect description of how the deploy process works when it's a zip file.
I'm not super familiar with OpenWhisk yet, but from tinkering with IBM Cloud Functions, and doing deploys involving both raw source code files and zip archives, this description in the readme doesn't sound accurate. I think what it was meant to say was that the zip archive would have either an executable or one or more Go source code files.
> fix deploy description in readme

- core/controller/src/main/resources/apiv1swagger.json
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Packages.scala
- docs/rest_api.md
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
Adds a force parameter to the delete package api so any actions in the package are deleted with it before confirming and deleting the package. If force is not set (by default), it still returns the same error of needing to delete the actions first before deleting the package. 
I could use some help on optimizing the package deletion because currently I need to do a get action list to get the list of actions in the package to check if it's non-empty which was already a part of the route, and then I have to do a get on the actions to get the revision id before I can delete the action. I don't think this is too much of an issue because normal action deletes have to do this get then delete anyways I believe. Any advice here would be appreciated because of my lack of familiarity with the code. …
> Force Delete Non-Empty Packages

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
ContainerProxyTests broken in recently merged #4958 
I think the test is failing because ContaineProxy terminates too early after failure, but some additional processing is required.
> fixing ContainerProxy - don't terminate early on failures

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/InstanceId.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ControllerInstanceIdTests.scala
Fixes deserialization issue for new instance id format for upgrades of live services that cannot have downtime.  Fix will provide upgrade path to upgrade controllers and invokers safely.
1. When upgrading the invokers to latest, the `ControllerInstanceId` in `ActivationMessage` fails to deserialize because the `instanceType` is not included in the message sent from the non-upgraded controllers.
2. Vice versa controllers fail to upgrade if invokers have not been upgraded yet because the completion messages can not deserialize in the controller because the invokers aren't including `instanceType`.
3. The fix here fixes case 1 so that `ControllerInstanceId` will still deserialize if `instanceType` is not included.
4. Upgrade all invokers in your cluster, wait a few minutes so all completed …
> Fix InstanceId Incompatibility

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Repairing more issues with ContainerProxy. Logic for aborting queued concurrent activations now waits for those activations to be processed before stopping.
> cleaning up logic and test issues with ContainerProxy

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
Fixing a toString issue for containerStart metric labels
Was using `namespace.toString` and should use `namespace.name.toString`
> use user.namespace.name instead of user.namespace for metric label

- common/scala/src/main/scala/org/apache/openwhisk/http/BasicHttpService.scala
When you sent the controller a malformed query string it would incorrectly return a 500 error, on top of that it wouldn't even log things properly. This adds some simple defensive code to prevent both issues.
For example:
```
curl -v "http://<controller_ip>:<controller_port>/?p=%2"
```
Would result in a 500 error from the controller.
> Add defensive code to the controller for when it gets bad query parameters

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
Remove unnecessary `[] ` in logs
Since https://github.com/apache/openwhisk/pull/4819 introduce the child transactionID, it will add a `[] ` to logs when the transactionId have no child, this PR just remove the useless `[] `
> Adjust log format

- common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactStoreExceptions.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/StoreUtils.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreCRUDBehaviors.scala
- tests/src/test/scala/system/basic/WskSequenceTests.scala
It fixes https://github.com/apache/openwhisk/issues/4953
If the action is updated while the sequence action is executing, the old revision is referred to when the sub action is executed.
```
1. [InvokerReactive] guest/B guest 8cd79... 38-41cde62e7493f5ffd83f31939dce8a84
2. [InvokerReactive] guest/B guest 2db43... 39-e8576e618c86251c246fc8c6804dbce2
3. [InvokerReactive] guest/B guest 72d6f... 40-a3892ba52d244f27b00a6526e5388e00
4. [InvokerReactive] guest/B guest 969be... 41-ad44c086275d0d7e4631298a3107f96c
5. [InvokerReactive] guest/B guest 0f7d3... 37-9f5e794ffcfc7d556a9154c39a1ce700 <- old revision is reffered
```
At this time, if the DB server returns the latest revision, then **a boxed error** occurs due to an assert condition.
```scala
assert(doc.rev.rev == null || doc.rev.rev == …
```
> Use latest code if action's revision is mismatched

- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala
See https://github.com/docker/for-win/issues/7898
See https://github.com/adobe/aio-cli-plugin-app/issues/304
The Windows docker.exe location has been changed, so the openwhisk.jar will fail to run since the search locations are hard-coded. This PR adds the new path to the search paths.
> fix: add new Windows docker.exe location

- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
Change new activation error logs to warn level and add a config on whether to output the activation errors to log for each activation error type. Application and developer errors default to false. Whisk errors default to true as a whisk error implies an internal system error.
> Add Activation Error Logging Config to Container Proxy

- core/controller/src/main/resources/apiv1swagger.json
Missing part of #4987 which added the go:1.15 kind.
> add go:1.15 kind to apiv1swagger

- ansible/group_vars/all
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Parameter.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ParameterEncryption.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskPackage.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/ParameterEncryptionTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
This PR extends @mcdan's work from #4756 to allow for per-namespace encryption keys. Each commit is an incremental refactoring which might help in understanding the progression.
There are two singleton references to the encryption configuration - these can be replaced by identity-specific encryption configurations but requires additional work on extending the subject schema. I will stage that in a subsequent PR.
The refactoring here is intended to be semantic preserving.
> Improvements to parameter encryption to support per-namespace keys

- tools/jenkins/apache/dockerhub.groovy
To prepare for making a 1.0.0 release, change to using 1.0.0
instead of nightly as the tag for docker images produced  by
building this branch.  Also drop the git commit hash tag, as
that is intended to be used only by the master branch.
NOTE: This PR should be merged to the 1.0.0 branch, not the master branch.
> Adjust "nightly" dockerhub Jenkins job on 1.0.0 branch

- tools/jenkins/apache/dockerhub.groovy
Apache Infra changed the way JDKs are named in Jenkins on Oct 18.
> adapt to change in JDK naming scheme in Apache Jenkins

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
The trait `WorkerState` and case class `WorkerData` are no longer used
anywhere. Keeping them in the code base makes no sense.
> Remove unused trait and case class

- core/standalone/build.gradle
To support building from a source release, allow the gitProperties task to fail without failing the build.
> make generation of git.properties optional

- core/standalone/start.sh
remove extra leading / in volume mount command
Fixes #5016
> fix start.sh to work on macos

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/StandaloneDockerContainerFactory.scala
The PR fix at https://github.com/apache/openwhisk/pull/4991 is incomplete. This fixes the docker exe not found error on Windows.
Microsoft Windows version 10.0.18362 N/A Build 18362
Docker (Windows) version 19.03.13, build 4484c46d9d
node (Windows) version 10.22.1
java (Windows) 15 2020-09-15
1. Build the standalone jar via `./gradlew :core:standalone:build`
2. Run the jar under Windows 10 via `java -jar bin\openwhisk-standalone.jar`
3.  See error:
```
$ java -jar openwhisk-standalone.jar
[36m
____      ___                   _    _ _     _     _
/\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
/\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
/  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
\   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| …
```
> re-fix: add new Windows docker.exe location

- common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/InstanceId.scala
- core/scheduler/Dockerfile
- core/scheduler/build.gradle
- core/scheduler/init.sh
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/SchedulerServer.scala
- settings.gradle
This is the first change to add the new scheduler component.
A series of subsequent PRs would be opened by me and my team members.
We would start from modules with fewer dependencies to modules that are highly dependent on the others.
We will add the "scheduler" label and `[New scheduler]` prefix in the title of PRs.
Please refer to the issue for more information and discussion history.
You may find this useful as well: [new scheduler design](https://cwiki.apache.org/confluence/display/OPENWHISK/New+architecture+proposal)
JFYI, this scheduler is running in production in Naver.
There are many "TODO"s in this PR.
As we agreed to incrementally merge PRs along with temporal commits, I left many parts of the original codes as "TODO".
I wanted to give some hints to reviewers about how it would …
> [New Scheduler] Initial commit for the scheduler component

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
If the activation is generated by the `generateFallbackActivation` method in the InvokerReactive, it contains the version in the path annotation.
In this case, the ES activation store can't search for activations by the name without version.
And also, all other components that generate activation don't store version, but only InvokerReactive stores the version in the path annotation. It must be consistent.
https://github.com/apache/openwhisk/blob/a1ba98778e3db80a06fe707c47c5f4c05d8b85ee/core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala#L589
https://github.com/apache/openwhisk/blob/a1ba98778e3db80a06fe707c47c5f4c05d8b85ee/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala#L1070 …
> Hide version in activation's path generated by generateFallbackActivation

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InstanceIdAssigner.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/InstanceIdAssignerTests.scala
This allows the operator to specifically set the instanceId for a unique name in zookeeper from the command line when starting the invoker. Added a comment that this command option should not be used unless you are sure that the invokerId does not exist for any unique name
For context, we use hostname for our invoker unique names. We have hosts that no longer exist and therefore invokers are created backfilled in the controller invoker pool for those invokers that will never be started again. This causes the invoker hashing algorithm to be off since these invokers are always considered down. This change allows us to easily move our highest lexicographical invokers into those slots in zookeeper without manually going into zookeeper to do so.
> Reset / Overwrite invokerId for unique name in zookeeper manually

- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
- core/standalone/src/main/resources/standalone-kcf.conf
- tests/src/test/resources/application.conf.j2
In kubenetes env,  if runtime pod number is big and `akka.coordinated-shutdown.phases.actor-system-terminate_timeout` is low(e.g default value is `30 s`), this may lead to `the runtime pods are not deleted completely after execute helm delete/uninstall xxx`, because when timeout happens, the `cleanup` is not executed finished.
In such a case, need to increase relative timeout value, it is better to make these timeout value configurable.
Another brother pr: https://github.com/apache/openwhisk-deploy-kube/pull/653
https://github.com/apache/openwhisk-deploy-kube/issues/652
> Make runtime delete timeout configurable

- common/scala/copyJMXFiles.sh
JMX related auth files are mounted as a read-only mode by k8s secret.
(configMap and secrets volumeMount are always read-only by k8s.)
So, It can't use the `mv` command in the copyJMXFiles.sh script.
I'll open a new subsequent PR  at the `apache/openwhisk-deploy-kube` repository for supporting JMX on the k8s environment 
No issues
> Copy JMX related files instead of moving to support jmx on k8s

- .travis.yml
- README.md
- tools/travis/runStandaloneTests.sh
- tools/travis/setup.sh
> Migrate the Travis configuration to travis-ci.com

- ansible/roles/nginx/templates/nginx.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
- tests/src/test/scala/services/HeadersTests.scala
This is to fix the intermittent test failures.
Intermittent test failures due to heisenbugs increase the CI time and make authors run tests multiple times.
> Fix heisenbug

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
Due to this pr (Adjust prewarm container dynamically): https://github.com/apache/openwhisk/pull/4871 is merged
I think it is a good chance to add this feature.
for master branch,  if invoker has `16GB` physical memory, currently, if we configure 12GB user memory and 5GB prewarm pool, invokers will try to create containers up to 17GB memory and it may will end up with OOM.
After apply this feature, user just configure invoker memory to a precise value:  `16GB` , when  reaches `16GB`, it will not create container any more, this can avoid `OOM`
This has another benefit that make user must calculate the prewarmed container's memory carefully, and configure the invoker memory more accurately
```
"CONFIG_whisk_containerPool_userMemory": "{{ hostvars[groups['invokers'][invoker_index | …
```
> take prewarmed container's memory as used memory

- .travis.yml
- tests/src/test/scala/org/apache/openwhisk/core/admin/WskAdminTests.scala
- tools/travis/runStandaloneTests.sh
- tools/travis/scan.sh
- tools/travis/setup.sh
- tools/travis/setupSystem.sh
Seems travis ci is broken again, trying to fix it
> Use focal release for travis ci

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala
The invoker health supervisor, on startup, eagerly went into the health state without confirming the test action was actually successful. This happens at startup, when the ring buffer is not yet primed. The patch herein adjusts the health protocol for the priming phase and stays unhealth/unresponsive if the test action failed.
> Fixes bug in invoker supervision on startup.

- docs/actions-rust.md
The command given `wsk action create helloRust hello.rs` does not work as given, yielding an error message. This can be corrected by specifying the action type via `--kind rust:1.34`
> Fix wsk action create command in Rust example

- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/Entitlement.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/FPCEntitlement.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LoadBalancer.scala
Implement a FPCEntitlementProvider
A new FPCEntitlementProvider for [scheduler](https://cwiki.apache.org/confluence/display/OPENWHISK/New+architecture+proposal):
Since the new scheduler is using different throttler logic, so this PR is created
> [New Scheduler]Implement FPCEntitlementProvider

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
> Don't create prewarm container when used memory reaches the limit

- core/invoker/Dockerfile
> format: format the invoker's Dockerfile

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/FPCSchedulerServer.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/FPCSchedulerServerTests.scala
This is the document for new Scheduler: https://cwiki.apache.org/confluence/display/OPENWHISK/New+architecture+proposal
Regarding FPCSchedulerServer, it provides some APIs to access the concrete info for scheduler node.  including
* /state
```
curl -u xxx:'xxx' http://xxx.xxx.xxx.xxx:13001/state
{"0":"104","creationCount":"0"}    # it means  current scheduler node: `scheduler0` includes `104`  total queue,  has no creating queues 
```
* /queue/total
```
curl -u xxx:'xxx' http://xxx.xxx.xxx.xxx:13001/queue/total
104 # it means includes 104 total queues
```
* /queue/status
```
curl -u xxx:'xxx' http://xxx.xxx.xxx.xxx:13001/queue/status
[{
"data": "RunningData(Actor[akka://scheduler-actor-system/user/$Qd#905522799],Actor[akka://scheduler-actor-system/user/$Pd#-785916053])",
"fqn": …
```
> [New Scheduler] Implement FCPSchedulerServer

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-python.md
Python 2 EOL was more than a year ago; finish the cleanup and
remove the python:2 kind from the core repository.
> remove deprecated python:2 kind

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- tests/build.gradle
- tools/travis/runSchedulerTests.sh
- A tavis job has been added to run separate tests related to the new scheduler.
- When all contributions are done (about scheduler), it looks good to move to the existing units and systems.
- Combined system tests and unit tests into one.
> [New Scheduler] CI for testing related new scheduler

- common/scala/src/main/scala/org/apache/openwhisk/core/service/WatcherService.scala
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/service/WatcherServiceTests.scala
The FPC scheduler will use etcd to store and share some data, and some components need to get noticed for some data when they are changed(inserted, updated or removed), this PR implements a centralized watcher for them, which will watch all changes on etcd and distribute them to subscribers
design document: https://cwiki.apache.org/confluence/display/OPENWHISK/WatcherService
> [New Scheduler] Add a centralized watcher for etcd data

- ansible/files/runtimes.json
- core/controller/src/main/resources/apiv1swagger.json
- docs/actions-docker.md
- docs/actions-php.md
Also, set example PHP runtime to v7.4.
> Add php:8.0 kind

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/service/LeaseKeepAliveService.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
- tests/src/test/scala/org/apache/openwhisk/core/service/LeaseKeepAliveServiceTests.scala
- In invoker and scheduler components, each host has a lease. This service manages lease to not disappear due to timeout.
- Each host writes health data to etcd with this lease. When lease disappears by timeout, each host's health data disappear together, so it can be determined as an unhealthy host by the scheduler.
- Because it is the service that has the greatest influence on the health state of the component, a dedicated dispatcher is allocated.
- https://cwiki.apache.org/confluence/display/OPENWHISK/LeaseKeepAliveService
> [New Scheduler] Implement KeepAliveService

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/ContainerCounter.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/ContainerCounterTests.scala
Get container count from ETCD when related data get updated in ETCD
It watchs ETCD data changes using `WatcherService` implemented in #5069, when any new container data under specified namespace is inserted/removed to/from ETCD, it will get count of containers for the namespace by querying ETCD
> [New Scheduler] Add container counter

- tools/travis/box-upload.py
The urllib.urlencode() function is now urllib.parse.urlencode()
Should fix the Python error seen at this build run -> https://travis-ci.com/github/apache/openwhisk/jobs/489965935
> fix: Python 3 urlencode

- tools/build/citool
> Change up travis URL.

- tools/macos/README.md
- tools/macos/docker-machine/README.md
- brew cask install -> brew install --cask
- brew tap caskroom/cask -> brew tap homebrew/cask
Updates the Mac install
> fix: update Homebrew commands

- ansible/group_vars/all
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/etcd/EtcdClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/service/DataManagementService.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/service/WatcherService.scala
- tests/src/test/scala/org/apache/openwhisk/common/etcd/EtcdLeaderShipUnitTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/service/DataManagementServiceTests.scala
- tools/travis/runStandaloneTests.sh
This component is in charge of storing data to ETCD.
It is based on eventual consistency.
If it fails to store data for some reason, it keeps retrying until data is stored.
> [New Scheduler] Add DataManagementService

- common/scala/src/main/scala/org/apache/openwhisk/common/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/InstanceId.scala
- core/invoker/build.gradle
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/ActivationClientProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/InvokerHealthManager.scala
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/InvokerHealthManagerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/entity/test/InvokerInstanceIdTests.scala
Manage New scheduler's invoker healthy management
Design document: https://cwiki.apache.org/confluence/display/OPENWHISK/InvokerHealthyManager
> [New Scheduler] Implement InvokerHealthyManager

- tools/macos/README.md
Listed ansible installation link is broken. Have updated the same.
> Fixed link for Ansible

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/DocInfo.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/FullyQualifiedEntityName.scala
- core/scheduler/build.gradle
- core/scheduler/src/main/java/Empty.java
- core/scheduler/src/main/protobuf/activation.proto
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/grpc/ActivationServiceImpl.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/grpc/test/ActivationServiceImplTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/grpc/test/CommonVariable.scala
- tools/travis/runUnitTests.sh
- tools/travis/setup.sh
ActivationService is a GRPC service implementation for the scheduler that communicates with the container proxy.
Please refer to this document:
https://cwiki.apache.org/confluence/display/OPENWHISK/ActivationServiceImpl
> [New Scheduler] Add ActivationService

- ansible/files/runtimes.json
We stopped building the old (non-actionloop) python 3 docker image
about six months ago. Update the default image name so we use/test the
actionloop-based python3 runtime.
> update default python3 image name

- ansible/group_vars/all
kafka latest version: `2.7.0` fixed a bug: https://issues.apache.org/jira/browse/KAFKA-8334
It happened in our env, after deploy latest kafka version in PM, the problem gone.
> Make kafka version configurable

- ansible/group_vars/all
- ansible/roles/invoker/tasks/deploy.yml
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/InvokerHealthManager.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/DefaultInvokerServer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerServer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/common/WhiskProperties.java
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/DefaultInvokerServerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/FPCInvokerServerTests.scala
Manage New scheduler's invokerServer. provide basic disable/enable for the invoker.
These http endpoints are for deployment or get the invoker's current situation, nomally, when do zerodowntime deployment,
need to send /disable request to invoker, make the invoker's status to `down`, then, the new activations will not be sent to the invoker, we can wait the invoker executed all flying activations, then, we can stop the invoker safely and deploy the invoker .
* /disable
e.g. curl -X POST -u xxx:xxx http://$invoker:12001/disable, disabled the invoker, the invoker status will be changed to `unhealthy` firstly and changed to`down` finally after several seconds.
* /enable
e.g. curl -X POST -u xxx:xxx http://$invoker:12001/enable, enable the invoker, the invoker status will be changed to `up` …
> [New Scheduler]Implement PFCInvokerServer

- ansible/group_vars/all
- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/common/UserEvents.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/ack/MessagingActiveAck.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/RemoteCacheInvalidation.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LoadBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
- tests/src/test/resources/application.conf.j2
This pr's target is, add prefix for all topics and add extra prefix for userEvent topic only.
After applied this pr, some zones(e.g. test1, test2, test3) can share same kafka instance using different prefix topic,
BTW, userEvent is special, user may want to send some zones's event to same topic, so added extra prefix for it, user can decide whether want to send the event to same topic or different topic.
I tested in my local env
* Default configuration (all topics's prefix is empty string), topics name as below
* kafka_topics_prefix: "blue_" and kafka_topics_userEvent_prefix: "test_"
And the activations are successful on above 2 cases both.
> Add prefix for topics

- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/DocInfo.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Size.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerPool.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/InvokerHealthManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/connector/test/TestConnector.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerPoolTests.scala
Manage container pool.
Design document: https://cwiki.apache.org/confluence/display/OPENWHISK/FunctionPullingContainerPool
> [New Scheduler] Implement FunctionPullingContainerPool

- ansible/files/runtimes.json
- tests/src/test/scala/common/WskTestHelpers.scala
- tools/travis/runStandaloneTests.sh
Node.js v10 hit end of life on April 30, 2021.  Mark nodejs:10 as deprecated; the next step towards removing nodejs:10 support.
> deprecate nodejs:10 kind

- docs/dev/modules.md
- tools/dev/src/main/groovy/CategoryManager.groovy
Regenerate the module list (and update category mapping used to generate it).
> refresh module list

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Size.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/ContainerMessageConsumer.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/ContainerMessageConsumerTests.scala
The container message consumer subscribes to Kafka's containerCreation topic and handles container creation/deletion requests.
The FPCInvokerReactive, which will be newly added, uses this consumer.
> [New Scheduler] Add container message consumer

- docs/actions.md
In slack, some guys said, didn't know how prewarmed conainers works, so i add  the `document for prewarmed container`
> Document for prewarmed container

- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/scheduler/src/main/resources/application.conf
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/ContainerManager.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/CreationJobManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/CreationJobManagerTests.scala
This module records container creation using a `CreationId`, when a new container creation request is created, one entry with an unique `CreationId` will be created and saved in to ETCD, and will be deleted when creation is finished(or timeout waiting for creation complete ack).
So that a `MemoryQueue` can query how many containers are being created from ETCD and then do containers scheduling based on this value.
It can also help to trace/debug the procedure of a container creation.
> [New Scheduler]Add CreationJobManager

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/ActivationClientProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/ActivationClientProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
Fix build error, and the error is leaded by this pr: Upgrade to Akka 2.6.12: https://github.com/apache/openwhisk/pull/5065
When i tested, forgot to rebase that pr.
> Fix build error

- common/scala/src/main/scala/org/apache/openwhisk/core/database/mongodb/MongoDBArtifactStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/mongodb/MongoDBArtifactStoreProvider.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/mongodb/MongoDBAsyncStreamGraphTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/mongodb/MongoDBStoreBehaviorBase.scala
> Fix deprecated error

- ansible/README.md
- tools/macos/README.md
I've recently configured a new Mac and I've taken the chance to use more recent libs. After successfully running OW locally, I've updated the docs with the versions. 
I've also included a section detailing how to run unit tests locally.
> Docs update for local dev

- ansible/README.md
Fixed steps Deploying Using CouchDB
Caused by this commit
https://github.com/apache/openwhisk/commit/f788d095565c14d3a2908cdf71215498a5512b36#diff-fac2c4b2da0d1130d0f929abfff14008a96373c769abad4fdd1c8ee2ffca5226L141
> Fix ansible README

- ansible/group_vars/all
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Size.scala
- core/scheduler/src/main/resources/application.conf
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
The queue manager has a queue pool and decides to create and delete queues. If there is a queue of the same action in another scheduler, it will not be created. It is also responsible for passing activations to each queue. And when the action is updated, it deletes the existing queue and creates a new version of the queue.
documents: https://cwiki.apache.org/confluence/display/OPENWHISK/QueueManager
> [New Scheduler] Manage memory queues in scheduler

- tests/src/test/scala/org/apache/openwhisk/standalone/StandaloneKCFTests.scala
The only test case being run (invoke a blocking action
and get a result) fails quite frequently when run in
a travis-ci environment.  It appears we usually hit the
60 second timeout and return a 202 with the activation id
instead of the expected result.  This is "ok", but the test
is not prepared to handle it.
An alternative would be to modify the test to also accept a 202
response and then poll until the result was available, but that
would take significantly more work.
> Disable StandaloneKCFTests

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
Remove bits of mesos code missed in #5133
> cleanup: remove obsolete mesos configuration

- ansible/files/runtimes.json
We changed the image name we use to publish on dockerhub
from actionloop-python-v3.7 to action-python-v3.7 and
forgot to update runtime.json to match.
> update name for Python 3 image

- common/scala/build.gradle
It appears the version 12.6.0 of com.azure:azure-storage-blob has
been removed from the maven central repo.  Our builds have been failing
for about 3 days trying to download it.  Version 12.7.0 is available,
so hack around the build problems by upgrading one minor version.
A typical failing build is: https://app.travis-ci.com/github/apache/openwhisk-runtime-rust/jobs/531822834#L279
> minor version bump of azure-storage-blob to fix builds

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
> Accept non-standard status codes.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Both of the links in the comment of the issue template are broken this replaces contact.html -> community.html and fixes the slack link to the current URL as well as the code style link in the pull request template
> Fix links in Issue and PR Template

- common/scala/src/main/scala/org/apache/openwhisk/common/AverageRingBuffer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/FPCPoolBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LoadBalancer.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/FPCPoolBalancerTests.scala
- tools/travis/setupPrereq.sh
This is to add FPCPoolBalancer
I opened a new PR to see if there is any difference in the Travis CI environment.
Old one: https://github.com/apache/openwhisk/pull/5158
> Add FPC Load Balancer

- common/scala/src/main/scala/org/apache/openwhisk/common/AverageRingBuffer.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/CreationJobManager.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/CreationJobManagerTests.scala
This is to update the main method of the scheduler.
> [New Scheduler] Update main method of the scheduler.

- ansible/group_vars/all
- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/ack/HealthActionAck.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/Identity.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerReactive.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/DefaultInvokerServerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/FPCInvokerServerTests.scala
This component is for `initialize the invoker side's components when invoker starts up`, can use `FPCInvokerReactive`
instead of `InvokerReactive` using SPI mechanism here: https://github.com/apache/openwhisk/blob/master/common/scala/src/main/resources/reference.conf#L29
> [New Scheduler] Implement FPCInvokerReactive

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/DefaultInvokerServer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerReactive.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerServer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/DefaultInvokerServerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/FPCInvokerServerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala
add enable/disable invoker support to old scheduler
Adds enable / disabling of original invoker implementation. Disabling will turn off the scheduler of health pings so the controller will view the invoker as offline. Enabling will reschedule the health pings if it was disabled. Also added a route for both invoker types to check if an invoker is disabled so that the state of a running invoker does not get lost.
> add enable/disable invoker support to old scheduler

- ansible/group_vars/all
- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- ansible/roles/schedulers/tasks/deploy.yml
- common/scala/src/main/resources/reference.conf
Add some missing configuration for new scheduler
> Fix new scheduler error

- core/invoker/src/main/resources/application.conf
This is to reduce the keeping duration.
In FPCScheduler, this value is used to decide how much time do we keep the warmed container.
Currently, it is 60 minutes and it means after a timeout of paused container(10mins), it will keep the last container for another 60 minutes.
I think this is not a good value for the default.
In many cases that people develop or test OpenWhisk, there would be fewer resources in their dev environment and this would cause out of resources easily.
> Adjust the keeping duration.

- ansible/roles/cli/tasks/deploy.yml
When I would run the command below:
```
ansible-playbook -i environments/$ENVIRONMENT openwhisk.yml -e db_activation_backend=ElasticSearch
```
I would get this CLI error:
```
TASK [cli : Download release archive to build directory ...] ***********************************************************************************************************************************************
Tuesday 22 March 2022  14:56:04 -0600 (0:00:00.397)       0:02:33.675 ********* 
fatal: [172.17.0.1]: FAILED! => {"changed": false, "msg": "argument 'headers' is of type <class 'str'> and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value"}
argument 'headers' is of type <class 'str'> and we were unable to convert
to dict: dictionary requested, could not parse JSON or …
```
> Fix ansible python dictionary error

- ansible/README.md
Update scheduler instructions based on recent commit (which rendered one step unnecessary) and add more information about using the scheduler without ElasticSearch.
Instructions tested in my local ansible setup on Ubuntu 20.04.
> Update Ansible scheduler instructions

- ansible/group_vars/all
- ansible/roles/schedulers/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/CreationJobManager.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/CreationJobManagerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueFlowTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
This is bug, if doesn't fix, the activation will be failed as below
```
activation processing is not initiated for 60000 ms
```
This is enhance point, during retry,
* wait 100.milliseconds for 0th retry
* wait 200.milliseconds for 1th retry
* wait 400.milliseconds for 2th retry
* wait 800.milliseconds for 3th retry
* wait 1600.milliseconds for 4th retry
> send old version memoryQueue's stale activation to queueManager when update action

- build.gradle
- common/scala/src/main/scala/org/apache/openwhisk/core/database/mongodb/MongoDBArtifactStoreProvider.scala
- tests/build.gradle
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/database/mongodb/MongoDBStoreBehaviorBase.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/grpc/test/ActivationServiceImplTests.scala
- tools/travis/runUnitTests.sh
Use testcontainers for testing mongodb just like elasticsearch, hope this can fix cron build error of master too
> Use testcontainers to test MongoDB stuff

- build.gradle
- tests/build.gradle
- tests/src/test/resources/templates/build.gradle.mustache
just use `mavenCentral()` to replace `jcenter()` in `build.gradle.mustache`
> Use a template for swagger code generating

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/ActivationClientProxy.scala
returned type for `RescheduleResponse` is not correct
> Fix wrong returned type when reschedule activation msg

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/ContainerManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala
Need to compare the revision when choose warmed container
> Take revision into consideration when choose warm container

- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/controller/src/main/resources/reference.conf
- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/Entitlement.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/FPCEntitlement.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/FPCPoolBalancer.scala
Could use some help verifying this actually works as I'm not totally familiar with the entitlement code path, but I'm pretty sure I have what is needed here since the `FPCEntitlementProvider` just extends from the original overriding the `checkThrottles`.
So FPC currently doesn't support per minute throttling of namespaces. While the system no longer needs these throttles to protect itself with the new fpc scheduler enhancement, it is still a valuable feature to allow for user functions to protect their downstream by having reasonable per minute limits. And it's just a feature that I think is unnecessarily lost if still needed for certain use cases. Ideally people can slowly move away from using this feature, but having the option at least available makes it easier for people to more …
> add per min throttling support to fpc

- proposals/POEM-3-action-limit-for-namespace.md
This is the POEM documentation for new feature providing action limits for each namespace. 
I refer to this guide document for POEM: https://github.com/apache/openwhisk/blob/master/proposals/README.md
- I have added the POEM full text to the PR body to make the document easier to read.
- If you have any concerns, questions, or typos, please leave a comment and I will check it out.
- The code for this change can be found here.
- https://github.com/apache/openwhisk/pull/5229
------
Providing action limits for each namespace
* Current state: In-progress
* Author(s): @upgle
This POEM proposes a new feature that allows administrators to set action limits (memory, timeout, log, and concurrency) for each namespace.
Sometimes some users want to make an action with more memory and longer duration. …
> [Proposal] POEM: Providing action limits for each namespace

- core/controller/src/main/resources/reference.conf
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/FPCPoolBalancer.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/SchedulingDecisionMaker.scala
- tests/src/test/resources/application.conf.j2
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/FPCEntitlementTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/FPCPoolBalancerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/grpc/test/ActivationServiceImplTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/ContainerCounterTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueFlowTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTestsFixture.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/SchedulingDecisionMakerTests.scala
Add some testcases&missing ASF headers
> Add some testcases and missing ASF headers for new scheduler 

- core/controller/src/main/resources/reference.conf
Quick fix for the conf key in the default conf file for the new per min throttle config for fpc I made yesterday. The config key in the configuration file was incorrect. I've verified this fixes the issue. I also have verified that per minute throttling now works on the new scheduler same as the old scheduler when setting this config.
N/A
> fix perMin throttle config for fpc

- core/scheduler/src/main/resources/application.conf
- tests/src/test/resources/application.conf.j2
The configuration for running the scheduler is missing, so I added the configuration.
> Add missing configuration for scheduler

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerPool.scala
There has container start relative metric in FunctionFullContainerPool,
It is better to provide container size histogram metric as well
> Add containerPool container histogram metric

- tools/macos/README.md
ERROR: Invalid requirement: 'six=1.16.0'
Hint: = is not a valid operator. Did you mean == ?
> Fix missing keystroke in requirements

- ansible/files/runtimes.json
Update runtimes.json for NodeJS and GoLang to remove EOL versions.
> refresh runtime versions for nodejs and golang

- ansible/group_vars/all
- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/DefaultInvokerServer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerServer.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/FPCSchedulerServer.scala
Replace hardcode username:password
> Use pureconfig for invoker/scheduler's basic http auth

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
Stop sending activation message to `QueueManager` itself again but recover `MemoryQueue` instead when cycle happens
> Prevent cycle sending

- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerPool.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
Don't remove lots of containers/pods at once to avoid overload
> Remove containers gradually when disable invoker

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
The current scheduler wait time metric emits as soon as the queue manager receives an activation. From this point it's then put on to the respective action queue in which it may wait for variable amounts of time until the activation is retrieved by an action container from the queue. The existing wait time metric still exists but is renamed to `kafkaWaitTime` since it's essentially the wait time from when the transaction starts to when it gets to the scheduler. The new version of `waitTime` metric emits for an action whenever the action either is force error completed within the memory queue or when the activation is forwarded to an action container and removed from the scheduler queue.
N/A
> rework scheduler wait time metric to include total time in scheduler

- tools/ow-utils/Dockerfile
Fix Issue#5260
I encountered this problem and raised the issue#5260. In short, the install-package pods deployed via openwhisk-deploy-kube project helm charts fails due to using the default npm installed by apt to install alarm package. This PR basically update the npm in docker image ow-utils which is used by the install-package pod.
I have built the image with `./gradlew tools:ow-utils:distDocker`, pushed my own repository, and configure the helm charts to use it. And I can successfully deploy openwhisk on my kubernetes cluster again.
> Update npm version for ow-utils docker

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
When some containers are terminated as they are idle, a memory queue still sends activations to them as their request are in the buffer.
> [Scheduler Enhancement] Remove deleted containers.

- common/scala/src/main/scala/org/apache/openwhisk/core/etcd/EtcdClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/etcd/EtcdUtils.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/FPCPoolBalancer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerReactive.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
- tests/src/test/scala/org/apache/openwhisk/common/etcd/EtcdConfigTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/FPCPoolBalancerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala
Allows connecting to an etcd cluster with authentication setup. Can just define etcd username and password through config like other db provider configs.
> add support for etcd client authentication

- common/scala/src/main/scala/org/apache/openwhisk/core/service/WatcherService.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/FPCPoolBalancer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerPool.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/InvokerHealthManager.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
Currently, binding action is not properly considered while creating or recovering queues.
It makes throttling for package actions work in an original namespace and actions from different namespaces share the same throttling limit.
This change will address the issue.
> [Scheduler Enhancement] Consider binding action when creating or recovering queue.

- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/InvokerBootUpTests.scala
These test cases would make sure invokers properly remove ETCD keys for health actions after becoming healthy.
> [Scheduler Enhancement] Add test cases to make sure an invoker properly boots up in terms of ETCD keys.

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/CreationJobManager.scala
In the recent commit, inProgressJobRetention is parsed as an integer. However, in places such as ```ansible/group_vars/all``` and ```src/test/resources/application.conf.j2``` it was defined as a Duration (e.g., default is ```'20 seconds'```)
This PR is to change inProgressJobRetention to be parsed as a duration.
> Fix scheduler inProgressJobRetention parsing

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainer.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala
- tests/src/test/scala/org/apache/openwhisk/common/etcd/EtcdConfigTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerClientTests.scala
Currently, if the system fails to pull a black-box image, it keeps waiting for the runtime pod to be running.
```
$ kubectl get pods
...
wsk-blue-test-invoker-38-47-style95-dockeraction     0/1     ImagePullBackOff   0          41h
wsk-blue-test-invoker-38-48-style95-dockeraction     0/1     ImagePullBackOff   0          41h
...
```
If the pod creation is failed due to image pulling, we can complete activations with an error.
Another case is a black-box pod is failed to run because a command is not found.
In such cases, the system can let users know about the issues in their images.
> Fail all activations when it fails to pull a blackbox image.

- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
- tests/dat/actions/params.js
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
- tests/src/test/scala/system/basic/WskSequenceTests.scala
This is to forward headers delivered to triggers to actions.
This is useful when an event source sends some information via headers.
A good example could be the `X-Github-Event` header in Github APIs.
Currently, this kind of information is dropped.
> Forward header from a trigger to actions.

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- settings.gradle
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/WhiskPodBuilderTests.scala
This is to fix #5274 by upgrading the Kubernetes client.
> Upgrade the Kubernetes client minor version.

- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/database/Batcher.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/elasticsearch/ElasticSearchActivationStore.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/test/BatcherTests.scala
Sometimes, the system fails to store activations for intermittent errors such as network rupture.
It would be great to retry storing them in such a case.
> Add retry to store activations.

- ansible/roles/nginx/templates/nginx.conf.j2
This is to increase the payload limit of Nginx.
It's related to this: https://github.com/apache/openwhisk/pull/3835
Because of the base64 overhead, we can't send a payload with 50MB.
> Increase the payload limit of Nginx.

- tests/src/test/scala/common/RunCliCmd.scala
- tests/src/test/scala/org/apache/openwhisk/common/RunCliCmdTests.scala
Sometimes, requests against CouchDB failed.
```
stdout: Failed to create subject ([Errno 110] Connection timed out)
.
.
.
stdout: The subject you want to edit is blocked
```
It is harmless to retry not only for the network error, but also for any errors.
> Retry on any errors.

- docs/warmed-containers.md
This is to add documentation about the configurations for warmed containers.
> Add a documentation for warmed containers configurations.

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivationResult.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
This is to support the graceful shutdown.
When OW is running on K8S and a pod is drained for some reason (server maintenance..)
Our runtime pod also shut down and a time-out error can occur.
In this case, activation's result is an action developer error but it's actually the internal system error.
So this is to handle such a case.
> Support graceful shutdown of runtime pods.

- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- docs/tag-based-scheduling.md
This is to enable tag-based scheduling.
We can add tags to invokers like below.
```
[invokers]
invoker0            ansible_host=172.17.0.1 ansible_connection=local tags="['v2', 'gpu']"
```
There are already some codes for tag-based scheduling.
https://github.com/apache/openwhisk/blob/master/tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala#L615
This is to add missing parts.
> Add tags to invokers.

- ansible/group_vars/all
- ansible/roles/elasticsearch/templates/elasticsearch.yml.j2
This is to make the ElasticSearch ports configurable.
> Make ElasticSearch ports configurable.

- ansible/README.md
- core/invoker/src/main/resources/application.conf
The default value of pause-grace, which is 50 milliseconds by default, is too short for FPCScheduler. If requests' time intervals are longer than 50ms, the container will be paused and can't pull requests from MemoryQueue, doesn't take advantage of the ActivationProxy-ActivationService path, which is the core of FPCScheduler design. So we need to set the pause-grace to a longer value, 10s by default now.
To prove this, I did a test for FPCScheduler. I sent 5 concurrent requests every 5 seconds, the second 5 requests would be successfully picked up by GetActivaion in MemoryQueue. But for subsequent concurrent requests, the SchedulingDecisionMaker would keep matching an exceptional case:
```
// this is an exceptional case, create a container immediately
case (Running, _) if totalContainers …
```
> Change the value of pause-grace for new scheduler

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/ContainerMessageConsumer.scala
- tests/src/test/scala/org/apache/openwhisk/core/invoker/test/ContainerMessageConsumerTests.scala
When an action is already updated but activations with an old revision arrive, this error can happen.
It is not supposed to happen in a normal case but it might happen when a cache invalidation issue happens for some reason.
> Adjust error for container creation.

- proposals/POEM-support-array-result.md
This is the POEM documentation for new feature providing `support array result for all runtime images`
I refer to this guide document for POEM: https://github.com/apache/openwhisk/blob/master/proposals/README.md
> [Proposal] POEM: provide array result for all runtime images

- tests/src/test/scala/common/WskTestHelpers.scala
- tests/src/test/scala/system/basic/WskActivationTests.scala
This is one of basic functionalities, but the test will help to guarantee it.
> This is to make sure activations for a shared action run in an invocation namespace.

- proposals/POEM-4-action-concurrency-limit-within-namespace.md
POEM for allowing users to configure fairness within their namespace across their actions. This allows users to control how much an action can autoscale within the confines of the system admin controlled namespace concurrency limit.
> [POEM] Allow Users To Configure Max Action Container Concurrency Under Their Namespace Limit

- .gitignore
Removed duplicate `.gitignore` entry
> chore: remove duplicate entry from .gitignore

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/AkkaContainerClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/elasticsearch/ElasticSearchActivationStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/ActivationResult.scala
- common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PostActionActivation.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/SequenceActions.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- tests/dat/actions/helloArray.js
- tests/dat/actions/sort-array.js
- tests/dat/actions/split-array.js
- tests/src/test/scala/actionContainers/ActionContainer.scala
- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
- tests/src/test/scala/common/WskTestHelpers.scala
- tests/src/test/scala/invokerShoot/ShootInvokerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ConductorsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
- tests/src/test/scala/system/basic/WskActionTests.scala
- tests/src/test/scala/system/basic/WskConductorTests.scala
- tests/src/test/scala/system/basic/WskSequenceTests.scala
- tests/src/test/scala/system/basic/WskUnicodeTests.scala
POEM document pr: https://github.com/apache/openwhisk/pull/5244
This feature is:  provide support array result feature for common action and sequence action. e.g.
* Support array result for common action (support nodejs by default, so let's use nodejs as example)
```
function main(params) {
console.log("-------------log test---------")
return [{"key1":"value1"},{"key2":"value2"}];
}
REQUEST:
[POST]	http://xxx.xxx.xxx.xxx:10001/api/v1/namespaces/_/actions/hello-array-nodejs?blocking=true&result=true
...
...
Response body size is 37 bytes
Response body received:
[{"key1":"value1"},{"key2":"value2"}]
```
* Support array result for sequence action
```
function main(msg) {
var separator = msg.separator || /\r?\n/;
var lines = payload.split(separator);
// below lines result is array, it will be …
```
> Support array result for common action and sequence action

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
This is to revert the recent change.
https://github.com/apache/openwhisk/pull/5251 is introduced to handle the cyclic activations storm in a queue manager.
But with this change, I observed severe performance degradation.
This is the performance measurement with the current master.
And this is the result of this change.
This is because even for normal activations, the queue manager tries to recover a queue.
There is a gap between the time that leader election is done(etcd data is written) and the queue is ready.
If activations come during that time, the queue manager tries to recover a queue and it increases the wait time.
And the result is well aligned with the one I performed for the initial run.
https://github.com/apache/openwhisk/pull/5194#issuecomment-1019875232
Since the cycle in a …
> Revert cycle handling.

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueFlowTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
Currently, MemoryQueue will go to the Flushing state when receiving an EnableNamespaceThrottling(dropMsg=true) message, but the Flushing state doesn't have a case to disable namespace throttling at all.
So without this change, the queue may not disable the namespace throttling.
> Go to the NamespaceThrottled state rather than Flushing state.

- tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
Some downstream runtimes may not support the array return type. 
(This also happens when using a legacy action loop base.)
In this case, test case will fail and you will be inconvenient for maintaining. 
I think it is should be preserved backward compatibility.
https://github.com/apache/openwhisk/pull/5290
> Fix runtime return type backward compatibility

- common/scala/src/main/scala/org/apache/openwhisk/common/time/Clock.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueFlowTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
There is an issue that the test results are different depending on the performance of the build machine because the test code is written in a time-dependent. This PR improves memory queue test code that fails like heisenbug.
- Use fake clock to improve time-dependent test code execution time.
- The memory queue test execution time was reduced from 7m3s -> 1m34s in downstream environment.
- Remove thread sleep and explicitly calls StateTimeout.
> Add fake clock for test code

- docs/actions-docker.md
- docs/actions-dotnet.md
- docs/actions-go.md
- docs/actions-java.md
- docs/actions-nodejs.md
- docs/actions-php.md
- docs/actions-python.md
- docs/actions-ruby.md
- docs/actions-rust.md
- docs/actions-swift.md
- tests/dat/actions/unicode.tests/swift-4.2.txt
- tests/dat/actions/unicode.tests/swift-5.1.txt
- tests/dat/actions/unicode.tests/swift-5.3.txt
> Add document for support array result

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerReactive.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/ContainerManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala
This is not to send container creation messages to disabled invokers.
> Exclude warmed containers in disabled invokers.

- common/scala/build.gradle
Current etcd client version is from 2019. Bump to latest patch version.
> bump java etcd client to 0.0.21

- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/StandaloneDockerSupport.scala
If additional args are added as the operator, you may not want those args exposed in logging. This gives the operator the option to just all up mask the args of the docker run command while still logging that the docker run occurred for the image.
> add config to mask docker run args when logging

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/ContainerManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala
This is to skip scheduling of cold creation if there is no message.
It's actually harmless but keeps printing an error log.
> Skip scheduling for empty cold creation.

- common/scala/build.gradle
This is to fix https://github.com/apache/openwhisk/issues/5317 by reverting https://github.com/apache/openwhisk/commit/40077664ab3011e7a333b0197fa9a285502a1d81.
It seems the version of gprc-core module in the ETCD client conflicts with akka-grpc module.
I am curious how it passed all checks in the first place, but anyway it would be the easiest way to resolve it for now.
I think we need to upgrade both modules at once.
> Revert etcd client version

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/container/ContainerManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/container/test/ContainerManagerTests.scala
There is no failure handling if the query to etcd for list of healthy invokers fails. The container manager swallows the message and the memory queue will never hear back the status of the container creation.
> add error handling to container manager when invoker query fails

- docs/concurrency.md
This PR adds information on concurrency.md about the existing concurrency limit config that needs to be changed if one wants to enable concurrency.
> Add note on concurrency limit config to concurrency.md

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
Include the container and creation ids in the log when queue attempts to stop. Will help with debugging when in memory queue data gets out of sync with etcd or if etcd data hasn't been properly updated. Helps with knowing if the id corresponds to the id in the invoker that failed to make a request to etcd or if that id recovered and another container was lost with regards to tracking in the memory queue
> add container and creation ids to memory queue log

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
You can read a more detailed series of events to hit this case in the corresponding issue, but here's the tldr:
1. Container doesn't have activations so transitions to pause container.
2. Container times out once paused and is ready to be deleted.
3. In order to delete once paused, a check is required for the count of containers to determine whether it should delete.
4. The etcd request fails and the failed future is piped to the fsm. The paused state doesn't handle this message type so it stashes it until a state transition and the container proxy will sit in this corrupted state until a new activation is received.
5. New activation is received and the container is attempted to be unpaused and the fsm transitions back to Running while it waits for the unpause future to complete.
6. When …
> Fix Orphaned Container Edge Case In Paused State of Container Proxy

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
This adds a periodic message to the container proxy that will make a request to the function cache to keep the function in the cache. The cache used to store downloaded functions has a keepalive for 5 minutes between accesses before it evicts. The default openwhisk container idleTimeout is 10 minutes. This means if you're using the default, you have a five minute gap between when a function is evicted and the container continues to run where once the container is unpaused it has to redownload the function before serving an activation. This doesn't really make any sense since behavior wise since the warm container already has the data it needs and the function check is mainly just for verifying it hasn't been updated. So this takes re-downloading the function cache off the critical path …
> Add Function Cache Refresh If Invoker Is Running Container For Function

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerReactive.scala
I don't think this feature should be turned on by default. You should be required to configure to keep the compute around rather than it leave one container by default for an extra x minutes (I think the default system config for this is 10min) past the idle timeout. It also isn't very helpful to default to that by namespace because there can be multiple actions per namespace so it's not very helpful to by default leave one container hanging around using resources when the next request may not even be for that action within the namespace.
We can discuss here, but figured I'd just go ahead and open the pr to discuss
> change default warmed container keeping count to 0 if not configured

- ansible/README.md
- ansible/roles/schedulers/tasks/deploy.yml
While trying to hot swap the scheduler as a single component using ansible, I came across a typo in the ansible documentation as well as a typo in the scheduler ansible deploy.yml file. Fixing the typo in the deploy.yml allowed me to successfully hot swap the scheduler component in my local ansible setup.
> Fix minor ansible typos

- common/scala/src/main/scala/org/apache/openwhisk/core/etcd/EtcdClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/etcd/EtcdWorker.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/service/DataManagementService.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/FPCInvokerReactive.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
- tests/src/test/scala/org/apache/openwhisk/common/etcd/EtcdWorkerTests.scala
I don't think this is the root of my issue with the scheduler not learning that a container has been removed, but nevertheless this is a valuable refactor to make sure everything is thread safe in this actor.
There should be no behavior change to the actor at all, should be 100% refactor.
This pr does a couple things:
1. Move etcd worker to its own file under the etcd folder in commons
2. Clean up the error handling to remove duplicate code
3. Make the retry handling more thread safe by first forwarding the retry message and using the actor's internal timers scheduler rather than the system scheduler
4. Fix non-thread safe access to actor member variable `lease` from future callbacks through 3.
5. Add unit tests for EtcdWorker which previously wasn't covered.
> Clean Up Etcd Worker Actor

- ansible/roles/controller/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
This is to delete ETCD data first when disabling an invoker.
Previously data was removed only after an activation client proxy is completely closed.
But when there are many containers running for a given action and we disable an invoker, it may cause a sudden container creation spike. Since some containers are suddenly removed, a scheduler would decide to provision similar numbers of containers at once.
If we delete the ETCD data first, then schedulers can initiate container provisioning while disabled containers are still processing the last activation for them.
- [] Scheduler
> Delete ETCD data first when disabling the invoker

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
This is basically based on https://github.com/apache/openwhisk/pull/5251
I just added a small change to improve the performance.
**Without** performance optimization.
**With** performance optimization.
> Prevent cycle in the QueueManager

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/SchedulingDecisionMaker.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/SchedulingDecisionMakerTests.scala
I believe this optimizes scheduling decisions and reduces overprovisioning without sacrificing any performance. The reasoning here is if a queue has stale activations, you risk over-provisioning if you make the calculation based on all available messages,  not just stale ones. Here is an example:
t0ms: 5 activation arrives and for whatever reason it takes 100ms before the activation is processed even if there are containers existing (random network latency or whatever the brief blip may be). Let's say container throughput is 10 (10ms duration) and there's already 10 containers.
t50ms: 100 activations arrive and are available
t100ms: 5 activation is stale and enters the decision case when there is a stale activation. However it uses all 105 activations available to make a scheduling …
> optimize scheduling decision when there are stale activations

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/ActivationClientProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
This is to make the test stable.
> Make the test stable

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/ActivationClientProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/InvokerHealthManager.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/SchedulingDecisionMaker.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/ActivationClientProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
This is to fix the regression introduced from https://github.com/apache/openwhisk/pull/5338
> Handle container cleanup from ActivationClient shutdown gracefully

- common/scala/src/main/scala/org/apache/openwhisk/core/database/DocumentFactory.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/ApiUtils.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/QueueManagerTests.scala
This is a critical bug that's gone unsolved for several years. Since attachments are considered secondary files to the main action document, if the attachment is lost for whatever reason (upload timeout, concurrent upload, bad database replication, etc.) the action document is therefore corrupted in a stuck state because the document factory is set up to do a get of the document first when performing a `putEntity` or `deleteEntity`. The `WhiskAction` type overrides the `get` operation to include getting the attachment as a part of the `get` operation. However once the root document is retrieved, the attachment is then tried to be read and returns a not found making the `get` return a `DocumentNotFoundException` to the `putEntity` or `deleteEntity`. You can therefore never delete or update …
> Fix missing attachment stuck actions

- .github/workflows/0-on-demand.yaml
- .github/workflows/1-unit.yaml
- .github/workflows/2-system.yaml
- .github/workflows/3-multi-runtime.yaml
- .github/workflows/4-standalone.yaml
- .github/workflows/5-scheduler.yaml
- .github/workflows/6-performance.yaml
- .github/workflows/README.md
- tests/src/test/scala/org/apache/openwhisk/core/database/s3/S3Aws.scala
- tools/github/checkAndUploadLogs.sh
- tools/github/s3-upload.sh
- tools/github/setup.sh
Changes to run without errors.
My github actions pass the AWS_ACCESS_ID secrets to the build but since they are pull requests they are empty. 
This enables some tests usually skipped that fails. So I changed the name of the variables used to upload logs.
Furthermore I made optional the upload of logs and slack notification and printed the results of the test in the job run for inspection.
Now all tests pass.
Build fails because of overlap of env variables
> fixes to use different secrets, show the results in the log

- .github/workflows/1-unit.yaml
- .github/workflows/2-system.yaml
- .github/workflows/3-multi-runtime.yaml
- .github/workflows/4-standalone.yaml
- .github/workflows/5-scheduler.yaml
- .github/workflows/6-performance.yaml
Add schedule clause to GitHub actions to cause them to run 3 times a week.  Schedule is offset by 1 hour for each workflow file to avoid heavy spikes.
> schedule actions to run at least 3 times a week

- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
I am unsure how it passed the CI tests in the first place but this bug is introduced by https://github.com/apache/openwhisk/pull/5229
> Fix the bug that match does not exhaustive

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/Scheduler.scala
First step to getting rid of the zookeeper dependency on the invokers. Invokers currently can already be started without the zookeeper config if `--id` flag is set which is already the case in ansible. The only case that needs to be covered still before removing the dependency is adding support for kubernetes deployment. If started without config and need to connect to zookeeper still, the invoker will fail and shut down anyways from failing to connect to zookeeper in the instance id assigner on startup so this shouldn't be a breaking change.
> remove zookeeper config requirement

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/SchedulingDecisionMaker.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueFlowTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/SchedulingDecisionMakerTests.scala
Have the scheduling decision maker make container creation decisions using a throughput calculation that considers how many concurrent requests a container can take. This should exhibit the same throughput guarantees as is, but without unnecessary potential fan out of containers when an action has concurrency greater than one since the scheduler didn't consider it up until this point. **There is no semantic change to behavior from this commit if action concurrency == 1.**
Example: consider you have 100 incoming activations in the queue for an action with a concurrency of 10 with 1 existing container up currently processing 10 activations when the scheduling decision is made. The average duration is 10ms so the container throughput for this action due to the concurrency is really 100. So …
> make scheduler consider action concurrency >1

- common/scala/build.gradle
The dependency upgrade I merged in over the weekend has an issue with the logback minor upgrade. It seems the package is built past jdk8 and fails at runtime when trying to run with jdk8. I don't think a full revert is necessary since validated things look good now just going forward to the latest patch which I think still covers the cve.
> rollback logback minor upgrade to latest patch

- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/ActivationClientProxyTests.scala
I don't believe the `inAnyOrder` actually works as expected. This should fix the problematic test.
> fix flaky ActivationClientProxy unit test

- common/scala/build.gradle
- settings.gradle
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/cache/CacheInvalidatorTests.scala
More dependency upgrades to deal with cve patches.
Have to pin the netty version. There's too many dependencies that pull it in that have breaking changes that it's not worth dealing with if pinning the latest patch works fine.
> dependency updates for cve patches (part 2)

- docs/actions-go.md
While reading the documentation I fell over some malformed/broken Markdown
> Docs golang broken markdown link

- common/scala/build.gradle
- core/monitoring/user-events/build.gradle
- core/standalone/build.gradle
- settings.gradle
- tests/build.gradle
- tools/admin/build.gradle
For what's left, I'm overriding transitive dependencies where possible and give a description on the reason for the constraint
> dependency updates for cve patches (part 3)

- common/scala/build.gradle
- core/controller/build.gradle
- core/cosmosdb/cache-invalidator/build.gradle
- core/invoker/build.gradle
- core/monitoring/user-events/build.gradle
- core/scheduler/build.gradle
- core/standalone/build.gradle
- tests/build.gradle
- tools/admin/build.gradle
> attempt to fix downstream runtime builds

- common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
The memory queue will now track the last time that an activation has been pulled by a grpc request to send to an invoker. If an activation is dropped from the queue from aging out and there hasn't been a single activation grabbed by an invoker for the entire duration that the activation sat in the queue, then this gauge will fire. This is needed as a fail safe to be made aware to any edge cases in the system where etcd data gets out of sync and containers are thought to exist by the scheduler that do not exist. Simply looking at activations timing out is not enough to determine an issue since the action may just be hitting throttling limits for number of containers.
So this should fire in only one case:
1. There's a bug in the scheduler that needs a restart of either the invokers and …
> Add Scheduler Queue Metric for Not Processing Any Activations

- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
I think this may be an additional case that was missed where the container proxy can shutdown without removing the container data from etcd.
> fix missed etcd unregister data case for an existing container in container proxy

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
- tests/src/test/scala/org/apache/openwhisk/core/scheduler/queue/test/MemoryQueueTests.scala
This is to handle the issue reported in https://github.com/apache/openwhisk/pull/5388 in another way.
> Send a queue removed message to the queue manager

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
Since the metric is a gauge, it will continue reporting the value once an action starts not processing and will never recover from the metric's perspective even if the action has actually recovered. Setting the gauge back to 0 should handle recovery without requiring a restart.
> fix action not processing metric

- common/scala/src/main/scala/org/apache/openwhisk/common/AverageRingBuffer.scala
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/SchedulingDecisionMaker.scala
The average ring buffer has an edge case where discarding the max and min outliers from the average calculation can result in the average being negative due to the max and min not ever being reset even when the max and min value is ultimately discarded from the ongoing buffer. So the way it's set up it keeps the absolute max and absolute min duration for this function that has ever occurred. I just got rid of the max and min outlier discarding for now because I don't think it's adding much value and to appropriately update the max and min would require a performance hit to the ring buffer. I've also added negative duration buffer protection to the scheduling decision maker so that if such a case were introduced again in the future, the scheduling decision maker can more gracefully handle …
> fix bug in average ring buffer and add negative duration protection to scheduler decision maker

- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/MemoryQueue.scala
This metric unfortunately does not work as a gauge. A gauge will report until there is a change in the value. I previously made a change so that the value would change back to 0 when a new activation is processed. However this does not account for 1. when the queue is stopped before setting the value back to 0 and 2. a queue is moved to a new host before the value is set back to 0 so the value for the action is still emitting 1 until a restart incorrectly reporting.
> update scheduler not processing metric to counter

- common/scala/build.gradle
- core/monitoring/user-events/build.gradle
- core/monitoring/user-events/src/test/scala/org/apache/openwhisk/core/monitoring/metrics/KafkaSpecBase.scala
- core/standalone/build.gradle
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/KafkaLauncher.scala
- settings.gradle
- tests/build.gradle
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/cache/CacheInvalidatorTests.scala
handles cve's and some critical bug fixes. This can be updated safely without updating underlying kafka of the ansible which is still set to 2.7.0. have tested a build myself that things still work but still need to see if all tests pass here.
cve's fixed:
- [CVE-2021-38153](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-38153)
cve's from transitive dependencies:
- [CVE-2020-25649](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25649)
- [CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250)
> upgrade kafka client library to 2.8.2

- common/scala/src/main/scala/org/apache/openwhisk/core/entity/InstanceConcurrencyLimit.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/entity/IntraConcurrencyLimit.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/controller/Limits.scala
- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
- core/standalone/src/main/scala/org/apache/openwhisk/standalone/KafkaLauncher.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/controller/test/LimitsApiTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/cache/CacheInvalidatorTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
I am not quite sure when this regression is introduced and why our CI could not catch it in the first place, but anyway, codes are wrongly formatted.
This change just applies one from scalaFmt.
> Apply scalaFmt

- tools/dev/build.gradle
quick security patch for groovy
> patch groovy 3.0.17

- .github/workflows/0-on-demand.yaml
- .github/workflows/1-unit.yaml
- .github/workflows/2-system.yaml
- .github/workflows/3-multi-runtime.yaml
- .github/workflows/4-standalone.yaml
- .github/workflows/5-scheduler.yaml
- .github/workflows/6-performance.yaml
- tools/github/setup.sh
This is to fast fail on any error.
> Finish setup on error

- .github/workflows/0-on-demand.yaml
- .github/workflows/1-unit.yaml
- .github/workflows/2-system.yaml
- .github/workflows/3-multi-runtime.yaml
- .github/workflows/4-standalone.yaml
- .github/workflows/5-scheduler.yaml
- .github/workflows/6-performance.yaml
Currently, every GitHub Actions workflow contains the `fail-fast` matrix strategy. However, none of these workflows are actually utilizing a matrix. Further, the on demand workflow has an improper indentation of this strategy block that causes a syntactical error.
This change remove the no-op strategy altogether to fix the broken on demand workflow and remove the IDE warnings regarding the missing matrix declaration.
> Remove `fail-fast` matrix strategy from GitHub Actions

- .github/workflows/0-on-demand.yaml
- .github/workflows/1-unit.yaml
- .github/workflows/2-system.yaml
- .github/workflows/3-multi-runtime.yaml
- .github/workflows/4-standalone.yaml
- .github/workflows/5-scheduler.yaml
- .github/workflows/6-performance.yaml
This change allows GitHub Actions builds to submit build scans to ge.apache.org by authenticating those builds. The access key has been stored as an organizational secret by the ASF Infrastructure team in the Apache GitHub organization. The access key is not available to workflows triggered from forks.
This builds on the changes in https://github.com/apache/openwhisk/pull/5411
> Authenticate GitHub Actions builds to ge.apache.org

- .github/workflows/3-multi-runtime.yaml
- core/scheduler/src/main/scala/org/apache/openwhisk/core/scheduler/queue/QueueManager.scala
This is to fix a bug in that ETCD data for non-existent containers persist forever.
This bug happens when a shared action is invoked.
When the queue manager receives an activation message, it finds a queue based on the `docId` only and this is wrong.
As a result, the activation message could be sent to the wrong queue as long as the `docId` is same.
But the `docId` is same for all shared actions.
ex) 
- original action: `/whisk.system/sharedPackage/hello`
- bound action1: `/style95/myPackage/hello` (docId: `/whisk.system/sharedPackage/hello`)
- bound action2: `/bdoyle/yourPackage/hello` (docId: `/whisk.system/sharedPackage/hello`) 
So an activation for `/style95/myPackage/hello` could be sent to `/bdoyle/yourPackage/hello`.
Then a memory queue will send the activation to a container for …
> Compare invocation namespaces when handling a cycle and recovering a queue

- .github/workflows/0-on-demand.yaml
- .github/workflows/1-unit.yaml
- .github/workflows/2-system.yaml
- .github/workflows/3-multi-runtime.yaml
- .github/workflows/4-standalone.yaml
- .github/workflows/5-scheduler.yaml
- .github/workflows/6-performance.yaml
While running tests, all indices of elasticsearch become read-only because of limited disk space.
This change maximize the build disk space by removing unnecessary built-in tools.
> Maximize build spaces of all workflows by manually removing unnecessary resources

- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerPoolTests.scala
This is just a missing part from [the recent update](https://github.com/apache/openwhisk/commit/54564cbc76771658c14a84dd413856d8b078eeb8#diff-263a4333bc9c835982b22be07c36c7d7be0f38c1f2d3602313d0bc7b498d4227R71).
> Update the nodejs action kind

- core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
As [`ZOOKEEPER_HOSTS` is removed from the required properties](https://github.com/apache/openwhisk/pull/5375), it is no longer transformed into the whisk config from the environment variables.
But when the instance id assigned is used, the zookeeper host becomes a required property.
This change is to make it an optional property.
> Add ZOOKEEPER_HOSTS as an optional property

- ansible/group_vars/all
- ansible/roles/invoker/tasks/deploy.yml
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNContainerFactory.scala
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainerFactory.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/StandaloneDockerContainerFactory.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/v2/FunctionPullingContainerProxy.scala
- tests/dat/actions/zippedaction/package-lock.json
- tests/src/test/scala/common/LoggedFunction.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolConfigTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerPoolTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/v2/test/FunctionPullingContainerProxyTests.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
This change provides the option to limit action container cpu usage proportional to the allocated memory. This helps to prevent an invoker from being overloaded by action cpu usage, and also provides more predictable performance for actions.
> Add optional cpu limit to spawned action containers

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/AkkaContainerClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/ElasticSearchLogStore.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/ElasticSearchRestClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestClient.scala
- common/scala/src/main/scala/org/apache/openwhisk/http/PoolingRestClient.scala
> Note: In our service, we use `PoolingRestClient` for communication between invokers and action pods and memory leak appears for long-running asynchronous invocations as it seems that objects allocated within streams are not clean properly after Akka materialization has been [removed](https://github.com/apache/openwhisk/pull/5065/files#diff-e0bd51cbcd58c3894e1ffa4894de22ddfd47ae87352912de0e30cd60db315758L131-R130).
- Replaced the usage of deprecated OverflowStrategy.dropNew with BoundedSourceQueueStage
- Added proper clean-up of materialized resources to prevent memory leaks for long-running streams
> Memory leak in `akka.actor.LocalActorRef`

- tools/github/setup.sh
> fix: message skipping typo

- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/AkkaContainerClient.scala
Handle https://github.com/apache/openwhisk/issues/5452
When sending concurrent requests, a queue full error happens.
So I increased the queue size according to [this value in the nodejs runtime repo](https://github.com/apache/openwhisk-runtime-nodejs/blob/master/tests/src/test/scala/runtime/actionContainers/NodeJsConcurrentTests.scala#L32).
> Use bigger queue size

- common/scala/src/main/scala/org/apache/openwhisk/common/Config.scala
The origin of issue is iteration through the config keys [here](https://github.com/apache/openwhisk/blob/master/common/scala/src/main/scala/org/apache/openwhisk/common/Config.scala#L145) and [here](https://github.com/apache/openwhisk/blob/master/common/scala/src/main/scala/org/apache/openwhisk/common/Config.scala#L156) and at the same time properties [change](https://github.com/apache/openwhisk/blob/master/common/scala/src/main/scala/org/apache/openwhisk/common/Config.scala#L150) in the loop which can lead to skipping some keys after `+=`.
- Fixed an issue with missed config keys while iterating through them on Scala 2.13.x
!Note: This issue reproduces only on Scala >= 2.13.x version and probably related to some internal changes in Scala.
> Missed config keys on Scala 2.13.x

- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/WhiskPodBuilder.scala
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/WhiskPodBuilderTests.scala
Building on setting a simple limit for k8s ephemeral storage this introduces another config setting to also allow scaling the storage based on the memory.
Along with CPU it seems reasonable action developers may need more disk as their actions use more and more memory. Ideally, we'd start to tease all this apart to allow developers to request a variety of resources but this simply creates a similar setting as CPU to allow the disk capacity to stretch along with memory.
> Add ability to scale Ephemeral storage along with memory, similar to CPU

- core/standalone/README.md
Clarify the documentation for adding options/args to the standalone openwhisk jar when running in the docker container.
Did not open one for a doc change.
> Clarify the OpenWhisk standalone extra args documentation when running it in Docker 

- tests/src/test/scala/org/apache/openwhisk/core/containerpool/kubernetes/test/WhiskPodBuilderTests.scala
This regression is introduced by merging https://github.com/apache/openwhisk/commit/b9f16dc68100e41f19a6a78f92c5e27dc5fab177
It seems the PR had passed all checks and was somewhat outdated after that.
So it was seemingly pass all checks but actually not.
> Fix unit test cases

- .asf.yaml
Change the required_status_checks to `strict` in the branch protection rule.
It has pros and cons because it would require all PRs to be updated before merging.
But it could prevent issues like [this](https://github.com/apache/openwhisk/pull/5459).
> Change the required_status_checks to strict

- core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/FPCPoolBalancer.scala
With FPC, the list of managed invoker ids is determined by what's in etcd. However the metric reporting and invokers api still assume that 0...n invokers exist up to the max available id in etcd and will auto fill in any missing ids as offline. This is fine for a range to fill in by the current min starting point, but it's not providing any value to assume things start at 0. A cluster could have a monotonically increasing range of ids and potentially if original nodes are lost they shouldn't be assumed to be filled back in at 0.
Further, the current implementation already will not include invokers that are offline at the high end of the pool since the api / metrics just assumes that max id stored in etcd is the max id of the cluster. **Example ten node cluster of 0-9**:
- nodes 8 and 9 …
> Update FPC invoker health reporting logic

- .github/workflows/3-multi-runtime.yaml
- ansible/group_vars/all
- ansible/roles/invoker/tasks/clean.yml
- ansible/roles/invoker/tasks/deploy.yml
- core/controller/Dockerfile
- core/controller/Dockerfile-debian
- core/invoker/Dockerfile
- core/invoker/Dockerfile-debian
- core/invoker/src/main/resources/application.conf
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
- core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/RuncClient.scala
- docs/deploy.md
- tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/RuncClientTests.scala
The docker version of the GitHub action runner is 23.0.6.
Instead of downgrading the engine version I want to give a shot to upgrade the client version.
> Upgrade the docker version to 23.0.6

- ansible/roles/prereq/tasks/deploy.yml
Use python requests 2.31.0.
- The previously installed requests==2.10.0 did not met the docker==4.0.2 requirements. Because of this pip always installed the latest version of requests when installing docker==4.0.2 (see ansible/roles/prereq/tasks/deploy.yml). This worked fine until requests==2.32.2 was latest version available and installed. This version contained changes which made docker==4.0.2 package to fail with for example: "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker". This caused the deployment step to fail the build.
- Installing requests==2.31.0 now avoids that the install of docker==4.0.2 updates to the latest requests and makes the builds successful again
> Use python requests 2.31.0.

- core/standalone/build.gradle
The pluging gradle-git-properties 2.0.0 referenced grgit-core:3.0.0 which is not available anymore (only 4.1.1+). Therefore upgrading to a newer version of gradle-git-properties to unblock the build.
> Move to gradle-git-properties 2.4.2 to unblock build.

- ansible/group_vars/all
quay.io/coreos/etcd:v3.4.0 is 5 years old and is using a deprecated Docker image format.
> update coreos/etcd version to 3.4.33 to unblock build

- build.gradle
- settings.gradle
Fix missing cz.alenkacz:gradle-scalafmt build error.
The 'cz.alenkacz:gradle-scalafmt' module could not be found anymore. Had to change the name to 'gradle.plugin.cz.alenkacz:gradle-scalafmt' and update the version to 1.5.1 since version 1.5.0 seems to have an invalid pom file (see https://plugins.gradle.org/m2/gradle/plugin/cz/alenkacz/gradle-scalafmt/1.5.0/gradle-scalafmt-1.5.0.pom) and refused to function. The version 1.5.1 seem to work fine (see https://plugins.gradle.org/m2/gradle/plugin/cz/alenkacz/gradle-scalafmt/1.5.1/gradle-scalafmt-1.5.1.pom).
> Fix missing cz.alenkacz:gradle-scalafmt build error.

- ansible/group_vars/all
- ansible/roles/etcd/tasks/deploy.yml
- ansible/roles/invoker/tasks/deploy.yml
- ansible/roles/zookeeper/tasks/deploy.yml
- common/scala/Dockerfile.arm
- common/scala/build.gradle
- core/scheduler/build.gradle
- gradle/docker.gradle
- tools/ow-utils/Dockerfile.arm
- tools/ow-utils/build.gradle
This is a very first step to make OW compatible with M1 Mac.
There could be many ways but I chose to minimize changes. I decided to have another Dockerfile for the M1 Mac. It will be selectively used according to the OS and its architecture.
I could build and deploy OW on M1 Mac and run an action.
(Though I had to install rosetta because openwhisk-cli is also not being built for M1 mac.)
```bash
$ wsk action invoke noop -i -r
{}
```
> M1 mac compatibility

- .github/workflows/README.md
- ansible/group_vars/all
- ansible/publish.yml
- common/scala/src/main/resources/application.conf
- common/scala/src/main/scala/org/apache/openwhisk/core/ack/MessagingActiveAck.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
- common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
- tools/owperf/README.md
> Fix spelling

- .github/workflows/0-on-demand.yaml
- .github/workflows/1-unit.yaml
- .github/workflows/2-system.yaml
- .github/workflows/3-multi-runtime.yaml
- .github/workflows/4-standalone.yaml
- .github/workflows/5-scheduler.yaml
- .github/workflows/6-performance.yaml
- settings.gradle
This PR migrates the OpenWhisk project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
Additionally, this PR migrates from the legacy Gradle Enterprise plugin to the renamed Develocity plugin and sets a projectId for use by Develocity.
> Publish build scans to develocity.apache.org

- ansible/files/whisks_design_document_for_entities_db_v2.1.0.json
These changes make whisks.v.2.1/packges-public view function to check whether doc.binding is undfined before getting the length of it. It can prevent from CouchDB producing unnecessary logs.
When 'packages-public' view builds the index, you can find these logs.
```
[info] 2024-09-07T02:25:38.312234Z nonode@nohost <0.1292.0> -------- OS Process #Port<0.8249> Log :: function raised exception (new TypeError("doc.binding is not an object", "undefined", 3)) with doc._id whisk.system/user25868/TEST
```
I modified 'isPublicPackage' function. I believe that use 'Falsy' because there's no need to check the length of doc.binding when it is not object type. And also, it's better to check Falsy or boolean before than the length of object.  
```javascript
// as-is
var isPublicPackage = functions(doc) …
```
> Fix packages-public view function
